In [2]:
from google.colab import drive

drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
from pathlib import Path

zip_path = Path(
    "/content/drive/MyDrive/AthletiQ/sportsmot/sportsmot_yolo.zip"
)

print("ZIP exists:", zip_path.exists())

if zip_path.exists():
    print("ZIP size:",
          round(zip_path.stat().st_size / (1024**3), 2),
          "GB")

ZIP exists: True
ZIP size: 4.21 GB

In [4]:
from pathlib import Path
import shutil
import time

src = Path("/content/drive/MyDrive/AthletiQ/sportsmot/sportsmot_yolo.zip")
dst = Path("/content/sportsmot_yolo.zip")

print("Copying dataset to Colab local storage...")
start = time.time()

shutil.copy2(src, dst)

elapsed = time.time() - start

print("Copy complete!")
print("Size:", round(dst.stat().st_size / (1024**3), 2), "GB")
print("Time:", round(elapsed / 60, 2), "minutes")

Copying dataset to Colab local storage...
Copy complete!
Size: 4.21 GB
Time: 2.68 minutes

In [5]:
from pathlib import Path
import zipfile
import time

zip_path = Path("/content/sportsmot_yolo.zip")
extract_root = Path("/content/AthletiQ/datasets/football/processed")

extract_root.mkdir(parents=True, exist_ok=True)

print("Extracting dataset...")
start = time.time()

with zipfile.ZipFile(zip_path, "r") as z:
    z.extractall(extract_root)

elapsed = time.time() - start

print("Extraction complete!")
print("Time:", round(elapsed / 60, 2), "minutes")

Extracting dataset...
Extraction complete!
Time: 0.68 minutes

In [6]:
from pathlib import Path

dataset = Path(
    "/content/AthletiQ/datasets/football/processed/sportsmot_yolo"
)

print("Dataset exists:", dataset.exists())

train_images = len(list((dataset / "images/train").glob("*")))
val_images = len(list((dataset / "images/val").glob("*")))

train_labels = len(list((dataset / "labels/train").glob("*.txt")))
val_labels = len(list((dataset / "labels/val").glob("*.txt")))

print()
print("Train images :", train_images)
print("Val images   :", val_images)
print("Train labels :", train_labels)
print("Val labels   :", val_labels)

Dataset exists: True

Train images : 15
Val images   : 15
Train labels : 0
Val labels   : 0

In [7]:
from pathlib import Path

root = Path("/content/AthletiQ/datasets/football/processed/sportsmot_yolo")

print("Root:")
print(root)
print()

print("Immediate contents:")
for item in sorted(root.iterdir()):
    print("DIR " if item.is_dir() else "FILE", item.name)

print("\nDirectories up to 3 levels deep:")
for p in sorted(root.glob("*/*")):
    print(p.relative_to(root))

Root:
/content/AthletiQ/datasets/football/processed/sportsmot_yolo

Immediate contents:
FILE data.yaml
DIR  images
DIR  labels

Directories up to 3 levels deep:
images/train
images/val
labels/train
labels/val

In [8]:
from pathlib import Path

root = Path("/content/AthletiQ/datasets/football/processed/sportsmot_yolo")

print("\nImage directories found:")
for p in sorted(root.rglob("images")):
    print(p)

print("\nLabel directories found:")
for p in sorted(root.rglob("labels")):
    print(p)

print("\nTotal image files:")
print(len(list(root.rglob("*.jpg"))))

print("\nTotal TXT files:")
print(len(list(root.rglob("*.txt"))))

Image directories found:
/content/AthletiQ/datasets/football/processed/sportsmot_yolo/images

Label directories found:
/content/AthletiQ/datasets/football/processed/sportsmot_yolo/labels

Total image files:
20171

Total TXT files:
20171

In [9]:
from pathlib import Path

dataset = Path(
    "/content/AthletiQ/datasets/football/processed/sportsmot_yolo"
)

train_images = list((dataset / "images/train").rglob("*.jpg"))
val_images = list((dataset / "images/val").rglob("*.jpg"))

train_labels = list((dataset / "labels/train").rglob("*.txt"))
val_labels = list((dataset / "labels/val").rglob("*.txt"))

print("========== DATASET VERIFICATION ==========")
print(f"Train images : {len(train_images):,}")
print(f"Val images   : {len(val_images):,}")
print(f"Train labels : {len(train_labels):,}")
print(f"Val labels   : {len(val_labels):,}")
print(f"Total images : {len(train_images) + len(val_images):,}")
print(f"Total labels : {len(train_labels) + len(val_labels):,}")

========== DATASET VERIFICATION ==========
Train images : 11,113
Val images   : 9,058
Train labels : 11,113
Val labels   : 9,058
Total images : 20,171
Total labels : 20,171

In [10]:
from pathlib import Path

model_drive = Path(
    "/content/drive/MyDrive/AthletiQ/sportsmot/models/yolov26m-sportsmot-football.pt"
)

print("Model exists:", model_drive.exists())

if model_drive.exists():
    print(
        "Model size:",
        round(model_drive.stat().st_size / (1024**2), 2),
        "MB"
    )

Model exists: True
Model size: 42.04 MB

In [11]:
from pathlib import Path
import shutil

model_drive = Path(
    "/content/drive/MyDrive/AthletiQ/sportsmot/models/yolov26m-sportsmot-football.pt"
)

model_local = Path(
    "/content/AthletiQ/ai-engine/models/yolov26m-sportsmot-football.pt"
)

model_local.parent.mkdir(parents=True, exist_ok=True)

shutil.copy2(model_drive, model_local)

print("Model copied successfully")
print("Path:", model_local)
print("Size:", round(model_local.stat().st_size / (1024**2), 2), "MB")

Model copied successfully
Path: /content/AthletiQ/ai-engine/models/yolov26m-sportsmot-football.pt
Size: 42.04 MB

In [12]:
!pip install ultralytics

Collecting ultralytics
  Downloading ultralytics-8.4.150-py3-none-any.whl.metadata (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.6/46.6 kB 167.6 kB/s eta 0:00:00
Requirement already satisfied: cloudpickle>=3.1.1 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (3.1.2)
Requirement already satisfied: filelock>=3.16.1 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (3.32.5)
Requirement already satisfied: numpy>=1.23.0 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (2.1.3)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (3.10.0)
Requirement already satisfied: opencv-python!=4.13.0.90,>=4.7.0 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (5.0.0.93)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (11.3.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (2.32.4)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (2.11.0+cu128)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (0.26.0+cu128)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (5.9.5)
Requirement already satisfied: polars>=0.20.0 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (1.35.2)
Requirement already satisfied: nvidia-ml-py>=12.0.0 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (13.610.43)
Collecting ultralytics-thop>=2.1.6 (from ultralytics)
  Downloading ultralytics_thop-2.1.6-py3-none-any.whl.metadata (13 kB)
Collecting ultralytics-platform>=0.1.32 (from ultralytics)
  Downloading ultralytics_platform-0.1.40-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3.0->ultralytics) (26.3)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Requirement already satisfied: polars-runtime-32==1.35.2 in /usr/local/lib/python3.13/dist-packages (from polars>=0.20.0->ultralytics) (1.35.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.23.0->ultralytics) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.23.0->ultralytics) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.23.0->ultralytics) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.23.0->ultralytics) (2026.7.22)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (2025.12.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.90)
Requirement already satisfied: httpx<1,>=0.28 in /usr/local/lib/python3.13/dist-packages (from ultralytics-platform>=0.1.32->ultralytics) (0.28.1)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.8.0->ultralytics) (1.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.28->ultralytics-platform>=0.1.32->ultralytics) (4.14.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.28->ultralytics-platform>=0.1.32->ultralytics) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.28->ultralytics-platform>=0.1.32->ultralytics) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.3)
Downloading ultralytics-8.4.150-py3-none-any.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 34.1 MB/s eta 0:00:00
Downloading ultralytics_platform-0.1.40-py3-none-any.whl (75 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.8/75.8 kB 7.0 MB/s eta 0:00:00
Downloading ultralytics_thop-2.1.6-py3-none-any.whl (30 kB)
Installing collected packages: ultralytics-platform, ultralytics-thop, ultralytics
Successfully installed ultralytics-8.4.150 ultralytics-platform-0.1.40 ultralytics-thop-2.1.6

In [13]:
from ultralytics import YOLO
import torch

model = YOLO(str(model_local))

print("========== MODEL VERIFICATION ==========")
print("Task:", model.task)
print("Classes:", model.names)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print(
        "VRAM:",
        round(
            torch.cuda.get_device_properties(0).total_memory / (1024**3),
            2
        ),
        "GB"
    )

Creating new Ultralytics Settings v0.0.8 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/usage/settings.
========== MODEL VERIFICATION ==========
Task: detect
Classes: {0: 'player'}
CUDA available: True
GPU: Tesla T4
VRAM: 14.56 GB

In [14]:
from pathlib import Path
import pandas as pd
import shutil
import os

# =========================
# Paths
# =========================

PROJECT_ROOT = Path("/content/AthletiQ")

DATASET_DIR = (
    PROJECT_ROOT
    / "datasets/football/processed/sportsmot_yolo"
)

VAL_IMAGES = DATASET_DIR / "images/val"
VAL_LABELS = DATASET_DIR / "labels/val"

MODEL_PATH = (
    PROJECT_ROOT
    / "ai-engine/models/yolov26m-sportsmot-football.pt"
)

EXPERIMENT_DIR = (
    PROJECT_ROOT
    / "experiments/yolov26m_sportsmot"
)

EXPERIMENT_DIR.mkdir(parents=True, exist_ok=True)

# Persistent Drive location
DRIVE_EXPERIMENT_DIR = Path(
    "/content/drive/MyDrive/AthletiQ/sportsmot/experiments/yolov26m_sportsmot"
)

DRIVE_EXPERIMENT_DIR.mkdir(parents=True, exist_ok=True)

CHECKPOINT_LOCAL = EXPERIMENT_DIR / "mining_checkpoint.csv"
RESULTS_LOCAL = EXPERIMENT_DIR / "mining_results.csv"

CHECKPOINT_DRIVE = DRIVE_EXPERIMENT_DIR / "mining_checkpoint.csv"
RESULTS_DRIVE = DRIVE_EXPERIMENT_DIR / "mining_results.csv"

# =========================
# Configuration
# =========================

CONF_THRESHOLD = 0.25
IOU_THRESHOLD = 0.50
IMAGE_SIZE = 1280
BATCH_SIZE = 1
FN_WEIGHT = 1.5
SAVE_EVERY = 100

# =========================
# Find images recursively
# =========================

val_images = sorted(
    VAL_IMAGES.rglob("*.jpg")
)

val_labels = sorted(
    VAL_LABELS.rglob("*.txt")
)

print("========== HARD MINING CONFIG ==========")

print("Dataset :", DATASET_DIR)
print("Model   :", MODEL_PATH)

print("\nValidation:")
print("Image root:", VAL_IMAGES)
print("Label root:", VAL_LABELS)

print("\nLocal experiment:", EXPERIMENT_DIR)
print("Drive checkpoint:", DRIVE_EXPERIMENT_DIR)

print("\n========== VERIFICATION ==========")

print("Dataset exists:", DATASET_DIR.exists())
print("Model exists:", MODEL_PATH.exists())

print("Validation images:", len(val_images))
print("Validation labels:", len(val_labels))

if len(val_images) == 9058:
    print("Validation image count: OK")
else:
    print("WARNING: Expected 9058 validation images.")

if len(val_labels) == 9058:
    print("Validation label count: OK")
else:
    print("WARNING: Expected 9058 validation labels.")

print("\nConfiguration:")
print("Confidence :", CONF_THRESHOLD)
print("IoU        :", IOU_THRESHOLD)
print("Image size :", IMAGE_SIZE)
print("Batch size :", BATCH_SIZE)
print("FN weight  :", FN_WEIGHT)
print("Save every :", SAVE_EVERY)

# Show a few examples
print("\nExample images:")
for p in val_images[:5]:
    print(" ", p)

========== HARD MINING CONFIG ==========
Dataset : /content/AthletiQ/datasets/football/processed/sportsmot_yolo
Model   : /content/AthletiQ/ai-engine/models/yolov26m-sportsmot-football.pt

Validation:
Image root: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val
Label root: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/labels/val

Local experiment: /content/AthletiQ/experiments/yolov26m_sportsmot
Drive checkpoint: /content/drive/MyDrive/AthletiQ/sportsmot/experiments/yolov26m_sportsmot

========== VERIFICATION ==========
Dataset exists: True
Model exists: True
Validation images: 9058
Validation labels: 9058
Validation image count: OK
Validation label count: OK

Configuration:
Confidence : 0.25
IoU        : 0.5
Image size : 1280
Batch size : 1
FN weight  : 1.5
Save every : 100

Example images:
  /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_2QhNRucNC7E_c017/000001.jpg
  /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_2QhNRucNC7E_c017/000002.jpg
  /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_2QhNRucNC7E_c017/000003.jpg
  /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_2QhNRucNC7E_c017/000004.jpg
  /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_2QhNRucNC7E_c017/000005.jpg

In [15]:
import numpy as np
import cv2

def load_yolo_labels(label_path):
    boxes = []

    if not label_path.exists():
        return np.empty((0, 4), dtype=np.float32)

    with open(label_path, "r") as f:
        for line in f:
            parts = line.strip().split()

            if len(parts) != 5:
                continue

            class_id = int(parts[0])

            if class_id != 0:
                continue

            xc, yc, w, h = map(float, parts[1:])

            boxes.append([xc, yc, w, h])

    if not boxes:
        return np.empty((0, 4), dtype=np.float32)

    return np.array(boxes, dtype=np.float32)


def yolo_to_xyxy(boxes, image_width, image_height):
    if len(boxes) == 0:
        return np.empty((0, 4), dtype=np.float32)

    result = []

    for xc, yc, w, h in boxes:
        x1 = (xc - w / 2) * image_width
        y1 = (yc - h / 2) * image_height
        x2 = (xc + w / 2) * image_width
        y2 = (yc + h / 2) * image_height

        result.append([x1, y1, x2, y2])

    return np.array(result, dtype=np.float32)


def calculate_iou(box1, box2):
    x1 = max(box1[0], box2[0])
    y1 = max(box1[1], box2[1])
    x2 = min(box1[2], box2[2])
    y2 = min(box1[3], box2[3])

    iw = max(0, x2 - x1)
    ih = max(0, y2 - y1)

    intersection = iw * ih

    area1 = max(0, box1[2] - box1[0]) * max(
        0, box1[3] - box1[1]
    )

    area2 = max(0, box2[2] - box2[0]) * max(
        0, box2[3] - box2[1]
    )

    union = area1 + area2 - intersection

    if union <= 0:
        return 0.0

    return intersection / union


def greedy_match(gt_boxes, pred_boxes, iou_threshold=0.5):

    if len(gt_boxes) == 0:
        return 0, len(pred_boxes), 0, []

    if len(pred_boxes) == 0:
        return 0, 0, len(gt_boxes), []

    pairs = []

    for gt_idx, gt_box in enumerate(gt_boxes):
        for pred_idx, pred_box in enumerate(pred_boxes):

            iou = calculate_iou(gt_box, pred_box)

            if iou >= iou_threshold:
                pairs.append(
                    (iou, gt_idx, pred_idx)
                )

    pairs.sort(reverse=True)

    matched_gt = set()
    matched_pred = set()
    matched_ious = []

    for iou, gt_idx, pred_idx in pairs:

        if gt_idx in matched_gt:
            continue

        if pred_idx in matched_pred:
            continue

        matched_gt.add(gt_idx)
        matched_pred.add(pred_idx)

        matched_ious.append(iou)

    tp = len(matched_gt)
    fp = len(pred_boxes) - tp
    fn = len(gt_boxes) - tp

    return tp, fp, fn, matched_ious


# ----------------------------------
# Test first validation image
# ----------------------------------

test_image = val_images[0]

print("Testing image:")
print(test_image)

# Run YOLO
results = model.predict(
    source=str(test_image),
    conf=CONF_THRESHOLD,
    imgsz=IMAGE_SIZE,
    device=0,
    verbose=False
)

result = results[0]

# Read image
image = cv2.imread(str(test_image))
height, width = image.shape[:2]

# Predictions
pred_boxes = result.boxes.xyxy.cpu().numpy()

# Ground truth
label_path = (
    VAL_LABELS
    / test_image.parent.name
    / f"{test_image.stem}.txt"
)

gt_yolo = load_yolo_labels(label_path)

gt_boxes = yolo_to_xyxy(
    gt_yolo,
    width,
    height
)

# Match
tp, fp, fn, matched_ious = greedy_match(
    gt_boxes,
    pred_boxes,
    IOU_THRESHOLD
)

print("\n========== SINGLE IMAGE TEST ==========")
print("Image size :", width, "x", height)
print("GT players:", len(gt_boxes))
print("Predictions:", len(pred_boxes))
print("TP:", tp)
print("FP:", fp)
print("FN:", fn)

if matched_ious:
    print(
        "Mean IoU:",
        round(float(np.mean(matched_ious)), 4)
    )

if len(result.boxes.conf) > 0:
    print(
        "Mean confidence:",
        round(
            float(result.boxes.conf.mean().item()),
            4
        )
    )

# GPU memory
import torch

if torch.cuda.is_available():
    print(
        "GPU memory allocated:",
        round(
            torch.cuda.memory_allocated() / (1024**3),
            2
        ),
        "GB"
    )

    print(
        "GPU memory reserved:",
        round(
            torch.cuda.memory_reserved() / (1024**3),
            2
        ),
        "GB"
    )

Testing image:
/content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_2QhNRucNC7E_c017/000001.jpg

========== SINGLE IMAGE TEST ==========
Image size : 1280 x 720
GT players: 19
Predictions: 21
TP: 19
FP: 2
FN: 0
Mean IoU: 0.9317
Mean confidence: 0.8761
GPU memory allocated: 0.14 GB
GPU memory reserved: 0.34 GB

In [16]:
import pandas as pd
import numpy as np
import shutil
import time
import torch
from pathlib import Path
from ultralytics import YOLO

# ============================================================
# HARD MINING
# ============================================================

print("========== STARTING HARD MINING ==========")

# ------------------------------------------------------------
# Load existing checkpoint if available
# ------------------------------------------------------------

if CHECKPOINT_DRIVE.exists():

    print("Found Drive checkpoint.")
    print("Loading previous progress...")

    shutil.copy2(
        CHECKPOINT_DRIVE,
        CHECKPOINT_LOCAL
    )

elif CHECKPOINT_LOCAL.exists():

    print("Found local checkpoint.")
    print("Resuming from local progress...")

else:

    print("No previous checkpoint found.")
    print("Starting from image 1.")

# ------------------------------------------------------------
# Load completed images
# ------------------------------------------------------------

if CHECKPOINT_LOCAL.exists():

    checkpoint_df = pd.read_csv(
        CHECKPOINT_LOCAL
    )

    completed_images = set(
        checkpoint_df["image_path"].astype(str)
    )

    print(
        "Previously completed:",
        len(completed_images)
    )

else:

    checkpoint_df = pd.DataFrame()
    completed_images = set()

# ------------------------------------------------------------
# Remaining images
# ------------------------------------------------------------

remaining_images = [
    p for p in val_images
    if str(p) not in completed_images
]

print(
    "Total validation images:",
    len(val_images)
)

print(
    "Already completed:",
    len(completed_images)
)

print(
    "Remaining:",
    len(remaining_images)
)

if len(remaining_images) == 0:

    print("\n========== MINING ALREADY COMPLETE ==========")

else:

    # --------------------------------------------------------
    # Mining results
    # --------------------------------------------------------

    results_list = []

    start_time = time.time()

    for idx, image_path in enumerate(
        remaining_images,
        start=1
    ):

        image_start = time.time()

        try:

            # ================================================
            # YOLO inference
            # ================================================

            predictions = model.predict(
                source=str(image_path),
                conf=CONF_THRESHOLD,
                imgsz=IMAGE_SIZE,
                device=0,
                verbose=False
            )

            result = predictions[0]

            # ================================================
            # Image dimensions
            # ================================================

            image = cv2.imread(
                str(image_path)
            )

            if image is None:
                raise RuntimeError(
                    "Could not read image"
                )

            height, width = image.shape[:2]

            # ================================================
            # Predictions
            # ================================================

            pred_boxes = (
                result.boxes.xyxy
                .cpu()
                .numpy()
            )

            pred_conf = (
                result.boxes.conf
                .cpu()
                .numpy()
            )

            # ================================================
            # Ground truth
            # ================================================

            sequence_name = image_path.parent.name

            label_path = (
                VAL_LABELS
                / sequence_name
                / f"{image_path.stem}.txt"
            )

            gt_yolo = load_yolo_labels(
                label_path
            )

            gt_boxes = yolo_to_xyxy(
                gt_yolo,
                width,
                height
            )

            # ================================================
            # Matching
            # ================================================

            tp, fp, fn, matched_ious = (
                greedy_match(
                    gt_boxes,
                    pred_boxes,
                    IOU_THRESHOLD
                )
            )

            # ================================================
            # Metrics
            # ================================================

            precision = (
                tp / (tp + fp)
                if (tp + fp) > 0
                else 0.0
            )

            recall = (
                tp / (tp + fn)
                if (tp + fn) > 0
                else 0.0
            )

            mean_iou = (
                float(np.mean(matched_ious))
                if matched_ious
                else 0.0
            )

            mean_confidence = (
                float(np.mean(pred_conf))
                if len(pred_conf) > 0
                else 0.0
            )

            difficulty = (
                fp + FN_WEIGHT * fn
            )

            elapsed = (
                time.time() - image_start
            )

            # ================================================
            # Save result
            # ================================================

            row = {
                "image_path": str(image_path),
                "sequence": sequence_name,
                "frame": image_path.stem,
                "gt": len(gt_boxes),
                "predictions": len(pred_boxes),
                "tp": tp,
                "fp": fp,
                "fn": fn,
                "precision": precision,
                "recall": recall,
                "mean_iou": mean_iou,
                "mean_confidence": mean_confidence,
                "difficulty": difficulty,
                "inference_time_sec": elapsed
            }

            results_list.append(row)

        except Exception as e:

            print(
                f"\nERROR processing {image_path}"
            )

            print(
                "Error:",
                repr(e)
            )

            # Record failure rather than losing progress
            results_list.append({
                "image_path": str(image_path),
                "sequence": image_path.parent.name,
                "frame": image_path.stem,
                "gt": -1,
                "predictions": -1,
                "tp": -1,
                "fp": -1,
                "fn": -1,
                "precision": -1,
                "recall": -1,
                "mean_iou": -1,
                "mean_confidence": -1,
                "difficulty": -1,
                "inference_time_sec": -1
            })

        # ====================================================
        # Periodic checkpoint
        # ====================================================

        if (
            len(results_list) >= SAVE_EVERY
            or idx == len(remaining_images)
        ):

            new_df = pd.DataFrame(
                results_list
            )

            if CHECKPOINT_LOCAL.exists():

                old_df = pd.read_csv(
                    CHECKPOINT_LOCAL
                )

                combined_df = pd.concat(
                    [old_df, new_df],
                    ignore_index=True
                )

            else:

                combined_df = new_df

            # Remove accidental duplicates
            combined_df = (
                combined_df
                .drop_duplicates(
                    subset=["image_path"],
                    keep="last"
                )
                .sort_values("image_path")
            )

            # Save locally
            combined_df.to_csv(
                CHECKPOINT_LOCAL,
                index=False
            )

            combined_df.to_csv(
                RESULTS_LOCAL,
                index=False
            )

            # ----------------------------------------------
            # Persistent Drive checkpoint
            # ----------------------------------------------

            shutil.copy2(
                CHECKPOINT_LOCAL,
                CHECKPOINT_DRIVE
            )

            shutil.copy2(
                RESULTS_LOCAL,
                RESULTS_DRIVE
            )

            # Clear temporary results
            results_list = []

            # ----------------------------------------------
            # Progress
            # ----------------------------------------------

            completed_now = len(
                combined_df
            )

            total_elapsed = (
                time.time() - start_time
            )

            avg_time = (
                total_elapsed / idx
            )

            remaining = (
                len(remaining_images) - idx
            )

            eta_minutes = (
                remaining * avg_time / 60
            )

            print(
                f"\n[{completed_now}/{len(val_images)}]"
                f" | Remaining: {len(val_images)-completed_now}"
                f" | Avg: {avg_time:.2f}s/image"
                f" | ETA: {eta_minutes:.1f} min"
            )

    print(
        "\n========== HARD MINING FINISHED =========="
    )

# ============================================================
# Final summary
# ============================================================

if CHECKPOINT_LOCAL.exists():

    mining_df = pd.read_csv(
        CHECKPOINT_LOCAL
    )

    print("\nTotal results:", len(mining_df))

    valid_df = mining_df[
        mining_df["gt"] >= 0
    ]

    print(
        "Valid results:",
        len(valid_df)
    )

    print(
        "Failed results:",
        len(mining_df) - len(valid_df)
    )

    print("\nAggregate:")
    print(
        "GT:",
        int(valid_df["gt"].sum())
    )

    print(
        "Predictions:",
        int(valid_df["predictions"].sum())
    )

    print(
        "TP:",
        int(valid_df["tp"].sum())
    )

    print(
        "FP:",
        int(valid_df["fp"].sum())
    )

    print(
        "FN:",
        int(valid_df["fn"].sum())
    )

    total_tp = valid_df["tp"].sum()
    total_fp = valid_df["fp"].sum()
    total_fn = valid_df["fn"].sum()

    overall_precision = (
        total_tp /
        (total_tp + total_fp)
        if (total_tp + total_fp) > 0
        else 0
    )

    overall_recall = (
        total_tp /
        (total_tp + total_fn)
        if (total_tp + total_fn) > 0
        else 0
    )

    print(
        "Overall precision:",
        round(overall_precision, 4)
    )

    print(
        "Overall recall:",
        round(overall_recall, 4)
    )

    print(
        "\nResults saved to:"
    )

    print(
        RESULTS_DRIVE
    )

========== STARTING HARD MINING ==========
No previous checkpoint found.
Starting from image 1.
Total validation images: 9058
Already completed: 0
Remaining: 9058

[100/9058] | Remaining: 8958 | Avg: 0.06s/image | ETA: 9.4 min

[200/9058] | Remaining: 8858 | Avg: 0.06s/image | ETA: 9.4 min

[300/9058] | Remaining: 8758 | Avg: 0.06s/image | ETA: 9.2 min

[400/9058] | Remaining: 8658 | Avg: 0.06s/image | ETA: 9.1 min

[500/9058] | Remaining: 8558 | Avg: 0.06s/image | ETA: 9.0 min

[600/9058] | Remaining: 8458 | Avg: 0.06s/image | ETA: 8.9 min

[700/9058] | Remaining: 8358 | Avg: 0.06s/image | ETA: 8.7 min

[800/9058] | Remaining: 8258 | Avg: 0.06s/image | ETA: 8.6 min

[900/9058] | Remaining: 8158 | Avg: 0.06s/image | ETA: 8.5 min

[1000/9058] | Remaining: 8058 | Avg: 0.06s/image | ETA: 8.4 min

[1100/9058] | Remaining: 7958 | Avg: 0.06s/image | ETA: 8.3 min

[1200/9058] | Remaining: 7858 | Avg: 0.06s/image | ETA: 8.2 min

[1300/9058] | Remaining: 7758 | Avg: 0.06s/image | ETA: 8.1 min

[1400/9058] | Remaining: 7658 | Avg: 0.06s/image | ETA: 8.0 min

[1500/9058] | Remaining: 7558 | Avg: 0.06s/image | ETA: 7.9 min

[1600/9058] | Remaining: 7458 | Avg: 0.06s/image | ETA: 7.8 min

[1700/9058] | Remaining: 7358 | Avg: 0.06s/image | ETA: 7.8 min

[1800/9058] | Remaining: 7258 | Avg: 0.06s/image | ETA: 7.7 min

[1900/9058] | Remaining: 7158 | Avg: 0.06s/image | ETA: 7.6 min

[2000/9058] | Remaining: 7058 | Avg: 0.06s/image | ETA: 7.5 min

[2100/9058] | Remaining: 6958 | Avg: 0.06s/image | ETA: 7.4 min

[2200/9058] | Remaining: 6858 | Avg: 0.06s/image | ETA: 7.3 min

[2300/9058] | Remaining: 6758 | Avg: 0.06s/image | ETA: 7.2 min

[2400/9058] | Remaining: 6658 | Avg: 0.06s/image | ETA: 7.1 min

[2500/9058] | Remaining: 6558 | Avg: 0.06s/image | ETA: 7.0 min

[2600/9058] | Remaining: 6458 | Avg: 0.06s/image | ETA: 6.9 min

[2700/9058] | Remaining: 6358 | Avg: 0.06s/image | ETA: 6.8 min

[2800/9058] | Remaining: 6258 | Avg: 0.06s/image | ETA: 6.7 min

[2900/9058] | Remaining: 6158 | Avg: 0.06s/image | ETA: 6.6 min

[3000/9058] | Remaining: 6058 | Avg: 0.06s/image | ETA: 6.5 min

[3100/9058] | Remaining: 5958 | Avg: 0.06s/image | ETA: 6.3 min

[3200/9058] | Remaining: 5858 | Avg: 0.06s/image | ETA: 6.3 min

[3300/9058] | Remaining: 5758 | Avg: 0.06s/image | ETA: 6.1 min

[3400/9058] | Remaining: 5658 | Avg: 0.06s/image | ETA: 6.0 min

[3500/9058] | Remaining: 5558 | Avg: 0.06s/image | ETA: 5.9 min

[3600/9058] | Remaining: 5458 | Avg: 0.06s/image | ETA: 5.8 min

[3700/9058] | Remaining: 5358 | Avg: 0.06s/image | ETA: 5.7 min

[3800/9058] | Remaining: 5258 | Avg: 0.06s/image | ETA: 5.6 min

[3900/9058] | Remaining: 5158 | Avg: 0.06s/image | ETA: 5.5 min

[4000/9058] | Remaining: 5058 | Avg: 0.06s/image | ETA: 5.4 min

[4100/9058] | Remaining: 4958 | Avg: 0.06s/image | ETA: 5.3 min

[4200/9058] | Remaining: 4858 | Avg: 0.06s/image | ETA: 5.2 min

[4300/9058] | Remaining: 4758 | Avg: 0.06s/image | ETA: 5.1 min

[4400/9058] | Remaining: 4658 | Avg: 0.06s/image | ETA: 5.0 min

[4500/9058] | Remaining: 4558 | Avg: 0.07s/image | ETA: 4.9 min

[4600/9058] | Remaining: 4458 | Avg: 0.07s/image | ETA: 4.8 min

[4700/9058] | Remaining: 4358 | Avg: 0.07s/image | ETA: 4.7 min

[4800/9058] | Remaining: 4258 | Avg: 0.07s/image | ETA: 4.6 min

[4900/9058] | Remaining: 4158 | Avg: 0.07s/image | ETA: 4.5 min

[5000/9058] | Remaining: 4058 | Avg: 0.07s/image | ETA: 4.4 min

[5100/9058] | Remaining: 3958 | Avg: 0.07s/image | ETA: 4.3 min

[5200/9058] | Remaining: 3858 | Avg: 0.07s/image | ETA: 4.2 min

[5300/9058] | Remaining: 3758 | Avg: 0.07s/image | ETA: 4.1 min

[5400/9058] | Remaining: 3658 | Avg: 0.07s/image | ETA: 4.0 min

[5500/9058] | Remaining: 3558 | Avg: 0.07s/image | ETA: 3.9 min

[5600/9058] | Remaining: 3458 | Avg: 0.07s/image | ETA: 3.8 min

[5700/9058] | Remaining: 3358 | Avg: 0.07s/image | ETA: 3.7 min

[5800/9058] | Remaining: 3258 | Avg: 0.07s/image | ETA: 3.6 min

[5900/9058] | Remaining: 3158 | Avg: 0.07s/image | ETA: 3.5 min

[6000/9058] | Remaining: 3058 | Avg: 0.07s/image | ETA: 3.4 min

[6100/9058] | Remaining: 2958 | Avg: 0.07s/image | ETA: 3.3 min

[6200/9058] | Remaining: 2858 | Avg: 0.07s/image | ETA: 3.2 min

[6300/9058] | Remaining: 2758 | Avg: 0.07s/image | ETA: 3.1 min

[6400/9058] | Remaining: 2658 | Avg: 0.07s/image | ETA: 2.9 min

[6500/9058] | Remaining: 2558 | Avg: 0.07s/image | ETA: 2.8 min

[6600/9058] | Remaining: 2458 | Avg: 0.07s/image | ETA: 2.7 min

[6700/9058] | Remaining: 2358 | Avg: 0.07s/image | ETA: 2.6 min

[6800/9058] | Remaining: 2258 | Avg: 0.07s/image | ETA: 2.5 min

[6900/9058] | Remaining: 2158 | Avg: 0.07s/image | ETA: 2.4 min

[7000/9058] | Remaining: 2058 | Avg: 0.07s/image | ETA: 2.3 min

[7100/9058] | Remaining: 1958 | Avg: 0.07s/image | ETA: 2.2 min

[7200/9058] | Remaining: 1858 | Avg: 0.07s/image | ETA: 2.1 min

[7300/9058] | Remaining: 1758 | Avg: 0.07s/image | ETA: 2.0 min

[7400/9058] | Remaining: 1658 | Avg: 0.07s/image | ETA: 1.9 min

[7500/9058] | Remaining: 1558 | Avg: 0.07s/image | ETA: 1.7 min

[7600/9058] | Remaining: 1458 | Avg: 0.07s/image | ETA: 1.6 min

[7700/9058] | Remaining: 1358 | Avg: 0.07s/image | ETA: 1.5 min

[7800/9058] | Remaining: 1258 | Avg: 0.07s/image | ETA: 1.4 min

[7900/9058] | Remaining: 1158 | Avg: 0.07s/image | ETA: 1.3 min

[8000/9058] | Remaining: 1058 | Avg: 0.07s/image | ETA: 1.2 min

[8100/9058] | Remaining: 958 | Avg: 0.07s/image | ETA: 1.1 min

[8200/9058] | Remaining: 858 | Avg: 0.07s/image | ETA: 1.0 min

[8300/9058] | Remaining: 758 | Avg: 0.07s/image | ETA: 0.9 min

[8400/9058] | Remaining: 658 | Avg: 0.07s/image | ETA: 0.7 min

[8500/9058] | Remaining: 558 | Avg: 0.07s/image | ETA: 0.6 min

[8600/9058] | Remaining: 458 | Avg: 0.07s/image | ETA: 0.5 min

[8700/9058] | Remaining: 358 | Avg: 0.07s/image | ETA: 0.4 min

[8800/9058] | Remaining: 258 | Avg: 0.07s/image | ETA: 0.3 min

[8900/9058] | Remaining: 158 | Avg: 0.07s/image | ETA: 0.2 min

[9000/9058] | Remaining: 58 | Avg: 0.07s/image | ETA: 0.1 min

[9058/9058] | Remaining: 0 | Avg: 0.07s/image | ETA: 0.0 min

========== HARD MINING FINISHED ==========

Total results: 9058
Valid results: 9058
Failed results: 0

Aggregate:
GT: 117115
Predictions: 124396
TP: 114280
FP: 10116
FN: 2835
Overall precision: 0.9187
Overall recall: 0.9758

Results saved to:
/content/drive/MyDrive/AthletiQ/sportsmot/experiments/yolov26m_sportsmot/mining_results.csv

In [17]:
import pandas as pd

results_path = (
    "/content/drive/MyDrive/AthletiQ/sportsmot/"
    "experiments/yolov26m_sportsmot/mining_results.csv"
)

df = pd.read_csv(results_path)

print("========== MINING RESULTS ==========")

print("Rows:", len(df))
print("Columns:", len(df.columns))

print("\nColumns:")
print(df.columns.tolist())

print("\n========== AGGREGATE ==========")

print("Total GT:", int(df["gt"].sum()))
print("Total predictions:", int(df["predictions"].sum()))
print("Total TP:", int(df["tp"].sum()))
print("Total FP:", int(df["fp"].sum()))
print("Total FN:", int(df["fn"].sum()))

print("\n========== DIFFICULTY ==========")

print(
    df["difficulty"].describe()
)

print("\n========== TOP 20 HARDEST ==========")

hardest = (
    df.sort_values(
        ["difficulty", "fn", "fp"],
        ascending=False
    )
    .head(20)
)

display(
    hardest[
        [
            "image_path",
            "sequence",
            "frame",
            "gt",
            "predictions",
            "tp",
            "fp",
            "fn",
            "precision",
            "recall",
            "mean_iou",
            "mean_confidence",
            "difficulty"
        ]
    ]
)

========== MINING RESULTS ==========
Rows: 9058
Columns: 14

Columns:
['image_path', 'sequence', 'frame', 'gt', 'predictions', 'tp', 'fp', 'fn', 'precision', 'recall', 'mean_iou', 'mean_confidence', 'difficulty', 'inference_time_sec']

========== AGGREGATE ==========
Total GT: 117115
Total predictions: 124396
Total TP: 114280
Total FP: 10116
Total FN: 2835

========== DIFFICULTY ==========
count    9058.000000
mean        1.586277
std         1.392234
min         0.000000
25%         1.000000
50%         1.000000
75%         2.500000
max        15.500000
Name: difficulty, dtype: float64

========== TOP 20 HARDEST ==========

,image_path,sequence,frame,gt,predictions,tp,fp,fn,precision,recall,mean_iou,mean_confidence,difficulty
6508,/content/AthletiQ/datasets/football/processed/...,v_i2_L4qquVg0_c006,36,1,14,0,14,1,0.000000,0.000000,0.000000,0.879714,15.5
1628,/content/AthletiQ/datasets/football/processed/...,v_G-vNjfx1GGc_c600,24,13,10,8,2,5,0.800000,0.615385,0.834392,0.782863,9.5
6228,/content/AthletiQ/datasets/football/processed/...,v_dw7LOz17Omg_c067,206,18,22,16,6,2,0.727273,0.888889,0.910659,0.817049,9.0
2304,/content/AthletiQ/datasets/football/processed/...,v_G-vNjfx1GGc_c601,200,13,19,12,7,1,0.631579,0.923077,0.856327,0.663019,8.5
1629,/content/AthletiQ/datasets/football/processed/...,v_G-vNjfx1GGc_c600,25,13,11,9,2,4,0.818182,0.692308,0.853132,0.711863,8.0
5503,/content/AthletiQ/datasets/football/processed/...,v_dw7LOz17Omg_c053,31,20,18,16,2,4,0.888889,0.800000,0.897318,0.799814,8.0
1406,/content/AthletiQ/datasets/football/processed/...,v_G-vNjfx1GGc_c008,282,11,14,9,5,2,0.642857,0.818182,0.906098,0.739479,8.0
2042,/content/AthletiQ/datasets/football/processed/...,v_G-vNjfx1GGc_c600,438,11,14,9,5,2,0.642857,0.818182,0.889265,0.718203,8.0
2690,/content/AthletiQ/datasets/football/processed/...,v_ITo3sCnpw_k_c007,105,14,17,12,5,2,0.705882,0.857143,0.860693,0.698048,8.0
2880,/content/AthletiQ/datasets/football/processed/...,v_ITo3sCnpw_k_c007,295,14,17,12,5,2,0.705882,0.857143,0.862674,0.716369,8.0
5983,/content/AthletiQ/datasets/football/processed/...,v_dw7LOz17Omg_c053,511,12,15,10,5,2,0.666667,0.833333,0.861616,0.707311,8.0
3109,/content/AthletiQ/datasets/football/processed/...,v_ITo3sCnpw_k_c007,524,15,23,15,8,0,0.652174,1.000000,0.916593,0.713410,8.0
2226,/content/AthletiQ/datasets/football/processed/...,v_G-vNjfx1GGc_c601,122,15,15,12,3,3,0.800000,0.800000,0.908992,0.790176,7.5
2287,/content/AthletiQ/datasets/football/processed/...,v_G-vNjfx1GGc_c601,183,17,17,14,3,3,0.823529,0.823529,0.887132,0.804026,7.5
2691,/content/AthletiQ/datasets/football/processed/...,v_ITo3sCnpw_k_c007,106,14,14,11,3,3,0.785714,0.785714,0.924211,0.742281,7.5
2281,/content/AthletiQ/datasets/football/processed/...,v_G-vNjfx1GGc_c601,177,17,22,16,6,1,0.727273,0.941176,0.891881,0.750839,7.5
5976,/content/AthletiQ/datasets/football/processed/...,v_dw7LOz17Omg_c053,504,12,17,11,6,1,0.647059,0.916667,0.901428,0.672969,7.5
1626,/content/AthletiQ/datasets/football/processed/...,v_G-vNjfx1GGc_c600,22,12,9,8,1,4,0.888889,0.666667,0.825258,0.785259,7.0
5493,/content/AthletiQ/datasets/football/processed/...,v_dw7LOz17Omg_c053,21,20,17,16,1,4,0.941176,0.800000,0.879132,0.766080,7.0
2161,/content/AthletiQ/datasets/football/processed/...,v_G-vNjfx1GGc_c601,57,15,17,13,4,2,0.764706,0.866667,0.930960,0.836562,7.0

In [18]:
# ============================================================
# DETAILED HARD-MINING ANALYSIS
# ============================================================

import pandas as pd
import numpy as np

results_path = (
    "/content/drive/MyDrive/AthletiQ/sportsmot/"
    "experiments/yolov26m_sportsmot/mining_results.csv"
)

df = pd.read_csv(results_path)

# ------------------------------------------------------------
# 1. Hardest by difficulty
# ------------------------------------------------------------

print("========== TOP 30 BY DIFFICULTY ==========")

hardest = (
    df.sort_values(
        ["difficulty", "fn", "fp"],
        ascending=False
    )
    .head(30)
)

display(
    hardest[
        [
            "sequence",
            "frame",
            "gt",
            "predictions",
            "tp",
            "fp",
            "fn",
            "precision",
            "recall",
            "mean_iou",
            "mean_confidence",
            "difficulty"
        ]
    ]
)

# ------------------------------------------------------------
# 2. Highest FN
# ------------------------------------------------------------

print("\n========== TOP 20 FN-HEAVY FRAMES ==========")

fn_heavy = (
    df.sort_values(
        ["fn", "fp"],
        ascending=False
    )
    .head(20)
)

display(
    fn_heavy[
        [
            "sequence",
            "frame",
            "gt",
            "predictions",
            "tp",
            "fp",
            "fn",
            "precision",
            "recall",
            "difficulty"
        ]
    ]
)

# ------------------------------------------------------------
# 3. Highest FP
# ------------------------------------------------------------

print("\n========== TOP 20 FP-HEAVY FRAMES ==========")

fp_heavy = (
    df.sort_values(
        ["fp", "fn"],
        ascending=False
    )
    .head(20)
)

display(
    fp_heavy[
        [
            "sequence",
            "frame",
            "gt",
            "predictions",
            "tp",
            "fp",
            "fn",
            "precision",
            "recall",
            "difficulty"
        ]
    ]
)

# ------------------------------------------------------------
# 4. Sequence-level difficulty
# ------------------------------------------------------------

print("\n========== SEQUENCE-LEVEL SUMMARY ==========")

sequence_summary = (
    df.groupby("sequence")
    .agg(
        images=("image_path", "count"),
        gt=("gt", "sum"),
        predictions=("predictions", "sum"),
        tp=("tp", "sum"),
        fp=("fp", "sum"),
        fn=("fn", "sum"),
        mean_difficulty=("difficulty", "mean"),
        max_difficulty=("difficulty", "max")
    )
)

sequence_summary["precision"] = (
    sequence_summary["tp"] /
    (
        sequence_summary["tp"] +
        sequence_summary["fp"]
    )
)

sequence_summary["recall"] = (
    sequence_summary["tp"] /
    (
        sequence_summary["tp"] +
        sequence_summary["fn"]
    )
)

sequence_summary = (
    sequence_summary
    .sort_values(
        "mean_difficulty",
        ascending=False
    )
)

display(
    sequence_summary.head(20)
)

========== TOP 30 BY DIFFICULTY ==========

,sequence,frame,gt,predictions,tp,fp,fn,precision,recall,mean_iou,mean_confidence,difficulty
6508,v_i2_L4qquVg0_c006,36,1,14,0,14,1,0.000000,0.000000,0.000000,0.879714,15.5
1628,v_G-vNjfx1GGc_c600,24,13,10,8,2,5,0.800000,0.615385,0.834392,0.782863,9.5
6228,v_dw7LOz17Omg_c067,206,18,22,16,6,2,0.727273,0.888889,0.910659,0.817049,9.0
2304,v_G-vNjfx1GGc_c601,200,13,19,12,7,1,0.631579,0.923077,0.856327,0.663019,8.5
1629,v_G-vNjfx1GGc_c600,25,13,11,9,2,4,0.818182,0.692308,0.853132,0.711863,8.0
5503,v_dw7LOz17Omg_c053,31,20,18,16,2,4,0.888889,0.800000,0.897318,0.799814,8.0
1406,v_G-vNjfx1GGc_c008,282,11,14,9,5,2,0.642857,0.818182,0.906098,0.739479,8.0
2042,v_G-vNjfx1GGc_c600,438,11,14,9,5,2,0.642857,0.818182,0.889265,0.718203,8.0
2690,v_ITo3sCnpw_k_c007,105,14,17,12,5,2,0.705882,0.857143,0.860693,0.698048,8.0
2880,v_ITo3sCnpw_k_c007,295,14,17,12,5,2,0.705882,0.857143,0.862674,0.716369,8.0
5983,v_dw7LOz17Omg_c053,511,12,15,10,5,2,0.666667,0.833333,0.861616,0.707311,8.0
3109,v_ITo3sCnpw_k_c007,524,15,23,15,8,0,0.652174,1.000000,0.916593,0.713410,8.0
2226,v_G-vNjfx1GGc_c601,122,15,15,12,3,3,0.800000,0.800000,0.908992,0.790176,7.5
2287,v_G-vNjfx1GGc_c601,183,17,17,14,3,3,0.823529,0.823529,0.887132,0.804026,7.5
2691,v_ITo3sCnpw_k_c007,106,14,14,11,3,3,0.785714,0.785714,0.924211,0.742281,7.5
2281,v_G-vNjfx1GGc_c601,177,17,22,16,6,1,0.727273,0.941176,0.891881,0.750839,7.5
5976,v_dw7LOz17Omg_c053,504,12,17,11,6,1,0.647059,0.916667,0.901428,0.672969,7.5
1626,v_G-vNjfx1GGc_c600,22,12,9,8,1,4,0.888889,0.666667,0.825258,0.785259,7.0
5493,v_dw7LOz17Omg_c053,21,20,17,16,1,4,0.941176,0.800000,0.879132,0.766080,7.0
2161,v_G-vNjfx1GGc_c601,57,15,17,13,4,2,0.764706,0.866667,0.930960,0.836562,7.0
2278,v_G-vNjfx1GGc_c601,174,17,19,15,4,2,0.789474,0.882353,0.893541,0.777832,7.0
2301,v_G-vNjfx1GGc_c601,197,15,17,13,4,2,0.764706,0.866667,0.833106,0.723854,7.0
2735,v_ITo3sCnpw_k_c007,150,14,16,12,4,2,0.750000,0.857143,0.913043,0.750257,7.0
2742,v_ITo3sCnpw_k_c007,157,13,15,11,4,2,0.733333,0.846154,0.900085,0.760387,7.0
2816,v_ITo3sCnpw_k_c007,231,16,18,14,4,2,0.777778,0.875000,0.886591,0.739628,7.0
2871,v_ITo3sCnpw_k_c007,286,15,17,13,4,2,0.764706,0.866667,0.884208,0.729497,7.0
2875,v_ITo3sCnpw_k_c007,290,14,16,12,4,2,0.750000,0.857143,0.865994,0.752393,7.0
2876,v_ITo3sCnpw_k_c007,291,14,16,12,4,2,0.750000,0.857143,0.887558,0.757898,7.0
6229,v_dw7LOz17Omg_c067,207,18,20,16,4,2,0.800000,0.888889,0.919767,0.860603,7.0
5996,v_dw7LOz17Omg_c053,524,11,18,11,7,0,0.611111,1.000000,0.910263,0.694372,7.0

========== TOP 20 FN-HEAVY FRAMES ==========

,sequence,frame,gt,predictions,tp,fp,fn,precision,recall,difficulty
1628,v_G-vNjfx1GGc_c600,24,13,10,8,2,5,0.800000,0.615385,9.5
1629,v_G-vNjfx1GGc_c600,25,13,11,9,2,4,0.818182,0.692308,8.0
5503,v_dw7LOz17Omg_c053,31,20,18,16,2,4,0.888889,0.800000,8.0
1626,v_G-vNjfx1GGc_c600,22,12,9,8,1,4,0.888889,0.666667,7.0
5493,v_dw7LOz17Omg_c053,21,20,17,16,1,4,0.941176,0.800000,7.0
1622,v_G-vNjfx1GGc_c600,18,13,9,9,0,4,1.000000,0.692308,6.0
1623,v_G-vNjfx1GGc_c600,19,12,8,8,0,4,1.000000,0.666667,6.0
5490,v_dw7LOz17Omg_c053,18,20,16,16,0,4,1.000000,0.800000,6.0
5498,v_dw7LOz17Omg_c053,26,20,16,16,0,4,1.000000,0.800000,6.0
5499,v_dw7LOz17Omg_c053,27,20,16,16,0,4,1.000000,0.800000,6.0
5501,v_dw7LOz17Omg_c053,29,20,16,16,0,4,1.000000,0.800000,6.0
5502,v_dw7LOz17Omg_c053,30,20,16,16,0,4,1.000000,0.800000,6.0
2226,v_G-vNjfx1GGc_c601,122,15,15,12,3,3,0.800000,0.800000,7.5
2287,v_G-vNjfx1GGc_c601,183,17,17,14,3,3,0.823529,0.823529,7.5
2691,v_ITo3sCnpw_k_c007,106,14,14,11,3,3,0.785714,0.785714,7.5
1151,v_G-vNjfx1GGc_c008,27,13,12,10,2,3,0.833333,0.769231,6.5
1162,v_G-vNjfx1GGc_c008,38,13,12,10,2,3,0.833333,0.769231,6.5
1627,v_G-vNjfx1GGc_c600,23,12,11,9,2,3,0.818182,0.750000,6.5
1630,v_G-vNjfx1GGc_c600,26,12,11,9,2,3,0.818182,0.750000,6.5
1632,v_G-vNjfx1GGc_c600,28,12,11,9,2,3,0.818182,0.750000,6.5

========== TOP 20 FP-HEAVY FRAMES ==========

,sequence,frame,gt,predictions,tp,fp,fn,precision,recall,difficulty
6508,v_i2_L4qquVg0_c006,36,1,14,0,14,1,0.000000,0.000000,15.5
3109,v_ITo3sCnpw_k_c007,524,15,23,15,8,0,0.652174,1.000000,8.0
2304,v_G-vNjfx1GGc_c601,200,13,19,12,7,1,0.631579,0.923077,8.5
5996,v_dw7LOz17Omg_c053,524,11,18,11,7,0,0.611111,1.000000,7.0
6228,v_dw7LOz17Omg_c067,206,18,22,16,6,2,0.727273,0.888889,9.0
2281,v_G-vNjfx1GGc_c601,177,17,22,16,6,1,0.727273,0.941176,7.5
5976,v_dw7LOz17Omg_c053,504,12,17,11,6,1,0.647059,0.916667,7.5
2331,v_G-vNjfx1GGc_c601,227,10,16,10,6,0,0.625000,1.000000,6.0
3107,v_ITo3sCnpw_k_c007,522,15,21,15,6,0,0.714286,1.000000,6.0
3108,v_ITo3sCnpw_k_c007,523,15,21,15,6,0,0.714286,1.000000,6.0
4903,v_ITo3sCnpw_k_c012,281,16,22,16,6,0,0.727273,1.000000,6.0
5994,v_dw7LOz17Omg_c053,522,12,18,12,6,0,0.666667,1.000000,6.0
5999,v_dw7LOz17Omg_c053,527,11,17,11,6,0,0.647059,1.000000,6.0
6000,v_dw7LOz17Omg_c053,528,11,17,11,6,0,0.647059,1.000000,6.0
8266,v_i2_L4qquVg0_c009,455,17,23,17,6,0,0.739130,1.000000,6.0
1406,v_G-vNjfx1GGc_c008,282,11,14,9,5,2,0.642857,0.818182,8.0
2042,v_G-vNjfx1GGc_c600,438,11,14,9,5,2,0.642857,0.818182,8.0
2690,v_ITo3sCnpw_k_c007,105,14,17,12,5,2,0.705882,0.857143,8.0
2880,v_ITo3sCnpw_k_c007,295,14,17,12,5,2,0.705882,0.857143,8.0
5983,v_dw7LOz17Omg_c053,511,12,15,10,5,2,0.666667,0.833333,8.0

========== SEQUENCE-LEVEL SUMMARY ==========

,images,gt,predictions,tp,fp,fn,mean_difficulty,max_difficulty,precision,recall
sequence,,,,,,,,,,
v_G-vNjfx1GGc_c601,481,5554,5915,5159,756,395,2.803534,8.5,0.872189,0.928880
v_ITo3sCnpw_k_c007,701,9780,10508,9401,1107,379,2.390157,8.0,0.894652,0.961247
v_G-vNjfx1GGc_c600,500,5462,5943,5196,747,266,2.292000,9.5,0.874306,0.951300
v_G-vNjfx1GGc_c008,480,4573,5103,4370,733,203,2.161458,8.0,0.856359,0.955609
v_G-vNjfx1GGc_c004,675,8137,8788,7908,880,229,1.812593,6.5,0.899863,0.971857
v_i2_L4qquVg0_c006,888,11900,11900,11312,588,588,1.655405,15.5,0.950588,0.950588
v_dw7LOz17Omg_c067,450,6959,7526,6908,618,51,1.543333,9.0,0.917885,0.992671
v_ITo3sCnpw_k_c011,776,9736,10755,9692,1063,44,1.454897,5.0,0.901162,0.995481
v_dw7LOz17Omg_c053,550,8829,9106,8624,482,205,1.435455,8.0,0.947068,0.976781
v_2QhNRucNC7E_c017,450,6622,7064,6546,518,76,1.404444,4.5,0.926670,0.988523
v_i2_L4qquVg0_c009,488,7936,8290,7817,473,119,1.335041,6.5,0.942943,0.985005
v_ITo3sCnpw_k_c012,850,10832,11695,10761,934,71,1.224118,6.0,0.920137,0.993445
v_ITo3sCnpw_k_c010,560,7705,7976,7575,401,130,1.064286,6.0,0.949724,0.983128
v_i2_L4qquVg0_c010,758,8262,8749,8191,558,71,0.876649,6.0,0.936221,0.991406
v_i2_L4qquVg0_c007,451,4828,5078,4820,258,8,0.598670,5.5,0.949193,0.998343

In [19]:
# ============================================================
# HARD FRAME VISUALIZATION
# ============================================================

import pandas as pd
import numpy as np
import cv2
import matplotlib.pyplot as plt
from pathlib import Path

# ------------------------------------------------------------
# Load mining results
# ------------------------------------------------------------

results_path = Path(
    "/content/drive/MyDrive/AthletiQ/sportsmot/"
    "experiments/yolov26m_sportsmot/mining_results.csv"
)

df = pd.read_csv(results_path)

# ------------------------------------------------------------
# Sequences we want to inspect
# ------------------------------------------------------------

target_sequences = [
    "v_G-vNjfx1GGc_c601",
    "v_G-vNjfx1GGc_c600",
    "v_ITo3sCnpw_k_c007",
    "v_G-vNjfx1GGc_c008",
    "v_dw7LOz17Omg_c053",
]

# Exclude c006 because of the known duplicate-label issue
df_visual = df[
    df["sequence"].isin(target_sequences)
].copy()

# ------------------------------------------------------------
# Select representative hard frames
#
# We take:
#   1. Highest difficulty
#   2. Highest FN
#   3. Highest FP
# ------------------------------------------------------------

selected_rows = []

for sequence in target_sequences:

    seq_df = df_visual[
        df_visual["sequence"] == sequence
    ]

    # Highest difficulty
    selected_rows.append(
        seq_df.sort_values(
            "difficulty",
            ascending=False
        ).iloc[0]
    )

    # Highest FN
    selected_rows.append(
        seq_df.sort_values(
            ["fn", "difficulty"],
            ascending=False
        ).iloc[0]
    )

    # Highest FP
    selected_rows.append(
        seq_df.sort_values(
            ["fp", "difficulty"],
            ascending=False
        ).iloc[0]
    )

# Remove duplicate frames
selected_df = pd.DataFrame(
    selected_rows
).drop_duplicates(
    subset=["image_path"]
)

print(
    "Selected frames:",
    len(selected_df)
)

display(
    selected_df[
        [
            "sequence",
            "frame",
            "gt",
            "predictions",
            "tp",
            "fp",
            "fn",
            "precision",
            "recall",
            "difficulty"
        ]
    ]
)

# ------------------------------------------------------------
# Output directory
# ------------------------------------------------------------

output_dir = Path(
    "/content/drive/MyDrive/AthletiQ/sportsmot/"
    "experiments/yolov26m_sportsmot/hard_visualizations"
)

output_dir.mkdir(
    parents=True,
    exist_ok=True
)

# ------------------------------------------------------------
# Helper: draw boxes
# ------------------------------------------------------------

def draw_boxes(
    image,
    boxes,
    color,
    thickness=2,
    label=None
):

    output = image.copy()

    for box in boxes:

        x1, y1, x2, y2 = map(
            int,
            box
        )

        cv2.rectangle(
            output,
            (x1, y1),
            (x2, y2),
            color,
            thickness
        )

        if label:

            cv2.putText(
                output,
                label,
                (x1, max(y1 - 5, 15)),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.45,
                color,
                1,
                cv2.LINE_AA
            )

    return output


# ------------------------------------------------------------
# Generate individual visualizations
# ------------------------------------------------------------

for _, row in selected_df.iterrows():

    image_path = Path(
        row["image_path"]
    )

    image = cv2.imread(
        str(image_path)
    )

    if image is None:
        print(
            "Could not read:",
            image_path
        )
        continue

    height, width = image.shape[:2]

    # ----------------------------
    # Ground truth
    # ----------------------------

    label_path = (
        VAL_LABELS
        / row["sequence"]
        / f"{row['frame']}.txt"
    )

    gt_yolo = load_yolo_labels(
        label_path
    )

    gt_boxes = yolo_to_xyxy(
        gt_yolo,
        width,
        height
    )

    # ----------------------------
    # YOLO prediction
    # ----------------------------

    prediction = model.predict(
        source=str(image_path),
        conf=CONF_THRESHOLD,
        imgsz=IMAGE_SIZE,
        device=0,
        verbose=False
    )[0]

    pred_boxes = (
        prediction.boxes.xyxy
        .cpu()
        .numpy()
    )

    # ----------------------------
    # Draw
    # ----------------------------

    # Green = GT
    visual = draw_boxes(
        image,
        gt_boxes,
        color=(0, 255, 0),
        thickness=2
    )

    # Red = predictions
    visual = draw_boxes(
        visual,
        pred_boxes,
        color=(0, 0, 255),
        thickness=2
    )

    # Convert BGR -> RGB
    visual_rgb = cv2.cvtColor(
        visual,
        cv2.COLOR_BGR2RGB
    )

    # ----------------------------
    # Save image
    # ----------------------------

    filename = (
        f"{row['sequence']}"
        f"_frame_{row['frame']}"
        f"_diff_{row['difficulty']}.jpg"
    )

    save_path = (
        output_dir / filename
    )

    cv2.imwrite(
        str(save_path),
        visual
    )

    # ----------------------------
    # Display
    # ----------------------------

    plt.figure(
        figsize=(16, 9)
    )

    plt.imshow(
        visual_rgb
    )

    plt.title(
        f"{row['sequence']} | "
        f"Frame {row['frame']} | "
        f"GT={int(row['gt'])} | "
        f"Pred={int(row['predictions'])} | "
        f"TP={int(row['tp'])} | "
        f"FP={int(row['fp'])} | "
        f"FN={int(row['fn'])} | "
        f"Difficulty={row['difficulty']}"
    )

    plt.axis("off")
    plt.show()

print("\n========== VISUALIZATION COMPLETE ==========")
print("Saved to:")
print(output_dir)

Output hidden; open in https://colab.research.google.com to view.

In [20]:
# ============================================================
# CONFIDENCE + NMS SWEEP ON HARD FRAMES
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

# ------------------------------------------------------------
# Load mining results
# ------------------------------------------------------------

results_path = Path(
    "/content/drive/MyDrive/AthletiQ/sportsmot/"
    "experiments/yolov26m_sportsmot/mining_results.csv"
)

df = pd.read_csv(results_path)

# ------------------------------------------------------------
# Hard sequences selected from visual analysis
# ------------------------------------------------------------

target_sequences = [
    "v_G-vNjfx1GGc_c601",
    "v_G-vNjfx1GGc_c600",
    "v_ITo3sCnpw_k_c007",
    "v_G-vNjfx1GGc_c008",
    "v_dw7LOz17Omg_c053",
]

hard_df = df[
    df["sequence"].isin(target_sequences)
].copy()

# Select top 30 hardest frames from these sequences
hard_df = hard_df.sort_values(
    "difficulty",
    ascending=False
).head(30)

print("Hard frames used:", len(hard_df))

display(
    hard_df[
        [
            "sequence",
            "frame",
            "gt",
            "predictions",
            "tp",
            "fp",
            "fn",
            "difficulty"
        ]
    ]
)

# ------------------------------------------------------------
# Load GT
# ------------------------------------------------------------

def get_gt_boxes(image_path, sequence, frame):
    image = cv2.imread(str(image_path))

    if image is None:
        return None

    h, w = image.shape[:2]

    label_path = (
        VAL_LABELS
        / sequence
        / f"{int(frame):06d}.txt"
    )

    gt_yolo = load_yolo_labels(label_path)

    return yolo_to_xyxy(
        gt_yolo,
        w,
        h
    )


# ------------------------------------------------------------
# IoU function
# ------------------------------------------------------------

def box_iou(box_a, box_b):

    x1 = max(box_a[0], box_b[0])
    y1 = max(box_a[1], box_b[1])
    x2 = min(box_a[2], box_b[2])
    y2 = min(box_a[3], box_b[3])

    inter_w = max(0, x2 - x1)
    inter_h = max(0, y2 - y1)

    inter = inter_w * inter_h

    area_a = max(
        0,
        box_a[2] - box_a[0]
    ) * max(
        0,
        box_a[3] - box_a[1]
    )

    area_b = max(
        0,
        box_b[2] - box_b[0]
    ) * max(
        0,
        box_b[3] - box_b[1]
    )

    union = area_a + area_b - inter

    if union <= 0:
        return 0.0

    return inter / union


# ------------------------------------------------------------
# Match predictions to GT
# ------------------------------------------------------------

def evaluate_predictions(
    gt_boxes,
    pred_boxes,
    iou_threshold=0.50
):

    if len(gt_boxes) == 0:

        return (
            0,
            len(pred_boxes),
            0
        )

    if len(pred_boxes) == 0:

        return (
            0,
            0,
            len(gt_boxes)
        )

    matches = []

    for pi, pred in enumerate(pred_boxes):

        for gi, gt in enumerate(gt_boxes):

            iou = box_iou(
                pred,
                gt
            )

            if iou >= iou_threshold:

                matches.append(
                    (
                        iou,
                        pi,
                        gi
                    )
                )

    # Highest IoU first
    matches.sort(
        reverse=True
    )

    matched_preds = set()
    matched_gts = set()

    tp = 0

    for iou, pi, gi in matches:

        if pi in matched_preds:
            continue

        if gi in matched_gts:
            continue

        matched_preds.add(pi)
        matched_gts.add(gi)

        tp += 1

    fp = len(pred_boxes) - tp
    fn = len(gt_boxes) - tp

    return tp, fp, fn


# ------------------------------------------------------------
# Parameter grid
# ------------------------------------------------------------

confidence_values = [
    0.20,
    0.25,
    0.30,
    0.35,
    0.40,
    0.50
]

nms_values = [
    0.40,
    0.45,
    0.50,
    0.55,
    0.60
]

# ------------------------------------------------------------
# Run sweep
# ------------------------------------------------------------

sweep_results = []

for conf in confidence_values:

    for nms_iou in nms_values:

        total_gt = 0
        total_pred = 0
        total_tp = 0
        total_fp = 0
        total_fn = 0

        for _, row in hard_df.iterrows():

            image_path = Path(
                row["image_path"]
            )

            gt_boxes = get_gt_boxes(
                image_path,
                row["sequence"],
                row["frame"]
            )

            if gt_boxes is None:
                continue

            prediction = model.predict(
                source=str(image_path),
                conf=conf,
                iou=nms_iou,
                imgsz=IMAGE_SIZE,
                device=0,
                verbose=False
            )[0]

            pred_boxes = (
                prediction.boxes.xyxy
                .cpu()
                .numpy()
            )

            tp, fp, fn = evaluate_predictions(
                gt_boxes,
                pred_boxes,
                iou_threshold=0.50
            )

            total_gt += len(gt_boxes)
            total_pred += len(pred_boxes)

            total_tp += tp
            total_fp += fp
            total_fn += fn

        precision = (
            total_tp /
            (total_tp + total_fp)
            if total_tp + total_fp > 0
            else 0
        )

        recall = (
            total_tp /
            (total_tp + total_fn)
            if total_tp + total_fn > 0
            else 0
        )

        f1 = (
            2 * precision * recall /
            (precision + recall)
            if precision + recall > 0
            else 0
        )

        sweep_results.append({
            "confidence": conf,
            "nms_iou": nms_iou,
            "gt": total_gt,
            "predictions": total_pred,
            "tp": total_tp,
            "fp": total_fp,
            "fn": total_fn,
            "precision": precision,
            "recall": recall,
            "f1": f1
        })

        print(
            f"conf={conf:.2f} | "
            f"nms={nms_iou:.2f} | "
            f"TP={total_tp} | "
            f"FP={total_fp} | "
            f"FN={total_fn} | "
            f"P={precision:.4f} | "
            f"R={recall:.4f} | "
            f"F1={f1:.4f}"
        )


# ------------------------------------------------------------
# Results table
# ------------------------------------------------------------

sweep_df = pd.DataFrame(
    sweep_results
)

sweep_df = sweep_df.sort_values(
    "f1",
    ascending=False
)

print("\n========== BEST CONFIGURATIONS ==========")

display(
    sweep_df.head(15)
)

# ------------------------------------------------------------
# Save results
# ------------------------------------------------------------

save_path = (
    Path(
        "/content/drive/MyDrive/AthletiQ/sportsmot/"
        "experiments/yolov26m_sportsmot/"
        "confidence_nms_sweep.csv"
    )
)

sweep_df.to_csv(
    save_path,
    index=False
)

print("\nSaved:")
print(save_path)

Hard frames used: 30

                sequence  frame  gt  predictions  tp  fp  fn  difficulty
1628  v_G-vNjfx1GGc_c600     24  13           10   8   2   5         9.5
2304  v_G-vNjfx1GGc_c601    200  13           19  12   7   1         8.5
2690  v_ITo3sCnpw_k_c007    105  14           17  12   5   2         8.0
5503  v_dw7LOz17Omg_c053     31  20           18  16   2   4         8.0
1406  v_G-vNjfx1GGc_c008    282  11           14   9   5   2         8.0
2042  v_G-vNjfx1GGc_c600    438  11           14   9   5   2         8.0
2880  v_ITo3sCnpw_k_c007    295  14           17  12   5   2         8.0
5983  v_dw7LOz17Omg_c053    511  12           15  10   5   2         8.0
1629  v_G-vNjfx1GGc_c600     25  13           11   9   2   4         8.0
3109  v_ITo3sCnpw_k_c007    524  15           23  15   8   0         8.0
2287  v_G-vNjfx1GGc_c601    183  17           17  14   3   3         7.5
2691  v_ITo3sCnpw_k_c007    106  14           14  11   3   3         7.5
2281  v_G-vNjfx1GGc_c601    177  17           22  16   6   1         7.5
5976  v_dw7LOz17Omg_c053    504  12           17  11   6   1         7.5
2226  v_G-vNjfx1GGc_c601    122  15           15  12   3   3         7.5
1626  v_G-vNjfx1GGc_c600     22  12            9   8   1   4         7.0
2876  v_ITo3sCnpw_k_c007    291  14           16  12   4   2         7.0
2875  v_ITo3sCnpw_k_c007    290  14           16  12   4   2         7.0
5493  v_dw7LOz17Omg_c053     21  20           17  16   1   4         7.0
2278  v_G-vNjfx1GGc_c601    174  17           19  15   4   2         7.0
2816  v_ITo3sCnpw_k_c007    231  16           18  14   4   2         7.0
2742  v_ITo3sCnpw_k_c007    157  13           15  11   4   2         7.0
2735  v_ITo3sCnpw_k_c007    150  14           16  12   4   2         7.0
5996  v_dw7LOz17Omg_c053    524  11           18  11   7   0         7.0
2301  v_G-vNjfx1GGc_c601    197  15           17  13   4   2         7.0
2161  v_G-vNjfx1GGc_c601     57  15           17  13   4   2         7.0
2871  v_ITo3sCnpw_k_c007    286  15           17  13   4   2         7.0
1636  v_G-vNjfx1GGc_c600     32  11           10   8   2   3         6.5
2811  v_ITo3sCnpw_k_c007    226  15           14  12   2   3         6.5
2812  v_ITo3sCnpw_k_c007    227  15           14  12   2   3         6.5

conf=0.20 | nms=0.40 | TP=357 | FP=77 | FN=71 | P=0.8226 | R=0.8341 | F1=0.8283
conf=0.20 | nms=0.45 | TP=359 | FP=83 | FN=69 | P=0.8122 | R=0.8388 | F1=0.8253
conf=0.20 | nms=0.50 | TP=362 | FP=88 | FN=66 | P=0.8044 | R=0.8458 | F1=0.8246
conf=0.20 | nms=0.55 | TP=364 | FP=100 | FN=64 | P=0.7845 | R=0.8505 | F1=0.8161
conf=0.20 | nms=0.60 | TP=366 | FP=107 | FN=62 | P=0.7738 | R=0.8551 | F1=0.8124
conf=0.25 | nms=0.40 | TP=347 | FP=72 | FN=81 | P=0.8282 | R=0.8107 | F1=0.8194
conf=0.25 | nms=0.45 | TP=349 | FP=77 | FN=79 | P=0.8192 | R=0.8154 | F1=0.8173
conf=0.25 | nms=0.50 | TP=352 | FP=78 | FN=76 | P=0.8186 | R=0.8224 | F1=0.8205
conf=0.25 | nms=0.55 | TP=353 | FP=90 | FN=75 | P=0.7968 | R=0.8248 | F1=0.8106
conf=0.25 | nms=0.60 | TP=356 | FP=96 | FN=72 | P=0.7876 | R=0.8318 | F1=0.8091
conf=0.30 | nms=0.40 | TP=347 | FP=70 | FN=81 | P=0.8321 | R=0.8107 | F1=0.8213
conf=0.30 | nms=0.45 | TP=348 | FP=73 | FN=80 | P=0.8266 | R=0.8131 | F1=0.8198
conf=0.30 | nms=0.50 | TP=349 | FP=73 | FN=79 | P=0.8270 | R=0.8154 | F1=0.8212
conf=0.30 | nms=0.55 | TP=350 | FP=80 | FN=78 | P=0.8140 | R=0.8178 | F1=0.8159
conf=0.30 | nms=0.60 | TP=353 | FP=84 | FN=75 | P=0.8078 | R=0.8248 | F1=0.8162
conf=0.35 | nms=0.40 | TP=345 | FP=66 | FN=83 | P=0.8394 | R=0.8061 | F1=0.8224
conf=0.35 | nms=0.45 | TP=346 | FP=69 | FN=82 | P=0.8337 | R=0.8084 | F1=0.8209
conf=0.35 | nms=0.50 | TP=347 | FP=69 | FN=81 | P=0.8341 | R=0.8107 | F1=0.8223
conf=0.35 | nms=0.55 | TP=348 | FP=73 | FN=80 | P=0.8266 | R=0.8131 | F1=0.8198
conf=0.35 | nms=0.60 | TP=350 | FP=76 | FN=78 | P=0.8216 | R=0.8178 | F1=0.8197
conf=0.40 | nms=0.40 | TP=344 | FP=60 | FN=84 | P=0.8515 | R=0.8037 | F1=0.8269
conf=0.40 | nms=0.45 | TP=345 | FP=62 | FN=83 | P=0.8477 | R=0.8061 | F1=0.8263
conf=0.40 | nms=0.50 | TP=346 | FP=62 | FN=82 | P=0.8480 | R=0.8084 | F1=0.8278
conf=0.40 | nms=0.55 | TP=347 | FP=66 | FN=81 | P=0.8402 | R=0.8107 | F1=0.8252
conf=0.40 | nms=0.60 | TP=348 | FP=69 | FN=80 | P=0.8345 | R=0.8131 | F1=0.8237
conf=0.50 | nms=0.40 | TP=337 | FP=49 | FN=91 | P=0.8731 | R=0.7874 | F1=0.8280
conf=0.50 | nms=0.45 | TP=339 | FP=49 | FN=89 | P=0.8737 | R=0.7921 | F1=0.8309
conf=0.50 | nms=0.50 | TP=340 | FP=50 | FN=88 | P=0.8718 | R=0.7944 | F1=0.8313
conf=0.50 | nms=0.55 | TP=340 | FP=53 | FN=88 | P=0.8651 | R=0.7944 | F1=0.8283
conf=0.50 | nms=0.60 | TP=341 | FP=53 | FN=87 | P=0.8655 | R=0.7967 | F1=0.8297

========== BEST CONFIGURATIONS ==========

,confidence,nms_iou,gt,predictions,tp,fp,fn,precision,recall,f1
27,0.50,0.50,428,390,340,50,88,0.871795,0.794393,0.831296
26,0.50,0.45,428,388,339,49,89,0.873711,0.792056,0.830882
29,0.50,0.60,428,394,341,53,87,0.865482,0.796729,0.829684
0,0.20,0.40,428,434,357,77,71,0.822581,0.834112,0.828306
28,0.50,0.55,428,393,340,53,88,0.865140,0.794393,0.828258
25,0.50,0.40,428,386,337,49,91,0.873057,0.787383,0.828010
22,0.40,0.50,428,408,346,62,82,0.848039,0.808411,0.827751
20,0.40,0.40,428,404,344,60,84,0.851485,0.803738,0.826923
21,0.40,0.45,428,407,345,62,83,0.847666,0.806075,0.826347
1,0.20,0.45,428,442,359,83,69,0.812217,0.838785,0.825287
23,0.40,0.55,428,413,347,66,81,0.840194,0.810748,0.825208
2,0.20,0.50,428,450,362,88,66,0.804444,0.845794,0.824601
24,0.40,0.60,428,417,348,69,80,0.834532,0.813084,0.823669
15,0.35,0.40,428,411,345,66,83,0.839416,0.806075,0.822408
17,0.35,0.50,428,416,347,69,81,0.834135,0.810748,0.822275

Saved:
/content/drive/MyDrive/AthletiQ/sportsmot/experiments/yolov26m_sportsmot/confidence_nms_sweep.csv

In [21]:
# ============================================================
# FULL SPORTSMOT VALIDATION
# CONFIDENCE + NMS COMPARISON
# ============================================================

import cv2
import pandas as pd
import numpy as np
from pathlib import Path
from time import time

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------

PROJECT_ROOT = Path(
    "/content/AthletiQ"
)

DATASET_ROOT = (
    PROJECT_ROOT
    / "datasets/football/processed/sportsmot_yolo"
)

VAL_IMAGES_ROOT = (
    DATASET_ROOT / "images" / "val"
)

VAL_LABELS_ROOT = (
    DATASET_ROOT / "labels" / "val"
)

OUTPUT_ROOT = Path(
    "/content/drive/MyDrive/AthletiQ/sportsmot/"
    "experiments/yolov26m_sportsmot"
)

OUTPUT_ROOT.mkdir(
    parents=True,
    exist_ok=True
)

# ------------------------------------------------------------
# Configurations
# ------------------------------------------------------------

CONFIGS = [
    {
        "name": "baseline",
        "confidence": 0.25,
        "nms_iou": 0.50
    },
    {
        "name": "candidate_A",
        "confidence": 0.30,
        "nms_iou": 0.40
    },
    {
        "name": "candidate_B",
        "confidence": 0.40,
        "nms_iou": 0.40
    },
    {
        "name": "candidate_C",
        "confidence": 0.50,
        "nms_iou": 0.45
    }
]

IMAGE_SIZE = 1280
BATCH_SIZE = 8
MATCH_IOU = 0.50

# ------------------------------------------------------------
# Collect validation images recursively
# ------------------------------------------------------------

image_paths = sorted(
    VAL_IMAGES_ROOT.rglob("*.jpg")
)

print(
    f"Validation images found: {len(image_paths):,}"
)

assert len(image_paths) == 9058, (
    f"Expected 9058 validation images, "
    f"found {len(image_paths)}"
)

# ------------------------------------------------------------
# IoU
# ------------------------------------------------------------

def box_iou(box_a, box_b):

    x1 = max(box_a[0], box_b[0])
    y1 = max(box_a[1], box_b[1])

    x2 = min(box_a[2], box_b[2])
    y2 = min(box_a[3], box_b[3])

    inter_w = max(
        0,
        x2 - x1
    )

    inter_h = max(
        0,
        y2 - y1
    )

    inter = (
        inter_w *
        inter_h
    )

    area_a = (
        max(0, box_a[2] - box_a[0]) *
        max(0, box_a[3] - box_a[1])
    )

    area_b = (
        max(0, box_b[2] - box_b[0]) *
        max(0, box_b[3] - box_b[1])
    )

    union = (
        area_a +
        area_b -
        inter
    )

    if union <= 0:
        return 0.0

    return inter / union


# ------------------------------------------------------------
# Greedy GT/prediction matching
# ------------------------------------------------------------

def match_boxes(
    gt_boxes,
    pred_boxes,
    threshold=0.50
):

    if len(gt_boxes) == 0:

        return (
            0,
            len(pred_boxes),
            0
        )

    if len(pred_boxes) == 0:

        return (
            0,
            0,
            len(gt_boxes)
        )

    candidates = []

    for pi, pred in enumerate(pred_boxes):

        for gi, gt in enumerate(gt_boxes):

            iou = box_iou(
                pred,
                gt
            )

            if iou >= threshold:

                candidates.append(
                    (
                        iou,
                        pi,
                        gi
                    )
                )

    candidates.sort(
        reverse=True
    )

    matched_predictions = set()
    matched_gt = set()

    tp = 0

    for iou, pi, gi in candidates:

        if pi in matched_predictions:
            continue

        if gi in matched_gt:
            continue

        matched_predictions.add(pi)
        matched_gt.add(gi)

        tp += 1

    fp = (
        len(pred_boxes) -
        tp
    )

    fn = (
        len(gt_boxes) -
        tp
    )

    return tp, fp, fn


# ------------------------------------------------------------
# Load YOLO GT labels
# ------------------------------------------------------------

def load_gt_for_image(image_path):

    image = cv2.imread(
        str(image_path)
    )

    if image is None:
        raise RuntimeError(
            f"Could not read {image_path}"
        )

    h, w = image.shape[:2]

    sequence = image_path.parent.name
    frame = image_path.stem

    label_path = (
        VAL_LABELS_ROOT
        / sequence
        / f"{frame}.txt"
    )

    if not label_path.exists():

        raise FileNotFoundError(
            f"Missing label: {label_path}"
        )

    gt_boxes = []

    with open(
        label_path,
        "r"
    ) as f:

        for line in f:

            parts = line.strip().split()

            if len(parts) < 5:
                continue

            # YOLO:
            # class cx cy width height

            cx = float(parts[1]) * w
            cy = float(parts[2]) * h
            bw = float(parts[3]) * w
            bh = float(parts[4]) * h

            x1 = cx - bw / 2
            y1 = cy - bh / 2
            x2 = cx + bw / 2
            y2 = cy + bh / 2

            gt_boxes.append(
                [
                    x1,
                    y1,
                    x2,
                    y2
                ]
            )

    return np.asarray(
        gt_boxes,
        dtype=np.float32
    )


# ------------------------------------------------------------
# Run one configuration
# ------------------------------------------------------------

def evaluate_configuration(
    config
):

    name = config["name"]
    confidence = config["confidence"]
    nms_iou = config["nms_iou"]

    print("\n" + "=" * 70)
    print(
        f"RUNNING: {name} | "
        f"conf={confidence:.2f} | "
        f"NMS IoU={nms_iou:.2f}"
    )
    print("=" * 70)

    total_gt = 0
    total_predictions = 0
    total_tp = 0
    total_fp = 0
    total_fn = 0

    failed = 0

    start_time = time()

    # Process batches
    for start in range(
        0,
        len(image_paths),
        BATCH_SIZE
    ):

        batch_paths = image_paths[
            start:start + BATCH_SIZE
        ]

        try:

            predictions = model.predict(
                source=[
                    str(p)
                    for p in batch_paths
                ],
                conf=confidence,
                iou=nms_iou,
                imgsz=IMAGE_SIZE,
                device=0,
                batch=BATCH_SIZE,
                verbose=False
            )

        except Exception as e:

            print(
                f"\nERROR in batch "
                f"{start}: {e}"
            )

            failed += len(
                batch_paths
            )

            continue

        for image_path, result in zip(
            batch_paths,
            predictions
        ):

            try:

                gt_boxes = (
                    load_gt_for_image(
                        image_path
                    )
                )

                pred_boxes = (
                    result.boxes.xyxy
                    .detach()
                    .cpu()
                    .numpy()
                )

                tp, fp, fn = (
                    match_boxes(
                        gt_boxes,
                        pred_boxes,
                        MATCH_IOU
                    )
                )

                total_gt += len(
                    gt_boxes
                )

                total_predictions += len(
                    pred_boxes
                )

                total_tp += tp
                total_fp += fp
                total_fn += fn

            except Exception as e:

                print(
                    f"\nERROR processing "
                    f"{image_path}: {e}"
                )

                failed += 1

        # Progress every 500 images
        processed = min(
            start + BATCH_SIZE,
            len(image_paths)
        )

        if (
            processed % 500 < BATCH_SIZE
            or processed == len(image_paths)
        ):

            elapsed = time() - start_time

            print(
                f"Progress: "
                f"{processed:,}/"
                f"{len(image_paths):,} | "
                f"elapsed={elapsed/60:.1f} min"
            )

    precision = (
        total_tp /
        (total_tp + total_fp)
        if total_tp + total_fp > 0
        else 0
    )

    recall = (
        total_tp /
        (total_tp + total_fn)
        if total_tp + total_fn > 0
        else 0
    )

    f1 = (
        2 * precision * recall /
        (precision + recall)
        if precision + recall > 0
        else 0
    )

    elapsed = time() - start_time

    result = {
        "name": name,
        "confidence": confidence,
        "nms_iou": nms_iou,
        "images": len(image_paths),
        "failed": failed,
        "gt": total_gt,
        "predictions": total_predictions,
        "tp": total_tp,
        "fp": total_fp,
        "fn": total_fn,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "time_minutes": elapsed / 60
    }

    print("\nRESULT")
    print("-" * 70)

    for key, value in result.items():
        print(
            f"{key:20s}: {value}"
        )

    return result


# ------------------------------------------------------------
# Run all configurations
# ------------------------------------------------------------

all_results = []

for config in CONFIGS:

    result = evaluate_configuration(
        config
    )

    all_results.append(
        result
    )

    # Save after EVERY configuration
    # so a runtime disconnect does not
    # destroy completed results.

    partial_df = pd.DataFrame(
        all_results
    )

    partial_path = (
        OUTPUT_ROOT
        / "full_validation_threshold_sweep.csv"
    )

    partial_df.to_csv(
        partial_path,
        index=False
    )

    print(
        f"\nSaved partial results to:\n"
        f"{partial_path}"
    )


# ------------------------------------------------------------
# Final comparison
# ------------------------------------------------------------

results_df = pd.DataFrame(
    all_results
)

results_df = results_df.sort_values(
    "f1",
    ascending=False
)

print("\n")
print("=" * 80)
print("FINAL FULL-VALIDATION COMPARISON")
print("=" * 80)

display(
    results_df[
        [
            "name",
            "confidence",
            "nms_iou",
            "gt",
            "predictions",
            "tp",
            "fp",
            "fn",
            "precision",
            "recall",
            "f1",
            "failed",
            "time_minutes"
        ]
    ]
)

# ------------------------------------------------------------
# Save final results
# ------------------------------------------------------------

final_path = (
    OUTPUT_ROOT
    / "full_validation_threshold_sweep.csv"
)

results_df.to_csv(
    final_path,
    index=False
)

print(
    "\nFinal results saved to:"
)

print(final_path)

Validation images found: 9,058

======================================================================
RUNNING: baseline | conf=0.25 | NMS IoU=0.50
======================================================================
Progress: 504/9,058 | elapsed=0.7 min
Progress: 1,000/9,058 | elapsed=1.3 min
Progress: 1,504/9,058 | elapsed=2.0 min
Progress: 2,000/9,058 | elapsed=2.7 min
Progress: 2,504/9,058 | elapsed=3.4 min
Progress: 3,000/9,058 | elapsed=4.0 min
Progress: 3,504/9,058 | elapsed=4.7 min
Progress: 4,000/9,058 | elapsed=5.4 min
Progress: 4,504/9,058 | elapsed=6.0 min
Progress: 5,000/9,058 | elapsed=6.7 min
Progress: 5,504/9,058 | elapsed=7.4 min
Progress: 6,000/9,058 | elapsed=8.0 min
Progress: 6,504/9,058 | elapsed=8.7 min
Progress: 7,000/9,058 | elapsed=9.4 min
Progress: 7,504/9,058 | elapsed=10.1 min
Progress: 8,000/9,058 | elapsed=10.7 min
Progress: 8,504/9,058 | elapsed=11.4 min
Progress: 9,000/9,058 | elapsed=12.1 min
Progress: 9,058/9,058 | elapsed=12.2 min

RESULT
----------------------------------------------------------------------
name                : baseline
confidence          : 0.25
nms_iou             : 0.5
images              : 9058
failed              : 0
gt                  : 117115
predictions         : 122201
tp                  : 113862
fp                  : 8339
fn                  : 3253
precision           : 0.931759969231021
recall              : 0.9722238825086453
f1                  : 0.9515619515619516
time_minutes        : 12.154749011993408

Saved partial results to:
/content/drive/MyDrive/AthletiQ/sportsmot/experiments/yolov26m_sportsmot/full_validation_threshold_sweep.csv

======================================================================
RUNNING: candidate_A | conf=0.30 | NMS IoU=0.40
======================================================================
Progress: 504/9,058 | elapsed=0.7 min
Progress: 1,000/9,058 | elapsed=1.4 min
Progress: 1,504/9,058 | elapsed=2.0 min
Progress: 2,000/9,058 | elapsed=2.7 min
Progress: 2,504/9,058 | elapsed=3.4 min
Progress: 3,000/9,058 | elapsed=4.0 min
Progress: 3,504/9,058 | elapsed=4.7 min
Progress: 4,000/9,058 | elapsed=5.4 min
Progress: 4,504/9,058 | elapsed=6.1 min
Progress: 5,000/9,058 | elapsed=6.7 min
Progress: 5,504/9,058 | elapsed=7.4 min
Progress: 6,000/9,058 | elapsed=8.1 min
Progress: 6,504/9,058 | elapsed=8.8 min
Progress: 7,000/9,058 | elapsed=9.4 min
Progress: 7,504/9,058 | elapsed=10.1 min
Progress: 8,000/9,058 | elapsed=10.8 min
Progress: 8,504/9,058 | elapsed=11.5 min
Progress: 9,000/9,058 | elapsed=12.1 min
Progress: 9,058/9,058 | elapsed=12.2 min

RESULT
----------------------------------------------------------------------
name                : candidate_A
confidence          : 0.3
nms_iou             : 0.4
images              : 9058
failed              : 0
gt                  : 117115
predictions         : 120489
tp                  : 113107
fp                  : 7382
fn                  : 4008
precision           : 0.9387329963731129
recall              : 0.9657772275114204
f1                  : 0.9520630965808656
time_minutes        : 12.204770004749298

Saved partial results to:
/content/drive/MyDrive/AthletiQ/sportsmot/experiments/yolov26m_sportsmot/full_validation_threshold_sweep.csv

======================================================================
RUNNING: candidate_B | conf=0.40 | NMS IoU=0.40
======================================================================
Progress: 504/9,058 | elapsed=0.7 min
Progress: 1,000/9,058 | elapsed=1.4 min
Progress: 1,504/9,058 | elapsed=2.0 min
Progress: 2,000/9,058 | elapsed=2.7 min
Progress: 2,504/9,058 | elapsed=3.4 min
Progress: 3,000/9,058 | elapsed=4.0 min
Progress: 3,504/9,058 | elapsed=4.7 min
Progress: 4,000/9,058 | elapsed=5.4 min
Progress: 4,504/9,058 | elapsed=6.1 min
Progress: 5,000/9,058 | elapsed=6.7 min
Progress: 5,504/9,058 | elapsed=7.4 min
Progress: 6,000/9,058 | elapsed=8.1 min
Progress: 6,504/9,058 | elapsed=8.8 min
Progress: 7,000/9,058 | elapsed=9.4 min
Progress: 7,504/9,058 | elapsed=10.1 min
Progress: 8,000/9,058 | elapsed=10.8 min
Progress: 8,504/9,058 | elapsed=11.4 min
Progress: 9,000/9,058 | elapsed=12.1 min
Progress: 9,058/9,058 | elapsed=12.2 min

RESULT
----------------------------------------------------------------------
name                : candidate_B
confidence          : 0.4
nms_iou             : 0.4
images              : 9058
failed              : 0
gt                  : 117115
predictions         : 119324
tp                  : 112651
fp                  : 6673
fn                  : 4464
precision           : 0.9440766316918642
recall              : 0.9618836186654144
f1                  : 0.9528969417058946
time_minutes        : 12.176644539833068

Saved partial results to:
/content/drive/MyDrive/AthletiQ/sportsmot/experiments/yolov26m_sportsmot/full_validation_threshold_sweep.csv

======================================================================
RUNNING: candidate_C | conf=0.50 | NMS IoU=0.45
======================================================================
Progress: 504/9,058 | elapsed=0.7 min
Progress: 1,000/9,058 | elapsed=1.4 min
Progress: 1,504/9,058 | elapsed=2.0 min
Progress: 2,000/9,058 | elapsed=2.7 min
Progress: 2,504/9,058 | elapsed=3.4 min
Progress: 3,000/9,058 | elapsed=4.0 min
Progress: 3,504/9,058 | elapsed=4.7 min
Progress: 4,000/9,058 | elapsed=5.4 min
Progress: 4,504/9,058 | elapsed=6.1 min
Progress: 5,000/9,058 | elapsed=6.7 min
Progress: 5,504/9,058 | elapsed=7.4 min
Progress: 6,000/9,058 | elapsed=8.1 min
Progress: 6,504/9,058 | elapsed=8.8 min
Progress: 7,000/9,058 | elapsed=9.4 min
Progress: 7,504/9,058 | elapsed=10.1 min
Progress: 8,000/9,058 | elapsed=10.8 min
Progress: 8,504/9,058 | elapsed=11.4 min
Progress: 9,000/9,058 | elapsed=12.1 min
Progress: 9,058/9,058 | elapsed=12.2 min

RESULT
----------------------------------------------------------------------
name                : candidate_C
confidence          : 0.5
nms_iou             : 0.45
images              : 9058
failed              : 0
gt                  : 117115
predictions         : 118500
tp                  : 112375
fp                  : 6125
fn                  : 4740
precision           : 0.9483122362869199
recall              : 0.9595269606796738
f1                  : 0.9538866370986566
time_minutes        : 12.175244613488514

Saved partial results to:
/content/drive/MyDrive/AthletiQ/sportsmot/experiments/yolov26m_sportsmot/full_validation_threshold_sweep.csv


================================================================================
FINAL FULL-VALIDATION COMPARISON
================================================================================

,name,confidence,nms_iou,gt,predictions,tp,fp,fn,precision,recall,f1,failed,time_minutes
3,candidate_C,0.50,0.45,117115,118500,112375,6125,4740,0.948312,0.959527,0.953887,0,12.175245
2,candidate_B,0.40,0.40,117115,119324,112651,6673,4464,0.944077,0.961884,0.952897,0,12.176645
1,candidate_A,0.30,0.40,117115,120489,113107,7382,4008,0.938733,0.965777,0.952063,0,12.204770
0,baseline,0.25,0.50,117115,122201,113862,8339,3253,0.931760,0.972224,0.951562,0,12.154749

Final results saved to:
/content/drive/MyDrive/AthletiQ/sportsmot/experiments/yolov26m_sportsmot/full_validation_threshold_sweep.csv

In [22]:
# ============================================================
# ATHLETIQ MODEL 1
# BUILD TARGETED HARD-EXAMPLE FINE-TUNING DATASET
# ============================================================

import pandas as pd
import numpy as np
import shutil
from pathlib import Path

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------

PROJECT_ROOT = Path("/content/AthletiQ")

SOURCE_IMAGES = (
    PROJECT_ROOT
    / "datasets/football/processed/sportsmot_yolo/images/val"
)

SOURCE_LABELS = (
    PROJECT_ROOT
    / "datasets/football/processed/sportsmot_yolo/labels/val"
)

MINING_RESULTS = Path(
    "/content/drive/MyDrive/AthletiQ/sportsmot/"
    "experiments/yolov26m_sportsmot/mining_results.csv"
)

OUTPUT_ROOT = (
    PROJECT_ROOT
    / "datasets/football/processed/"
    "sportsmot_hard_finetune"
)

OUTPUT_IMAGES = OUTPUT_ROOT / "images/train"
OUTPUT_LABELS = OUTPUT_ROOT / "labels/train"

OUTPUT_IMAGES.mkdir(
    parents=True,
    exist_ok=True
)

OUTPUT_LABELS.mkdir(
    parents=True,
    exist_ok=True
)

# ------------------------------------------------------------
# Load mining results
# ------------------------------------------------------------

df = pd.read_csv(
    MINING_RESULTS
)

print(
    "Total mining records:",
    len(df)
)

# ------------------------------------------------------------
# Target sequences
# ------------------------------------------------------------

target_sequences = [
    "v_G-vNjfx1GGc_c601",
    "v_G-vNjfx1GGc_c600",
    "v_ITo3sCnpw_k_c007",
    "v_dw7LOz17Omg_c053",
    "v_G-vNjfx1GGc_c008",
]

# IMPORTANT:
# c006 is deliberately excluded because of
# the previously discovered duplicate GT annotations.

df = df[
    df["sequence"].isin(
        target_sequences
    )
].copy()

print(
    "Records in target sequences:",
    len(df)
)

# ------------------------------------------------------------
# Create difficulty score specifically
# for fine-tuning selection
#
# FN is weighted more heavily because
# missed players are especially harmful
# for downstream tracking.
# ------------------------------------------------------------

df["hard_score"] = (
    df["fp"] +
    2.0 * df["fn"]
)

# ------------------------------------------------------------
# Select:
#
# 1. Highest hard_score
# 2. FN-heavy frames
# 3. FP-heavy frames
#
# Per sequence, keep a controlled number
# rather than letting one sequence dominate.
# ------------------------------------------------------------

selected = []

MAX_PER_SEQUENCE = 120

for sequence in target_sequences:

    seq_df = df[
        df["sequence"] == sequence
    ].copy()

    if len(seq_df) == 0:
        continue

    # Sort by hard score
    seq_df = seq_df.sort_values(
        "hard_score",
        ascending=False
    )

    # Take top difficult frames
    top_frames = seq_df.head(
        MAX_PER_SEQUENCE
    )

    selected.append(
        top_frames
    )

selected_df = pd.concat(
    selected,
    ignore_index=True
)

# Remove duplicate image paths
selected_df = selected_df.drop_duplicates(
    subset=["image_path"]
)

print(
    "\nSelected hard frames:",
    len(selected_df)
)

# ------------------------------------------------------------
# Print sequence distribution
# ------------------------------------------------------------

print("\nSequence distribution:")

print(
    selected_df["sequence"]
    .value_counts()
)

# ------------------------------------------------------------
# Print error statistics
# ------------------------------------------------------------

print("\nSelected dataset statistics:")

print(
    "GT:",
    int(selected_df["gt"].sum())
)

print(
    "Predictions:",
    int(selected_df["predictions"].sum())
)

print(
    "TP:",
    int(selected_df["tp"].sum())
)

print(
    "FP:",
    int(selected_df["fp"].sum())
)

print(
    "FN:",
    int(selected_df["fn"].sum())
)

# ------------------------------------------------------------
# Copy images and labels
# ------------------------------------------------------------

copied = 0
missing = 0

manifest = []

for _, row in selected_df.iterrows():

    sequence = row["sequence"]
    frame = str(row["frame"])

    # Original image path
    source_image = Path(
        row["image_path"]
    )

    # Label path
    source_label = (
        SOURCE_LABELS
        / sequence
        / f"{int(row['frame']):06d}.txt"
    )

    if not source_image.exists():

        missing += 1
        continue

    if not source_label.exists():

        missing += 1
        continue

    # Unique filename prevents collisions
    filename = (
        f"{sequence}__"
        f"{int(row['frame']):06d}.jpg"
    )

    label_filename = (
        f"{sequence}__"
        f"{int(row['frame']):06d}.txt"
    )

    destination_image = (
        OUTPUT_IMAGES / filename
    )

    destination_label = (
        OUTPUT_LABELS / label_filename
    )

    shutil.copy2(
        source_image,
        destination_image
    )

    shutil.copy2(
        source_label,
        destination_label
    )

    manifest.append({
        "sequence": sequence,
        "frame": int(row["frame"]),
        "source_image": str(source_image),
        "hard_score": row["hard_score"],
        "fp": int(row["fp"]),
        "fn": int(row["fn"]),
        "difficulty": row["difficulty"],
        "new_image": str(destination_image)
    })

    copied += 1

# ------------------------------------------------------------
# Save manifest
# ------------------------------------------------------------

manifest_df = pd.DataFrame(
    manifest
)

manifest_path = (
    OUTPUT_ROOT
    / "hard_finetune_manifest.csv"
)

manifest_df.to_csv(
    manifest_path,
    index=False
)

# ------------------------------------------------------------
# data.yaml
# ------------------------------------------------------------

yaml_path = (
    OUTPUT_ROOT
    / "data.yaml"
)

yaml_content = f"""
path: {OUTPUT_ROOT}
train: images/train

names:
  0: player
"""

yaml_path.write_text(
    yaml_content.strip()
)

# ------------------------------------------------------------
# Final report
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("HARD FINE-TUNING DATASET READY")
print("=" * 70)

print(
    f"Copied images : {copied}"
)

print(
    f"Missing files : {missing}"
)

print(
    f"Labels        : "
    f"{len(list(OUTPUT_LABELS.glob('*.txt')))}"
)

print(
    "\nDataset:"
)

print(
    OUTPUT_ROOT
)

print(
    "\nYAML:"
)

print(
    yaml_path
)

print(
    "\nManifest:"
)

print(
    manifest_path
)

Total mining records: 9058
Records in target sequences: 2712

Selected hard frames: 600

Sequence distribution:
sequence
v_G-vNjfx1GGc_c601    120
v_G-vNjfx1GGc_c600    120
v_ITo3sCnpw_k_c007    120
v_dw7LOz17Omg_c053    120
v_G-vNjfx1GGc_c008    120
Name: count, dtype: int64

Selected dataset statistics:
GT: 7885
Predictions: 8343
TP: 6973
FP: 1370
FN: 912

======================================================================
HARD FINE-TUNING DATASET READY
======================================================================
Copied images : 600
Missing files : 0
Labels        : 600

Dataset:
/content/AthletiQ/datasets/football/processed/sportsmot_hard_finetune

YAML:
/content/AthletiQ/datasets/football/processed/sportsmot_hard_finetune/data.yaml

Manifest:
/content/AthletiQ/datasets/football/processed/sportsmot_hard_finetune/hard_finetune_manifest.csv

In [24]:
# ============================================================
# FIX HARD FINE-TUNING DATASET YAML
# ============================================================

from pathlib import Path

HARD_DATASET = Path(
    "/content/AthletiQ/datasets/football/processed/"
    "sportsmot_hard_finetune"
)

ORIGINAL_DATASET = Path(
    "/content/AthletiQ/datasets/football/processed/"
    "sportsmot_yolo"
)

yaml_path = HARD_DATASET / "data.yaml"

yaml_content = f"""path: {HARD_DATASET}
train: images/train
val: {ORIGINAL_DATASET}/images/val

names:
  0: player
"""

yaml_path.write_text(
    yaml_content
)

print("=" * 70)
print("DATASET YAML FIXED")
print("=" * 70)

print(yaml_path.read_text())

print("\nTrain images:")

print(
    len(
        list(
            (HARD_DATASET / "images/train")
            .glob("*.jpg")
        )
    )
)

print("\nTrain labels:")

print(
    len(
        list(
            (HARD_DATASET / "labels/train")
            .glob("*.txt")
        )
    )
)

print("\nValidation images:")

print(
    len(
        list(
            (ORIGINAL_DATASET / "images/val")
            .rglob("*.jpg")
        )
    )
)

======================================================================
DATASET YAML FIXED
======================================================================
path: /content/AthletiQ/datasets/football/processed/sportsmot_hard_finetune
train: images/train
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val

names:
  0: player


Train images:
600

Train labels:
600

Validation images:
9058

In [25]:
# ============================================================
# ATHLETIQ MODEL 1 — START FINE-TUNING
# YOLOv26m SportsMOT Football
# ============================================================

from pathlib import Path
from ultralytics import YOLO
import torch

# ------------------------------------------------------------
# 1. Paths
# ------------------------------------------------------------

PROJECT_ROOT = Path("/content/AthletiQ")

MODEL_PATH = (
    PROJECT_ROOT
    / "ai-engine/models/"
    "yolov26m-sportsmot-football.pt"
)

DATA_YAML = (
    PROJECT_ROOT
    / "datasets/football/processed/"
    "sportsmot_hard_finetune/data.yaml"
)

DRIVE_OUTPUT = Path(
    "/content/drive/MyDrive/AthletiQ/sportsmot/"
    "experiments/yolov26m_sportsmot/fine_tuning"
)

DRIVE_OUTPUT.mkdir(
    parents=True,
    exist_ok=True
)

# ------------------------------------------------------------
# 2. Verify GPU
# ------------------------------------------------------------

print("=" * 70)
print("ATHLETIQ MODEL 1 — FINE-TUNING")
print("=" * 70)

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if not torch.cuda.is_available():
    raise RuntimeError(
        "CUDA GPU is not available. "
        "Switch Colab to a GPU runtime before training."
    )

print(
    "GPU:",
    torch.cuda.get_device_name(0)
)

print(
    "VRAM:",
    round(
        torch.cuda.get_device_properties(0).total_memory
        / 1024**3,
        2
    ),
    "GB"
)

# ------------------------------------------------------------
# 3. Verify model and dataset
# ------------------------------------------------------------

if not MODEL_PATH.exists():
    raise FileNotFoundError(
        f"Model not found:\n{MODEL_PATH}"
    )

if not DATA_YAML.exists():
    raise FileNotFoundError(
        f"Dataset YAML not found:\n{DATA_YAML}"
    )

print("\nModel:")
print(MODEL_PATH)

print("\nDataset YAML:")
print(DATA_YAML)

print("\nDataset YAML contents:")
print(DATA_YAML.read_text())

# ------------------------------------------------------------
# 4. Load existing SportsMOT football model
# ------------------------------------------------------------

model = YOLO(
    str(MODEL_PATH)
)

print("\nModel loaded successfully.")

print("Task:", model.task)
print("Classes:", model.names)

# ------------------------------------------------------------
# 5. Fine-tuning configuration
# ------------------------------------------------------------

EPOCHS = 20
IMAGE_SIZE = 1280
BATCH_SIZE = 4

# ------------------------------------------------------------
# 6. Start fine-tuning
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STARTING TRAINING")
print("=" * 70)

results = model.train(

    # Dataset
    data=str(DATA_YAML),

    # Training
    epochs=EPOCHS,
    imgsz=IMAGE_SIZE,
    batch=BATCH_SIZE,

    # GPU
    device=0,

    # Data loading
    workers=2,
    cache=False,

    # Mixed precision for T4
    amp=True,

    # Early stopping
    patience=5,

    # Save checkpoints
    save=True,
    save_period=1,

    # Output
    project=str(DRIVE_OUTPUT),
    name="yolov26m_hard_finetune",

    # Start from our existing trained model
    pretrained=str(MODEL_PATH),

    # Let Ultralytics select optimizer
    optimizer="auto",

    # Reproducibility
    seed=42,
    deterministic=True,

    # Validate during training
    val=True,

    # Logging
    verbose=True
)

# ------------------------------------------------------------
# 7. Training finished
# ------------------------------------------------------------

TRAIN_DIR = (
    DRIVE_OUTPUT /
    "yolov26m_hard_finetune"
)

BEST_MODEL = (
    TRAIN_DIR /
    "weights" /
    "best.pt"
)

LAST_MODEL = (
    TRAIN_DIR /
    "weights" /
    "last.pt"
)

print("\n" + "=" * 70)
print("TRAINING FINISHED")
print("=" * 70)

print("\nTraining directory:")
print(TRAIN_DIR)

print("\nBest model:")
print(BEST_MODEL)

print("\nLast model:")
print(LAST_MODEL)

print("\nBest model exists:", BEST_MODEL.exists())
print("Last model exists:", LAST_MODEL.exists())

======================================================================
ATHLETIQ MODEL 1 — FINE-TUNING
======================================================================
PyTorch: 2.11.0+cu128
CUDA available: True
GPU: Tesla T4
VRAM: 14.56 GB

Model:
/content/AthletiQ/ai-engine/models/yolov26m-sportsmot-football.pt

Dataset YAML:
/content/AthletiQ/datasets/football/processed/sportsmot_hard_finetune/data.yaml

Dataset YAML contents:
path: /content/AthletiQ/datasets/football/processed/sportsmot_hard_finetune
train: images/train
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val

names:
  0: player


Model loaded successfully.
Task: detect
Classes: {0: 'player'}

======================================================================
STARTING TRAINING
======================================================================
Ultralytics 8.4.150 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/AthletiQ/datasets/football/processed/sportsmot_hard_finetune/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=20, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=1280, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/content/AthletiQ/ai-engine/models/yolov26m-sportsmot-football.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=yolov26m_hard_finetune-2, nbs=64, nms=None, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=5, perspective=0.0, plots=True, pose=12.0, pretrained=/content/AthletiQ/ai-engine/models/yolov26m-sportsmot-football.pt, profile=False, project=/content/drive/MyDrive/AthletiQ/sportsmot/experiments/yolov26m_sportsmot/fine_tuning, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/AthletiQ/sportsmot/experiments/yolov26m_sportsmot/fine_tuning/yolov26m_hard_finetune-2, save_frames=False, save_json=False, save_period=1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 10.5MB/s 0.1s

                   from  n    params  module                                       arguments
  0                  -1  1      1856  ultralytics.nn.modules.conv.Conv             [3, 64, 3, 2]
  1                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  2                  -1  1    111872  ultralytics.nn.modules.block.C3k2            [128, 256, 1, True, 0.25]
  3                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  4                  -1  1    444928  ultralytics.nn.modules.block.C3k2            [256, 512, 1, True, 0.25]
  5                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
  6                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  7                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5, 3, True]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1   1642496  ultralytics.nn.modules.block.C3k2            [1024, 512, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    542720  ultralytics.nn.modules.block.C3k2            [1024, 256, 1, True]
 17                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 20                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1974784  ultralytics.nn.modules.block.C3k2            [1024, 512, 1, True, 0.5, True]
 23        [16, 19, 22]  1   2800158  ultralytics.nn.modules.head.Detect           [1, 1, True, [256, 512, 512]]
YOLO26m summary: 280 layers, 21,774,430 parameters, 21,774,430 gradients, 75.0 GFLOPs

Transferred 768/768 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: downloading yolo26n.pt for AMP checks (one-time, not used for training)...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'weights/yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 54.7MB/s 0.1s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2370.4±714.6 MB/s, size: 197.1 KB)
train: Scanning /content/AthletiQ/datasets/football/processed/sportsmot_hard_finetune/labels/train... 600 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 600/600 2.0Kit/s 0.3s
train: New cache created: /content/AthletiQ/datasets/football/processed/sportsmot_hard_finetune/labels/train.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2022.7±1256.1 MB/s, size: 210.6 KB)
val: Scanning /content/AthletiQ/datasets/football/processed/sportsmot_yolo/labels/val/v_2QhNRucNC7E_c017... 9058 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 9058/9058 1.7Kit/s 5.4s
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000456.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000462.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000475.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000482.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000485.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000492.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000494.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000499.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000500.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000501.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000504.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000509.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000510.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000511.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000517.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000519.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000525.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000526.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000529.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000532.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000540.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000541.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000548.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000559.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000560.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000562.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000564.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000565.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000580.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000590.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000596.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000610.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000611.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000613.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000614.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000618.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000619.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000623.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000628.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000636.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000638.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000649.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000650.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000651.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000655.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000658.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000664.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000670.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000672.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000681.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000682.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000683.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000687.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000690.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000698.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000700.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000707.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000718.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000728.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000730.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000738.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000739.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000748.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000754.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000769.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000792.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000793.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000795.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000798.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000799.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000803.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000820.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000824.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000825.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000826.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000833.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000836.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000839.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000840.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000841.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000843.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000845.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000854.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000858.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000860.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000868.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000875.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000877.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000879.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000883.jpg: 1 duplicate labels removed
val: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/images/val/v_i2_L4qquVg0_c006/000887.jpg: 1 duplicate labels removed
val: New cache created: /content/AthletiQ/datasets/football/processed/sportsmot_yolo/labels/val/v_2QhNRucNC7E_c017.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 124 weight(decay=0.0), 136 weight(decay=0.0005), 136 bias(decay=0.0)
Plotting labels to /content/drive/MyDrive/AthletiQ/sportsmot/experiments/yolov26m_sportsmot/fine_tuning/yolov26m_hard_finetune-2/labels.jpg...
Using 600 train, 9058 val images for fraction=1.0 at imgsz=1280
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/AthletiQ/sportsmot/experiments/yolov26m_sportsmot/fine_tuning/yolov26m_hard_finetune-2

======================================================================
ATHLETIQ MODEL 1 — CLEAN FINAL EVALUATION
======================================================================

CUDA: True
GPU: Tesla T4

FileNotFoundError: Fine-tuned model not found:
/content/drive/MyDrive/AthletiQ/sportsmot/experiments/yolov26m_sportsmot/fine_tuning/yolov26m_hard_finetune/weights/best.pt