In [1]:
from pathlib import Path

# AthletiQ project root
PROJECT_ROOT = Path("/mnt/d/My Projects/AthletiQ/AthletiQ")

SPORTSMOT = PROJECT_ROOT / "datasets/football/benchmarks/sportsmot/extracted"

print("SportsMOT path:")
print(SPORTSMOT)

print("\nExists:", SPORTSMOT.exists())

if not SPORTSMOT.exists():
    raise FileNotFoundError(f"SportsMOT dataset not found: {SPORTSMOT}")

print("\nSplits:")
for split in ["train", "val", "test"]:
    split_dir = SPORTSMOT / split

    if split_dir.exists():
        sequences = [p for p in split_dir.iterdir() if p.is_dir()]
        print(f"{split:5s}: {len(sequences):3d} sequences")
    else:
        print(f"{split:5s}: NOT FOUND")

SportsMOT path:
/mnt/d/My Projects/AthletiQ/AthletiQ/datasets/football/benchmarks/sportsmot/extracted

Exists: True

Splits:
train:  15 sequences
val  :  15 sequences
test :  50 sequences

In [2]:
from pathlib import Path

VAL_DIR = SPORTSMOT / "val"

# Pick the first sequence
seq = sorted([p for p in VAL_DIR.iterdir() if p.is_dir()])[0]

print("Selected sequence:", seq.name)
print("\nContents:")

for item in sorted(seq.iterdir()):
    if item.is_dir():
        print(f"📁 {item.name}/")
    else:
        print(f"📄 {item.name}")

Selected sequence: v_2QhNRucNC7E_c017

Contents:
📁 gt/
📁 img1/
📄 seqinfo.ini

In [3]:
SEQINFO = seq / "seqinfo.ini"
GT_FILE = seq / "gt" / "gt.txt"
IMG_DIR = seq / "img1"

print("\nImage directory:", IMG_DIR)
print("Images:", len(list(IMG_DIR.glob("*.jpg"))))

print("\n--- seqinfo.ini ---")
print(SEQINFO.read_text())

print("\n--- First 10 GT lines ---")
with open(GT_FILE, "r") as f:
    for _ in range(10):
        print(f.readline().strip())

Image directory: /mnt/d/My Projects/AthletiQ/AthletiQ/datasets/football/benchmarks/sportsmot/extracted/val/v_2QhNRucNC7E_c017/img1
Images: 450

--- seqinfo.ini ---
[Sequence]
name=v_2QhNRucNC7E_c017
imDir=img1
frameRate=25
seqLength=450
imWidth=1280
imHeight=720
imExt=.jpg

--- First 10 GT lines ---
1, 0, 509, 458, 36, 92, 1, 1, 1
1, 1, 874, 398, 32, 81, 1, 1, 1
1, 2, 931, 208, 26, 58, 1, 1, 1
1, 3, 197, 313, 51, 65, 1, 1, 1
1, 4, 400, 223, 23, 55, 1, 1, 1
1, 5, 358, 207, 26, 53, 1, 1, 1
1, 6, 8, 470, 38, 104, 1, 1, 1
1, 7, 292, 195, 32, 55, 1, 1, 1
1, 8, 0, 231, 27, 66, 1, 1, 1
1, 10, 778, 386, 39, 82, 1, 1, 1

In [4]:
from ultralytics import YOLO
import torch

MODEL_PATH = PROJECT_ROOT / "ai-engine/models/football_player_detector.pt"

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

player_model = YOLO(str(MODEL_PATH))

print("\nModel loaded successfully.")
print("Task:", player_model.task)
print("Classes:", player_model.names)

PyTorch: 2.14.0+cu130
CUDA available: True
GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU

Model loaded successfully.
Task: detect
Classes: {0: 'player'}

In [5]:
# Read the first frame
first_frame = sorted(IMG_DIR.glob("*.jpg"))[0]

result = player_model.predict(
    source=str(first_frame),
    conf=0.25,
    imgsz=1280,
    device=0,
    verbose=False
)[0]

print("Frame:", first_frame.name)
print("Detections:", len(result.boxes))

if len(result.boxes) > 0:
    print("\nFirst 5 detections:")
    for box in result.boxes[:5]:
        xyxy = box.xyxy[0].cpu().numpy()
        conf = float(box.conf[0])
        cls = int(box.cls[0])

        print(
            f"bbox={xyxy.astype(int)}, "
            f"conf={conf:.3f}, "
            f"class={cls}"
        )

Frame: 000001.jpg
Detections: 22

First 5 detections:
bbox=[776 385 816 467], conf=0.959, class=0
bbox=[953 240 992 307], conf=0.955, class=0
bbox=[1073  303 1100  376], conf=0.952, class=0
bbox=[509 459 544 549], conf=0.950, class=0
bbox=[505 378 536 465], conf=0.944, class=0

In [6]:
from types import SimpleNamespace
from ultralytics.trackers.byte_tracker import BYTETracker

tracker_args = SimpleNamespace(
    track_high_thresh=0.5,
    track_low_thresh=0.1,
    new_track_thresh=0.5,
    track_buffer=30,
    match_thresh=0.8,
    fuse_score=True
)

tracker = BYTETracker(tracker_args)

print("ByteTrack initialized successfully.")

ByteTrack initialized successfully.

In [7]:
# Run ByteTrack through Ultralytics' built-in tracking pipeline
track_result = player_model.track(
    source=str(first_frame),
    tracker="bytetrack.yaml",
    conf=0.25,
    imgsz=1280,
    device=0,
    persist=True,
    verbose=False
)[0]

print("Frame:", first_frame.name)
print("Detections:", len(track_result.boxes))

if track_result.boxes.id is not None:
    track_ids = track_result.boxes.id.cpu().numpy().astype(int)
    print("Track IDs:", track_ids)
    print("Number of tracks:", len(track_ids))
else:
    print("No track IDs returned.")

Frame: 000001.jpg
Detections: 22
Track IDs: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]
Number of tracks: 22

In [8]:
from collections import defaultdict

# Fresh tracker state through Ultralytics
track_history = defaultdict(list)

results = player_model.track(
    source=[str(p) for p in sorted(IMG_DIR.glob("*.jpg"))[:30]],
    tracker="bytetrack.yaml",
    conf=0.25,
    imgsz=1280,
    device=0,
    persist=True,
    verbose=False
)

for frame_idx, r in enumerate(results, start=1):
    if r.boxes.id is not None:
        ids = r.boxes.id.cpu().numpy().astype(int)
        track_history[frame_idx] = ids.tolist()

        print(
            f"Frame {frame_idx:02d}: "
            f"{len(ids):2d} detections | "
            f"IDs: {ids.tolist()}"
        )
    else:
        print(f"Frame {frame_idx:02d}: 0 tracks")

print("\nUnique track IDs:", len(set(
    tid for ids in track_history.values() for tid in ids
)))

Frame 01: 22 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
Frame 02: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 19, 20, 21]
Frame 03: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 19, 20, 21, 11]
Frame 04: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 19, 20, 21, 11]
Frame 05: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 19, 20, 21, 11]
Frame 06: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 19, 20, 21, 11]
Frame 07: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 19, 20, 21, 11]
Frame 08: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 19, 20, 21, 11]
Frame 09: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 19, 20, 21, 11]
Frame 10: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 19, 20, 21, 11]
Frame 11: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 19, 20, 21, 11]
Frame 12: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 19, 20, 21, 11]
Frame 13: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 19, 20, 21, 11]
Frame 14: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 19, 20, 21, 11]
Frame 15: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 19, 20, 21, 11]
Frame 16: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 19, 20, 21, 11]
Frame 17: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 19, 20, 21, 11]
Frame 18: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 19, 20, 21, 11]
Frame 19: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 19, 20, 21, 11]
Frame 20: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 19, 20, 21, 11]
Frame 21: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 19, 20, 21, 11]
Frame 22: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 19, 20, 21, 11]
Frame 23: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 19, 20, 21, 11]
Frame 24: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 19, 20, 21, 11]
Frame 25: 18 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 17, 19, 20, 21, 11]
Frame 26: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 17, 19, 20, 21, 11, 16]
Frame 27: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 17, 19, 20, 21, 11, 16]
Frame 28: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 17, 19, 20, 21, 11, 16]
Frame 29: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 17, 19, 20, 21, 11, 16]
Frame 30: 19 detections | IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 17, 19, 20, 21, 11, 16]

Unique track IDs: 22

In [9]:
import gc
import torch

# Remove current model/tracking objects from GPU
del player_model
gc.collect()
torch.cuda.empty_cache()

print(f"GPU allocated after cleanup: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")
print(f"GPU reserved after cleanup:  {torch.cuda.memory_reserved() / 1024**3:.2f} GB")

GPU allocated after cleanup: 0.03 GB
GPU reserved after cleanup:  0.06 GB

In [10]:
from pathlib import Path
import torch

PROJECT_ROOT = Path("/mnt/d/My Projects/AthletiQ/AthletiQ")
SPORTSMOT = PROJECT_ROOT / "datasets/football/benchmarks/sportsmot/extracted"

VAL_DIR = SPORTSMOT / "val"
seq = VAL_DIR / "v_2QhNRucNC7E_c017"

IMG_DIR = seq / "img1"
GT_FILE = seq / "gt" / "gt.txt"

print("GPU available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))
print(f"GPU memory allocated: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")

print("\nSequence:", seq.name)
print("Frames:", len(list(IMG_DIR.glob("*.jpg"))))

GPU available: True
GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU
GPU memory allocated: 0.03 GB

Sequence: v_2QhNRucNC7E_c017
Frames: 450

In [11]:
from ultralytics import YOLO

MODEL_PATH = PROJECT_ROOT / "ai-engine/models/football_player_detector.pt"

player_model = YOLO(str(MODEL_PATH))

print("Model loaded successfully.")
print("Task:", player_model.task)
print("Classes:", player_model.names)
print(f"GPU memory allocated: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")

Model loaded successfully.
Task: detect
Classes: {0: 'player'}
GPU memory allocated: 0.03 GB

In [12]:
import time
import pandas as pd

start_time = time.time()
tracking_rows = []

results = player_model.track(
    source=str(IMG_DIR),       # directory, NOT list of images
    tracker="bytetrack.yaml",
    conf=0.25,
    imgsz=1280,
    device=0,
    persist=True,
    stream=True,
    verbose=False
)

for frame_idx, r in enumerate(results, start=1):

    if r.boxes.id is not None:
        boxes = r.boxes.xyxy.cpu().numpy()
        ids = r.boxes.id.cpu().numpy().astype(int)
        confs = r.boxes.conf.cpu().numpy()

        for bbox, track_id, conf in zip(boxes, ids, confs):
            x1, y1, x2, y2 = bbox

            tracking_rows.append({
                "frame": frame_idx,
                "track_id": track_id,
                "x1": x1,
                "y1": y1,
                "x2": x2,
                "y2": y2,
                "confidence": conf
            })

    if frame_idx % 50 == 0:
        print(f"Processed {frame_idx}/450 frames")

elapsed = time.time() - start_time

tracks_df = pd.DataFrame(tracking_rows)

print("\n========== TRACKING COMPLETE ==========")
print(f"Frames processed : {frame_idx}")
print(f"Tracking rows    : {len(tracks_df):,}")
print(f"Unique track IDs : {tracks_df['track_id'].nunique()}")
print(f"Time             : {elapsed:.2f} sec")
print(f"FPS              : {frame_idx / elapsed:.2f}")

Processed 50/450 frames
Processed 100/450 frames
Processed 150/450 frames
Processed 200/450 frames
Processed 250/450 frames
Processed 300/450 frames
Processed 350/450 frames
Processed 400/450 frames
Processed 450/450 frames

========== TRACKING COMPLETE ==========
Frames processed : 450
Tracking rows    : 6,757
Unique track IDs : 69
Time             : 48.04 sec
FPS              : 9.37

In [13]:
track_stats = (
    tracks_df
    .groupby("track_id")
    .agg(
        frames_tracked=("frame", "nunique"),
        first_frame=("frame", "min"),
        last_frame=("frame", "max"),
        avg_confidence=("confidence", "mean")
    )
    .sort_values("frames_tracked", ascending=False)
)

print("Total unique tracks:", len(track_stats))

print("\nTrack duration statistics:")
print(track_stats["frames_tracked"].describe())

print("\nTop 20 longest tracks:")
display(track_stats.head(20))

print("\nShort tracks (<= 10 frames):",
      (track_stats["frames_tracked"] <= 10).sum())

print("Tracks lasting > 100 frames:",
      (track_stats["frames_tracked"] > 100).sum())

print("Tracks lasting > 300 frames:",
      (track_stats["frames_tracked"] > 300).sum())

Total unique tracks: 69

Track duration statistics:
count     69.000000
mean      97.927536
std      129.860029
min        1.000000
25%        3.000000
50%       48.000000
75%      139.000000
max      419.000000
Name: frames_tracked, dtype: float64

Top 20 longest tracks:

          frames_tracked  first_frame  last_frame  avg_confidence
track_id
19                   419            1         450        0.874056
1                    403            1         403        0.946143
13                   379            1         389        0.899606
8                    375            1         381        0.922716
17                   373            1         375        0.891045
21                   366            1         391        0.907755
12                   364            1         378        0.875920
20                   358            1         379        0.833786
4                    357            1         358        0.946149
55                   291           71         371        0.906578
5                    253            1         253        0.941850
11                   244            1         246        0.916567
106                  233          191         450        0.902772
16                   215            1         226        0.870272
89                   177          155         340        0.864698
10                   175            1         175        0.949856
9                    174            1         175        0.918677
134                  139          312         450        0.948044
127                  133          244         401        0.930751
7                    107            1         108        0.870759

Short tracks (<= 10 frames): 29
Tracks lasting > 100 frames: 20
Tracks lasting > 300 frames: 9

In [14]:
# Load SportsMOT ground truth
gt = pd.read_csv(
    GT_FILE,
    header=None,
    names=[
        "frame",
        "track_id",
        "x",
        "y",
        "width",
        "height",
        "conf",
        "class",
        "visibility"
    ]
)

print("GT rows:", len(gt))
print("GT unique IDs:", gt["track_id"].nunique())
print("GT frames:", gt["frame"].nunique())

print("\nGT players per frame:")
print(
    gt.groupby("frame")["track_id"]
    .nunique()
    .describe()
)

print("\nFirst 10 GT rows:")
display(gt.head(10))

GT rows: 6622
GT unique IDs: 21
GT frames: 450

GT players per frame:
count    450.000000
mean      14.715556
std        1.907430
min       11.000000
25%       13.000000
50%       14.500000
75%       16.000000
max       19.000000
Name: track_id, dtype: float64

First 10 GT rows:

   frame  track_id    x    y  width  height  conf  class  visibility
0      1         0  509  458     36      92     1      1           1
1      1         1  874  398     32      81     1      1           1
2      1         2  931  208     26      58     1      1           1
3      1         3  197  313     51      65     1      1           1
4      1         4  400  223     23      55     1      1           1
5      1         5  358  207     26      53     1      1           1
6      1         6    8  470     38     104     1      1           1
7      1         7  292  195     32      55     1      1           1
8      1         8    0  231     27      66     1      1           1
9      1        10  778  386     39      82     1      1           1

In [15]:
import numpy as np

def calculate_iou(box_a, box_b):
    """
    box format: [x1, y1, x2, y2]
    """
    xa1, ya1, xa2, ya2 = box_a
    xb1, yb1, xb2, yb2 = box_b

    inter_x1 = max(xa1, xb1)
    inter_y1 = max(ya1, yb1)
    inter_x2 = min(xa2, xb2)
    inter_y2 = min(ya2, yb2)

    inter_w = max(0, inter_x2 - inter_x1)
    inter_h = max(0, inter_y2 - inter_y1)
    intersection = inter_w * inter_h

    area_a = max(0, xa2 - xa1) * max(0, ya2 - ya1)
    area_b = max(0, xb2 - xb1) * max(0, yb2 - yb1)

    union = area_a + area_b - intersection

    return intersection / union if union > 0 else 0.0


# Convert GT boxes to x1,y1,x2,y2
gt_eval = gt.copy()

gt_eval["x1"] = gt_eval["x"]
gt_eval["y1"] = gt_eval["y"]
gt_eval["x2"] = gt_eval["x"] + gt_eval["width"]
gt_eval["y2"] = gt_eval["y"] + gt_eval["height"]

IOU_THRESHOLD = 0.5

matches = []

for frame in range(1, 451):

    gt_frame = gt_eval[gt_eval["frame"] == frame]
    pred_frame = tracks_df[tracks_df["frame"] == frame]

    used_preds = set()

    # Match each GT player to the best unused prediction
    for _, gt_row in gt_frame.iterrows():

        gt_box = [
            gt_row["x1"],
            gt_row["y1"],
            gt_row["x2"],
            gt_row["y2"]
        ]

        best_iou = 0
        best_pred_idx = None

        for pred_idx, pred_row in pred_frame.iterrows():

            if pred_idx in used_preds:
                continue

            pred_box = [
                pred_row["x1"],
                pred_row["y1"],
                pred_row["x2"],
                pred_row["y2"]
            ]

            iou = calculate_iou(gt_box, pred_box)

            if iou > best_iou:
                best_iou = iou
                best_pred_idx = pred_idx

        if best_iou >= IOU_THRESHOLD:
            used_preds.add(best_pred_idx)

            matches.append({
                "frame": frame,
                "gt_id": int(gt_row["track_id"]),
                "pred_id": int(
                    pred_frame.loc[best_pred_idx, "track_id"]
                ),
                "iou": best_iou
            })

matches_df = pd.DataFrame(matches)

print("GT annotations:", len(gt))
print("Predicted tracks:", len(tracks_df))
print("Successful matches:", len(matches_df))

print(
    f"Match rate: "
    f"{len(matches_df) / len(gt) * 100:.2f}%"
)

print(
    f"Mean matched IoU: "
    f"{matches_df['iou'].mean():.3f}"
)

print("\nFirst 10 matches:")
display(matches_df.head(10))

GT annotations: 6622
Predicted tracks: 6757
Successful matches: 6249
Match rate: 94.37%
Mean matched IoU: 0.848

First 10 matches:

   frame  gt_id  pred_id       iou
0      1      0        4  0.963602
1      1      1        6  0.911591
2      1      2        7  0.871807
3      1      3        9  0.981912
4      1      4       14  0.972763
5      1      5       20  0.926516
6      1      6       10  0.954642
7      1      7       12  0.923101
8      1      8       16  0.982965
9      1     10        1  0.946463

In [16]:
from scipy.optimize import linear_sum_assignment
import numpy as np
import pandas as pd

IOU_THRESHOLD = 0.5
matches = []

for frame in range(1, 451):

    gt_frame = gt_eval[gt_eval["frame"] == frame].reset_index(drop=True)
    pred_frame = tracks_df[tracks_df["frame"] == frame].reset_index(drop=True)

    if len(gt_frame) == 0 or len(pred_frame) == 0:
        continue

    # Build IoU matrix
    iou_matrix = np.zeros((len(gt_frame), len(pred_frame)))

    for i, gt_row in gt_frame.iterrows():

        gt_box = [
            gt_row["x1"], gt_row["y1"],
            gt_row["x2"], gt_row["y2"]
        ]

        for j, pred_row in pred_frame.iterrows():

            pred_box = [
                pred_row["x1"], pred_row["y1"],
                pred_row["x2"], pred_row["y2"]
            ]

            iou_matrix[i, j] = calculate_iou(gt_box, pred_box)

    # Hungarian assignment maximizes IoU
    gt_indices, pred_indices = linear_sum_assignment(
        -iou_matrix
    )

    for gt_idx, pred_idx in zip(gt_indices, pred_indices):

        iou = iou_matrix[gt_idx, pred_idx]

        if iou >= IOU_THRESHOLD:

            matches.append({
                "frame": frame,
                "gt_id": int(gt_frame.loc[gt_idx, "track_id"]),
                "pred_id": int(pred_frame.loc[pred_idx, "track_id"]),
                "iou": float(iou)
            })

matches_df = pd.DataFrame(matches)

print("========== HUNGARIAN MATCHING ==========")
print("GT annotations:", len(gt))
print("Predicted detections:", len(tracks_df))
print("Successful matches:", len(matches_df))
print(f"Match rate: {len(matches_df) / len(gt) * 100:.2f}%")
print(f"Mean matched IoU: {matches_df['iou'].mean():.3f}")

print("\nMatches per frame:")
print(
    matches_df.groupby("frame")
    .size()
    .describe()
)

display(matches_df.head(10))

========== HUNGARIAN MATCHING ==========
GT annotations: 6622
Predicted detections: 6757
Successful matches: 6249
Match rate: 94.37%
Mean matched IoU: 0.848

Matches per frame:
count    450.000000
mean      13.886667
std        2.536688
min        5.000000
25%       13.000000
50%       14.000000
75%       16.000000
max       19.000000
dtype: float64

   frame  gt_id  pred_id       iou
0      1      0        4  0.963602
1      1      1        6  0.911591
2      1      2        7  0.871807
3      1      3        9  0.981912
4      1      4       14  0.972763
5      1      5       20  0.926516
6      1      6       10  0.954642
7      1      7       12  0.923101
8      1      8       16  0.982965
9      1     10        1  0.946463

In [17]:
# Sort matches chronologically
matches_sorted = matches_df.sort_values(
    ["gt_id", "frame"]
).reset_index(drop=True)

id_switches = 0
switch_details = []

for gt_id, group in matches_sorted.groupby("gt_id"):

    group = group.sort_values("frame")

    previous_pred = None
    previous_frame = None

    for _, row in group.iterrows():

        current_pred = int(row["pred_id"])
        current_frame = int(row["frame"])

        if previous_pred is not None:

            if current_pred != previous_pred:
                id_switches += 1

                switch_details.append({
                    "gt_id": int(gt_id),
                    "frame": current_frame,
                    "previous_pred_id": previous_pred,
                    "new_pred_id": current_pred
                })

        previous_pred = current_pred
        previous_frame = current_frame

switch_df = pd.DataFrame(switch_details)

print("========== ID SWITCH ANALYSIS ==========")
print("Total ID switches:", id_switches)
print("GT identities:", gt["track_id"].nunique())

if len(switch_df) > 0:
    print("\nFirst 20 ID switches:")
    display(switch_df.head(20))
else:
    print("\nNo ID switches found.")

========== ID SWITCH ANALYSIS ==========
Total ID switches: 86
GT identities: 21

First 20 ID switches:

    gt_id  frame  previous_pred_id  new_pred_id
0       0    371                 4          155
1       0    389               155          296
2       1    191                 6          106
3       2    155                 7           89
4       2    351                89          146
5       2    377               146          127
6       2    378               127          106
7       2    381               106          189
8       2    382               189          196
9       2    384               196          225
10      2    388               225          261
11      3    377                 9           21
12      3    381                21           19
13      3    391                19          156
14      3    395               156          343
15      4     71                14           55
16      4     72                55           14
17      4     78                14           55
18      4    381                55          156
19      4    390               156          309

In [18]:
print("========== FRAMES 360–400 ==========")

region = matches_df[
    matches_df["frame"].between(360, 400)
].copy()

summary = (
    region
    .groupby("frame")
    .agg(
        matched_gt=("gt_id", "nunique"),
        unique_pred=("pred_id", "nunique"),
        mean_iou=("iou", "mean")
    )
    .reset_index()
)

display(summary)

print("\nID changes in this region:")

region = region.sort_values(["gt_id", "frame"])

for gt_id, group in region.groupby("gt_id"):
    group = group.sort_values("frame")
    ids = group["pred_id"].tolist()

    changes = []
    for i in range(1, len(ids)):
        if ids[i] != ids[i-1]:
            changes.append(
                f"frame {group.iloc[i]['frame']}: "
                f"{ids[i-1]} → {ids[i]}"
            )

    if changes:
        print(f"\nGT player {gt_id}:")
        for change in changes:
            print(" ", change)

========== FRAMES 360–400 ==========

    frame  matched_gt  unique_pred  mean_iou
0     360          13           13  0.866177
1     361          13           13  0.877640
2     362          14           14  0.860621
3     363          14           14  0.839941
4     364          13           13  0.841636
5     365          13           13  0.847570
6     366          13           13  0.837645
7     367          13           13  0.873394
8     368          13           13  0.841310
9     369          13           13  0.830858
10    370          11           11  0.782421
11    371          15           15  0.760710
12    372          11           11  0.738622
13    373           9            9  0.706093
14    374           8            8  0.671323
15    375           8            8  0.669666
16    376           5            5  0.656982
17    377          10           10  0.720564
18    378           8            8  0.714714
19    379           7            7  0.694345
20    380           6            6  0.720433
21    381           9            9  0.719005
22    382           5            5  0.774017
23    383           6            6  0.716872
24    384           5            5  0.769622
25    385           7            7  0.745198
26    386           7            7  0.750406
27    387           5            5  0.819003
28    388           6            6  0.794033
29    389           7            7  0.773609
30    390           6            6  0.772728
31    391          10           10  0.696782
32    392           8            8  0.776301
33    393           8            8  0.813255
34    394           7            7  0.811905
35    395          11           11  0.823778
36    396          12           12  0.808260
37    397          13           13  0.841996
38    398          13           13  0.832985
39    399          11           11  0.832261
40    400          12           12  0.787155

ID changes in this region:

GT player 0:
  frame 389.0: 155 → 296

GT player 2:
  frame 377.0: 146 → 127
  frame 378.0: 127 → 106
  frame 381.0: 106 → 189
  frame 382.0: 189 → 196
  frame 384.0: 196 → 225
  frame 388.0: 225 → 261

GT player 3:
  frame 381.0: 21 → 19
  frame 391.0: 19 → 156
  frame 395.0: 156 → 343

GT player 4:
  frame 381.0: 55 → 156
  frame 390.0: 156 → 309
  frame 399.0: 309 → 350
  frame 400.0: 350 → 309

GT player 5:
  frame 371.0: 20 → 156
  frame 383.0: 156 → 146
  frame 385.0: 146 → 127
  frame 386.0: 127 → 106
  frame 387.0: 106 → 13
  frame 395.0: 13 → 344

GT player 7:
  frame 380.0: 12 → 13
  frame 381.0: 13 → 8
  frame 385.0: 8 → 189
  frame 386.0: 189 → 196
  frame 388.0: 196 → 225
  frame 391.0: 225 → 318
  frame 398.0: 318 → 320

GT player 8:
  frame 395.0: 334 → 342
  frame 396.0: 342 → 346
  frame 400.0: 346 → 348

GT player 9:
  frame 371.0: 151 → 154

GT player 11:
  frame 377.0: 138 → 185

GT player 12:
  frame 397.0: 21 → 348

GT player 13:
  frame 379.0: 13 → 8
  frame 391.0: 8 → 320

GT player 14:
  frame 377.0: 21 → 19
  frame 386.0: 19 → 156
  frame 392.0: 156 → 328

GT player 15:
  frame 373.0: 127 → 106
  frame 375.0: 106 → 170
  frame 377.0: 170 → 189
  frame 378.0: 189 → 196
  frame 379.0: 196 → 204
  frame 380.0: 204 → 213
  frame 381.0: 213 → 225
  frame 383.0: 225 → 247

GT player 17:
  frame 385.0: 8 → 261

GT player 18:
  frame 379.0: 17 → 20
  frame 389.0: 20 → 301
  frame 400.0: 301 → 127

In [19]:
from pathlib import Path

tracker_config = PROJECT_ROOT / "ai-engine/notebooks/bytetrack_sportsmot.yaml"

tracker_config.write_text("""
tracker_type: bytetrack

track_high_thresh: 0.5
track_low_thresh: 0.1
new_track_thresh: 0.5
track_buffer: 60
match_thresh: 0.8
fuse_score: True
""")

print("Tracker config created:")
print(tracker_config)
print()
print(tracker_config.read_text())

Tracker config created:
/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/notebooks/bytetrack_sportsmot.yaml


tracker_type: bytetrack

track_high_thresh: 0.5
track_low_thresh: 0.1
new_track_thresh: 0.5
track_buffer: 60
match_thresh: 0.8
fuse_score: True

In [20]:
import time
import pandas as pd

start_time = time.time()
tracking_rows_60 = []

results_60 = player_model.track(
    source=str(IMG_DIR),
    tracker=str(tracker_config),
    conf=0.25,
    imgsz=1280,
    device=0,
    persist=True,
    stream=True,
    verbose=False
)

for frame_idx, r in enumerate(results_60, start=1):

    if r.boxes.id is None:
        continue

    boxes = r.boxes.xyxy.cpu().numpy()
    ids = r.boxes.id.cpu().numpy().astype(int)
    confs = r.boxes.conf.cpu().numpy()

    for bbox, track_id, conf in zip(boxes, ids, confs):
        x1, y1, x2, y2 = bbox

        tracking_rows_60.append({
            "frame": frame_idx,
            "track_id": track_id,
            "x1": x1,
            "y1": y1,
            "x2": x2,
            "y2": y2,
            "confidence": conf
        })

    if frame_idx % 50 == 0:
        print(f"Processed {frame_idx}/450 frames")

elapsed_60 = time.time() - start_time

tracks_df_60 = pd.DataFrame(tracking_rows_60)

print("\n========== TRACKING BUFFER 60 ==========")
print(f"Frames processed : {frame_idx}")
print(f"Tracking rows    : {len(tracks_df_60):,}")
print(f"Unique track IDs : {tracks_df_60['track_id'].nunique()}")
print(f"Time             : {elapsed_60:.2f} sec")
print(f"FPS              : {frame_idx / elapsed_60:.2f}")

Processed 50/450 frames
Processed 100/450 frames
Processed 150/450 frames
Processed 200/450 frames
Processed 250/450 frames
Processed 300/450 frames
Processed 350/450 frames
Processed 400/450 frames
Processed 450/450 frames

========== TRACKING BUFFER 60 ==========
Frames processed : 450
Tracking rows    : 6,735
Unique track IDs : 69
Time             : 38.51 sec
FPS              : 11.69

In [21]:
matches_60 = []

for frame in range(1, 451):

    gt_frame = gt_eval[gt_eval["frame"] == frame].reset_index(drop=True)
    pred_frame = tracks_df_60[
        tracks_df_60["frame"] == frame
    ].reset_index(drop=True)

    if len(gt_frame) == 0 or len(pred_frame) == 0:
        continue

    iou_matrix = np.zeros(
        (len(gt_frame), len(pred_frame))
    )

    for i, gt_row in gt_frame.iterrows():

        gt_box = [
            gt_row["x1"], gt_row["y1"],
            gt_row["x2"], gt_row["y2"]
        ]

        for j, pred_row in pred_frame.iterrows():

            pred_box = [
                pred_row["x1"], pred_row["y1"],
                pred_row["x2"], pred_row["y2"]
            ]

            iou_matrix[i, j] = calculate_iou(
                gt_box,
                pred_box
            )

    gt_indices, pred_indices = linear_sum_assignment(
        -iou_matrix
    )

    for gt_idx, pred_idx in zip(gt_indices, pred_indices):

        iou = iou_matrix[gt_idx, pred_idx]

        if iou >= 0.5:
            matches_60.append({
                "frame": frame,
                "gt_id": int(gt_frame.loc[gt_idx, "track_id"]),
                "pred_id": int(
                    pred_frame.loc[pred_idx, "track_id"]
                ),
                "iou": float(iou)
            })

matches_df_60 = pd.DataFrame(matches_60)

print("========== BUFFER 60 EVALUATION ==========")
print("Successful matches:", len(matches_df_60))
print(
    f"Match rate: "
    f"{len(matches_df_60) / len(gt) * 100:.2f}%"
)
print(
    f"Mean IoU: "
    f"{matches_df_60['iou'].mean():.3f}"
)

========== BUFFER 60 EVALUATION ==========
Successful matches: 6229
Match rate: 94.07%
Mean IoU: 0.847

In [22]:
# Build per-GT-player matched prediction history
# Only count an ID switch when the GT player is matched
# in consecutive frames.

matches_sorted = matches_df.sort_values(
    ["gt_id", "frame"]
).reset_index(drop=True)

true_id_switches = 0
switch_events = []

for gt_id, group in matches_sorted.groupby("gt_id"):

    group = group.sort_values("frame").reset_index(drop=True)

    for i in range(1, len(group)):

        prev = group.iloc[i - 1]
        curr = group.iloc[i]

        # Only consecutive frames
        if curr["frame"] == prev["frame"] + 1:

            if curr["pred_id"] != prev["pred_id"]:

                true_id_switches += 1

                switch_events.append({
                    "gt_id": int(gt_id),
                    "frame": int(curr["frame"]),
                    "previous_pred_id": int(prev["pred_id"]),
                    "new_pred_id": int(curr["pred_id"])
                })

true_switch_df = pd.DataFrame(switch_events)

print("========== CONSECUTIVE-FRAME ID SWITCHES ==========")
print("ID switches:", true_id_switches)

if len(true_switch_df):
    display(true_switch_df.head(20))

========== CONSECUTIVE-FRAME ID SWITCHES ==========
ID switches: 41

    gt_id  frame  previous_pred_id  new_pred_id
0       2    378               127          106
1       2    382               189          196
2       4     71                14           55
3       4     72                55           14
4       4     78                14           55
5       4    399               309          350
6       4    400               350          309
7       5    386               127          106
8       5    387               106           13
9       7    381                13            8
10      7    386               189          196
11      7    388               196          225
12      7    398               318          320
13      8    396               342          346
14     10    404                 1          204
15     11     60                 3           47
16     13     97                13           69
17     13     98                69           13
18     13    123                13           81
19     13    124                81           13

In [23]:
TP = len(matches_df)
FP = len(tracks_df) - TP
FN = len(gt) - TP
IDSW = true_id_switches

MOTA = 1 - (FN + FP + IDSW) / len(gt)

print("========== PRELIMINARY TRACKING METRICS ==========")
print(f"True Positives : {TP}")
print(f"False Positives: {FP}")
print(f"False Negatives: {FN}")
print(f"ID Switches    : {IDSW}")
print(f"MOTA           : {MOTA:.4f} ({MOTA * 100:.2f}%)")

========== PRELIMINARY TRACKING METRICS ==========
True Positives : 6249
False Positives: 508
False Negatives: 373
ID Switches    : 41
MOTA           : 0.8608 (86.08%)

In [24]:
!pip install motmetrics

Requirement already satisfied: motmetrics in /home/jatin/tf312/lib/python3.12/site-packages (1.4.0)
Requirement already satisfied: numpy>=1.12.1 in /home/jatin/tf312/lib/python3.12/site-packages (from motmetrics) (2.3.5)
Requirement already satisfied: pandas>=0.23.1 in /home/jatin/tf312/lib/python3.12/site-packages (from motmetrics) (2.3.3)
Requirement already satisfied: scipy>=0.19.0 in /home/jatin/tf312/lib/python3.12/site-packages (from motmetrics) (1.16.3)
Requirement already satisfied: xmltodict>=0.12.0 in /home/jatin/tf312/lib/python3.12/site-packages (from motmetrics) (1.0.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/jatin/tf312/lib/python3.12/site-packages (from pandas>=0.23.1->motmetrics) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/jatin/tf312/lib/python3.12/site-packages (from pandas>=0.23.1->motmetrics) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in /home/jatin/tf312/lib/python3.12/site-packages (from pandas>=0.23.1->motmetrics) (2026.3)
Requirement already satisfied: six>=1.5 in /home/jatin/tf312/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=0.23.1->motmetrics) (1.17.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [25]:
# Check whether motmetrics is installed

try:
    import motmetrics as mm
    print("motmetrics version:", mm.__version__)
except ImportError:
    print("motmetrics is NOT installed.")

motmetrics version: 1.4.0

In [26]:
import motmetrics as mm

acc = mm.MOTAccumulator(auto_id=True)

# Add frame-by-frame GT ↔ prediction distances
for frame in sorted(set(gt_eval["frame"]) | set(tracks_df["frame"])):
    gt_frame = gt_eval[gt_eval["frame"] == frame]
    pred_frame = tracks_df[tracks_df["frame"] == frame]

    gt_ids = gt_frame["track_id"].astype(int).tolist()
    pred_ids = pred_frame["track_id"].astype(int).tolist()

    gt_boxes = gt_frame[["x1", "y1", "x2", "y2"]].values
    pred_boxes = pred_frame[["x1", "y1", "x2", "y2"]].values

    distances = []

    for gt_box in gt_boxes:
        row = []
        for pred_box in pred_boxes:
            row.append(1 - calculate_iou(gt_box, pred_box))
        distances.append(row)

    if len(gt_boxes) == 0 or len(pred_boxes) == 0:
        distances = None
    else:
        distances = np.array(distances)
        distances[distances > 0.5] = np.nan

    acc.update(
        gt_ids,
        pred_ids,
        distances
    )

print("MOT accumulator created successfully.")

MOT accumulator created successfully.

In [27]:
mh = mm.metrics.create()

summary = mh.compute(
    acc,
    metrics=[
        "num_frames",
        "num_objects",
        "num_matches",
        "num_switches",
        "num_false_positives",
        "num_misses",
        "mota",
        "motp",
        "idf1",
    ],
    name="SportsMOT_v_2QhNRucNC7E_c017"
)

display(summary.T)

                     SportsMOT_v_2QhNRucNC7E_c017
num_frames                             450.000000
num_objects                           6622.000000
num_matches                           6182.000000
num_switches                            67.000000
num_false_positives                    508.000000
num_misses                             373.000000
mota                                     0.856841
motp                                     0.152122
idf1                                     0.759399

In [28]:
VAL_DIR = Path(
    "/mnt/d/My Projects/AthletiQ/AthletiQ/"
    "datasets/football/benchmarks/sportsmot/extracted/val"
)

val_sequences = sorted([
    p for p in VAL_DIR.iterdir()
    if p.is_dir()
])

print("Total validation sequences:", len(val_sequences))

# Select 5 sequences spread through the validation set
selected_sequences = [
    val_sequences[i]
    for i in np.linspace(0, len(val_sequences) - 1, 5, dtype=int)
]

print("\nSelected sequences:")
for seq in selected_sequences:
    print("-", seq.name)

Total validation sequences: 15

Selected sequences:
- v_2QhNRucNC7E_c017
- v_G-vNjfx1GGc_c600
- v_ITo3sCnpw_k_c011
- v_dw7LOz17Omg_c067
- v_i2_L4qquVg0_c010

In [29]:
print("Detector:", player_model.ckpt_path)
print("Tracker config:", "default bytetrack.yaml")
print("Sequences:", len(selected_sequences))

for seq in selected_sequences:
    print(f"{seq.name}: {len(list((seq / 'img1').glob('*.jpg')))} frames")

Detector: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/models/football_player_detector.pt
Tracker config: default bytetrack.yaml
Sequences: 5
v_2QhNRucNC7E_c017: 450 frames
v_G-vNjfx1GGc_c600: 500 frames
v_ITo3sCnpw_k_c011: 776 frames
v_dw7LOz17Omg_c067: 450 frames
v_i2_L4qquVg0_c010: 758 frames

In [30]:
all_tracking_results = {}

for seq in selected_sequences:
    seq_name = seq.name
    img_dir = seq / "img1"

    print(f"\n{'='*60}")
    print(f"TRACKING: {seq_name}")
    print(f"{'='*60}")

    results = player_model.track(
        source=str(img_dir),
        tracker="bytetrack.yaml",
        persist=False,
        stream=True,
        verbose=False,
        conf=0.25,
        imgsz=1280,
        device=0
    )

    rows = []

    for frame_idx, result in enumerate(results, start=1):
        if result.boxes is None or result.boxes.id is None:
            continue

        boxes = result.boxes.xyxy.cpu().numpy()
        ids = result.boxes.id.cpu().numpy().astype(int)
        confs = result.boxes.conf.cpu().numpy()

        for box, track_id, confidence in zip(boxes, ids, confs):
            x1, y1, x2, y2 = box

            rows.append({
                "frame": frame_idx,
                "track_id": track_id,
                "x1": float(x1),
                "y1": float(y1),
                "x2": float(x2),
                "y2": float(y2),
                "confidence": float(confidence)
            })

    seq_tracks = pd.DataFrame(rows)
    all_tracking_results[seq_name] = seq_tracks

    print(f"Frames processed : {frame_idx}")
    print(f"Tracking rows    : {len(seq_tracks):,}")
    print(f"Unique track IDs : {seq_tracks['track_id'].nunique()}")

============================================================
TRACKING: v_2QhNRucNC7E_c017
============================================================
Frames processed : 450
Tracking rows    : 7,113
Unique track IDs : 23

============================================================
TRACKING: v_G-vNjfx1GGc_c600
============================================================
Frames processed : 500
Tracking rows    : 5,686
Unique track IDs : 17

============================================================
TRACKING: v_ITo3sCnpw_k_c011
============================================================
Frames processed : 776
Tracking rows    : 10,795
Unique track IDs : 22

============================================================
TRACKING: v_dw7LOz17Omg_c067
============================================================
Frames processed : 450
Tracking rows    : 7,534
Unique track IDs : 25

============================================================
TRACKING: v_i2_L4qquVg0_c010
============================================================
Frames processed : 758
Tracking rows    : 8,726
Unique track IDs : 20

In [31]:
for seq_name, df in all_tracking_results.items():
    print(f"\n{seq_name}")
    print(f"  Frames with tracks : {df['frame'].nunique()}")
    print(f"  Tracking rows      : {len(df):,}")
    print(f"  Unique IDs         : {df['track_id'].nunique()}")
    print(f"  Avg tracks/frame   : {len(df) / df['frame'].nunique():.2f}")
    print(f"  Max tracks/frame   : {df.groupby('frame').size().max()}")

v_2QhNRucNC7E_c017
  Frames with tracks : 450
  Tracking rows      : 7,113
  Unique IDs         : 23
  Avg tracks/frame   : 15.81
  Max tracks/frame   : 23

v_G-vNjfx1GGc_c600
  Frames with tracks : 500
  Tracking rows      : 5,686
  Unique IDs         : 17
  Avg tracks/frame   : 11.37
  Max tracks/frame   : 17

v_ITo3sCnpw_k_c011
  Frames with tracks : 776
  Tracking rows      : 10,795
  Unique IDs         : 22
  Avg tracks/frame   : 13.91
  Max tracks/frame   : 22

v_dw7LOz17Omg_c067
  Frames with tracks : 450
  Tracking rows      : 7,534
  Unique IDs         : 25
  Avg tracks/frame   : 16.74
  Max tracks/frame   : 25

v_i2_L4qquVg0_c010
  Frames with tracks : 758
  Tracking rows      : 8,726
  Unique IDs         : 20
  Avg tracks/frame   : 11.51
  Max tracks/frame   : 20

In [32]:
sequence_metrics = []

for seq_name, pred_df in all_tracking_results.items():

    seq_dir = VAL_DIR / seq_name
    gt_file = seq_dir / "gt" / "gt.txt"

    gt_seq = pd.read_csv(
        gt_file,
        header=None,
        names=[
            "frame", "track_id", "x", "y",
            "width", "height", "conf", "class", "visibility"
        ]
    )

    gt_seq["x1"] = gt_seq["x"]
    gt_seq["y1"] = gt_seq["y"]
    gt_seq["x2"] = gt_seq["x"] + gt_seq["width"]
    gt_seq["y2"] = gt_seq["y"] + gt_seq["height"]

    acc = mm.MOTAccumulator(auto_id=True)

    for frame in sorted(
        set(gt_seq["frame"]) | set(pred_df["frame"])
    ):
        gt_frame = gt_seq[gt_seq["frame"] == frame]
        pred_frame = pred_df[pred_df["frame"] == frame]

        gt_ids = gt_frame["track_id"].astype(int).tolist()
        pred_ids = pred_frame["track_id"].astype(int).tolist()

        gt_boxes = gt_frame[
            ["x1", "y1", "x2", "y2"]
        ].values

        pred_boxes = pred_frame[
            ["x1", "y1", "x2", "y2"]
        ].values

        if len(gt_boxes) == 0 or len(pred_boxes) == 0:
            distances = None
        else:
            distances = np.array([
                [
                    1 - calculate_iou(gt_box, pred_box)
                    for pred_box in pred_boxes
                ]
                for gt_box in gt_boxes
            ])

            distances[distances > 0.5] = np.nan

        acc.update(
            gt_ids,
            pred_ids,
            distances
        )

    summary = mh.compute(
        acc,
        metrics=[
            "num_frames",
            "num_objects",
            "num_matches",
            "num_switches",
            "num_false_positives",
            "num_misses",
            "mota",
            "motp",
            "idf1"
        ],
        name=seq_name
    )

    sequence_metrics.append(summary)

metrics_df = pd.concat(sequence_metrics)

display(
    metrics_df[
        [
            "num_frames",
            "num_objects",
            "num_matches",
            "num_switches",
            "num_false_positives",
            "num_misses",
            "mota",
            "idf1"
        ]
    ]
)

,num_frames,num_objects,num_matches,num_switches,num_false_positives,num_misses,mota,idf1
v_2QhNRucNC7E_c017,450,6622,1151,5333,629,138,0.078828,0.120131
v_G-vNjfx1GGc_c600,500,5462,1156,3848,682,458,0.086781,0.128095
v_ITo3sCnpw_k_c011,776,9736,2278,7313,1204,145,0.110312,0.115727
v_dw7LOz17Omg_c067,450,6959,1068,5735,731,156,0.048426,0.100048
v_i2_L4qquVg0_c010,758,8262,1899,6196,631,167,0.153474,0.111726

In [33]:
seq_name = "v_2QhNRucNC7E_c017"

pred_df = all_tracking_results[seq_name]

gt_file = VAL_DIR / seq_name / "gt" / "gt.txt"

gt_test = pd.read_csv(
    gt_file,
    header=None,
    names=[
        "frame", "track_id", "x", "y",
        "width", "height", "conf", "class", "visibility"
    ]
)

gt_test["x1"] = gt_test["x"]
gt_test["y1"] = gt_test["y"]
gt_test["x2"] = gt_test["x"] + gt_test["width"]
gt_test["y2"] = gt_test["y"] + gt_test["height"]

print("GT rows:", len(gt_test))
print("Prediction rows:", len(pred_df))

print("GT frames:", gt_test["frame"].min(), "→", gt_test["frame"].max())
print("Pred frames:", pred_df["frame"].min(), "→", pred_df["frame"].max())

print("GT unique IDs:", gt_test["track_id"].nunique())
print("Pred unique IDs:", pred_df["track_id"].nunique())

# Check one frame manually
frame = 1

g = gt_test[gt_test["frame"] == frame]
p = pred_df[pred_df["frame"] == frame]

print("\nFrame 1")
print("GT boxes:", len(g))
print("Pred boxes:", len(p))

if len(g) and len(p):
    ious = []

    for _, gt_row in g.iterrows():
        gt_box = [
            gt_row["x1"], gt_row["y1"],
            gt_row["x2"], gt_row["y2"]
        ]

        best_iou = max(
            calculate_iou(
                gt_box,
                [
                    r["x1"], r["y1"],
                    r["x2"], r["y2"]
                ]
            )
            for _, r in p.iterrows()
        )

        ious.append(best_iou)

    print("Best IoU per GT box:")
    print(np.round(ious, 3))

    print("GT boxes with IoU >= 0.5:",
          sum(i >= 0.5 for i in ious))

GT rows: 6622
Prediction rows: 7113
GT frames: 1 → 450
Pred frames: 1 → 450
GT unique IDs: 21
Pred unique IDs: 23

Frame 1
GT boxes: 19
Pred boxes: 22
Best IoU per GT box:
[      0.964       0.912       0.872       0.982       0.973       0.927       0.955       0.923       0.983       0.946       0.967       0.959       0.977       0.904       0.952        0.95       0.934       0.782       0.921]
GT boxes with IoU >= 0.5: 19

In [34]:
# Test the MOT accumulator on a single frame

acc_test = mm.MOTAccumulator(auto_id=True)

frame = 1

g = gt_test[gt_test["frame"] == frame]
p = pred_df[pred_df["frame"] == frame]

gt_ids = g["track_id"].astype(int).tolist()
pred_ids = p["track_id"].astype(int).tolist()

gt_boxes = g[["x1", "y1", "x2", "y2"]].values
pred_boxes = p[["x1", "y1", "x2", "y2"]].values

distances = np.array([
    [
        1 - calculate_iou(gt_box, pred_box)
        for pred_box in pred_boxes
    ]
    for gt_box in gt_boxes
])

# Reject IoU < 0.5
distances[distances > 0.5] = np.nan

acc_test.update(
    gt_ids,
    pred_ids,
    distances
)

test_summary = mh.compute(
    acc_test,
    metrics=[
        "num_matches",
        "num_false_positives",
        "num_misses",
        "num_switches",
        "mota",
        "idf1"
    ],
    name="frame_1"
)

display(test_summary.T)

                       frame_1
num_matches          19.000000
num_false_positives   3.000000
num_misses            0.000000
num_switches          0.000000
mota                  0.842105
idf1                  0.926829

In [35]:
print("Prediction ID summary:")
print(
    pred_df.groupby("track_id")["frame"]
    .agg(["min", "max", "count"])
    .sort_values("count", ascending=False)
    .head(15)
)

print("\nNumber of prediction IDs:", pred_df["track_id"].nunique())
print("Prediction ID range:",
      pred_df["track_id"].min(),
      "→",
      pred_df["track_id"].max())

print("\nGT ID range:",
      gt_test["track_id"].min(),
      "→",
      gt_test["track_id"].max())

Prediction ID summary:
          min  max  count
track_id
1           1  450    450
2           1  450    450
3           1  450    450
4           1  450    450
5           1  450    450
6           1  450    450
7           1  450    450
8           1  450    450
9           1  450    450
10          1  450    450
11          1  450    450
12          1  450    447
13          1  449    433
14          1  448    393
15          1  417    306

Number of prediction IDs: 23
Prediction ID range: 1 → 23

GT ID range: 0 → 20

In [36]:
print("GT confidence values:")
print(gt_test["conf"].value_counts().sort_index())

print("\nGT class values:")
print(gt_test["class"].value_counts().sort_index())

print("\nGT visibility statistics:")
print(gt_test["visibility"].describe())

print("\nGT rows by class:")
print(gt_test.groupby("class").size())

GT confidence values:
conf
1    6622
Name: count, dtype: int64

GT class values:
class
1    6622
Name: count, dtype: int64

GT visibility statistics:
count    6622.0
mean        1.0
std         0.0
min         1.0
25%         1.0
50%         1.0
75%         1.0
max         1.0
Name: visibility, dtype: float64

GT rows by class:
class
1    6622
dtype: int64

In [37]:
# Recalculate frame-level Hungarian matches for this exact run

all_matches = []

for frame in sorted(gt_test["frame"].unique()):

    g = gt_test[gt_test["frame"] == frame]
    p = pred_df[pred_df["frame"] == frame]

    gt_boxes = g[["x1", "y1", "x2", "y2"]].values
    pred_boxes = p[["x1", "y1", "x2", "y2"]].values

    if len(gt_boxes) == 0 or len(pred_boxes) == 0:
        continue

    iou_matrix = np.array([
        [
            calculate_iou(gt_box, pred_box)
            for pred_box in pred_boxes
        ]
        for gt_box in gt_boxes
    ])

    cost = 1 - iou_matrix

    row_ind, col_ind = linear_sum_assignment(cost)

    for r, c in zip(row_ind, col_ind):
        if iou_matrix[r, c] >= 0.5:
            all_matches.append({
                "frame": frame,
                "gt_id": int(g.iloc[r]["track_id"]),
                "pred_id": int(p.iloc[c]["track_id"]),
                "iou": float(iou_matrix[r, c])
            })

matches_current = pd.DataFrame(all_matches)

print("========== HUNGARIAN MATCHING ==========")
print("Matches:", len(matches_current))
print("Match rate:", len(matches_current) / len(gt_test))
print("Mean IoU:", matches_current["iou"].mean())

========== HUNGARIAN MATCHING ==========
Matches: 6484
Match rate: 0.9791603745092117
Mean IoU: 0.9311683026294354

In [38]:
matches_sorted = matches_current.sort_values(
    ["gt_id", "frame"]
).reset_index(drop=True)

switch_events = []

for gt_id, group in matches_sorted.groupby("gt_id"):

    group = group.sort_values("frame").reset_index(drop=True)

    for i in range(1, len(group)):

        prev = group.iloc[i - 1]
        curr = group.iloc[i]

        # Only count a switch when the same GT is matched
        # in consecutive frames.
        if curr["frame"] == prev["frame"] + 1:

            if curr["pred_id"] != prev["pred_id"]:

                switch_events.append({
                    "gt_id": int(gt_id),
                    "frame": int(curr["frame"]),
                    "previous_pred_id": int(prev["pred_id"]),
                    "new_pred_id": int(curr["pred_id"])
                })

switch_df_current = pd.DataFrame(switch_events)

print("========== CURRENT TRACKING DIAGNOSTIC ==========")
print("Matches:", len(matches_current))
print("Match rate:", f"{len(matches_current) / len(gt_test) * 100:.2f}%")
print("Mean IoU:", f"{matches_current['iou'].mean():.4f}")
print("Consecutive-frame ID switches:", len(switch_df_current))

if len(switch_df_current):
    display(switch_df_current.head(20))

========== CURRENT TRACKING DIAGNOSTIC ==========
Matches: 6484
Match rate: 97.92%
Mean IoU: 0.9312
Consecutive-frame ID switches: 5269

    gt_id  frame  previous_pred_id  new_pred_id
0       0      3                 4            5
1       0      4                 5            7
2       0      5                 7            6
3       0      6                 6            3
4       0      7                 3            5
5       0      8                 5            3
6       0      9                 3           15
7       0     10                15            3
8       0     13                 3            1
9       0     15                 1            2
10      0     16                 2            1
11      0     18                 1            3
12      0     20                 3            2
13      0     23                 2            3
14      0     27                 3            5
15      0     29                 5            6
16      0     30                 6            7
17      0     31                 7            6
18      0     32                 6            5
19      0     33                 5            3

In [39]:
# Rebuild MOTAccumulator for only the first 10 frames
# so we can inspect the identity events directly.

acc_debug = mm.MOTAccumulator(auto_id=True)

for frame in range(1, 11):

    g = gt_test[gt_test["frame"] == frame]
    p = pred_df[pred_df["frame"] == frame]

    gt_ids = g["track_id"].astype(int).tolist()
    pred_ids = p["track_id"].astype(int).tolist()

    gt_boxes = g[["x1", "y1", "x2", "y2"]].values
    pred_boxes = p[["x1", "y1", "x2", "y2"]].values

    distances = np.array([
        [
            1 - calculate_iou(gt_box, pred_box)
            for pred_box in pred_boxes
        ]
        for gt_box in gt_boxes
    ])

    distances[distances > 0.5] = np.nan

    acc_debug.update(
        gt_ids,
        pred_ids,
        distances
    )

events = acc_debug.events

display(events.head(50))

                Type   OId   HId         D
FrameId Event
0       0        RAW   NaN   NaN       NaN
        1        RAW   0.0   4.0  0.036398
        2        RAW   1.0   6.0  0.088409
        3        RAW   2.0   7.0  0.128193
        4        RAW   3.0   9.0  0.018088
        5        RAW   4.0  14.0  0.027237
        6        RAW   5.0  20.0  0.073484
        7        RAW   6.0  10.0  0.045358
        8        RAW   7.0  12.0  0.076899
        9        RAW   8.0  16.0  0.017035
        10       RAW  10.0   1.0  0.053537
        11       RAW  11.0   3.0  0.033107
        12       RAW  12.0  11.0  0.040721
        13       RAW  13.0  13.0  0.022779
        14       RAW  14.0  21.0  0.098144
        15       RAW  14.0  22.0  0.096355
        16       RAW  15.0   2.0  0.048246
        17       RAW  16.0   5.0  0.049710
        18       RAW  17.0   8.0  0.066217
        19       RAW  18.0  17.0  0.217740
        20       RAW  20.0  15.0  0.078618
        21       RAW   NaN  18.0       NaN
        22       RAW   NaN  19.0       NaN
        23     MATCH   0.0   4.0  0.036398
        24     MATCH   1.0   6.0  0.088409
        25     MATCH   2.0   7.0  0.128193
        26     MATCH   3.0   9.0  0.018088
        27     MATCH   4.0  14.0  0.027237
        28     MATCH   5.0  20.0  0.073484
        29     MATCH   6.0  10.0  0.045358
        30     MATCH   7.0  12.0  0.076899
        31     MATCH   8.0  16.0  0.017035
        32     MATCH  10.0   1.0  0.053537
        33     MATCH  11.0   3.0  0.033107
        34     MATCH  12.0  11.0  0.040721
        35     MATCH  13.0  13.0  0.022779
        36     MATCH  14.0  22.0  0.096355
        37     MATCH  15.0   2.0  0.048246
        38     MATCH  16.0   5.0  0.049710
        39     MATCH  17.0   8.0  0.066217
        40     MATCH  18.0  17.0  0.217740
        41     MATCH  20.0  15.0  0.078618
        42        FP   NaN  18.0       NaN
        43        FP   NaN  19.0       NaN
        44        FP   NaN  21.0       NaN
1       0        RAW   NaN   NaN       NaN
        1        RAW   0.0   4.0  0.056095
        2        RAW   1.0  19.0  0.034839
        3        RAW   2.0   6.0  0.058423
        4        RAW   3.0  15.0  0.052785

In [40]:
track_id = 4

track_4 = pred_df[
    pred_df["track_id"] == track_id
].sort_values("frame").copy()

track_4["cx"] = (track_4["x1"] + track_4["x2"]) / 2
track_4["cy"] = (track_4["y1"] + track_4["y2"]) / 2

print("Track ID:", track_id)
print("Frames:", len(track_4))
print("Frame range:", track_4["frame"].min(), "→", track_4["frame"].max())

print("\nFirst 20 positions:")
display(
    track_4[
        ["frame", "cx", "cy", "confidence"]
    ].head(20)
)

print("\nLargest frame-to-frame position jumps:")

track_4["jump"] = np.sqrt(
    track_4["cx"].diff() ** 2 +
    track_4["cy"].diff() ** 2
)

display(
    track_4.nlargest(
        15,
        "jump"
    )[
        ["frame", "cx", "cy", "jump"]
    ]
)

Track ID: 4
Frames: 450
Frame range: 1 → 450

First 20 positions:

     frame           cx          cy  confidence
3        1   527.026718  504.680450    0.950326
25       2   534.277222  505.706360    0.952642
44       3   808.423462  427.286591    0.956991
63       4   811.854248  427.314240    0.956056
83       5   541.809570  426.793396    0.959769
102      6   946.127930  437.112915    0.952424
121      7    77.234896  519.758301    0.957423
140      8   560.230225  429.895874    0.949734
161      9   977.275635  435.316956    0.952475
180     10   271.446953  352.089661    0.948595
199     11   274.162659  353.877319    0.950752
218     12   280.019714  355.014099    0.953363
238     13   745.367065  211.202148    0.949257
257     14   872.123596  425.942688    0.947743
276     15   577.142212  310.142029    0.954190
295     16   879.033203  425.053711    0.952071
315     17   881.069824  424.064056    0.951065
335     18   883.738647  423.586853    0.954270
355     19  1080.635742  284.572014    0.952312
375     20  1195.139160  355.071106    0.956760

Largest frame-to-frame position jumps:

      frame           cx          cy         jump
2874    165    31.001871  539.715759  1237.313089
951      50   101.886955  506.007904  1133.816292
932      49  1225.755981  356.148651  1126.184798
2184    121   124.270218  526.482040  1085.864752
5431    334  1247.355225  464.630402  1081.057251
3838    224  1157.412354  328.365967   989.491915
2908    167  1219.467041  311.275635   967.691710
2169    120  1174.459106  250.428497   959.002873
816      43  1207.447754  355.141937   937.429381
4704    281   245.541687  290.158325   936.294173
719      38  1194.512939  354.331238   927.812631
2477    140   127.546585  532.126114   917.253337
452      24   278.639099  359.174103   914.419566
1973    107   213.791107  342.102112   911.213787
5270    323   232.706879  308.073189   909.252677

In [41]:
strict_tracker_config = Path(
    "/mnt/d/My Projects/AthletiQ/AthletiQ/"
    "ai-engine/notebooks/bytetrack_strict.yaml"
)

strict_tracker_config.write_text("""
tracker_type: bytetrack
track_high_thresh: 0.5
track_low_thresh: 0.1
new_track_thresh: 0.5
track_buffer: 30
match_thresh: 0.9
fuse_score: True
""")

print(strict_tracker_config)
print(strict_tracker_config.read_text())

/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/notebooks/bytetrack_strict.yaml

tracker_type: bytetrack
track_high_thresh: 0.5
track_low_thresh: 0.1
new_track_thresh: 0.5
track_buffer: 30
match_thresh: 0.9
fuse_score: True

In [42]:
test_seq = VAL_DIR / "v_2QhNRucNC7E_c017"
img_dir = test_seq / "img1"

strict_results = player_model.track(
    source=str(img_dir),
    tracker=str(strict_tracker_config),
    persist=False,
    stream=True,
    verbose=False,
    conf=0.25,
    imgsz=1280,
    device=0
)

strict_rows = []

for frame_idx, result in enumerate(strict_results, start=1):

    if result.boxes is None or result.boxes.id is None:
        continue

    boxes = result.boxes.xyxy.cpu().numpy()
    ids = result.boxes.id.cpu().numpy().astype(int)
    confs = result.boxes.conf.cpu().numpy()

    for box, track_id, confidence in zip(boxes, ids, confs):
        x1, y1, x2, y2 = box

        strict_rows.append({
            "frame": frame_idx,
            "track_id": track_id,
            "x1": float(x1),
            "y1": float(y1),
            "x2": float(x2),
            "y2": float(y2),
            "confidence": float(confidence)
        })

strict_df = pd.DataFrame(strict_rows)

print("========== STRICT BYTETRACK ==========")
print("Frames:", strict_df["frame"].nunique())
print("Tracking rows:", len(strict_df))
print("Unique IDs:", strict_df["track_id"].nunique())
print("Avg tracks/frame:",
      len(strict_df) / strict_df["frame"].nunique())

========== STRICT BYTETRACK ==========
Frames: 450
Tracking rows: 6862
Unique IDs: 21
Avg tracks/frame: 15.248888888888889

In [43]:
track_id = 4

track_strict = strict_df[
    strict_df["track_id"] == track_id
].sort_values("frame").copy()

track_strict["cx"] = (
    track_strict["x1"] + track_strict["x2"]
) / 2

track_strict["cy"] = (
    track_strict["y1"] + track_strict["y2"]
) / 2

track_strict["jump"] = np.sqrt(
    track_strict["cx"].diff() ** 2 +
    track_strict["cy"].diff() ** 2
)

print("Track ID:", track_id)
print("Frames:", len(track_strict))
print("Frame range:",
      track_strict["frame"].min(),
      "→",
      track_strict["frame"].max())

print("\nLargest position jumps:")
display(
    track_strict.nlargest(
        15, "jump"
    )[[
        "frame",
        "cx",
        "cy",
        "jump"
    ]]
)

Track ID: 4
Frames: 450
Frame range: 1 → 450

Largest position jumps:

      frame           cx          cy         jump
2765    165    31.001871  539.715759  1237.313089
926      50   101.886955  506.007904  1133.816292
908      49  1225.755981  356.148651  1126.184798
2096    121   124.270218  526.482040  1085.864752
5258    334  1247.355225  464.630402  1081.057251
3696    224  1157.412354  328.365967   989.491915
2798    167  1219.467041  311.275635   967.691710
2081    120  1174.459106  250.428497   959.002873
795      43  1207.447754  355.141937   937.429381
4547    281   245.541687  290.158325   936.294173
700      38  1194.512939  354.331238   927.812631
2377    140   127.546585  532.126114   917.253337
442      24   278.639099  359.174103   914.419566
1893    107   213.791107  342.102112   911.213787
5103    323   232.706879  308.073189   909.252677

In [44]:
print("========== FIRST 10 FRAMES ==========")

for frame in range(1, 11):
    f = strict_df[strict_df["frame"] == frame]

    print(
        f"Frame {frame:3d}: "
        f"{len(f):2d} detections | "
        f"IDs = {sorted(f['track_id'].tolist())}"
    )

========== FIRST 10 FRAMES ==========
Frame   1: 21 detections | IDs = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
Frame   2: 19 detections | IDs = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Frame   3: 19 detections | IDs = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Frame   4: 20 detections | IDs = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
Frame   5: 19 detections | IDs = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Frame   6: 19 detections | IDs = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Frame   7: 19 detections | IDs = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Frame   8: 19 detections | IDs = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Frame   9: 18 detections | IDs = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
Frame  10: 19 detections | IDs = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [45]:
# Build a GT ↔ prediction association table
# using the existing Hungarian matches.

association = (
    matches_current
    .groupby(["pred_id", "gt_id"])
    .size()
    .reset_index(name="frames")
    .sort_values(["pred_id", "frames"], ascending=[True, False])
)

print("========== PREDICTION ID → GT ID ASSOCIATIONS ==========")

for pred_id in sorted(association["pred_id"].unique()):
    rows = association[association["pred_id"] == pred_id]

    print(
        f"\nPred ID {pred_id}:"
    )

    display(
        rows.head(5)[
            ["pred_id", "gt_id", "frames"]
        ]
    )

========== PREDICTION ID → GT ID ASSOCIATIONS ==========

Pred ID 1:

    pred_id  gt_id  frames
0         1      0      92
10        1     10      80
18        1     19      52
11        1     11      41
6         1      6      39

Pred ID 2:

    pred_id  gt_id  frames
29        2     10      90
19        2      0      66
35        2     16      63
30        2     11      47
34        2     15      28

Pred ID 3:

    pred_id  gt_id  frames
55        3     16      66
49        3     10      63
39        3      0      58
50        3     11      34
53        3     14      24

Pred ID 4:

    pred_id  gt_id  frames
69        4     10      64
59        4      0      52
75        4     16      43
73        4     14      31
76        4     17      28

Pred ID 5:

    pred_id  gt_id  frames
93        5     14      48
79        5      0      46
95        5     16      44
89        5     10      39
91        5     12      28

Pred ID 6:

     pred_id  gt_id  frames
113        6     14      52
116        6     17      37
103        6      4      33
109        6     10      33
105        6      6      32

Pred ID 7:

     pred_id  gt_id  frames
123        7      4      43
136        7     17      43
133        7     14      42
120        7      1      37
122        7      3      32

Pred ID 8:

     pred_id  gt_id  frames
153        8     14      53
152        8     13      48
143        8      4      40
151        8     12      36
156        8     17      29

Pred ID 9:

     pred_id  gt_id  frames
163        9      4      59
172        9     13      43
177        9     18      37
173        9     14      35
166        9      7      33

Pred ID 10:

     pred_id  gt_id  frames
197       10     18      57
183       10      4      55
192       10     13      42
191       10     12      31
196       10     17      30

Pred ID 11:

     pred_id  gt_id  frames
215       11     18      82
210       11     13      49
202       11      4      47
205       11      7      41
203       11      5      35

Pred ID 12:

     pred_id  gt_id  frames
233       12     18      69
224       12      7      55
222       12      5      42
221       12      4      41
232       12     17      32

Pred ID 13:

     pred_id  gt_id  frames
240       13      5      56
242       13      7      51
253       13     18      43
239       13      4      37
237       13      2      32

Pred ID 14:

     pred_id  gt_id  frames
262       14      7      60
260       14      5      57
271       14     18      43
257       14      2      39
263       14      8      28

Pred ID 15:

     pred_id  gt_id  frames
279       15      5      49
276       15      2      36
281       15      7      33
282       15      8      17
286       15     13      15

Pred ID 16:

     pred_id  gt_id  frames
297       16      5      36
294       16      2      24
305       16     14      12
309       16     18      12
299       16      7      11

Pred ID 17:

     pred_id  gt_id  frames
315       17      5      22
312       17      2      20
317       17      8      15
316       17      7      12
321       17     14      10

Pred ID 18:

     pred_id  gt_id  frames
332       18      8      15
330       18      5      13
336       18     14       7
327       18      2       6
334       18     12       6

Pred ID 19:

     pred_id  gt_id  frames
348       19      8      12
345       19      5       7
342       19      2       5
353       19     14       5
351       19     12       4

Pred ID 20:

     pred_id  gt_id  frames
361       20     14       3
363       20     17       2
358       20      1       1
359       20      4       1
360       20      5       1

Pred ID 21:

     pred_id  gt_id  frames
364       21     11       1
365       21     14       1
366       21     15       1

Pred ID 22:

     pred_id  gt_id  frames
367       22     14       1
368       22     17       1

Pred ID 23:

     pred_id  gt_id  frames
369       23      4       1

In [46]:
import motmetrics as mm

print("motmetrics version:", mm.__version__)
print("Available metrics:", len(mm.metrics.motchallenge_metrics))
print(mm.metrics.motchallenge_metrics)

motmetrics version: 1.4.0
Available metrics: 18
['idf1', 'idp', 'idr', 'recall', 'precision', 'num_unique_objects', 'mostly_tracked', 'partially_tracked', 'mostly_lost', 'num_false_positives', 'num_misses', 'num_switches', 'num_fragmentations', 'mota', 'motp', 'num_transfer', 'num_ascend', 'num_migrate']

In [47]:
continuity_stats = []

for track_id, group in strict_df.groupby("track_id"):

    group = group.sort_values("frame").copy()

    cx = (group["x1"] + group["x2"]) / 2
    cy = (group["y1"] + group["y2"]) / 2

    jumps = np.sqrt(
        cx.diff() ** 2 +
        cy.diff() ** 2
    ).dropna()

    continuity_stats.append({
        "track_id": int(track_id),
        "frames": len(group),
        "start": int(group["frame"].min()),
        "end": int(group["frame"].max()),
        "max_jump_px": float(jumps.max()) if len(jumps) else 0,
        "mean_jump_px": float(jumps.mean()) if len(jumps) else 0,
        "jumps_over_300": int((jumps > 300).sum()),
        "jumps_over_500": int((jumps > 500).sum()),
    })

continuity_df = pd.DataFrame(continuity_stats)

display(
    continuity_df.sort_values(
        "max_jump_px",
        ascending=False
    )
)

,track_id,frames,start,end,max_jump_px,mean_jump_px,jumps_over_300,jumps_over_500
14,15,259,1,415,1251.995867,300.461438,117,59
2,3,450,1,450,1245.890221,374.037321,249,140
5,6,450,1,450,1244.033036,378.859647,247,138
3,4,450,1,450,1237.313089,345.726069,230,105
1,2,450,1,450,1214.794212,338.418610,222,129
9,10,450,1,450,1172.825892,334.529185,221,124
11,12,442,1,450,1170.468542,281.249661,184,92
17,18,71,1,389,1167.440140,465.636463,50,30
6,7,450,1,450,1162.941092,377.480000,243,146
8,9,450,1,450,1152.749365,342.577510,219,116
13,14,361,1,416,1151.626249,265.512963,135,56
7,8,450,1,450,1145.578314,348.606403,221,133
4,5,450,1,450,1124.252380,353.646813,232,136
0,1,450,1,450,1114.234811,306.380631,194,123
10,11,447,1,450,1099.459609,312.329594,218,108
16,17,125,1,398,1085.374771,299.648803,57,26
15,16,178,1,398,1067.715896,245.341486,57,25
12,13,423,1,448,1049.277679,301.372437,188,90
18,19,44,1,162,929.283502,318.506123,20,9
19,20,11,1,66,730.426660,338.264500,5,3
20,21,1,1,1,0.000000,0.000000,0,0

In [48]:
continuity_stats = []

for track_id, group in strict_df.groupby("track_id"):

    # IMPORTANT: sort chronologically
    group = group.sort_values("frame").copy()

    cx = (group["x1"] + group["x2"]) / 2
    cy = (group["y1"] + group["y2"]) / 2

    jumps = np.sqrt(
        cx.diff() ** 2 +
        cy.diff() ** 2
    ).dropna()

    continuity_stats.append({
        "track_id": int(track_id),
        "frames": len(group),
        "start": int(group["frame"].min()),
        "end": int(group["frame"].max()),
        "max_jump_px": float(jumps.max()) if len(jumps) else 0,
        "mean_jump_px": float(jumps.mean()) if len(jumps) else 0,
        "jumps_over_300": int((jumps > 300).sum()),
        "jumps_over_500": int((jumps > 500).sum()),
    })

continuity_df = pd.DataFrame(continuity_stats)

display(
    continuity_df.sort_values(
        "max_jump_px",
        ascending=False
    ).reset_index(drop=True)
)

,track_id,frames,start,end,max_jump_px,mean_jump_px,jumps_over_300,jumps_over_500
0,15,259,1,415,1251.995867,300.461438,117,59
1,3,450,1,450,1245.890221,374.037321,249,140
2,6,450,1,450,1244.033036,378.859647,247,138
3,4,450,1,450,1237.313089,345.726069,230,105
4,2,450,1,450,1214.794212,338.418610,222,129
5,10,450,1,450,1172.825892,334.529185,221,124
6,12,442,1,450,1170.468542,281.249661,184,92
7,18,71,1,389,1167.440140,465.636463,50,30
8,7,450,1,450,1162.941092,377.480000,243,146
9,9,450,1,450,1152.749365,342.577510,219,116
10,14,361,1,416,1151.626249,265.512963,135,56
11,8,450,1,450,1145.578314,348.606403,221,133
12,5,450,1,450,1124.252380,353.646813,232,136
13,1,450,1,450,1114.234811,306.380631,194,123
14,11,447,1,450,1099.459609,312.329594,218,108
15,17,125,1,398,1085.374771,299.648803,57,26
16,16,178,1,398,1067.715896,245.341486,57,25
17,13,423,1,448,1049.277679,301.372437,188,90
18,19,44,1,162,929.283502,318.506123,20,9
19,20,11,1,66,730.426660,338.264500,5,3
20,21,1,1,1,0.000000,0.000000,0,0

In [49]:
print("Columns:")
print(strict_df.columns.tolist())

print("\nShape:")
print(strict_df.shape)

print("\nFirst 10 rows:")
display(strict_df.head(10))

print("\nLast 10 rows:")
display(strict_df.tail(10))

print("\nFrame statistics:")
print(strict_df["frame"].describe())

print("\nTrack ID statistics:")
print(strict_df["track_id"].describe())

Columns:
['frame', 'track_id', 'x1', 'y1', 'x2', 'y2', 'confidence']

Shape:
(6862, 7)

First 10 rows:

,frame,track_id,x1,y1,x2,y2,confidence
0,1,1,776.609619,385.219666,816.669189,467.823547,0.958812
1,1,2,953.606995,240.375244,992.615417,307.178589,0.955291
2,1,3,1073.547852,303.178772,1100.982422,376.013000,0.951863
3,1,4,509.419830,459.365112,544.633606,549.995789,0.950326
4,1,5,505.393768,378.801636,536.201477,465.070984,0.943560
5,1,6,873.090149,398.265869,907.199646,481.103210,0.940528
6,1,7,928.057434,207.583313,956.454041,266.102753,0.936946
7,1,8,877.174988,208.466522,902.128479,271.671265,0.934530
8,1,9,197.156128,312.695312,247.974945,378.660950,0.934529
9,1,10,7.413300,469.603912,46.784611,574.750854,0.934207

Last 10 rows:

,frame,track_id,x1,y1,x2,y2,confidence
6852,450,3,944.676147,446.710144,982.937866,536.862305,0.956555
6853,450,4,424.891937,287.842834,472.261505,359.166077,0.955474
6854,450,5,988.925903,358.883484,1035.437378,437.231079,0.950609
6855,450,6,1080.456421,244.413193,1108.844116,315.322998,0.938196
6856,450,7,506.662079,215.084351,554.186584,278.006104,0.927266
6857,450,8,714.116150,293.553375,750.391418,364.821930,0.923574
6858,450,9,822.670044,246.934555,856.195068,310.239380,0.921279
6859,450,10,633.494568,221.817688,661.512024,283.290222,0.894812
6860,450,11,1127.622192,208.592590,1172.544067,268.261749,0.793734
6861,450,12,1141.762817,242.714386,1173.812866,308.396576,0.711225

Frame statistics:
count    6862.000000
mean      212.120519
std       130.526209
min         1.000000
25%        96.000000
50%       208.000000
75%       326.000000
max       450.000000
Name: frame, dtype: float64

Track ID statistics:
count    6862.000000
mean        8.268289
std         4.641452
min         1.000000
25%         4.000000
50%         8.000000
75%        12.000000
max        21.000000
Name: track_id, dtype: float64

In [50]:
# Check chronological continuity for ONE track
test_track_id = 1

g = (
    strict_df[strict_df["track_id"] == test_track_id]
    .sort_values("frame")
    .reset_index(drop=True)
)

cx = (g["x1"] + g["x2"]) / 2
cy = (g["y1"] + g["y2"]) / 2

g["cx"] = cx
g["cy"] = cy
g["jump_px"] = np.sqrt(
    g["cx"].diff() ** 2 +
    g["cy"].diff() ** 2
)

print(f"Track ID: {test_track_id}")
print(f"Number of detections: {len(g)}")
print(f"Start frame: {g['frame'].min()}")
print(f"End frame: {g['frame'].max()}")

display(
    g[
        ["frame", "track_id", "cx", "cy", "jump_px"]
    ].head(20)
)

print("\nLargest jumps:")
display(
    g[
        ["frame", "cx", "cy", "jump_px"]
    ]
    .sort_values("jump_px", ascending=False)
    .head(10)
)

Track ID: 1
Number of detections: 450
Start frame: 1
End frame: 450

    frame  track_id           cx          cy      jump_px
0       1         1   796.639404  426.521606          NaN
1       2         1   804.894409  426.814697     8.260206
2       3         1   511.038971  304.369507   318.345478
3       4         1  1001.233154  275.729828   491.030110
4       5         1  1120.937378  343.111450   137.365877
5       6         1  1018.129883  276.520081   122.489965
6       7         1  1139.062012  344.109894   138.538668
7       8         1    82.735535  519.300476  1070.755512
8       9         1  1152.762939  345.570007  1084.039170
9      10         1   572.546509  429.782837   586.295921
10     11         1   577.080688  429.072754     4.589445
11     12         1   863.776550  426.414062   286.708189
12     13         1   610.701233  513.449890   267.623526
13     14         1   618.696777  514.700134     8.092703
14     15         1  1180.696289  351.608948   585.185600
15     16         1   631.073547  517.156601   574.013226
16     17         1   634.237793  518.364243     3.386864
17     18         1  1191.402832  353.897797   580.932089
18     19         1  1193.301758  354.754730     2.083328
19     20         1   589.277466  432.740479   609.037866

Largest jumps:

     frame           cx          cy      jump_px
286    287   116.819565  262.018608  1114.234811
244    245    43.921311  377.266785  1107.994138
126    127  1206.228882  251.928894  1102.895888
8        9  1152.762939  345.570007  1084.039170
7        8    82.735535  519.300476  1070.755512
110    111  1135.527344  251.982758  1065.171748
319    320   228.973145  537.474670  1002.605576
317    318   245.320892  535.331421  1002.546214
214    215   215.145767  351.443970  1001.794736
220    221   180.220688  353.961243   997.489284

In [51]:
for frame_id in range(1, 6):

    g = (
        strict_df[strict_df["frame"] == frame_id]
        .copy()
    )

    g["cx"] = (g["x1"] + g["x2"]) / 2
    g["cy"] = (g["y1"] + g["y2"]) / 2

    print(f"\n===== FRAME {frame_id} =====")

    display(
        g[
            ["track_id", "cx", "cy", "confidence"]
        ]
        .sort_values("track_id")
        .reset_index(drop=True)
    )

===== FRAME 1 =====

    track_id           cx          cy  confidence
0          1   796.639404  426.521606    0.958812
1          2   973.111206  273.776917    0.955291
2          3  1087.265137  339.595886    0.951863
3          4   527.026718  504.680450    0.950326
4          5   520.797623  421.936310    0.943560
5          6   890.144897  439.684540    0.940528
6          7   942.255737  236.843033    0.936946
7          8   889.651733  240.068893    0.934530
8          9   222.565536  345.678131    0.934529
9         10    27.098955  522.177383    0.934207
10        11   497.227234  304.273682    0.930450
11        12   307.141357  221.735733    0.929904
12        13   668.068237  207.257385    0.926908
13        14   411.620605  250.859955    0.926640
14        15  1269.291260  220.059937    0.920308
15        16    13.496259  264.562447    0.908129
16        17   818.762939  221.851715    0.907301
17        18  1267.806396  197.997070    0.785031
18        19   641.552124  281.008842    0.769087
19        20   370.363098  234.253815    0.738288
20        21   782.831482  269.147095    0.631088

===== FRAME 2 =====

    track_id           cx          cy  confidence
0          1   804.894409  426.814697    0.959645
1          2   982.333740  274.608948    0.958364
2          3  1095.218994  340.373230    0.957256
3          4   534.277222  505.706360    0.952642
4          5   528.082153  421.979584    0.951447
5          6   951.914795  236.906586    0.934695
6          7   897.078613  240.755981    0.933730
7          8   317.345062  220.495514    0.933498
8          9   675.416260  206.938858    0.925753
9         10   649.647705  279.989799    0.918691
10        11    19.236740  263.852852    0.903948
11        12   421.827576  251.188965    0.901581
12        13   826.847290  222.029785    0.900796
13        14  1273.527100  223.070343    0.880152
14        15   226.651550  345.297424    0.870899
15        16    35.621009  521.020370    0.852789
16        17   789.551208  269.281799    0.803989
17        18   382.619202  234.939484    0.773599
18        19   901.597778  439.285797    0.743323

===== FRAME 3 =====

    track_id           cx          cy  confidence
0          1   511.038971  304.369507    0.962025
1          2  1102.445312  341.640320    0.958585
2          3   991.504517  275.176849    0.957834
3          4   808.423462  427.286591    0.956991
4          5   541.622559  506.876831    0.947068
5          6   533.638794  422.644775    0.946507
6          7   433.330048  252.413788    0.938974
7          8   797.243225  269.856079    0.937979
8          9    43.578144  520.508789    0.935168
9         10   904.817505  241.027756    0.930814
10        11   961.491333  236.960022    0.930750
11        12   682.167908  206.746521    0.923907
12        13   231.411255  345.034058    0.918900
13        14   835.904663  221.944855    0.917678
14        15    27.391071  263.425995    0.917273
15        16   326.628845  220.050262    0.912001
16        17   656.827942  279.339478    0.893486
17        18   912.814819  439.786987    0.891889
18        19   393.292236  234.819458    0.768159

===== FRAME 4 =====

    track_id           cx          cy  confidence
0          1  1001.233154  275.729828    0.962101
1          2  1110.680176  342.368652    0.958899
2          3   518.518051  304.817261    0.957363
3          4   811.854248  427.314240    0.956056
4          5   536.380615  424.732910    0.953809
5          6   924.435059  439.055420    0.945540
6          7   549.665771  507.594635    0.943795
7          8   237.588867  345.032959    0.942916
8          9   911.757324  242.082306    0.933131
9         10   443.309509  253.200165    0.929681
10        11   844.371338  222.021393    0.927417
11        12   335.920166  219.616180    0.925284
12        13   970.045532  236.985229    0.922602
13        14    52.287899  520.516846    0.912619
14        15   688.707703  206.970154    0.911808
15        16   663.711365  277.786713    0.898658
16        17   404.354309  234.632492    0.893290
17        18   805.533081  270.538116    0.839792
18        19    35.956818  262.946167    0.826014
19        20   805.300903  270.476166    0.639541

===== FRAME 5 =====

    track_id           cx          cy  confidence
0          1  1120.937378  343.111450    0.964449
1          2   527.268311  304.476013    0.961592
2          3  1010.467468  275.889954    0.960360
3          4   541.809570  426.793396    0.959769
4          5   817.707031  427.375214    0.956755
5          6   557.683960  507.800781    0.947952
6          7   242.995377  345.531921    0.947821
7          8   916.945068  243.028900    0.940500
8          9   852.661377  222.284363    0.931093
9         10   453.005249  254.098206    0.930313
10        11    60.354080  520.770386    0.924944
11        12   345.945496  219.240204    0.923500
12        13   977.998962  237.310425    0.922214
13        14   696.246460  207.026581    0.916610
14        15   670.007324  276.378731    0.909046
15        16   414.865845  234.279572    0.902660
16        17   934.864807  438.285706    0.894302
17        18   813.207886  270.724251    0.884331
18        19    44.785660  262.740814    0.655402

In [52]:
from ultralytics import YOLO
import pandas as pd
import numpy as np
import time

PLAYER_MODEL_PATH = "/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/models/football_player_detector.pt"

# Fresh model instance — clears any previous tracker state
fresh_model = YOLO(PLAYER_MODEL_PATH)

fresh_results = []

start_time = time.time()

results = fresh_model.track(
    source=str(IMG_DIR),
    tracker="bytetrack.yaml",
    persist=True,
    stream=True,
    conf=0.25,
    imgsz=1280,
    verbose=False
)

for frame_idx, result in enumerate(results, start=1):

    if result.boxes is None or result.boxes.id is None:
        continue

    boxes = result.boxes.xyxy.cpu().numpy()
    ids = result.boxes.id.cpu().numpy().astype(int)
    confs = result.boxes.conf.cpu().numpy()

    for box, track_id, conf in zip(boxes, ids, confs):

        x1, y1, x2, y2 = box

        fresh_results.append({
            "frame": frame_idx,
            "track_id": track_id,
            "x1": x1,
            "y1": y1,
            "x2": x2,
            "y2": y2,
            "confidence": conf
        })

fresh_df = pd.DataFrame(fresh_results)

elapsed = time.time() - start_time

print(f"Frames: {fresh_df['frame'].nunique()}")
print(f"Rows: {len(fresh_df)}")
print(f"Unique IDs: {fresh_df['track_id'].nunique()}")
print(f"Time: {elapsed:.2f}s")
print(f"FPS: {450 / elapsed:.2f}")

Frames: 450
Rows: 6757
Unique IDs: 69
Time: 33.81s
FPS: 13.31

In [53]:
for frame_id in range(1, 6):

    g = fresh_df[fresh_df["frame"] == frame_id].copy()

    g["cx"] = (g["x1"] + g["x2"]) / 2
    g["cy"] = (g["y1"] + g["y2"]) / 2

    print(f"\n===== FRAME {frame_id} =====")

    display(
        g[
            ["track_id", "cx", "cy", "confidence"]
        ]
        .sort_values("track_id")
        .reset_index(drop=True)
    )

===== FRAME 1 =====

    track_id           cx          cy  confidence
0          1   796.639404  426.521606    0.958812
1          2   973.111206  273.776917    0.955291
2          3  1087.265137  339.595886    0.951863
3          4   527.026733  504.680450    0.950326
4          5   520.797607  421.936310    0.943560
5          6   890.144897  439.684540    0.940528
6          7   942.255737  236.843033    0.936946
7          8   889.651733  240.068893    0.934530
8          9   222.565536  345.678131    0.934529
9         10    27.098955  522.177368    0.934207
10        11   497.227234  304.273682    0.930450
11        12   307.141357  221.735733    0.929904
12        13   668.068237  207.257385    0.926908
13        14   411.620605  250.859955    0.926640
14        15  1269.291260  220.059937    0.920308
15        16    13.496259  264.562439    0.908129
16        17   818.762939  221.851715    0.907301
17        18  1267.806396  197.997070    0.785031
18        19   641.552124  281.008850    0.769087
19        20   370.363098  234.253815    0.738288
20        21   782.831482  269.147095    0.631088
21        22   782.727173  269.013519    0.442686

===== FRAME 2 =====

    track_id           cx          cy  confidence
0          1   803.802856  426.775940    0.959645
1          2   981.114258  274.498932    0.958364
2          3  1094.167236  340.270447    0.957256
3          4   533.318481  505.570679    0.952642
4          5   527.118896  421.973877    0.951447
5          6   900.083374  439.338531    0.743323
6          7   950.637573  236.898193    0.934695
7          8   896.096558  240.665131    0.933730
8          9   226.111237  345.347778    0.870899
9         10    34.494125  521.173401    0.852789
10        12   315.995819  220.659515    0.933498
11        13   674.444641  206.980972    0.925753
12        14   420.477905  251.145447    0.901581
13        15  1271.492798  222.672272    0.880152
14        16    18.477669  263.946686    0.903948
15        17   825.778259  222.006241    0.900796
16        19   648.577271  280.124573    0.918691
17        20   380.998566  234.848816    0.773599
18        21   788.662659  269.263977    0.803989

===== FRAME 3 =====

    track_id           cx          cy  confidence
0          1   807.786804  427.188293    0.956991
1          2   989.672546  275.067596    0.957834
2          3  1101.002197  341.377319    0.958585
3          4   540.110229  506.633728    0.947068
4          5   532.531616  422.498596    0.946507
5          6   910.564575  439.671753    0.891889
6          7   959.545166  236.949326    0.930750
7          8   903.208862  240.978363    0.930814
8          9   230.406860  345.087036    0.918900
9         10    41.962208  520.602661    0.935168
10        11   509.997803  304.362305    0.962025
11        12   324.799255  220.126022    0.912001
12        13   680.792358  206.783905    0.923907
13        14   430.966583  252.149719    0.938974
14        16    25.654640  263.510071    0.917273
15        17   834.032349  221.966599    0.917678
16        19   655.407471  279.463531    0.893486
17        20   391.076324  234.858292    0.768159
18        21   795.670898  269.732727    0.937979

===== FRAME 4 =====

    track_id           cx          cy  confidence
0          1   811.529053  427.332733    0.956056
1          2   999.634155  275.654327    0.962101
2          3  1109.309570  342.266602    0.958899
3          4   548.255981  507.499084    0.943795
4          5   536.205078  424.248749    0.953809
5          6   922.525024  439.221466    0.945540
6          7   968.712585  236.983566    0.922602
7          8   910.647705  241.872772    0.933131
8          9   236.383240  345.008667    0.942916
9         10    50.829391  520.448608    0.912619
10        11   517.293152  304.716400    0.957363
11        12   334.442230  219.648956    0.925284
12        13   687.652527  206.896805    0.911808
13        14   441.679688  253.056824    0.929681
14        16    34.359341  263.017731    0.826014
15        17   842.961914  222.009659    0.927417
16        19   662.646973  278.090332    0.898658
17        20   402.543884  234.706543    0.893290
18        21   804.106323  270.399994    0.839792

===== FRAME 5 =====

    track_id           cx          cy  confidence
0          1   816.892700  427.412048    0.956755
1          2  1009.362183  275.938812    0.960360
2          3  1119.336060  343.067047    0.964449
3          4   556.571899  507.897461    0.947952
4          5   541.187988  426.307098    0.959769
5          6   933.696899  438.506836    0.894302
6          7   977.231689  237.232788    0.922214
7          8   916.638367  242.850647    0.940500
8          9   242.146744  345.352875    0.947821
9         10    59.381325  520.609436    0.924944
10        11   525.899170  304.571777    0.961592
11        12   344.648560  219.240173    0.923500
12        13   695.199097  206.981430    0.916610
13        14   451.966431  253.985825    0.930313
14        16    43.456276  262.723206    0.655402
15        17   851.679077  222.216919    0.931093
16        19   669.389954  276.634918    0.909046
17        20   413.638031  234.392731    0.902660
18        21   812.227661  270.736572    0.884331

In [54]:
continuity_stats = []

for track_id, group in fresh_df.groupby("track_id"):

    group = group.sort_values("frame").reset_index(drop=True)

    cx = (group["x1"] + group["x2"]) / 2
    cy = (group["y1"] + group["y2"]) / 2

    jumps = np.sqrt(
        cx.diff() ** 2 +
        cy.diff() ** 2
    ).dropna()

    continuity_stats.append({
        "track_id": int(track_id),
        "frames": len(group),
        "start": int(group["frame"].min()),
        "end": int(group["frame"].max()),
        "max_jump_px": float(jumps.max()) if len(jumps) else 0,
        "mean_jump_px": float(jumps.mean()) if len(jumps) else 0,
        "jumps_over_300": int((jumps > 300).sum()),
        "jumps_over_500": int((jumps > 500).sum()),
    })

continuity_df = pd.DataFrame(continuity_stats)

display(
    continuity_df
    .sort_values("max_jump_px", ascending=False)
    .reset_index(drop=True)
)

,track_id,frames,start,end,max_jump_px,mean_jump_px,jumps_over_300,jumps_over_500
0,13,379,1,389,67.714256,3.076351,0,0
1,189,3,377,385,55.648067,45.831589,0,0
2,225,4,381,389,52.292587,34.553848,0,0
3,196,4,378,387,52.022346,34.855747,0,0
4,106,233,191,450,50.963165,4.261807,0,0
...,...,...,...,...,...,...,...,...
64,213,1,380,380,0.000000,0.000000,0,0
65,334,1,393,393,0.000000,0.000000,0,0
66,342,1,395,395,0.000000,0.000000,0,0
67,346,1,396,396,0.000000,0.000000,0,0
68,350,1,399,399,0.000000,0.000000,0,0

In [55]:
top10 = continuity_df.sort_values(
    "max_jump_px",
    ascending=False
).head(10)

for _, row in top10.iterrows():
    print(
        f"ID={int(row['track_id'])} | "
        f"frames={int(row['frames'])} | "
        f"start={int(row['start'])} | "
        f"end={int(row['end'])} | "
        f"max_jump={row['max_jump_px']:.2f}px | "
        f"mean_jump={row['mean_jump_px']:.2f}px | "
        f">300={int(row['jumps_over_300'])} | "
        f">500={int(row['jumps_over_500'])}"
    )

ID=13 | frames=379 | start=1 | end=389 | max_jump=67.71px | mean_jump=3.08px | >300=0 | >500=0
ID=189 | frames=3 | start=377 | end=385 | max_jump=55.65px | mean_jump=45.83px | >300=0 | >500=0
ID=225 | frames=4 | start=381 | end=389 | max_jump=52.29px | mean_jump=34.55px | >300=0 | >500=0
ID=196 | frames=4 | start=378 | end=387 | max_jump=52.02px | mean_jump=34.86px | >300=0 | >500=0
ID=106 | frames=233 | start=191 | end=450 | max_jump=50.96px | mean_jump=4.26px | >300=0 | >500=0
ID=154 | frames=78 | start=371 | end=450 | max_jump=50.39px | mean_jump=7.97px | >300=0 | >500=0
ID=146 | frames=24 | start=351 | end=383 | max_jump=47.69px | mean_jump=6.82px | >300=0 | >500=0
ID=347 | frames=45 | start=397 | end=450 | max_jump=47.45px | mean_jump=5.58px | >300=0 | >500=0
ID=127 | frames=133 | start=244 | end=401 | max_jump=46.11px | mean_jump=5.45px | >300=0 | >500=0
ID=19 | frames=419 | start=1 | end=450 | max_jump=45.70px | mean_jump=4.38px | >300=0 | >500=0

In [56]:
import motmetrics as mm
import numpy as np

# Fresh MOT accumulator
acc_fresh = mm.MOTAccumulator(auto_id=True)

# Process every frame
for frame_id in range(1, 451):

    gt_frame = gt_eval[gt_eval["frame"] == frame_id]
    pred_frame = fresh_df[fresh_df["frame"] == frame_id]

    gt_ids = gt_frame["track_id"].astype(int).to_numpy()
    pred_ids = pred_frame["track_id"].astype(int).to_numpy()

    distances = np.ones(
        (len(gt_ids), len(pred_ids)),
        dtype=float
    )

    # IoU distance
    for i, gt_row in enumerate(gt_frame.itertuples()):
        gt_box = (
            gt_row.x1,
            gt_row.y1,
            gt_row.x2,
            gt_row.y2
        )

        for j, pred_row in enumerate(pred_frame.itertuples()):
            pred_box = (
                pred_row.x1,
                pred_row.y1,
                pred_row.x2,
                pred_row.y2
            )

            distances[i, j] = 1 - calculate_iou(
                gt_box,
                pred_box
            )

    # Only allow IoU >= 0.5
    distances[distances > 0.5] = np.nan

    acc_fresh.update(
        gt_ids,
        pred_ids,
        distances
    )

# MOTChallenge metrics
mh = mm.metrics.create()

summary = mh.compute(
    acc_fresh,
    metrics=[
        "num_frames",
        "num_objects",
        "num_matches",
        "num_switches",
        "num_false_positives",
        "num_misses",
        "mota",
        "motp",
        "idf1",
        "idp",
        "idr"
    ],
    name="fresh_bytetrack"
)

display(summary)

,num_frames,num_objects,num_matches,num_switches,num_false_positives,num_misses,mota,motp,idf1,idp,idr
fresh_bytetrack,450,6622,6182,67,508,373,0.856841,0.152122,0.759399,0.751813,0.76714

In [57]:
from pathlib import Path

SPORTS_MOT_VAL_DIR = Path(
    "/mnt/d/My Projects/AthletiQ/AthletiQ/"
    "datasets/football/benchmarks/sportsmot/extracted/val"
)

print("Validation directory:", SPORTS_MOT_VAL_DIR)
print("Exists:", SPORTS_MOT_VAL_DIR.exists())

Validation directory: /mnt/d/My Projects/AthletiQ/AthletiQ/datasets/football/benchmarks/sportsmot/extracted/val
Exists: True

In [58]:
from ultralytics import YOLO
import pandas as pd
import time

remaining_sequences = [
    "v_G-vNjfx1GGc_c600",
    "v_ITo3sCnpw_k_c011",
    "v_dw7LOz17Omg_c067",
    "v_i2_L4qquVg0_c010",
]

multi_tracking_results = {}

for seq_name in remaining_sequences:

    print(f"\n{'='*60}")
    print(f"Running: {seq_name}")
    print(f"{'='*60}")

    seq_img_dir = SPORTS_MOT_VAL_DIR / seq_name / "img1"

    # Fresh model for every sequence
    model = YOLO(PLAYER_MODEL_PATH)

    rows = []
    start_time = time.time()

    results = model.track(
        source=str(seq_img_dir),
        tracker="bytetrack.yaml",
        persist=True,
        stream=True,
        conf=0.25,
        imgsz=1280,
        verbose=False
    )

    for frame_idx, result in enumerate(results, start=1):

        if result.boxes is None or result.boxes.id is None:
            continue

        boxes = result.boxes.xyxy.cpu().numpy()
        ids = result.boxes.id.cpu().numpy().astype(int)
        confs = result.boxes.conf.cpu().numpy()

        for box, track_id, conf in zip(boxes, ids, confs):

            x1, y1, x2, y2 = box

            rows.append({
                "frame": frame_idx,
                "track_id": track_id,
                "x1": x1,
                "y1": y1,
                "x2": x2,
                "y2": y2,
                "confidence": conf
            })

    elapsed = time.time() - start_time

    seq_df = pd.DataFrame(rows)
    multi_tracking_results[seq_name] = seq_df

    print(f"Frames: {seq_df['frame'].nunique()}")
    print(f"Rows: {len(seq_df)}")
    print(f"Unique IDs: {seq_df['track_id'].nunique()}")
    print(f"Time: {elapsed:.2f}s")
    print(f"FPS: {seq_df['frame'].nunique() / elapsed:.2f}")

============================================================
Running: v_G-vNjfx1GGc_c600
============================================================
Frames: 500
Rows: 5222
Unique IDs: 89
Time: 46.74s
FPS: 10.70

============================================================
Running: v_ITo3sCnpw_k_c011
============================================================
Frames: 776
Rows: 10205
Unique IDs: 105
Time: 69.48s
FPS: 11.17

============================================================
Running: v_dw7LOz17Omg_c067
============================================================
Frames: 450
Rows: 7138
Unique IDs: 97
Time: 41.68s
FPS: 10.80

============================================================
Running: v_i2_L4qquVg0_c010
============================================================
Frames: 758
Rows: 7682
Unique IDs: 154
Time: 60.72s
FPS: 12.48

In [59]:
def evaluate_mot_sequence(seq_name, pred_df, gt_file):
    
    gt = pd.read_csv(
        gt_file,
        header=None,
        names=[
            "frame",
            "track_id",
            "x",
            "y",
            "width",
            "height",
            "conf",
            "class",
            "visibility"
        ]
    )

    gt["x1"] = gt["x"]
    gt["y1"] = gt["y"]
    gt["x2"] = gt["x"] + gt["width"]
    gt["y2"] = gt["y"] + gt["height"]

    acc = mm.MOTAccumulator(auto_id=True)

    max_frame = max(
        int(gt["frame"].max()),
        int(pred_df["frame"].max())
    )

    for frame_id in range(1, max_frame + 1):

        gt_frame = gt[gt["frame"] == frame_id]
        pred_frame = pred_df[pred_df["frame"] == frame_id]

        gt_ids = gt_frame["track_id"].astype(int).to_numpy()
        pred_ids = pred_frame["track_id"].astype(int).to_numpy()

        distances = np.ones(
            (len(gt_ids), len(pred_ids)),
            dtype=float
        )

        for i, gt_row in enumerate(gt_frame.itertuples()):

            gt_box = (
                gt_row.x1,
                gt_row.y1,
                gt_row.x2,
                gt_row.y2
            )

            for j, pred_row in enumerate(pred_frame.itertuples()):

                pred_box = (
                    pred_row.x1,
                    pred_row.y1,
                    pred_row.x2,
                    pred_row.y2
                )

                distances[i, j] = 1 - calculate_iou(
                    gt_box,
                    pred_box
                )

        distances[distances > 0.5] = np.nan

        acc.update(
            gt_ids,
            pred_ids,
            distances
        )

    mh = mm.metrics.create()

    summary = mh.compute(
        acc,
        metrics=[
            "num_frames",
            "num_objects",
            "num_matches",
            "num_switches",
            "num_false_positives",
            "num_misses",
            "mota",
            "motp",
            "idf1",
            "idp",
            "idr"
        ],
        name=seq_name
    )

    return summary


c600_gt = (
    SPORTS_MOT_VAL_DIR /
    "v_G-vNjfx1GGc_c600" /
    "gt" /
    "gt.txt"
)

c600_metrics = evaluate_mot_sequence(
    "c600",
    multi_tracking_results["v_G-vNjfx1GGc_c600"],
    c600_gt
)

display(c600_metrics)

,num_frames,num_objects,num_matches,num_switches,num_false_positives,num_misses,mota,motp,idf1,idp,idr
c600,500,5462,4635,67,520,760,0.753387,0.190715,0.558405,0.571237,0.546137

In [60]:
c011_gt = (
    SPORTS_MOT_VAL_DIR /
    "v_ITo3sCnpw_k_c011" /
    "gt" /
    "gt.txt"
)

c011_metrics = evaluate_mot_sequence(
    "c011",
    multi_tracking_results["v_ITo3sCnpw_k_c011"],
    c011_gt
)

display(c011_metrics)

,num_frames,num_objects,num_matches,num_switches,num_false_positives,num_misses,mota,motp,idf1,idp,idr
c011,776,9736,9254,107,844,375,0.863804,0.169892,0.586631,0.57315,0.60076

In [61]:
c067_gt = (
    SPORTS_MOT_VAL_DIR /
    "v_dw7LOz17Omg_c067" /
    "gt" /
    "gt.txt"
)

c067_metrics = evaluate_mot_sequence(
    "c067",
    multi_tracking_results["v_dw7LOz17Omg_c067"],
    c067_gt
)

display(c067_metrics)

,num_frames,num_objects,num_matches,num_switches,num_false_positives,num_misses,mota,motp,idf1,idp,idr
c067,450,6959,6649,53,436,257,0.892801,0.160411,0.693623,0.684926,0.702543

In [62]:
c010_gt = (
    SPORTS_MOT_VAL_DIR /
    "v_i2_L4qquVg0_c010" /
    "gt" /
    "gt.txt"
)

c010_metrics = evaluate_mot_sequence(
    "c010",
    multi_tracking_results["v_i2_L4qquVg0_c010"],
    c010_gt
)

display(c010_metrics)

,num_frames,num_objects,num_matches,num_switches,num_false_positives,num_misses,mota,motp,idf1,idp,idr
c010,758,8262,7271,125,286,866,0.845437,0.167643,0.44995,0.466936,0.434156

In [63]:
all_acc = mm.MOTAccumulator(auto_id=True)

sequence_pairs = [
    ("c017", "v_2QhNRucNC7E_c017", fresh_df),
    ("c600", "v_G-vNjfx1GGc_c600", multi_tracking_results["v_G-vNjfx1GGc_c600"]),
    ("c011", "v_ITo3sCnpw_k_c011", multi_tracking_results["v_ITo3sCnpw_k_c011"]),
    ("c067", "v_dw7LOz17Omg_c067", multi_tracking_results["v_dw7LOz17Omg_c067"]),
    ("c010", "v_i2_L4qquVg0_c010", multi_tracking_results["v_i2_L4qquVg0_c010"]),
]

for short_name, seq_name, pred_df in sequence_pairs:

    gt_file = (
        SPORTS_MOT_VAL_DIR /
        seq_name /
        "gt" /
        "gt.txt"
    )

    gt = pd.read_csv(
        gt_file,
        header=None,
        names=[
            "frame", "track_id", "x", "y",
            "width", "height", "conf",
            "class", "visibility"
        ]
    )

    gt["x1"] = gt["x"]
    gt["y1"] = gt["y"]
    gt["x2"] = gt["x"] + gt["width"]
    gt["y2"] = gt["y"] + gt["height"]

    for frame_id in range(
        1,
        max(
            int(gt["frame"].max()),
            int(pred_df["frame"].max())
        ) + 1
    ):

        gt_frame = gt[gt["frame"] == frame_id]
        pred_frame = pred_df[pred_df["frame"] == frame_id]

        gt_ids = gt_frame["track_id"].astype(int).to_numpy()
        pred_ids = pred_frame["track_id"].astype(int).to_numpy()

        distances = np.ones(
            (len(gt_ids), len(pred_ids)),
            dtype=float
        )

        for i, gt_row in enumerate(gt_frame.itertuples()):

            gt_box = (
                gt_row.x1,
                gt_row.y1,
                gt_row.x2,
                gt_row.y2
            )

            for j, pred_row in enumerate(pred_frame.itertuples()):

                pred_box = (
                    pred_row.x1,
                    pred_row.y1,
                    pred_row.x2,
                    pred_row.y2
                )

                distances[i, j] = 1 - calculate_iou(
                    gt_box,
                    pred_box
                )

        distances[distances > 0.5] = np.nan

        all_acc.update(
            gt_ids,
            pred_ids,
            distances
        )

overall_metrics = mm.metrics.create().compute(
    all_acc,
    metrics=[
        "num_frames",
        "num_objects",
        "num_matches",
        "num_switches",
        "num_false_positives",
        "num_misses",
        "mota",
        "motp",
        "idf1",
        "idp",
        "idr"
    ],
    name="5_sequence_baseline"
)

display(overall_metrics)

,num_frames,num_objects,num_matches,num_switches,num_false_positives,num_misses,mota,motp,idf1,idp,idr
5_sequence_baseline,2934,37041,33909,501,2594,2631,0.845415,0.16718,0.217381,0.21749,0.217273

In [64]:
# Recompute aggregate MOT metrics with globally unique prediction IDs

global_acc = mm.MOTAccumulator(auto_id=True)

sequence_pairs = [
    ("c017", "v_2QhNRucNC7E_c017", fresh_df),
    ("c600", "v_G-vNjfx1GGc_c600", multi_tracking_results["v_G-vNjfx1GGc_c600"]),
    ("c011", "v_ITo3sCnpw_k_c011", multi_tracking_results["v_ITo3sCnpw_k_c011"]),
    ("c067", "v_dw7LOz17Omg_c067", multi_tracking_results["v_dw7LOz17Omg_c067"]),
    ("c010", "v_i2_L4qquVg0_c010", multi_tracking_results["v_i2_L4qquVg0_c010"]),
]

for seq_idx, (short_name, seq_name, pred_df) in enumerate(sequence_pairs):

    gt_file = (
        SPORTS_MOT_VAL_DIR / seq_name / "gt" / "gt.txt"
    )

    gt = pd.read_csv(
        gt_file,
        header=None,
        names=[
            "frame", "track_id", "x", "y",
            "width", "height", "conf",
            "class", "visibility"
        ]
    )

    gt["x1"] = gt["x"]
    gt["y1"] = gt["y"]
    gt["x2"] = gt["x"] + gt["width"]
    gt["y2"] = gt["y"] + gt["height"]

    # Make prediction IDs globally unique across sequences
    pred_df = pred_df.copy()
    pred_df["global_track_id"] = (
        pred_df["track_id"].astype(int)
        + (seq_idx + 1) * 100000
    )

    for frame_id in range(
        1,
        max(
            int(gt["frame"].max()),
            int(pred_df["frame"].max())
        ) + 1
    ):

        gt_frame = gt[gt["frame"] == frame_id]
        pred_frame = pred_df[pred_df["frame"] == frame_id]

        gt_ids = (
            gt_frame["track_id"]
            .astype(int)
            .to_numpy()
        )

        pred_ids = (
            pred_frame["global_track_id"]
            .astype(int)
            .to_numpy()
        )

        distances = np.ones(
            (len(gt_ids), len(pred_ids)),
            dtype=float
        )

        for i, gt_row in enumerate(gt_frame.itertuples()):

            gt_box = (
                gt_row.x1,
                gt_row.y1,
                gt_row.x2,
                gt_row.y2
            )

            for j, pred_row in enumerate(pred_frame.itertuples()):

                pred_box = (
                    pred_row.x1,
                    pred_row.y1,
                    pred_row.x2,
                    pred_row.y2
                )

                distances[i, j] = 1 - calculate_iou(
                    gt_box,
                    pred_box
                )

        distances[distances > 0.5] = np.nan

        global_acc.update(
            gt_ids,
            pred_ids,
            distances
        )

global_metrics = mm.metrics.create().compute(
    global_acc,
    metrics=[
        "num_frames",
        "num_objects",
        "num_matches",
        "num_switches",
        "num_false_positives",
        "num_misses",
        "mota",
        "motp",
        "idf1",
        "idp",
        "idr"
    ],
    name="5_sequence_global_id_baseline"
)

display(global_metrics)

,num_frames,num_objects,num_matches,num_switches,num_false_positives,num_misses,mota,motp,idf1,idp,idr
5_sequence_global_id_baseline,2934,37041,33908,502,2594,2631,0.845388,0.16718,0.214923,0.215031,0.214816

In [65]:
from pathlib import Path

BYTE_TRACK_09 = Path(
    "/mnt/d/My Projects/AthletiQ/AthletiQ/"
    "ai-engine/notebooks/bytetrack_09.yaml"
)

BYTE_TRACK_09.write_text("""
tracker_type: bytetrack
track_high_thresh: 0.5
track_low_thresh: 0.1
new_track_thresh: 0.5
track_buffer: 30
match_thresh: 0.9
fuse_score: True
""")

print(BYTE_TRACK_09)
print(BYTE_TRACK_09.exists())

/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/notebooks/bytetrack_09.yaml
True

In [66]:
# Experiment 1: ByteTrack match_thresh = 0.9
# Sequence: c017

from ultralytics import YOLO
import pandas as pd
import time

exp_model = YOLO(PLAYER_MODEL_PATH)

exp_rows = []
start_time = time.time()

results = exp_model.track(
    source=str(IMG_DIR),
    tracker=str(BYTE_TRACK_09),
    persist=True,
    stream=True,
    conf=0.25,
    imgsz=1280,
    verbose=False
)

for frame_idx, result in enumerate(results, start=1):

    if result.boxes is None or result.boxes.id is None:
        continue

    boxes = result.boxes.xyxy.cpu().numpy()
    ids = result.boxes.id.cpu().numpy().astype(int)
    confs = result.boxes.conf.cpu().numpy()

    for box, track_id, conf in zip(boxes, ids, confs):

        x1, y1, x2, y2 = box

        exp_rows.append({
            "frame": frame_idx,
            "track_id": track_id,
            "x1": x1,
            "y1": y1,
            "x2": x2,
            "y2": y2,
            "confidence": conf
        })

exp_df = pd.DataFrame(exp_rows)

elapsed = time.time() - start_time

print(f"Frames: {exp_df['frame'].nunique()}")
print(f"Rows: {len(exp_df)}")
print(f"Unique IDs: {exp_df['track_id'].nunique()}")
print(f"Time: {elapsed:.2f}s")
print(f"FPS: {exp_df['frame'].nunique() / elapsed:.2f}")

Frames: 450
Rows: 6791
Unique IDs: 44
Time: 39.70s
FPS: 11.33

In [67]:
exp09_metrics = evaluate_mot_sequence(
    "c017_match09",
    exp_df,
    SPORTS_MOT_VAL_DIR /
    "v_2QhNRucNC7E_c017" /
    "gt" /
    "gt.txt"
)

display(exp09_metrics)

,num_frames,num_objects,num_matches,num_switches,num_false_positives,num_misses,mota,motp,idf1,idp,idr
c017_match09,450,6622,6236,39,516,347,0.863787,0.153781,0.786401,0.776616,0.796436

In [68]:
exp09_c600_model = YOLO(PLAYER_MODEL_PATH)

exp09_c600_rows = []
start_time = time.time()

c600_img_dir = (
    SPORTS_MOT_VAL_DIR /
    "v_G-vNjfx1GGc_c600" /
    "img1"
)

results = exp09_c600_model.track(
    source=str(c600_img_dir),
    tracker=str(BYTE_TRACK_09),
    persist=True,
    stream=True,
    conf=0.25,
    imgsz=1280,
    verbose=False
)

for frame_idx, result in enumerate(results, start=1):

    if result.boxes is None or result.boxes.id is None:
        continue

    boxes = result.boxes.xyxy.cpu().numpy()
    ids = result.boxes.id.cpu().numpy().astype(int)
    confs = result.boxes.conf.cpu().numpy()

    for box, track_id, conf in zip(boxes, ids, confs):

        x1, y1, x2, y2 = box

        exp09_c600_rows.append({
            "frame": frame_idx,
            "track_id": track_id,
            "x1": x1,
            "y1": y1,
            "x2": x2,
            "y2": y2,
            "confidence": conf
        })

exp09_c600_df = pd.DataFrame(exp09_c600_rows)

elapsed = time.time() - start_time

print(f"Frames: {exp09_c600_df['frame'].nunique()}")
print(f"Rows: {len(exp09_c600_df)}")
print(f"Unique IDs: {exp09_c600_df['track_id'].nunique()}")
print(f"Time: {elapsed:.2f}s")
print(f"FPS: {exp09_c600_df['frame'].nunique() / elapsed:.2f}")

Frames: 500
Rows: 5213
Unique IDs: 68
Time: 42.99s
FPS: 11.63

In [69]:
exp09_c600_metrics = evaluate_mot_sequence(
    "c600_match_0.9",
    exp09_c600_df,
    SPORTS_MOT_VAL_DIR / "v_G-vNjfx1GGc_c600" / "gt" / "gt.txt"
)

exp09_c600_metrics

,num_frames,num_objects,num_matches,num_switches,num_false_positives,num_misses,mota,motp,idf1,idp,idr
c600_match_0.9,500,5462,4703,51,459,708,0.777005,0.190167,0.576487,0.590255,0.563347

In [70]:
exp09_c011_model = YOLO(PLAYER_MODEL_PATH)

exp09_c011_rows = []
start_time = time.time()

c011_img_dir = (
    SPORTS_MOT_VAL_DIR /
    "v_ITo3sCnpw_k_c011" /
    "img1"
)

results = exp09_c011_model.track(
    source=str(c011_img_dir),
    tracker=str(BYTE_TRACK_09),
    persist=True,
    stream=True,
    conf=0.25,
    imgsz=1280,
    verbose=False
)

for frame_idx, result in enumerate(results, start=1):
    if result.boxes is None or result.boxes.id is None:
        continue

    boxes = result.boxes.xyxy.cpu().numpy()
    ids = result.boxes.id.cpu().numpy().astype(int)
    confs = result.boxes.conf.cpu().numpy()

    for box, track_id, conf in zip(boxes, ids, confs):
        x1, y1, x2, y2 = box

        exp09_c011_rows.append({
            "frame": frame_idx,
            "track_id": track_id,
            "x1": x1,
            "y1": y1,
            "x2": x2,
            "y2": y2,
            "confidence": conf
        })

exp09_c011_df = pd.DataFrame(exp09_c011_rows)

elapsed = time.time() - start_time

print(f"Frames: {exp09_c011_df['frame'].max()}")
print(f"Rows: {len(exp09_c011_df)}")
print(f"Unique IDs: {exp09_c011_df['track_id'].nunique()}")
print(f"Time: {elapsed:.2f}s")
print(f"FPS: {exp09_c011_df['frame'].max() / elapsed:.2f}")

Frames: 776
Rows: 10146
Unique IDs: 67
Time: 68.27s
FPS: 11.37

In [71]:
exp09_c011_metrics = evaluate_mot_sequence(
    "c011_match_0.9",
    exp09_c011_df,
    SPORTS_MOT_VAL_DIR / "v_ITo3sCnpw_k_c011" / "gt" / "gt.txt"
)

exp09_c011_metrics

,num_frames,num_objects,num_matches,num_switches,num_false_positives,num_misses,mota,motp,idf1,idp,idr
c011_match_0.9,776,9736,9332,54,760,350,0.880444,0.170569,0.644704,0.631678,0.658279

In [72]:
exp09_c067_model = YOLO(PLAYER_MODEL_PATH)

exp09_c067_rows = []
start_time = time.time()

c067_img_dir = (
    SPORTS_MOT_VAL_DIR /
    "v_dw7LOz17Omg_c067" /
    "img1"
)

results = exp09_c067_model.track(
    source=str(c067_img_dir),
    tracker=str(BYTE_TRACK_09),
    persist=True,
    stream=True,
    conf=0.25,
    imgsz=1280,
    verbose=False
)

for frame_idx, result in enumerate(results, start=1):
    if result.boxes is None or result.boxes.id is None:
        continue

    boxes = result.boxes.xyxy.cpu().numpy()
    ids = result.boxes.id.cpu().numpy().astype(int)
    confs = result.boxes.conf.cpu().numpy()

    for box, track_id, conf in zip(boxes, ids, confs):
        x1, y1, x2, y2 = box

        exp09_c067_rows.append({
            "frame": frame_idx,
            "track_id": track_id,
            "x1": x1,
            "y1": y1,
            "x2": x2,
            "y2": y2,
            "confidence": conf
        })

exp09_c067_df = pd.DataFrame(exp09_c067_rows)

elapsed = time.time() - start_time

print(f"Frames: {exp09_c067_df['frame'].max()}")
print(f"Rows: {len(exp09_c067_df)}")
print(f"Unique IDs: {exp09_c067_df['track_id'].nunique()}")
print(f"Time: {elapsed:.2f}s")
print(f"FPS: {exp09_c067_df['frame'].max() / elapsed:.2f}")

Frames: 450
Rows: 7055
Unique IDs: 68
Time: 37.16s
FPS: 12.11

In [73]:
exp09_c067_metrics = evaluate_mot_sequence(
    "c067_match_0.9",
    exp09_c067_df,
    SPORTS_MOT_VAL_DIR / "v_dw7LOz17Omg_c067" / "gt" / "gt.txt"
)

exp09_c067_metrics

,num_frames,num_objects,num_matches,num_switches,num_false_positives,num_misses,mota,motp,idf1,idp,idr
c067_match_0.9,450,6959,6652,32,371,275,0.902572,0.161202,0.777936,0.772644,0.783302

In [74]:
exp09_c010_model = YOLO(PLAYER_MODEL_PATH)

exp09_c010_rows = []
start_time = time.time()

c010_img_dir = (
    SPORTS_MOT_VAL_DIR /
    "v_i2_L4qquVg0_c010" /
    "img1"
)

results = exp09_c010_model.track(
    source=str(c010_img_dir),
    tracker=str(BYTE_TRACK_09),
    persist=True,
    stream=True,
    conf=0.25,
    imgsz=1280,
    verbose=False
)

for frame_idx, result in enumerate(results, start=1):
    if result.boxes is None or result.boxes.id is None:
        continue

    boxes = result.boxes.xyxy.cpu().numpy()
    ids = result.boxes.id.cpu().numpy().astype(int)
    confs = result.boxes.conf.cpu().numpy()

    for box, track_id, conf in zip(boxes, ids, confs):
        x1, y1, x2, y2 = box

        exp09_c010_rows.append({
            "frame": frame_idx,
            "track_id": track_id,
            "x1": x1,
            "y1": y1,
            "x2": x2,
            "y2": y2,
            "confidence": conf
        })

exp09_c010_df = pd.DataFrame(exp09_c010_rows)

elapsed = time.time() - start_time

print(f"Frames: {exp09_c010_df['frame'].max()}")
print(f"Rows: {len(exp09_c010_df)}")
print(f"Unique IDs: {exp09_c010_df['track_id'].nunique()}")
print(f"Time: {elapsed:.2f}s")
print(f"FPS: {exp09_c010_df['frame'].max() / elapsed:.2f}")

Frames: 758
Rows: 7810
Unique IDs: 85
Time: 61.95s
FPS: 12.24

In [75]:
exp09_c010_metrics = evaluate_mot_sequence(
    "c010_match_0.9",
    exp09_c010_df,
    SPORTS_MOT_VAL_DIR / "v_i2_L4qquVg0_c010" / "gt" / "gt.txt"
)

exp09_c010_metrics

,num_frames,num_objects,num_matches,num_switches,num_false_positives,num_misses,mota,motp,idf1,idp,idr
c010_match_0.9,758,8262,7523,71,216,668,0.884411,0.169786,0.50784,0.522535,0.493948

In [76]:
# Final 5-sequence comparison
# Baseline values recorded earlier
baseline_data = {
    "c017": {
        "mota": 0.856841,
        "idf1": 0.759399,
        "switches": 67,
    },
    "c600": {
        "mota": 0.753387,
        "idf1": 0.558405,
        "switches": 760,
    },
    "c011": {
        "mota": 0.863804,
        "idf1": 0.586631,
        "switches": 107,
    },
    "c067": {
        "mota": 0.892801,
        "idf1": 0.693623,
        "switches": 257,
    },
    "c010": {
        "mota": 0.845437,
        "idf1": 0.449950,
        "switches": 866,
    },
}

# match_thresh = 0.9 values from our evaluations
match09_data = {
    "c017": {
        "mota": 0.863787,
        "idf1": 0.786401,
        "switches": 39,
    },
    "c600": {
        "mota": 0.777005,
        "idf1": 0.576487,
        "switches": 470,
    },
    "c011": {
        "mota": 0.880444,
        "idf1": 0.644704,
        "switches": 54,
    },
    "c067": {
        "mota": 0.902572,
        "idf1": 0.777936,
        "switches": 32,
    },
    "c010": {
        "mota": 0.884411,
        "idf1": 0.507840,
        "switches": 668,
    },
}

comparison_rows = []

for seq in baseline_data:
    b = baseline_data[seq]
    e = match09_data[seq]

    comparison_rows.append({
        "Sequence": seq,
        "Baseline MOTA (%)": b["mota"] * 100,
        "0.9 MOTA (%)": e["mota"] * 100,
        "MOTA Δ (pp)": (e["mota"] - b["mota"]) * 100,
        "Baseline IDF1 (%)": b["idf1"] * 100,
        "0.9 IDF1 (%)": e["idf1"] * 100,
        "IDF1 Δ (pp)": (e["idf1"] - b["idf1"]) * 100,
        "Baseline Switches": b["switches"],
        "0.9 Switches": e["switches"],
        "Switch Reduction": b["switches"] - e["switches"],
    })

comparison_df = pd.DataFrame(comparison_rows)

comparison_df.round(3)

,Sequence,Baseline MOTA (%),0.9 MOTA (%),MOTA Δ (pp),Baseline IDF1 (%),0.9 IDF1 (%),IDF1 Δ (pp),Baseline Switches,0.9 Switches,Switch Reduction
0,c017,85.684,86.379,0.695,75.940,78.640,2.700,67,39,28
1,c600,75.339,77.700,2.362,55.841,57.649,1.808,760,470,290
2,c011,86.380,88.044,1.664,58.663,64.470,5.807,107,54,53
3,c067,89.280,90.257,0.977,69.362,77.794,8.431,257,32,225
4,c010,84.544,88.441,3.897,44.995,50.784,5.789,866,668,198

In [77]:
from pathlib import Path

BYTE_TRACK_FINAL = Path(
    "/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/notebooks/bytetrack_final.yaml"
)

BYTE_TRACK_FINAL.write_text(
    """tracker_type: bytetrack
track_high_thresh: 0.5
track_low_thresh: 0.1
new_track_thresh: 0.5
track_buffer: 30
match_thresh: 0.9
fuse_score: True
""",
    encoding="utf-8"
)

print(f"Saved: {BYTE_TRACK_FINAL}")
print()
print(BYTE_TRACK_FINAL.read_text())

Saved: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/notebooks/bytetrack_final.yaml

tracker_type: bytetrack
track_high_thresh: 0.5
track_low_thresh: 0.1
new_track_thresh: 0.5
track_buffer: 30
match_thresh: 0.9
fuse_score: True

In [78]:
from pathlib import Path

possible_mixsort_paths = [
    Path("/mnt/d/My Projects/AthletiQ/AthletiQ/MixSort"),
    Path("/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/MixSort"),
    Path("/mnt/d/My Projects/AthletiQ/AthletiQ/third_party/MixSort"),
]

for p in possible_mixsort_paths:
    print(f"{p} -> {'FOUND' if p.exists() else 'not found'}")

/mnt/d/My Projects/AthletiQ/AthletiQ/MixSort -> not found
/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/MixSort -> not found
/mnt/d/My Projects/AthletiQ/AthletiQ/third_party/MixSort -> not found

In [79]:
import subprocess
from pathlib import Path

MIXSORT_DIR = Path(
    "/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort"
)

MIXSORT_DIR.parent.mkdir(parents=True, exist_ok=True)

if not MIXSORT_DIR.exists():
    subprocess.run(
        [
            "git",
            "clone",
            "--recursive",
            "https://github.com/MCG-NJU/MixSort.git",
            str(MIXSORT_DIR),
        ],
        check=True
    )
    print("MixSort cloned successfully.")
else:
    print("MixSort directory already exists.")

print("\nLocation:", MIXSORT_DIR)
print("Exists:", MIXSORT_DIR.exists())
print("Files:", len(list(MIXSORT_DIR.iterdir())))

MixSort directory already exists.

Location: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort
Exists: True
Files: 18

In [80]:
from pathlib import Path

for p in sorted(MIXSORT_DIR.iterdir()):
    print(f"{'[DIR] ' if p.is_dir() else '[FILE]'} {p.name}")

[DIR]  .git
[FILE] .gitignore
[FILE] .gitmodules
[FILE] Dockerfile
[FILE] LICENSE
[DIR]  MixViT
[FILE] README.md
[DIR]  TrackEval
[DIR]  assets
[DIR]  deploy
[DIR]  exps
[DIR]  pretrained
[FILE] requirements.txt
[FILE] setup.cfg
[FILE] setup.py
[DIR]  tools
[DIR]  videos
[DIR]  yolox

In [81]:
from pathlib import Path

# Find files mentioning SportsMOT / MixSort / MOT
patterns = ["*sportsmot*", "*mixsort*", "*mot*"]

for pattern in patterns:
    print(f"\n===== {pattern} =====")
    matches = list(MIXSORT_DIR.rglob(pattern))
    
    for p in matches[:80]:
        print(p.relative_to(MIXSORT_DIR))
    
    if len(matches) > 80:
        print(f"... and {len(matches) - 80} more")

===== *sportsmot* =====
tools/convert_sportsmot_anno.py
tools/convert_sportsmot_mix_anno.py
tools/convert_sportsmot_to_coco.py
tools/mix_sportsmot.py
exps/example/mot/yolox_x_sportsmot.py
exps/example/mot/yolox_x_sportsmot_mix.py
MixViT/lib/train/dataset/sportsmot.py
MixViT/lib/train/dataset/__pycache__/sportsmot.cpython-312.pyc

===== *mixsort* =====
tools/track_mixsort.py
tools/track_mixsort_oc.py
yolox/mixsort_oc_tracker
yolox/mixsort_tracker
yolox/mixsort_oc_tracker/mixsort_oc_tracker.py
yolox/mixsort_tracker/mixsort_iou_tracker.py
yolox/mixsort_tracker/mixsort_tracker.py
yolox/mixsort_tracker/__pycache__/mixsort_tracker.cpython-312.pyc

===== *mot* =====
tools/convert_mot17_anno.py
tools/convert_mot17_to_coco.py
tools/convert_sportsmot_anno.py
tools/convert_sportsmot_mix_anno.py
tools/convert_sportsmot_to_coco.py
tools/mix_sportsmot.py
tools/mota.py
tools/track_motdt.py
yolox/motdt_tracker
.git/refs/remotes
.git/logs/refs/remotes
.git/modules/TrackEval/refs/remotes
.git/modules/TrackEval/logs/refs/remotes
exps/example/mot
exps/example/mot/yolox_x_sportsmot.py
exps/example/mot/yolox_x_sportsmot_mix.py
MixViT/lib/train/dataset/mot17.py
MixViT/lib/train/dataset/mot20.py
MixViT/lib/train/dataset/sportsmot.py
MixViT/lib/train/dataset/__pycache__/mot17.cpython-312.pyc
MixViT/lib/train/dataset/__pycache__/mot20.cpython-312.pyc
MixViT/lib/train/dataset/__pycache__/sportsmot.cpython-312.pyc
TrackEval/scripts/eval_mot.py
TrackEval/scripts/run_kitti_mots.py
TrackEval/scripts/run_mots_challenge.py
TrackEval/scripts/run_mot_challenge.py
TrackEval/scripts/run_rob_mots.py
TrackEval/tests/test_mot17.py
TrackEval/tests/test_mots.py
TrackEval/data/gt/mot_challenge
TrackEval/trackeval/datasets/kitti_mots.py
TrackEval/trackeval/datasets/mots_challenge.py
TrackEval/trackeval/datasets/mot_challenge_2d_box.py
TrackEval/trackeval/datasets/rob_mots.py
TrackEval/trackeval/datasets/rob_mots_classmap.py
TrackEval/trackeval/datasets/run_rob_mots.py
yolox/evaluators/mot_evaluator.py
yolox/motdt_tracker/motdt_tracker.py
yolox/data/datasets/mot.py

In [82]:
track_mixsort_file = MIXSORT_DIR / "tools" / "track_mixsort.py"

print(track_mixsort_file.read_text(encoding="utf-8"))

from loguru import logger

import torch
import torch.backends.cudnn as cudnn
from torch.nn.parallel import DistributedDataParallel as DDP
import sys, os
sys.path.append(os.path.join(os.path.dirname(__file__), '../MixViT'))
from yolox.core import launch
from yolox.exp import get_exp
from yolox.utils import configure_nccl, fuse_model, get_local_rank, get_model_info, setup_logger
from yolox.evaluators import MOTEvaluator

import argparse
import random
import warnings
import glob
import motmetrics as mm
from collections import OrderedDict
from pathlib import Path


def make_parser():
    parser = argparse.ArgumentParser("YOLOX Eval")
    parser.add_argument("-expn", "--experiment-name", type=str, default=None)
    parser.add_argument("-n", "--name", type=str, default=None, help="model name")

    # distributed
    parser.add_argument(
        "--dist-backend", default="nccl", type=str, help="distributed backend"
    )
    parser.add_argument(
        "--dist-url",
        default=None,
        type=str,
        help="url used to set up distributed training",
    )
    parser.add_argument("-b", "--batch-size", type=int, default=1, help="batch size")
    parser.add_argument(
        "-d", "--devices", default=1, type=int, help="device for training"
    )
    parser.add_argument(
        "--local_rank", default=0, type=int, help="local rank for dist training"
    )
    parser.add_argument(
        "--num_machines", default=1, type=int, help="num of node for training"
    )
    parser.add_argument(
        "--machine_rank", default=0, type=int, help="node rank for multi-node training"
    )
    parser.add_argument(
        "-f",
        "--exp_file",
        default='exps/example/mot/yolox_x_sports_mix.py',
        type=str,
        help="pls input your expriment description file",
    )
    parser.add_argument(
        "--fp16",
        dest="fp16",
        default=False,
        action="store_true",
        help="Adopting mix precision evaluating.",
    )
    parser.add_argument(
        "--fuse",
        dest="fuse",
        default=False,
        action="store_true",
        help="Fuse conv and bn for testing.",
    )
    parser.add_argument(
        "--trt",
        dest="trt",
        default=False,
        action="store_true",
        help="Using TensorRT model for testing.",
    )
    parser.add_argument(
        "--test",
        dest="test",
        default=False,
        action="store_true",
        help="Evaluating on test-dev set.",
    )
    parser.add_argument(
        "--speed",
        dest="speed",
        default=False,
        action="store_true",
        help="speed test only.",
    )
    parser.add_argument(
        "opts",
        help="Modify config options using the command-line",
        default=None,
        nargs=argparse.REMAINDER,
    )
    # det args
    parser.add_argument("-c", "--ckpt", default='pretrained/yolox_x_sportsmix_ch.pth.tar', type=str, help="ckpt for eval")
    parser.add_argument("--conf", default=0.01, type=float, help="test conf")
    parser.add_argument("--nms", default=0.7, type=float, help="test nms threshold")
    parser.add_argument("--tsize", default=None, type=int, help="test img size")
    parser.add_argument("--seed", default=None, type=int, help="eval seed")
    # tracking args
    parser.add_argument("--track_thresh", type=float, default=0.6, help="tracking confidence threshold")
    parser.add_argument("--track_buffer", type=int, default=30, help="the frames for keep lost tracks")
    parser.add_argument("--match_thresh", type=float, default=0.9, help="matching threshold for tracking")
    parser.add_argument("--iou_thresh",type=float,default=0.3)
    parser.add_argument("--min-box-area", type=float, default=100, help='filter out tiny boxes')
    parser.add_argument("--mot20", dest="mot20", default=False, action="store_true", help="test mot20.")
    # mixformer args
    parser.add_argument("--script",type=str,default='mixformer_deit')
    parser.add_argument("--config",type=str,default='track')
    parser.add_argument("--alpha",type=float,default=0.6,help='fuse parameter')
    parser.add_argument("--radius",type=int,default=0,help='radius for computing similarity')

    parser.add_argument("--iou_only",dest="iou_only",default=False, action="store_true",help='only use iou for similarity')
    return parser


def compare_dataframes(gts, ts):
    accs = []
    names = []
    for k, tsacc in ts.items():
        if k in gts:
            logger.info('Comparing {}...'.format(k))
            accs.append(mm.utils.compare_to_groundtruth(gts[k], tsacc, 'iou', distth=0.5))
            names.append(k)
        else:
            logger.warning('No ground truth for {}, skipping.'.format(k))

    return accs, names


#@logger.catch
def main(exp, args, num_gpu):
    if args.seed is not None:
        random.seed(args.seed)
        torch.manual_seed(args.seed)
        cudnn.deterministic = True
        warnings.warn(
            "You have chosen to seed testing. This will turn on the CUDNN deterministic setting, "
        )

    is_distributed = num_gpu > 1

    # set environment variables for distributed training
    cudnn.benchmark = True

    rank = args.local_rank
    # rank = get_local_rank()

    file_name = os.path.join(exp.output_dir, args.experiment_name)

    if rank == 0:
        os.makedirs(file_name, exist_ok=True)

    results_folder = os.path.join(file_name, "track_results")
    os.makedirs(results_folder, exist_ok=True)

    setup_logger(file_name, distributed_rank=rank, filename="val_log.txt", mode="a")
    logger.info("Args: {}".format(args))

    if args.conf is not None:
        exp.test_conf = args.conf
    if args.nms is not None:
        exp.nmsthre = args.nms
    if args.tsize is not None:
        exp.test_size = (args.tsize, args.tsize)

    model = exp.get_model()
    logger.info("Model Summary: {}".format(get_model_info(model, exp.test_size)))
    #logger.info("Model Structure:\n{}".format(str(model)))

    val_loader = exp.get_eval_loader(args.batch_size, is_distributed, args.test, return_origin_img=True)
    evaluator = MOTEvaluator(
        args=args,
        dataloader=val_loader,
        img_size=exp.test_size,
        confthre=exp.test_conf,
        nmsthre=exp.nmsthre,
        num_classes=exp.num_classes,
        )

    torch.cuda.set_device(rank)
    model.cuda(rank)
    model.eval()

    if not args.speed and not args.trt:
        if args.ckpt is None:
            ckpt_file = os.path.join(file_name, "best_ckpt.pth.tar")
        else:
            ckpt_file = args.ckpt
        logger.info("loading checkpoint")
        loc = "cuda:{}".format(rank)
        ckpt = torch.load(ckpt_file, map_location=loc)
        # load the model state dict
        model.load_state_dict(ckpt["model"])
        # torch.jit.load()
        logger.info("loaded checkpoint done.")

    if is_distributed:
        model = DDP(model, device_ids=[rank])

    if args.fuse:
        logger.info("\tFusing model...")
        model = fuse_model(model)

    if args.trt:
        assert (
            not args.fuse and not is_distributed and args.batch_size == 1
        ), "TensorRT model is not support model fusing and distributed inferencing!"
        trt_file = os.path.join(file_name, "model_trt.pth")
        assert os.path.exists(
            trt_file
        ), "TensorRT model is not found!\n Run tools/trt.py first!"
        model.head.decode_in_inference = False
        decoder = model.head.decode_outputs
    else:
        trt_file = None
        decoder = None

    # start evaluate
    *_, summary = evaluator.evaluate_mixsort(
        model, is_distributed, args.fp16, trt_file, decoder, exp.test_size, results_folder
    )
    logger.info("\n" + summary)

    logger.info('Completed')


if __name__ == "__main__":
    args = make_parser().parse_args()
    exp = get_exp(args.exp_file, args.name)
    exp.merge(args.opts)

    if not args.experiment_name:
        args.experiment_name = exp.exp_name

    num_gpu = torch.cuda.device_count() if args.devices is None else args.devices
    assert num_gpu <= torch.cuda.device_count()

    launch(
        main,
        num_gpu,
        args.num_machines,
        args.machine_rank,
        backend=args.dist_backend,
        dist_url=args.dist_url,
        args=(exp, args, num_gpu),
    )

In [83]:
mixsort_tracker_file = (
    MIXSORT_DIR
    / "yolox"
    / "mixsort_tracker"
    / "mixsort_tracker.py"
)

print(mixsort_tracker_file.read_text(encoding="utf-8"))

import numpy as np
from collections import deque
import os
import os.path as osp
import copy
import torch
import torch.nn.functional as F
from torchvision.transforms.functional import resized_crop, normalize
import math
from torch.utils.tensorboard import SummaryWriter

from .kalman_filter import KalmanFilter
from . import matching
from .basetrack import BaseTrack, TrackState
from MixViT.lib.models.mixformer_vit import build_mixformer_deit
from MixViT.lib.train.data.processing import MixformerProcessing as MP
from MixViT.lib.train.data.transforms import Transform, ToTensor, Normalize
import MixViT.lib.train.data.processing_utils as prutils
import MixViT.lib.train.admin.settings as ws_settings
import importlib
from MixViT.lib.train.base_functions import update_settings
import MixViT.lib.train.data.transforms as tfm
from typing import List, Union, Tuple


class STrack(BaseTrack):
    shared_kalman = KalmanFilter()

    def __init__(self, tlwh, score, iou):

        # wait activate
        self._tlwh = np.asarray(tlwh, dtype=np.float)
        self.kalman_filter = None
        self.mean, self.covariance = None, None
        self.is_activated = False
        self.template = None
        self._iou = iou

        self.score = score
        self.tracklet_len = 0

    def predict(self):
        mean_state = self.mean.copy()
        if self.state != TrackState.Tracked:
            mean_state[7] = 0
        self.mean, self.covariance = self.kalman_filter.predict(
            mean_state, self.covariance
        )

    @staticmethod
    def multi_predict(stracks):
        if len(stracks) > 0:
            multi_mean = np.asarray([st.mean.copy() for st in stracks])
            multi_covariance = np.asarray([st.covariance for st in stracks])
            for i, st in enumerate(stracks):
                if st.state != TrackState.Tracked:
                    multi_mean[i][7] = 0
            multi_mean, multi_covariance = STrack.shared_kalman.multi_predict(
                multi_mean, multi_covariance
            )
            for i, (mean, cov) in enumerate(zip(multi_mean, multi_covariance)):
                stracks[i].mean = mean
                stracks[i].covariance = cov

    def activate(self, kalman_filter, frame_id, template):
        """Start a new tracklet"""
        self.kalman_filter = kalman_filter
        self.track_id = self.next_id()
        self.mean, self.covariance = self.kalman_filter.initiate(
            self.tlwh_to_xyah(self._tlwh)
        )
        self.template = template

        self.tracklet_len = 0
        self.state = TrackState.Tracked
        if frame_id == 1:
            self.is_activated = True
        # self.is_activated = True
        self.frame_id = frame_id
        self.start_frame = frame_id

    def re_activate(self, new_track, frame_id, new_id=False, template=None):
        self.mean, self.covariance = self.kalman_filter.update(
            self.mean, self.covariance, self.tlwh_to_xyah(new_track.tlwh)
        )
        self.tracklet_len = 0
        self.state = TrackState.Tracked
        self.is_activated = True
        self.frame_id = frame_id
        if new_id:
            self.track_id = self.next_id()
        self.score = new_track.score

        if template is not None:
            self.template = template

    def update(self, new_track, frame_id, template=None):
        """
        Update a matched track
        :type new_track: STrack
        :type frame_id: int
        :type update_feature: bool
        :return:
        """
        self.frame_id = frame_id
        self.tracklet_len += 1

        new_tlwh = new_track.tlwh
        self.mean, self.covariance = self.kalman_filter.update(
            self.mean, self.covariance, self.tlwh_to_xyah(new_tlwh)
        )
        self.state = TrackState.Tracked
        self.is_activated = True

        self.score = new_track.score

        if template is not None:
            self.template = template

    @property
    # @jit(nopython=True)
    def tlwh(self):
        """Get current position in bounding box format `(top left x, top left y,
        width, height)`.
        """
        if self.mean is None:
            return self._tlwh.copy()
        ret = self.mean[:4].copy()
        ret[2] *= ret[3]
        ret[:2] -= ret[2:] / 2
        return ret

    @property
    # @jit(nopython=True)
    def tlbr(self):
        """Convert bounding box to format `(min x, min y, max x, max y)`, i.e.,
        `(top left, bottom right)`.
        """
        ret = self.tlwh.copy()
        ret[2:] += ret[:2]
        return ret

    @staticmethod
    # @jit(nopython=True)
    def tlwh_to_xyah(tlwh):
        """Convert bounding box to format `(center x, center y, aspect ratio,
        height)`, where the aspect ratio is `width / height`.
        """
        ret = np.asarray(tlwh).copy()
        ret[:2] += ret[2:] / 2
        ret[2] /= ret[3]
        return ret

    def to_xyah(self):
        return self.tlwh_to_xyah(self.tlwh)

    @staticmethod
    # @jit(nopython=True)
    def tlbr_to_tlwh(tlbr):
        ret = np.asarray(tlbr).copy()
        ret[2:] -= ret[:2]
        return ret

    @staticmethod
    # @jit(nopython=True)
    def tlwh_to_tlbr(tlwh):
        ret = np.asarray(tlwh).copy()
        ret[2:] += ret[:2]
        return ret

    def __repr__(self):
        return "OT_{}_({}-{})".format(self.track_id, self.start_frame, self.end_frame)


class MIXTracker(object):
    def __init__(self, args, frame_rate=30):
        self.tracked_stracks = []  # type: list[STrack]
        self.lost_stracks = []  # type: list[STrack]
        self.removed_stracks = []  # type: list[STrack]

        self.frame_id = 0
        self.args = args
        # self.det_thresh = args.track_thresh
        self.det_thresh = args.track_thresh + 0.1
        self.buffer_size = int(frame_rate / 30.0 * args.track_buffer)
        self.max_time_lost = self.buffer_size
        self.kalman_filter = KalmanFilter()

        self.last_img = None
        self.alpha = args.alpha
        self.radius = args.radius
        self.iou_thresh = args.iou_thresh

        # mixformer setting & cfg
        # adapted from lib/train/run_training.py & train_script_mixformer.py
        self.settings = ws_settings.Settings()
        self.settings.script_name = args.script
        self.settings.config_name = args.config
        prj_dir = os.path.abspath(
            os.path.join(os.path.dirname(__file__), "../../MixViT")
        )
        self.settings.cfg_file = os.path.join(
            prj_dir, f"experiments/{args.script}/{args.config}.yaml"
        )
        config_module = importlib.import_module(
            "lib.config.%s.config" % self.settings.script_name
        )
        self.cfg = config_module.cfg
        config_module.update_config_from_file(self.settings.cfg_file)
        update_settings(self.settings, self.cfg)

        # need modification, for distributed
        network = build_mixformer_deit(self.cfg)
        self.network = network.cuda(torch.device(f"cuda:{args.local_rank}"))
        self.network.eval()

    def re_init(self, args, frame_rate=30):
        BaseTrack._count = 0 # set to 0 for new video
        self.tracked_stracks = []  # type: list[STrack]
        self.lost_stracks = []  # type: list[STrack]
        self.removed_stracks = []  # type: list[STrack]

        self.frame_id = 0
        self.args = args
        # self.det_thresh = args.track_thresh
        self.det_thresh = args.track_thresh + 0.1
        self.buffer_size = int(frame_rate / 30.0 * args.track_buffer)
        self.max_time_lost = self.buffer_size
        self.kalman_filter = KalmanFilter()

        self.last_img = None
        self.alpha = args.alpha
        self.radius = args.radius
        self.iou_thresh = args.iou_thresh

    def visualize(self, logger: SummaryWriter, template, search, search_box):
        # utils for debugging
        logger.add_image("template", template)
        for box in search_box:
            box[2:4] = box[0:2] + box[2:4]
        logger.add_image_with_boxes("search", search, search_box)

    def visualize_box(self, logger: SummaryWriter, img, dets:List[STrack], name):
        # utils for debugging
        logger.add_image_with_boxes(name, img, np.array([s.tlbr for s in dets]),labels=[str(i) for i in range(len(dets))])

    def crop_and_resize(
        self, img: torch.Tensor, center: np.ndarray, s: str, annos: torch.Tensor = None
    ) -> Union[Tuple[torch.Tensor, torch.Tensor], torch.Tensor]:
        """crop&resize the `img` centered at `center` and transform `annos` to the cropped position.

        Args:
            img (torch.Tensor): image to be cropped
            center (np.ndarray): center coord
            s (str): 'template' or 'search'
            annos (torch.Tensor, optional): boxes to be transformed. Defaults to None.

        Returns:
            Union[Tuple[torch.Tensor,torch.Tensor],torch.Tensor]: transfromed image (and boxes)
        """
        # compute params
        center = torch.from_numpy(center.astype(np.int))
        search_area_factor = self.settings.search_area_factor[s]
        output_sz = self.settings.output_sz[s]
        x, y, w, h = [int(i) for i in center]
        crop_sz = math.ceil(math.sqrt(w * h) * search_area_factor)

        # x:left, y:top
        x = int(round(x + 0.5 * w - crop_sz * 0.5))
        y = int(round(y + 0.5 * h - crop_sz * 0.5))

        try:
            resized_img = resized_crop(
                img, y, x, crop_sz, crop_sz, [output_sz, output_sz]
            )
        except:  # too small box
            zero_img = torch.zeros((3, output_sz, output_sz)).cuda()
            return zero_img if annos is None else zero_img, []

        if annos is not None:
            # (origin_x - x, origin_y - y, origin_w, origin_h)/factor
            transforemd_coord = torch.cat(
                (annos[:, 0:2] - torch.tensor([x, y]), annos[:, 2:4]), dim=1
            )
            return resized_img, transforemd_coord / (crop_sz / output_sz)
        else:
            return resized_img

    @torch.no_grad()
    def compute_mix_dist(
        self,
        stracks: List[STrack],
        dets: List[STrack],
        img: torch.Tensor,
        fuse: bool = False,
    ) -> np.ndarray:
        """compute mix distance between stracks and dets.

        Args:
            stracks (List[STrack]): len = m
            dets (List[STrack]): len = n
            img (torch.Tensor): current image
            fuse (bool, optional): whether to fuse det score into iou. Defaults to False.

        Returns:
            np.ndarray: m x n
        """

        # Predict the current location with KF
        STrack.multi_predict(stracks)
        # compute iou dist
        iou = matching.iou_distance(stracks, dets)
        if fuse:
            iou = matching.fuse_score(iou, dets)

        if len(stracks) * len(dets) == 0:
            return iou

        # for every strack, compute its vit-dist with dets
        search_bbox = torch.stack(
            [torch.from_numpy(det.tlwh.astype(np.int)) for det in dets]
        )
        search_imgs = []
        search_boxes = []
        # vit dist
        # self.logger=SummaryWriter('./debug_tensorboard')
        # self.visualize(self.logger,template_imgs[0],search_img,search_box.clone())
        # self.visualize_box(self.logger,img,stracks,"stracks")
        # self.visualize_box(self.logger,img,dets,"dets")
        vit = np.zeros((len(stracks), len(dets)), dtype=np.float64)
        template_imgs = [s.template for s in stracks]
        for strack in stracks:
            # centered at predicted position
            center = strack.tlwh
            # crop search area & transform det coord
            s_img, s_box = self.crop_and_resize(img, center, "search", search_bbox)
            search_imgs.append(s_img)
            search_boxes.append(s_box)

        # img transform & compute
        template_imgs = normalize(
            torch.stack(template_imgs).float().div(255),
            self.cfg.DATA.MEAN,
            self.cfg.DATA.STD,
        )
        search_imgs = normalize(
            torch.stack(search_imgs).float().div(255),
            self.cfg.DATA.MEAN,
            self.cfg.DATA.STD,
        )
        heatmap = self.network(template_imgs, search_imgs).cpu().detach().numpy()
        # linear transform to [0,1]
        for i in range(heatmap.shape[0]):
            heatmap[i][0] = heatmap[i][0] - heatmap[i][0].min()
            heatmap[i][0] = heatmap[i][0] / heatmap[i][0].max()

        # compute similarity
        search_size = s_img[0].shape[-1]
        heatmap_size = heatmap.shape[-1]
        factor = search_size // heatmap_size
        for i, boxes in enumerate(search_boxes):
            # correspond to strack[i]
            for j, (t, l, w, h) in enumerate(boxes):
                cx, cy = t + w / 2, l + h / 2
                # don't consider outsiders
                if cx > 0 and cy > 0 and cx < search_size and cy < search_size:
                    cx, cy = int(cx) // factor, int(cy) // factor
                    top = max(0, cy - self.radius)
                    bottom = min(heatmap_size, cy + self.radius + 1)
                    left = max(0, cx - self.radius)
                    right = min(heatmap_size, cx + self.radius + 1)
                    vit[i][j] = heatmap[i][0][top:bottom, left:right].mean()
                    # vit[i][j] = heatmap[i][0][cy][cx]

        # fuse iou&vit cost
        return self.alpha * iou + (1 - self.alpha) * (1 - vit)
        # if iou.min()<self.args.fuse_iou_thresh:
        #     return iou
        # else:
        #     return 1-vit
        # vit=1-vit
        # for i in range(iou.shape[0]):
        #     for j in range(iou.shape[1]):
        #         if iou[i][j]>self.args.fuse_iou_thresh and vit[i][j]<self.args.fuse_vit_thresh:
        #             iou[i][j]=vit[i][j]
        # return iou

    def update(self, output_results, img_info, img_size, img):
        self.frame_id += 1
        activated_starcks = []
        refind_stracks = []
        lost_stracks = []
        removed_stracks = []

        if output_results.shape[1] == 5:
            scores = output_results[:, 4]
            bboxes = output_results[:, :4]
        else:
            output_results = output_results.cpu().numpy()
            scores = output_results[:, 4] * output_results[:, 5]
            bboxes = output_results[:, :4]  # x1y1x2y2
        img_h, img_w = img_info[0], img_info[1]
        scale = min(img_size[0] / float(img_h), img_size[1] / float(img_w))
        bboxes /= scale

        # compute all ious
        all_dets = [x for x in bboxes]
        iou = matching.ious(all_dets, all_dets)
        # compute max iou for every det
        max_iou = []
        for i in range(len(all_dets)):
            iou[i][i] = 0
            max_iou.append(iou[i].max())
        max_iou = np.array(max_iou)

        remain_inds = scores > self.args.track_thresh
        inds_low = scores > 0.1
        inds_high = scores < self.args.track_thresh

        inds_second = np.logical_and(inds_low, inds_high)
        dets_second = bboxes[inds_second]
        dets = bboxes[remain_inds]
        max_iou_keep = max_iou[remain_inds]
        max_iou_second = max_iou[inds_second]
        scores_keep = scores[remain_inds]
        scores_second = scores[inds_second]

        if len(dets) > 0:
            """Detections"""
            detections = [
                STrack(STrack.tlbr_to_tlwh(tlbr), s, u)
                for (tlbr, s, u) in zip(dets, scores_keep, max_iou_keep)
            ]
        else:
            detections = []

        """ Add newly detected tracklets to tracked_stracks"""
        unconfirmed = []
        tracked_stracks = []  # type: list[STrack]
        for track in self.tracked_stracks:
            if not track.is_activated:
                unconfirmed.append(track)
            else:
                tracked_stracks.append(track)

        """ Step 2: First association, with high score detection boxes"""
        strack_pool = joint_stracks(tracked_stracks, self.lost_stracks)
        dists = self.compute_mix_dist(strack_pool, detections, img, fuse=True)
        # if not self.args.mot20:
        #     dists = matching.fuse_score(dists, detections)
        matches, u_track, u_detection = matching.linear_assignment(
            dists, thresh=self.args.match_thresh
        )

        for itracked, idet in matches:
            track = strack_pool[itracked]
            det = detections[idet]
            template = (
                self.crop_and_resize(img, det.tlwh, "template")
                if det._iou < self.iou_thresh
                else None
            )
            if track.state == TrackState.Tracked:
                track.update(detections[idet], self.frame_id, template)
                activated_starcks.append(track)
            else:
                track.re_activate(det, self.frame_id, new_id=False, template=template)
                refind_stracks.append(track)

        """ Step 3: Second association, with low score detection boxes"""
        # association the untrack to the low score detections
        if len(dets_second) > 0:
            """Detections"""
            detections_second = [
                STrack(STrack.tlbr_to_tlwh(tlbr), s, u)
                for (tlbr, s, u) in zip(dets_second, scores_second, max_iou_second)
            ]
        else:
            detections_second = []
        r_tracked_stracks = [
            strack_pool[i]
            for i in u_track
            if strack_pool[i].state == TrackState.Tracked
        ]
        # dists = matching.iou_distance(r_tracked_stracks, detections_second)
        dists = self.compute_mix_dist(r_tracked_stracks, detections_second, img)
        matches, u_track, u_detection_second = matching.linear_assignment(
            dists, thresh=0.5
        )
        for itracked, idet in matches:
            track = r_tracked_stracks[itracked]
            det = detections_second[idet]
            template = (
                self.crop_and_resize(img, det.tlwh, "template")
                if det._iou < self.iou_thresh
                else None
            )
            if track.state == TrackState.Tracked:
                track.update(det, self.frame_id, template)
                activated_starcks.append(track)
            else:
                track.re_activate(det, self.frame_id, new_id=False, template=template)
                refind_stracks.append(track)

        for it in u_track:
            track = r_tracked_stracks[it]
            if not track.state == TrackState.Lost:
                track.mark_lost()
                lost_stracks.append(track)

        """Deal with unconfirmed tracks, usually tracks with only one beginning frame"""
        detections = [detections[i] for i in u_detection]
        dists = self.compute_mix_dist(unconfirmed, detections, img, fuse=True)
        # dists = matching.iou_distance(unconfirmed, detections)
        # if not self.args.mot20:
        #     dists = matching.fuse_score(dists, detections)
        matches, u_unconfirmed, u_detection = matching.linear_assignment(
            dists, thresh=0.7
        )
        for itracked, idet in matches:
            det = detections[idet]
            template = (
                self.crop_and_resize(img, det.tlwh, "template")
                if det._iou < self.iou_thresh
                else None
            )
            unconfirmed[itracked].update(detections[idet], self.frame_id, template)
            activated_starcks.append(unconfirmed[itracked])
        for it in u_unconfirmed:
            track = unconfirmed[it]
            track.mark_removed()
            removed_stracks.append(track)

        """ Step 4: Init new stracks"""
        for inew in u_detection:
            track = detections[inew]
            if track.score < self.det_thresh:
                continue
            # do not consider iou constraint
            track.activate(
                self.kalman_filter,
                self.frame_id,

In [84]:
TRACK_YAML = (
    MIXSORT_DIR
    / "MixViT"
    / "experiments"
    / "mixformer_deit"
    / "track.yaml"
)

print(TRACK_YAML)
print()
print(TRACK_YAML.read_text(encoding="utf-8"))

/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/experiments/mixformer_deit/track.yaml

DATA:
  MAX_SAMPLE_INTERVAL: 10
  MEAN:
  - 0.485
  - 0.456
  - 0.406
  SEARCH:
    CENTER_JITTER: 3
    FACTOR: 4.0
    SCALE_JITTER: 0.3
    SIZE: 224
  STD:
  - 0.229
  - 0.224
  - 0.225
  TEMPLATE:
    CENTER_JITTER: 0
    FACTOR: 1.5
    SCALE_JITTER: 0
    SIZE: 96
    NUMBER: 1
  TRAIN:
    # DATASETS_NAME: "SoccerNet_train","SoccerNet_test","DanceTrack_train","DanceTrack_val","SportsMOT_train","SportsMOT_val","SportsMOT_mix","SportsMOT_test","MOT17-train","MOT17-train_half","MOT20-train","MOT17-val_half"
    DATASETS_NAME:
    - SportsMOT_train
    DATASETS_RATIO:
    - 1
    SAMPLE_PER_EPOCH: 60000
  VAL:
    DATASETS_NAME:
    - SportsMOT_val
    DATASETS_RATIO:
    - 1
    SAMPLE_PER_EPOCH: 10000
MODEL:
  BACKBONE:
    PRETRAINED: True
    PRETRAINED_PATH: '/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/pretrained/MixFormer_sports_train.pth.tar'
    INIT: 'trunc_norm'
    NUM_STAGES: 3
    PATCH_SIZE: [ 7, 3, 3 ]
    PATCH_STRIDE: [ 4, 2, 2 ]
    PATCH_PADDING: [ 2, 1, 1 ]
    DIM_EMBED: [ 64, 192, 768 ]
    NUM_HEADS: [ 1, 3, 12 ]
    DEPTH: [ 1, 2, 9 ]
    MLP_RATIO: [ 4.0, 4.0, 4.0 ]
    ATTN_DROP_RATE: [ 0.0, 0.0, 0.0 ]
    DROP_RATE: [ 0.0, 0.0, 0.0 ]
    DROP_PATH_RATE: [ 0.0, 0.0, 0.1 ]
    QKV_BIAS: [ True, True, True ]
    CLS_TOKEN: [ False, False, False ]
    POS_EMBED: [ False, False, False ]
    QKV_PROJ_METHOD: [ 'dw_bn', 'dw_bn', 'dw_bn' ]
    KERNEL_QKV: [ 3, 3, 3 ]
    PADDING_KV: [ 1, 1, 1 ]
    STRIDE_KV: [ 2, 2, 2 ]
    PADDING_Q: [ 1, 1, 1 ]
    STRIDE_Q: [ 1, 1, 1 ]
    FREEZE_BN: False
  HEAD_TYPE: Heatmap
  HIDDEN_DIM: 768
  NUM_OBJECT_QUERIES: 1 # use when tokenHead is applied.
  POSITION_EMBEDDING: sine
  PREDICT_MASK: false
TRAIN:
  AMP: True
  BACKBONE_MULTIPLIER: 0.1
  BATCH_SIZE: 96  # 8 for 2080ti (maybe 10), 32 for tesla V100(32 G)
  DEEP_SUPERVISION: false
  EPOCH: 300
  IOU_WEIGHT: 2.0
  GRAD_CLIP_NORM: 0.1
  L1_WEIGHT: 5.0
  LR: 0.0004
  LR_DROP_EPOCH: 100
  NUM_WORKER: 5
  OPTIMIZER: ADAMW
  PRINT_INTERVAL: 20
  SCHEDULER:
    TYPE: step
    DECAY_RATE: 0.1
  VAL_EPOCH_INTERVAL: 1
  WEIGHT_DECAY: 0.0001
TEST:
  EPOCH: 500
  SEARCH_FACTOR: 4.5
  SEARCH_SIZE: 288
  TEMPLATE_FACTOR: 2.0
  TEMPLATE_SIZE: 128
  UPDATE_INTERVALS:
    LASOT: [200]
    GOT10K_TEST: [200]
    TRACKINGNET: [25]
    VOT20: [10]
    VOT20LT: [200]

In [85]:
MIXSORT_PRETRAINED = (
    MIXSORT_DIR
    / "pretrained"
    / "MixFormer_sports_train.pth.tar"
)

print("Checkpoint:")
print(MIXSORT_PRETRAINED)
print("Exists:", MIXSORT_PRETRAINED.exists())

if MIXSORT_PRETRAINED.exists():
    print(f"Size: {MIXSORT_PRETRAINED.stat().st_size / (1024**2):.2f} MB")

Checkpoint:
/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/pretrained/MixFormer_sports_train.pth.tar
Exists: True
Size: 375.89 MB

In [86]:
README = MIXSORT_DIR / "README.md"

text = README.read_text(encoding="utf-8")

for i, line in enumerate(text.splitlines(), start=1):
    if any(x in line.lower() for x in [
        "google",
        "baidu",
        "mixformer_sports",
        "model zoo",
        "pretrained models",
    ]):
        print(f"{i}: {line}")

99: ## Model zoo
101: The trained models are provided in [[google]](https://drive.google.com/drive/folders/1pQs1gFC_jG0TlGIUMgf3E0I3OztCvgxI?usp=sharing), [[baidu (code:7438)]](https://pan.baidu.com/s/1YAP1zKtx-M_ay6uZINoCHg). For YOLOX model trained on MOT17 or DanceTrack, you can refer to [ByteTrack](https://github.com/ifzhang/ByteTrack#model-zoo) and [DanceTrack](https://github.com/DanceTrack/DanceTrack/blob/main/ByteTrack/README.md).
103: After downloading the pretrained models, you can put them under `<MixSort_HOME>/pretrained`.
109: The COCO pretrained YOLOX model (`yolox_x.pth`) can be downloaded from their [model zoo](https://github.com/Megvii-BaseDetection/YOLOX/tree/0.1.0).

In [87]:
from pathlib import Path

MIXSORT_DIR = Path(
    "/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort"
)

MIXSORT_PRETRAINED = (
    MIXSORT_DIR / "pretrained" / "MixFormer_sports_train.pth.tar"
)

print("Checkpoint:")
print(MIXSORT_PRETRAINED)
print("Exists:", MIXSORT_PRETRAINED.exists())

if MIXSORT_PRETRAINED.exists():
    print(f"Size: {MIXSORT_PRETRAINED.stat().st_size / (1024**2):.2f} MB")

Checkpoint:
/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/pretrained/MixFormer_sports_train.pth.tar
Exists: True
Size: 375.89 MB

In [88]:
from pathlib import Path

for p in [
    MIXSORT_DIR / "MixViT",
    MIXSORT_DIR / "MixViT" / "lib",
    MIXSORT_DIR / "yolox",
]:
    print(f"\n{p}")
    if p.exists():
        for x in list(p.iterdir())[:20]:
            print("  ", x.name)

/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT
   experiments
   external
   install_pytorch17.sh
   lib
   LICENSE
   README.md
   requirements.txt
   segmentation
   tracking

/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib
   config
   models
   test
   train
   utils
   __init__.py
   __pycache__

/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/yolox
   byte_tracker
   core
   data
   deepsort_tracker
   evaluators
   exp
   layers
   mixsort_oc_tracker
   mixsort_tracker
   models
   motdt_tracker
   ocsort_tracker
   sort_tracker
   tracking_utils
   utils
   __init__.py
   __pycache__

In [89]:
CONFIG_DIR = MIXSORT_DIR / "MixViT" / "lib" / "config"

print("Config directory:", CONFIG_DIR)
print("Exists:", CONFIG_DIR.exists())
print()

for p in CONFIG_DIR.iterdir():
    print(p.name)

Config directory: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/config
Exists: True

mixformer
mixformerpp_vit_multi
mixformer_deit
mixformer_deit_multi
mixformer_online
mixformer_vit
mixformer_vit_decoder
mixformer_vit_learn_pos
mixformer_vit_multi
__init__.py
__pycache__

In [90]:
MIXFORMER_CONFIG_DIR = (
    MIXSORT_DIR / "MixViT" / "lib" / "config" / "mixformer_deit"
)

print("Directory:", MIXFORMER_CONFIG_DIR)
print("Exists:", MIXFORMER_CONFIG_DIR.exists())
print()

for p in MIXFORMER_CONFIG_DIR.iterdir():
    print(p.name)

Directory: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/config/mixformer_deit
Exists: True

config.py
__pycache__

In [91]:
CONFIG_FILE = MIXFORMER_CONFIG_DIR / "config.py"

print(CONFIG_FILE.read_text(encoding="utf-8"))

from easydict import EasyDict as edict
import yaml

"""
Add default config for MixFormer.
"""
cfg = edict()

# MODEL
cfg.MODEL = edict()
cfg.MODEL.HEAD_TYPE = "Heatmap"
cfg.MODEL.HIDDEN_DIM = 384
cfg.MODEL.NUM_OBJECT_QUERIES = 1
cfg.MODEL.POSITION_EMBEDDING = 'sine'  # sine or learned
cfg.MODEL.PREDICT_MASK = False
cfg.MODEL.VIT_TYPE = 'deit3_4layers'
# MODEL.BACKBONE
cfg.MODEL.BACKBONE = edict()
cfg.MODEL.BACKBONE.PRETRAINED = True
cfg.MODEL.BACKBONE.PRETRAINED_PATH = ''
cfg.MODEL.BACKBONE.INIT = 'trunc_norm'
cfg.MODEL.BACKBONE.NUM_STAGES = 3
cfg.MODEL.BACKBONE.PATCH_SIZE = [ 7, 3, 3 ]
cfg.MODEL.BACKBONE.PATCH_STRIDE = [ 4, 2, 2 ]
cfg.MODEL.BACKBONE.PATCH_PADDING = [ 2, 1, 1 ]
cfg.MODEL.BACKBONE.DIM_EMBED = [ 64, 192, 384 ]
cfg.MODEL.BACKBONE.NUM_HEADS = [ 1, 3, 6 ]
cfg.MODEL.BACKBONE.DEPTH = [ 1, 2, 10 ]
cfg.MODEL.BACKBONE.MLP_RATIO = [ 4.0, 4.0, 4.0 ]
cfg.MODEL.BACKBONE.ATTN_DROP_RATE = [ 0.0, 0.0, 0.0 ]
cfg.MODEL.BACKBONE.DROP_RATE = [ 0.0, 0.0, 0.0 ]
cfg.MODEL.BACKBONE.DROP_PATH_RATE = [ 0.0, 0.0, 0.1 ]
cfg.MODEL.BACKBONE.QKV_BIAS = [ True, True, True ]
cfg.MODEL.BACKBONE.CLS_TOKEN = [ False, False, True ]
cfg.MODEL.BACKBONE.POS_EMBED = [ False, False, False ]
cfg.MODEL.BACKBONE.QKV_PROJ_METHOD = [ 'dw_bn', 'dw_bn', 'dw_bn' ]
cfg.MODEL.BACKBONE.KERNEL_QKV = [ 3, 3, 3 ]
cfg.MODEL.BACKBONE.PADDING_KV = [ 1, 1, 1 ]
cfg.MODEL.BACKBONE.STRIDE_KV = [ 2, 2, 2 ]
cfg.MODEL.BACKBONE.PADDING_Q = [ 1, 1, 1 ]
cfg.MODEL.BACKBONE.STRIDE_Q = [ 1, 1, 1 ]
cfg.MODEL.BACKBONE.FREEZE_BN = True


# TRAIN
cfg.TRAIN = edict()
cfg.TRAIN.AMP = False
cfg.TRAIN.LR = 0.0001
cfg.TRAIN.WEIGHT_DECAY = 0.0001
cfg.TRAIN.EPOCH = 500
cfg.TRAIN.LR_DROP_EPOCH = 400
cfg.TRAIN.BATCH_SIZE = 16
cfg.TRAIN.NUM_WORKER = 8
cfg.TRAIN.OPTIMIZER = "ADAMW"
cfg.TRAIN.BACKBONE_MULTIPLIER = 0.1
cfg.TRAIN.IOU_WEIGHT = 2.0
cfg.TRAIN.L1_WEIGHT = 5.0
cfg.TRAIN.DEEP_SUPERVISION = False
cfg.TRAIN.FREEZE_STAGE0 = False
cfg.TRAIN.PRINT_INTERVAL = 50
cfg.TRAIN.VAL_EPOCH_INTERVAL = 20
cfg.TRAIN.GRAD_CLIP_NORM = 0.1
# TRAIN.SCHEDULER
cfg.TRAIN.SCHEDULER = edict()
cfg.TRAIN.SCHEDULER.TYPE = "step"
cfg.TRAIN.SCHEDULER.DECAY_RATE = 0.1

# DATA
cfg.DATA = edict()
cfg.DATA.MEAN = [0.485, 0.456, 0.406]
cfg.DATA.STD = [0.229, 0.224, 0.225]
cfg.DATA.MAX_SAMPLE_INTERVAL = 200
# DATA.TRAIN
cfg.DATA.TRAIN = edict()
cfg.DATA.TRAIN.DATASETS_NAME = ["SportsMOT"]#["LASOT", "GOT10K_vottrain"]
cfg.DATA.TRAIN.DATASETS_RATIO = [1]
cfg.DATA.TRAIN.SAMPLE_PER_EPOCH = 60000
# DATA.VAL
cfg.DATA.VAL = edict()
cfg.DATA.VAL.DATASETS_NAME = ["SportsMOT"]
cfg.DATA.VAL.DATASETS_RATIO = [1]
cfg.DATA.VAL.SAMPLE_PER_EPOCH = 10000
# DATA.SEARCH
cfg.DATA.SEARCH = edict()
cfg.DATA.SEARCH.SIZE = 320
cfg.DATA.SEARCH.FACTOR = 5.0
cfg.DATA.SEARCH.CENTER_JITTER = 4.5
cfg.DATA.SEARCH.SCALE_JITTER = 0.5
# DATA.TEMPLATE
cfg.DATA.TEMPLATE = edict()
cfg.DATA.TEMPLATE.SIZE = 128
cfg.DATA.TEMPLATE.FACTOR = 2.0
cfg.DATA.TEMPLATE.NUMBER = 1
cfg.DATA.TEMPLATE.CENTER_JITTER = 0
cfg.DATA.TEMPLATE.SCALE_JITTER = 0

# TEST
cfg.TEST = edict()
cfg.TEST.TEMPLATE_FACTOR = 2.0
cfg.TEST.TEMPLATE_SIZE = 128
cfg.TEST.SEARCH_FACTOR = 5.0
cfg.TEST.SEARCH_SIZE = 320
cfg.TEST.EPOCH = 500
cfg.TEST.UPDATE_INTERVALS = edict()
cfg.TEST.UPDATE_INTERVALS.LASOT = [200]
cfg.TEST.UPDATE_INTERVALS.GOT10K_TEST = [200]
cfg.TEST.UPDATE_INTERVALS.TRACKINGNET = [200]
cfg.TEST.UPDATE_INTERVALS.VOT20 = [200]
cfg.TEST.UPDATE_INTERVALS.VOT20LT = [200]


def _edict2dict(dest_dict, src_edict):
    if isinstance(dest_dict, dict) and isinstance(src_edict, dict):
        for k, v in src_edict.items():
            if not isinstance(v, edict):
                dest_dict[k] = v
            else:
                dest_dict[k] = {}
                _edict2dict(dest_dict[k], v)
    else:
        return


def gen_config(config_file):
    cfg_dict = {}
    _edict2dict(cfg_dict, cfg)
    with open(config_file, 'w') as f:
        yaml.dump(cfg_dict, f, default_flow_style=False)


def _update_config(base_cfg, exp_cfg):
    if isinstance(base_cfg, dict) and isinstance(exp_cfg, edict):
        for k, v in exp_cfg.items():
            if k in base_cfg:
                if not isinstance(v, dict):
                    base_cfg[k] = v
                else:
                    _update_config(base_cfg[k], v)
            else:
                raise ValueError("{} not exist in config.py".format(k))
    else:
        return


def update_config_from_file(filename):
    exp_config = None
    with open(filename) as f:
        exp_config = edict(yaml.safe_load(f))
        _update_config(cfg, exp_config)

In [92]:
import sys
from pathlib import Path

MIXVIT_DIR = Path(
    "/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT"
)

# Put MixViT FIRST in Python's module search path
sys.path.insert(0, str(MIXVIT_DIR))

print("MixViT exists:", MIXVIT_DIR.exists())
print("lib exists:", (MIXVIT_DIR / "lib").exists())
print("sys.path[0]:", sys.path[0])

# Check what Python actually resolves
import importlib.util

spec = importlib.util.find_spec("lib")
print("lib spec:", spec)

MixViT exists: True
lib exists: True
sys.path[0]: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT
lib spec: ModuleSpec(name='lib', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7d7dccd6ac30>, origin='/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/__init__.py', submodule_search_locations=['/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib'])

In [93]:
import sys

# Remove the conflicting already-loaded "lib" package
for name in list(sys.modules):
    if name == "lib" or name.startswith("lib."):
        del sys.modules[name]

# Make MixViT the first search location
MIXVIT_DIR = MIXSORT_DIR / "MixViT"

if str(MIXVIT_DIR) in sys.path:
    sys.path.remove(str(MIXVIT_DIR))

sys.path.insert(0, str(MIXVIT_DIR))

# Check what Python now resolves
import importlib.util

spec = importlib.util.find_spec("lib")

print("Resolved lib:")
print(spec)
print()
print("Expected:")
print(MIXVIT_DIR / "lib" / "__init__.py")

Resolved lib:
ModuleSpec(name='lib', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7d7dcc8de930>, origin='/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/__init__.py', submodule_search_locations=['/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib'])

Expected:
/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/__init__.py

In [94]:
!pip install easydict

Requirement already satisfied: easydict in /home/jatin/tf312/lib/python3.12/site-packages (1.13)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [95]:
from lib.config.mixformer_deit.config import cfg, update_config_from_file

TRACK_CONFIG = (
    MIXSORT_DIR
    / "MixViT"
    / "experiments"
    / "mixformer_deit"
    / "track.yaml"
)

update_config_from_file(str(TRACK_CONFIG))

print("Configuration loaded successfully")
print("VIT_TYPE:", cfg.MODEL.VIT_TYPE)
print("HEAD_TYPE:", cfg.MODEL.HEAD_TYPE)
print("PRETRAINED:", cfg.MODEL.BACKBONE.PRETRAINED)
print("PRETRAINED_PATH:", cfg.MODEL.BACKBONE.PRETRAINED_PATH)
print("HIDDEN_DIM:", cfg.MODEL.HIDDEN_DIM)

Configuration loaded successfully
VIT_TYPE: deit3_4layers
HEAD_TYPE: Heatmap
PRETRAINED: True
PRETRAINED_PATH: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/pretrained/MixFormer_sports_train.pth.tar
HIDDEN_DIM: 768

In [96]:
MODELS_DIR = MIXSORT_DIR / "MixViT" / "lib" / "models"

print("Models directory:", MODELS_DIR)
print("Exists:", MODELS_DIR.exists())
print()

for p in MODELS_DIR.iterdir():
    print(p.name)

Models directory: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models
Exists: True

losses
mixformer
mixformer_vit
__init__.py
__pycache__

In [97]:
MIXFORMER_DIR = MODELS_DIR / "mixformer"

print("Directory:", MIXFORMER_DIR)
print("Exists:", MIXFORMER_DIR.exists())
print()

for p in MIXFORMER_DIR.iterdir():
    print(p.name)

Directory: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models/mixformer
Exists: True

head.py
mixformer.py
mixformer_online.py
mixformer_vit_multi_stage_ablation.py
utils.py
__init__.py
__pycache__

In [98]:
MIXFORMER_FILE = MIXFORMER_DIR / "mixformer.py"

text = MIXFORMER_FILE.read_text(encoding="utf-8")

for i, line in enumerate(text.splitlines(), start=1):
    if (
        "def build_" in line
        or "class Mix" in line
        or "def build" in line
    ):
        print(f"{i}: {line}")

765: class MixFormer(nn.Module):
818: def build_mixformer(cfg):

In [99]:
print("\n".join(
    text.splitlines()[800:850]
))

        self.backbone.set_online(template, online_template)

    def forward_box_head(self, search):
        """
        :param search: (b, c, h, w)
        :return:
        """
        if self.head_type == "CORNER":
            # run the corner head
            b = search.size(0)
            outputs_coord = box_xyxy_to_cxcywh(self.box_head(search))
            outputs_coord_new = outputs_coord.view(b, 1, 4)
            out = {'pred_boxes': outputs_coord_new}
            return out, outputs_coord_new
        else:
            raise KeyError

def build_mixformer(cfg):
    backbone = get_mixformer_model(cfg)  # backbone without positional encoding and attention mask
    box_head = build_box_head(cfg)  # a simple corner head
    model = MixFormer(
        backbone,
        box_head,
        head_type=cfg.MODEL.HEAD_TYPE
    )

    return model

In [100]:
# Find where get_mixformer_model is defined
import re

for root in [
    MIXSORT_DIR / "MixViT" / "lib" / "models",
]:
    for file in root.rglob("*.py"):
        content = file.read_text(encoding="utf-8", errors="ignore")
        if "def get_mixformer_model" in content:
            print("Found in:")
            print(file)
            print()

            lines = content.splitlines()
            for i, line in enumerate(lines):
                if "def get_mixformer_model" in line:
                    print("\n".join(
                        f"{j+1}: {lines[j]}"
                        for j in range(max(0, i-5), min(len(lines), i+40))
                    ))

Found in:
/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models/mixformer/mixformer.py

735:     def set_online(self, template, online_template):
736:         for i in range(self.num_stages):
737:             template, online_template = getattr(self, f'stage{i}').set_online(template, online_template)
738:
739:
740: def get_mixformer_model(config, **kwargs):
741:     msvit_spec = config.MODEL.BACKBONE
742:     msvit = ConvolutionalVisionTransformer(
743:         in_chans=3,
744:         act_layer=QuickGELU,
745:         norm_layer=partial(LayerNorm, eps=1e-5),
746:         init=getattr(msvit_spec, 'INIT', 'trunc_norm'),
747:         spec=msvit_spec
748:     )
749:
750:     if config.MODEL.BACKBONE.PRETRAINED:
751:         try:
752:             ckpt_path = config.MODEL.BACKBONE.PRETRAINED_PATH
753:             ckpt = torch.load(ckpt_path, map_location='cpu')
754:             missing_keys, unexpected_keys = msvit.load_state_dict(ckpt, strict=False)
755:             if is_main_process():
756:                 print("missing keys:", missing_keys)
757:                 print("unexpected keys:", unexpected_keys)
758:                 print("Loading pretrained CVT done.")
759:         except:
760:             print("Warning: Pretrained CVT weights are not loaded")
761:
762:     return msvit
763:
764:
765: class MixFormer(nn.Module):
766:     """ This is the base class for Transformer Tracking, whcih jointly perform feature extraction and interaction. """
767:     def __init__(self, backbone, box_head, head_type="CORNER"):
768:         """ Initializes the model.
769:         """
770:         super().__init__()
771:         self.backbone = backbone
772:         self.box_head = box_head
773:         self.head_type = head_type
774:
775:     def forward(self, template, online_template, search, run_score_head=False, gt_bboxes=None):
776:         # search: (b, c, h, w)
777:         if template.dim() == 5:
778:             template = template.squeeze(0)
779:         if online_template.dim() == 5:
Found in:
/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models/mixformer/mixformer_vit_multi_stage_ablation.py

643:     # def set_online(self, template, online_template):
644:     #     for i in range(self.num_stages):
645:     #         template, online_template = getattr(self, f'stage{i}').set_online(template, online_template)
646:
647:
648: def get_mixformer_model(config, **kwargs):
649:     msvit_spec = config.MODEL.BACKBONE
650:     msvit = ConvolutionalVisionTransformer(
651:         in_chans=3,
652:         act_layer=QuickGELU,
653:         norm_layer=partial(LayerNorm, eps=1e-5),
654:         init=getattr(msvit_spec, 'INIT', 'trunc_norm'),
655:         spec=msvit_spec
656:     )
657:
658:     if config.MODEL.BACKBONE.PRETRAINED:
659:         try:
660:             ckpt_path = config.MODEL.BACKBONE.PRETRAINED_PATH
661:             ckpt = torch.load(ckpt_path, map_location='cpu')
662:             missing_keys, unexpected_keys = msvit.load_state_dict(ckpt, strict=False)
663:             if is_main_process():
664:                 print("missing keys:", missing_keys)
665:                 print("unexpected keys:", unexpected_keys)
666:                 print("Loading pretrained CVT done.")
667:         except:
668:             print("Warning: Pretrained CVT weights are not loaded")
669:
670:     return msvit
671:
672:
673: class MixFormer(nn.Module):
674:     """ This is the base class for Transformer Tracking, whcih jointly perform feature extraction and interaction. """
675:     def __init__(self, backbone, box_head, head_type="CORNER"):
676:         """ Initializes the model.
677:         """
678:         super().__init__()
679:         self.backbone = backbone
680:         self.box_head = box_head
681:         self.head_type = head_type
682:
683:     def forward(self, template, online_template, search, run_score_head=False, gt_bboxes=None):
684:         # search: (b, c, h, w)
685:         if template.dim() == 5:
686:             template = template.squeeze(0)
687:         if online_template.dim() == 5:

In [101]:
cfg.MODEL.BACKBONE.PRETRAINED_PATH = str(MIXSORT_PRETRAINED)

print("Checkpoint configured as:")
print(cfg.MODEL.BACKBONE.PRETRAINED_PATH)
print()
print("Exists:", MIXSORT_PRETRAINED.exists())

Checkpoint configured as:
/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/pretrained/MixFormer_sports_train.pth.tar

Exists: True

In [102]:
!pip install einops
!pip install timm

Requirement already satisfied: einops in /home/jatin/tf312/lib/python3.12/site-packages (0.8.2)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: timm in /home/jatin/tf312/lib/python3.12/site-packages (1.0.30)
Requirement already satisfied: torch in /home/jatin/tf312/lib/python3.12/site-packages (from timm) (2.14.0)
Requirement already satisfied: torchvision in /home/jatin/tf312/lib/python3.12/site-packages (from timm) (0.29.0)
Requirement already satisfied: pyyaml in /home/jatin/tf312/lib/python3.12/site-packages (from timm) (6.0.3)
Requirement already satisfied: huggingface_hub in /home/jatin/tf312/lib/python3.12/site-packages (from timm) (2.0.0)
Requirement already satisfied: safetensors in /home/jatin/tf312/lib/python3.12/site-packages (from timm) (0.8.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /home/jatin/tf312/lib/python3.12/site-packages (from huggingface_hub->timm) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /home/jatin/tf312/lib/python3.12/site-packages (from huggingface_hub->timm) (3.32.3)
Requirement already satisfied: fsspec>=2023.5.0 in /home/jatin/tf312/lib/python3.12/site-packages (from huggingface_hub->timm) (2026.6.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /home/jatin/tf312/lib/python3.12/site-packages (from huggingface_hub->timm) (1.6.0)
Requirement already satisfied: httpx2<3,>=2.0.0 in /home/jatin/tf312/lib/python3.12/site-packages (from huggingface_hub->timm) (2.13.1)
Requirement already satisfied: packaging>=20.9 in /home/jatin/tf312/lib/python3.12/site-packages (from huggingface_hub->timm) (26.2)
Requirement already satisfied: tqdm>=4.42.1 in /home/jatin/tf312/lib/python3.12/site-packages (from huggingface_hub->timm) (4.69.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/jatin/tf312/lib/python3.12/site-packages (from huggingface_hub->timm) (4.16.0)
Requirement already satisfied: anyio>=4.10 in /home/jatin/tf312/lib/python3.12/site-packages (from httpx2<3,>=2.0.0->huggingface_hub->timm) (4.14.2)
Requirement already satisfied: httpcore2==2.13.1 in /home/jatin/tf312/lib/python3.12/site-packages (from httpx2<3,>=2.0.0->huggingface_hub->timm) (2.13.1)
Requirement already satisfied: idna>=3.18 in /home/jatin/tf312/lib/python3.12/site-packages (from httpx2<3,>=2.0.0->huggingface_hub->timm) (3.18)
Requirement already satisfied: truststore>=0.10 in /home/jatin/tf312/lib/python3.12/site-packages (from httpx2<3,>=2.0.0->huggingface_hub->timm) (0.10.4)
Requirement already satisfied: h11>=0.16 in /home/jatin/tf312/lib/python3.12/site-packages (from httpcore2==2.13.1->httpx2<3,>=2.0.0->huggingface_hub->timm) (0.16.0)
Requirement already satisfied: setuptools>=77.0.3 in /home/jatin/tf312/lib/python3.12/site-packages (from torch->timm) (83.0.0)
Requirement already satisfied: sympy>=1.13.3 in /home/jatin/tf312/lib/python3.12/site-packages (from torch->timm) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/jatin/tf312/lib/python3.12/site-packages (from torch->timm) (3.6.1)
Requirement already satisfied: jinja2 in /home/jatin/tf312/lib/python3.12/site-packages (from torch->timm) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.3 in /home/jatin/tf312/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->timm) (13.0.3.0)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /home/jatin/tf312/lib/python3.12/site-packages (from torch->timm) (13.3.1)
Requirement already satisfied: nvidia-cudnn-cu13==9.24.0.43 in /home/jatin/tf312/lib/python3.12/site-packages (from torch->timm) (9.24.0.43)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.1 in /home/jatin/tf312/lib/python3.12/site-packages (from torch->timm) (0.8.1)
Requirement already satisfied: nvidia-nccl-cu13==2.30.7 in /home/jatin/tf312/lib/python3.12/site-packages (from torch->timm) (2.30.7)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /home/jatin/tf312/lib/python3.12/site-packages (from torch->timm) (3.4.5)
Requirement already satisfied: triton~=3.8.0 in /home/jatin/tf312/lib/python3.12/site-packages (from torch->timm) (3.8.0)
Requirement already satisfied: nvidia-cublas==13.1.1.3.* in /home/jatin/tf312/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->timm) (13.1.1.3)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /home/jatin/tf312/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->timm) (13.0.88)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /home/jatin/tf312/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->timm) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /home/jatin/tf312/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->timm) (12.0.0.61)
Requirement already satisfied: nvidia-nvjitlink<14,>=13.0.88 in /home/jatin/tf312/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->timm) (13.3.33)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /home/jatin/tf312/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->timm) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /home/jatin/tf312/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->timm) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /home/jatin/tf312/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->timm) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /home/jatin/tf312/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->timm) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /home/jatin/tf312/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->timm) (12.6.3.3)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /home/jatin/tf312/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->timm) (13.0.85)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in /home/jatin/tf312/lib/python3.12/site-packages (from cuda-bindings<14,>=13.0.3->torch->timm) (1.6.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/jatin/tf312/lib/python3.12/site-packages (from sympy>=1.13.3->torch->timm) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/jatin/tf312/lib/python3.12/site-packages (from jinja2->torch->timm) (3.0.3)
Requirement already satisfied: numpy in /home/jatin/tf312/lib/python3.12/site-packages (from torchvision->timm) (2.3.5)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /home/jatin/tf312/lib/python3.12/site-packages (from torchvision->timm) (12.3.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [103]:
from lib.models.mixformer.mixformer import build_mixformer

print("build_mixformer imported successfully")
print(build_mixformer)

/home/jatin/tf312/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

build_mixformer imported successfully
<function build_mixformer at 0x7d7db9f43920>

In [104]:
import time

print("Building MixFormer...")
t0 = time.time()

network = build_mixformer(cfg)

elapsed = time.time() - t0

print(f"\nBuild finished in {elapsed:.2f} seconds")
print("Model type:", type(network))

Building MixFormer...
Warning: Pretrained CVT weights are not loaded
head channel: 384

Build finished in 5.87 seconds
Model type: <class 'lib.models.mixformer.mixformer.MixFormer'>

In [105]:
import torch

print("Loading trusted MixSort checkpoint...")

checkpoint = torch.load(
    str(MIXSORT_PRETRAINED),
    map_location="cpu",
    weights_only=False
)

print("Checkpoint loaded successfully!")
print("Type:", type(checkpoint))

if isinstance(checkpoint, dict):
    print("Keys:", list(checkpoint.keys())[:20])

Loading trusted MixSort checkpoint...

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1791018564.131975     888 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1791018569.520735     888 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

Checkpoint loaded successfully!
Type: <class 'dict'>
Keys: ['epoch', 'actor_type', 'net_type', 'net', 'net_info', 'constructor', 'optimizer', 'stats', 'settings']

In [106]:
net_state = checkpoint["net"]

print("net type:", type(net_state))

if isinstance(net_state, dict):
    print("Number of parameters:", len(net_state))
    print("\nFirst 15 keys:")
    for key in list(net_state.keys())[:15]:
        value = net_state[key]
        print(f"{key:70s} {tuple(value.shape) if hasattr(value, 'shape') else type(value)}")

net type: <class 'collections.OrderedDict'>
Number of parameters: 88

First 15 keys:
backbone.cls_token                                                     (1, 1, 768)
backbone.pos_embed                                                     (1, 197, 768)
backbone.pos_embed_s                                                   (1, 196, 768)
backbone.pos_embed_t                                                   (1, 36, 768)
backbone.patch_embed.proj.weight                                       (768, 3, 16, 16)
backbone.patch_embed.proj.bias                                         (768,)
backbone.blocks.0.norm1.weight                                         (768,)
backbone.blocks.0.norm1.bias                                           (768,)
backbone.blocks.0.attn.qkv.weight                                      (2304, 768)
backbone.blocks.0.attn.qkv.bias                                        (2304,)
backbone.blocks.0.attn.proj.weight                                     (768, 768)
backbone.blocks.0.attn.proj.bias                                       (768,)
backbone.blocks.0.norm2.weight                                         (768,)
backbone.blocks.0.norm2.bias                                           (768,)
backbone.blocks.0.mlp.fc1.weight                                       (3072, 768)

In [107]:
print("net_type:")
print(checkpoint["net_type"])

print("\nactor_type:")
print(checkpoint["actor_type"])

print("\nconstructor:")
print(checkpoint["constructor"])

print("\nnet_info:")
print(checkpoint["net_info"])

print("\nsettings:")
print(checkpoint["settings"])

net_type:
MixFormer

actor_type:
MixFormerActor

constructor:
None

net_info:
None

settings:
<lib.train.admin.settings.Settings object at 0x7d7db9cb95e0>

In [108]:
settings = checkpoint["settings"]

print("Settings attributes:")
for name in dir(settings):
    if not name.startswith("_"):
        try:
            value = getattr(settings, name)
            if not callable(value):
                print(f"{name}: {value}")
        except Exception:
            pass

Settings attributes:
batchsize: 96
center_jitter_factor: {'template': 0, 'search': 3}
cfg: {'MODEL': {'HEAD_TYPE': 'Heatmap', 'HIDDEN_DIM': 768, 'NUM_OBJECT_QUERIES': 1, 'POSITION_EMBEDDING': 'sine', 'PREDICT_MASK': False, 'VIT_TYPE': 'deit3_4layers', 'BACKBONE': {'PRETRAINED': True, 'PRETRAINED_PATH': '/data3/zck/MixTrack/pretrained/MixFormerOnlineScore_ep0600.pth.tar', 'INIT': 'trunc_norm', 'NUM_STAGES': 3, 'PATCH_SIZE': [7, 3, 3], 'PATCH_STRIDE': [4, 2, 2], 'PATCH_PADDING': [2, 1, 1], 'DIM_EMBED': [64, 192, 768], 'NUM_HEADS': [1, 3, 12], 'DEPTH': [1, 2, 9], 'MLP_RATIO': [4.0, 4.0, 4.0], 'ATTN_DROP_RATE': [0.0, 0.0, 0.0], 'DROP_RATE': [0.0, 0.0, 0.0], 'DROP_PATH_RATE': [0.0, 0.0, 0.1], 'QKV_BIAS': [True, True, True], 'CLS_TOKEN': [False, False, False], 'POS_EMBED': [False, False, False], 'QKV_PROJ_METHOD': ['dw_bn', 'dw_bn', 'dw_bn'], 'KERNEL_QKV': [3, 3, 3], 'PADDING_KV': [1, 1, 1], 'STRIDE_KV': [2, 2, 2], 'PADDING_Q': [1, 1, 1], 'STRIDE_Q': [1, 1, 1], 'FREEZE_BN': False}}, 'TRAIN': {'AMP': True, 'LR': 0.0004, 'WEIGHT_DECAY': 0.0001, 'EPOCH': 300, 'LR_DROP_EPOCH': 100, 'BATCH_SIZE': 96, 'NUM_WORKER': 6, 'OPTIMIZER': 'ADAMW', 'BACKBONE_MULTIPLIER': 0.1, 'IOU_WEIGHT': 2.0, 'L1_WEIGHT': 5.0, 'DEEP_SUPERVISION': False, 'FREEZE_STAGE0': False, 'PRINT_INTERVAL': 20, 'VAL_EPOCH_INTERVAL': 1, 'GRAD_CLIP_NORM': 0.1, 'SCHEDULER': {'TYPE': 'step', 'DECAY_RATE': 0.1}}, 'DATA': {'MEAN': [0.485, 0.456, 0.406], 'STD': [0.229, 0.224, 0.225], 'MAX_SAMPLE_INTERVAL': 10, 'TRAIN': {'DATASETS_NAME': ['SportsMOT_train'], 'DATASETS_RATIO': [1], 'SAMPLE_PER_EPOCH': 60000}, 'VAL': {'DATASETS_NAME': ['SportsMOT_test'], 'DATASETS_RATIO': [1], 'SAMPLE_PER_EPOCH': 10000}, 'SEARCH': {'SIZE': 224, 'FACTOR': 4.0, 'CENTER_JITTER': 3, 'SCALE_JITTER': 0.3}, 'TEMPLATE': {'SIZE': 96, 'FACTOR': 1.5, 'NUMBER': 1, 'CENTER_JITTER': 0, 'SCALE_JITTER': 0}}, 'TEST': {'TEMPLATE_FACTOR': 2.0, 'TEMPLATE_SIZE': 128, 'SEARCH_FACTOR': 4.5, 'SEARCH_SIZE': 288, 'EPOCH': 500, 'UPDATE_INTERVALS': {'LASOT': [200], 'GOT10K_TEST': [200], 'TRACKINGNET': [25], 'VOT20': [10], 'VOT20LT': [200]}}}
cfg_file: /data3/zck/MixTrack/MixViT/experiments/mixformer_deit/baseline.yaml
config_name: baseline
deep_sup: False
description: Training script for Mixformer
device: cuda:0
distill: False
distill_loss_type: KL
env: <lib.train.admin.local.EnvironmentSettings object at 0x7d7db9cb9580>
generate_sep_labels: False
grad_clip_norm: 0.1
local_rank: 0
log_file: /data3/zck/MixTrack/exp/1023_sports_train/logs/mixformer_deit-baseline.log
num_search: 1
num_template: 1
output_sz: {'template': 96, 'search': 224}
print_interval: 20
print_stats: None
project_path: train/mixformer_deit/baseline
save_dir: /data3/zck/MixTrack/exp/1023_sports_train
scale_jitter_factor: {'template': 0, 'search': 0.3}
scheduler_type: step
script_name: mixformer_deit
search_area_factor: {'template': 1.5, 'search': 4.0}
stage1_model: None
use_gpu: True
use_lmdb: 0

In [109]:
# Keys expected by the MixSort model we constructed
model_keys = list(network.state_dict().keys())

# Keys stored in the downloaded checkpoint
checkpoint_keys = list(checkpoint["net"].keys())

print("Constructed model parameters:", len(model_keys))
print("Checkpoint parameters:", len(checkpoint_keys))

print("\nConstructed model — first 20 keys:")
for k in model_keys[:20]:
    print(k)

print("\nCheckpoint — first 20 keys:")
for k in checkpoint_keys[:20]:
    print(k)

Constructed model parameters: 346
Checkpoint parameters: 88

Constructed model — first 20 keys:
backbone.stage0.patch_embed.proj.weight
backbone.stage0.patch_embed.proj.bias
backbone.stage0.patch_embed.norm.weight
backbone.stage0.patch_embed.norm.bias
backbone.stage0.blocks.0.norm1.weight
backbone.stage0.blocks.0.norm1.bias
backbone.stage0.blocks.0.attn.conv_proj_q.conv.weight
backbone.stage0.blocks.0.attn.conv_proj_q.bn.weight
backbone.stage0.blocks.0.attn.conv_proj_q.bn.bias
backbone.stage0.blocks.0.attn.conv_proj_k.conv.weight
backbone.stage0.blocks.0.attn.conv_proj_k.bn.weight
backbone.stage0.blocks.0.attn.conv_proj_k.bn.bias
backbone.stage0.blocks.0.attn.conv_proj_v.conv.weight
backbone.stage0.blocks.0.attn.conv_proj_v.bn.weight
backbone.stage0.blocks.0.attn.conv_proj_v.bn.bias
backbone.stage0.blocks.0.attn.proj_q.weight
backbone.stage0.blocks.0.attn.proj_q.bias
backbone.stage0.blocks.0.attn.proj_k.weight
backbone.stage0.blocks.0.attn.proj_k.bias
backbone.stage0.blocks.0.attn.proj_v.weight

Checkpoint — first 20 keys:
backbone.cls_token
backbone.pos_embed
backbone.pos_embed_s
backbone.pos_embed_t
backbone.patch_embed.proj.weight
backbone.patch_embed.proj.bias
backbone.blocks.0.norm1.weight
backbone.blocks.0.norm1.bias
backbone.blocks.0.attn.qkv.weight
backbone.blocks.0.attn.qkv.bias
backbone.blocks.0.attn.proj.weight
backbone.blocks.0.attn.proj.bias
backbone.blocks.0.norm2.weight
backbone.blocks.0.norm2.bias
backbone.blocks.0.mlp.fc1.weight
backbone.blocks.0.mlp.fc1.bias
backbone.blocks.0.mlp.fc2.weight
backbone.blocks.0.mlp.fc2.bias
backbone.blocks.1.norm1.weight
backbone.blocks.1.norm1.bias

In [110]:
BASELINE_CONFIG = (
    MIXSORT_DIR
    / "MixViT"
    / "experiments"
    / "mixformer_deit"
    / "baseline.yaml"
)

print("Baseline config:")
print(BASELINE_CONFIG)
print()
print(BASELINE_CONFIG.read_text(encoding="utf-8"))

Baseline config:
/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/experiments/mixformer_deit/baseline.yaml

DATA:
  MAX_SAMPLE_INTERVAL: 10
  MEAN:
  - 0.485
  - 0.456
  - 0.406
  SEARCH:
    CENTER_JITTER: 3
    FACTOR: 4.0
    SCALE_JITTER: 0.3
    SIZE: 224
  STD:
  - 0.229
  - 0.224
  - 0.225
  TEMPLATE:
    CENTER_JITTER: 0
    FACTOR: 1.5
    SCALE_JITTER: 0
    SIZE: 96
    NUMBER: 1
  TRAIN:
    # DATASETS_NAME: "SoccerNet_train","SoccerNet_test","DanceTrack_train","DanceTrack_val","SportsMOT_train","SportsMOT_val","SportsMOT_mix","MOT17-train","MOT17-train_half","MOT17-val_half"
    DATASETS_NAME:
    - SportsMOT_train
    DATASETS_RATIO:
    - 1
    SAMPLE_PER_EPOCH: 60000
  VAL:
    DATASETS_NAME:
    - SportsMOT_val
    DATASETS_RATIO:
    - 1
    SAMPLE_PER_EPOCH: 10000
MODEL:
  BACKBONE:
    PRETRAINED: True
    PRETRAINED_PATH: 'pretrained/MixFormerOnlineScore.pth.tar'
    INIT: 'trunc_norm'
    NUM_STAGES: 3
    PATCH_SIZE: [ 7, 3, 3 ]
    PATCH_STRIDE: [ 4, 2, 2 ]
    PATCH_PADDING: [ 2, 1, 1 ]
    DIM_EMBED: [ 64, 192, 768 ]
    NUM_HEADS: [ 1, 3, 12 ]
    DEPTH: [ 1, 2, 9 ]
    MLP_RATIO: [ 4.0, 4.0, 4.0 ]
    ATTN_DROP_RATE: [ 0.0, 0.0, 0.0 ]
    DROP_RATE: [ 0.0, 0.0, 0.0 ]
    DROP_PATH_RATE: [ 0.0, 0.0, 0.1 ]
    QKV_BIAS: [ True, True, True ]
    CLS_TOKEN: [ False, False, False ]
    POS_EMBED: [ False, False, False ]
    QKV_PROJ_METHOD: [ 'dw_bn', 'dw_bn', 'dw_bn' ]
    KERNEL_QKV: [ 3, 3, 3 ]
    PADDING_KV: [ 1, 1, 1 ]
    STRIDE_KV: [ 2, 2, 2 ]
    PADDING_Q: [ 1, 1, 1 ]
    STRIDE_Q: [ 1, 1, 1 ]
    FREEZE_BN: False
  HEAD_TYPE: Heatmap
  HIDDEN_DIM: 768
  NUM_OBJECT_QUERIES: 1 # use when tokenHead is applied.
  POSITION_EMBEDDING: sine
  PREDICT_MASK: false
TRAIN:
  AMP: True
  BACKBONE_MULTIPLIER: 0.1
  BATCH_SIZE: 96  # 8 for 2080ti (maybe 10), 32 for tesla V100(32 G)
  DEEP_SUPERVISION: false
  EPOCH: 300
  IOU_WEIGHT: 2.0
  GRAD_CLIP_NORM: 0.1
  L1_WEIGHT: 5.0
  LR: 0.0004
  LR_DROP_EPOCH: 100
  NUM_WORKER: 5
  OPTIMIZER: ADAMW
  PRINT_INTERVAL: 20
  SCHEDULER:
    TYPE: step
    DECAY_RATE: 0.1
  VAL_EPOCH_INTERVAL: 1
  WEIGHT_DECAY: 0.0001
TEST:
  EPOCH: 500
  SEARCH_FACTOR: 4.5
  SEARCH_SIZE: 288
  TEMPLATE_FACTOR: 2.0
  TEMPLATE_SIZE: 128
  UPDATE_INTERVALS:
    LASOT: [200]
    GOT10K_TEST: [200]
    TRACKINGNET: [25]
    VOT20: [10]
    VOT20LT: [200]

In [111]:
PRETRAINED_DIR = MIXSORT_DIR / "pretrained"

print("Pretrained directory:")
print(PRETRAINED_DIR)
print()

for p in sorted(PRETRAINED_DIR.iterdir()):
    if p.is_file():
        print(f"{p.name:45s} {p.stat().st_size / (1024**2):8.2f} MB")

Pretrained directory:
/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/pretrained

MixFormerOnlineScore.pth.tar                    439.43 MB
MixFormer_sports_train.pth.tar                  375.89 MB

In [112]:
net_state = checkpoint["net"]

print("Total checkpoint tensors:", len(net_state))
print()

for i, (key, value) in enumerate(net_state.items()):
    print(f"{i:3d}  {key:65s}  {tuple(value.shape)}")

Total checkpoint tensors: 88

  0  backbone.cls_token                                                 (1, 1, 768)
  1  backbone.pos_embed                                                 (1, 197, 768)
  2  backbone.pos_embed_s                                               (1, 196, 768)
  3  backbone.pos_embed_t                                               (1, 36, 768)
  4  backbone.patch_embed.proj.weight                                   (768, 3, 16, 16)
  5  backbone.patch_embed.proj.bias                                     (768,)
  6  backbone.blocks.0.norm1.weight                                     (768,)
  7  backbone.blocks.0.norm1.bias                                       (768,)
  8  backbone.blocks.0.attn.qkv.weight                                  (2304, 768)
  9  backbone.blocks.0.attn.qkv.bias                                    (2304,)
 10  backbone.blocks.0.attn.proj.weight                                 (768, 768)
 11  backbone.blocks.0.attn.proj.bias                                   (768,)
 12  backbone.blocks.0.norm2.weight                                     (768,)
 13  backbone.blocks.0.norm2.bias                                       (768,)
 14  backbone.blocks.0.mlp.fc1.weight                                   (3072, 768)
 15  backbone.blocks.0.mlp.fc1.bias                                     (3072,)
 16  backbone.blocks.0.mlp.fc2.weight                                   (768, 3072)
 17  backbone.blocks.0.mlp.fc2.bias                                     (768,)
 18  backbone.blocks.1.norm1.weight                                     (768,)
 19  backbone.blocks.1.norm1.bias                                       (768,)
 20  backbone.blocks.1.attn.qkv.weight                                  (2304, 768)
 21  backbone.blocks.1.attn.qkv.bias                                    (2304,)
 22  backbone.blocks.1.attn.proj.weight                                 (768, 768)
 23  backbone.blocks.1.attn.proj.bias                                   (768,)
 24  backbone.blocks.1.norm2.weight                                     (768,)
 25  backbone.blocks.1.norm2.bias                                       (768,)
 26  backbone.blocks.1.mlp.fc1.weight                                   (3072, 768)
 27  backbone.blocks.1.mlp.fc1.bias                                     (3072,)
 28  backbone.blocks.1.mlp.fc2.weight                                   (768, 3072)
 29  backbone.blocks.1.mlp.fc2.bias                                     (768,)
 30  backbone.blocks.2.norm1.weight                                     (768,)
 31  backbone.blocks.2.norm1.bias                                       (768,)
 32  backbone.blocks.2.attn.qkv.weight                                  (2304, 768)
 33  backbone.blocks.2.attn.qkv.bias                                    (2304,)
 34  backbone.blocks.2.attn.proj.weight                                 (768, 768)
 35  backbone.blocks.2.attn.proj.bias                                   (768,)
 36  backbone.blocks.2.norm2.weight                                     (768,)
 37  backbone.blocks.2.norm2.bias                                       (768,)
 38  backbone.blocks.2.mlp.fc1.weight                                   (3072, 768)
 39  backbone.blocks.2.mlp.fc1.bias                                     (3072,)
 40  backbone.blocks.2.mlp.fc2.weight                                   (768, 3072)
 41  backbone.blocks.2.mlp.fc2.bias                                     (768,)
 42  backbone.blocks.3.norm1.weight                                     (768,)
 43  backbone.blocks.3.norm1.bias                                       (768,)
 44  backbone.blocks.3.attn.qkv.weight                                  (2304, 768)
 45  backbone.blocks.3.attn.qkv.bias                                    (2304,)
 46  backbone.blocks.3.attn.proj.weight                                 (768, 768)
 47  backbone.blocks.3.attn.proj.bias                                   (768,)
 48  backbone.blocks.3.norm2.weight                                     (768,)
 49  backbone.blocks.3.norm2.bias                                       (768,)
 50  backbone.blocks.3.mlp.fc1.weight                                   (3072, 768)
 51  backbone.blocks.3.mlp.fc1.bias                                     (3072,)
 52  backbone.blocks.3.mlp.fc2.weight                                   (768, 3072)
 53  backbone.blocks.3.mlp.fc2.bias                                     (768,)
 54  backbone.norm.weight                                               (768,)
 55  backbone.norm.bias                                                 (768,)
 56  backbone.head.weight                                               (1000, 768)
 57  backbone.head.bias                                                 (1000,)
 58  box_head.conv1.0.weight                                            (384, 768, 3, 3)
 59  box_head.conv1.0.bias                                              (384,)
 60  box_head.conv1.1.weight                                            (384,)
 61  box_head.conv1.1.bias                                              (384,)
 62  box_head.conv1.1.running_mean                                      (384,)
 63  box_head.conv1.1.running_var                                       (384,)
 64  box_head.conv1.1.num_batches_tracked                               ()
 65  box_head.conv2.0.weight                                            (192, 384, 3, 3)
 66  box_head.conv2.0.bias                                              (192,)
 67  box_head.conv2.1.weight                                            (192,)
 68  box_head.conv2.1.bias                                              (192,)
 69  box_head.conv2.1.running_mean                                      (192,)
 70  box_head.conv2.1.running_var                                       (192,)
 71  box_head.conv2.1.num_batches_tracked                               ()
 72  box_head.conv3.0.weight                                            (96, 192, 3, 3)
 73  box_head.conv3.0.bias                                              (96,)
 74  box_head.conv3.1.weight                                            (96,)
 75  box_head.conv3.1.bias                                              (96,)
 76  box_head.conv3.1.running_mean                                      (96,)
 77  box_head.conv3.1.running_var                                       (96,)
 78  box_head.conv3.1.num_batches_tracked                               ()
 79  box_head.conv4.0.weight                                            (48, 96, 3, 3)
 80  box_head.conv4.0.bias                                              (48,)
 81  box_head.conv4.1.weight                                            (48,)
 82  box_head.conv4.1.bias                                              (48,)
 83  box_head.conv4.1.running_mean                                      (48,)
 84  box_head.conv4.1.running_var                                       (48,)
 85  box_head.conv4.1.num_batches_tracked                               ()
 86  box_head.conv5.weight                                              (1, 48, 1, 1)
 87  box_head.conv5.bias                                                (1,)

In [113]:
ONLINE_CKPT = (
    MIXSORT_DIR
    / "pretrained"
    / "MixFormerOnlineScore.pth.tar"
)

print("Checkpoint:")
print(ONLINE_CKPT)
print("Exists:", ONLINE_CKPT.exists())

if ONLINE_CKPT.exists():
    print(f"Size: {ONLINE_CKPT.stat().st_size / (1024**2):.2f} MB")

Checkpoint:
/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/pretrained/MixFormerOnlineScore.pth.tar
Exists: True
Size: 439.43 MB

In [114]:
ONLINE_CKPT = (
    MIXSORT_DIR
    / "pretrained"
    / "MixFormerOnlineScore.pth.tar"
)

cfg.MODEL.BACKBONE.PRETRAINED = True
cfg.MODEL.BACKBONE.PRETRAINED_PATH = str(ONLINE_CKPT)

print("Configured checkpoint:")
print(cfg.MODEL.BACKBONE.PRETRAINED_PATH)
print("Exists:", ONLINE_CKPT.exists())

Configured checkpoint:
/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/pretrained/MixFormerOnlineScore.pth.tar
Exists: True

In [115]:
from lib.config.mixformer_deit.config import cfg, update_config_from_file

BASELINE_CONFIG = (
    MIXSORT_DIR
    / "MixViT"
    / "experiments"
    / "mixformer_deit"
    / "baseline.yaml"
)

update_config_from_file(str(BASELINE_CONFIG))

# Override the relative checkpoint path with our actual absolute path
cfg.MODEL.BACKBONE.PRETRAINED = True
cfg.MODEL.BACKBONE.PRETRAINED_PATH = str(ONLINE_CKPT)

print("Baseline configuration loaded")
print("VIT_TYPE:", cfg.MODEL.VIT_TYPE)
print("HIDDEN_DIM:", cfg.MODEL.HIDDEN_DIM)
print("Checkpoint:", cfg.MODEL.BACKBONE.PRETRAINED_PATH)

Baseline configuration loaded
VIT_TYPE: deit3_4layers
HIDDEN_DIM: 768
Checkpoint: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/pretrained/MixFormerOnlineScore.pth.tar

In [116]:
import time

print("Building MixFormer with MixFormerOnlineScore...")
t0 = time.time()

network = build_mixformer(cfg)

elapsed = time.time() - t0

print(f"\nBuild finished in {elapsed:.2f} seconds")
print("Model type:", type(network))

Building MixFormer with MixFormerOnlineScore...
Warning: Pretrained CVT weights are not loaded
head channel: 384

Build finished in 8.00 seconds
Model type: <class 'lib.models.mixformer.mixformer.MixFormer'>

In [117]:
import torch

print("Loading MixFormerOnlineScore directly...")

online_checkpoint = torch.load(
    str(ONLINE_CKPT),
    map_location="cpu",
    weights_only=False
)

print("Loaded successfully!")
print("Type:", type(online_checkpoint))

if isinstance(online_checkpoint, dict):
    print("Keys:")
    print(list(online_checkpoint.keys()))

Loading MixFormerOnlineScore directly...
Loaded successfully!
Type: <class 'dict'>
Keys:
['epoch', 'actor_type', 'net_type', 'net', 'net_info', 'constructor', 'optimizer', 'stats', 'settings']

In [118]:
online_net = online_checkpoint["net"]

print("Number of tensors:", len(online_net))
print()

for i, (key, value) in enumerate(online_net.items()):
    if i >= 20:
        break

    shape = tuple(value.shape) if hasattr(value, "shape") else type(value)
    print(f"{i:2d}  {key:65s} {shape}")

Number of tensors: 155

 0  backbone.cls_token                                                (1, 1, 768)
 1  backbone.pos_embed                                                (1, 197, 768)
 2  backbone.pos_embed_s                                              (1, 324, 768)
 3  backbone.pos_embed_t                                              (1, 64, 768)
 4  backbone.patch_embed.proj.weight                                  (768, 3, 16, 16)
 5  backbone.patch_embed.proj.bias                                    (768,)
 6  backbone.blocks.0.norm1.weight                                    (768,)
 7  backbone.blocks.0.norm1.bias                                      (768,)
 8  backbone.blocks.0.attn.qkv.weight                                 (2304, 768)
 9  backbone.blocks.0.attn.qkv.bias                                   (2304,)
10  backbone.blocks.0.attn.proj.weight                                (768, 768)
11  backbone.blocks.0.attn.proj.bias                                  (768,)
12  backbone.blocks.0.ls1.gamma                                       (768,)
13  backbone.blocks.0.norm2.weight                                    (768,)
14  backbone.blocks.0.norm2.bias                                      (768,)
15  backbone.blocks.0.mlp.fc1.weight                                  (3072, 768)
16  backbone.blocks.0.mlp.fc1.bias                                    (3072,)
17  backbone.blocks.0.mlp.fc2.weight                                  (768, 3072)
18  backbone.blocks.0.mlp.fc2.bias                                    (768,)
19  backbone.blocks.0.ls2.gamma                                       (768,)

In [119]:
import re

SEARCH_ROOT = MIXSORT_DIR / "MixViT" / "lib"

patterns = [
    "checkpoint['net']",
    'checkpoint["net"]',
    "load_state_dict",
]

for file in SEARCH_ROOT.rglob("*.py"):
    text = file.read_text(encoding="utf-8", errors="ignore")

    if "load_state_dict" in text and (
        "checkpoint" in text or "ckpt" in text
    ):
        print("\nFILE:", file)

        for i, line in enumerate(text.splitlines(), start=1):
            if "load_state_dict" in line:
                print(f"{i}: {line.strip()}")

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models/mixformer/mixformer.py
754: missing_keys, unexpected_keys = msvit.load_state_dict(ckpt, strict=False)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models/mixformer/mixformer_online.py
810: missing_keys, unexpected_keys = msvit.load_state_dict(ckpt, strict=False)
913: missing_keys, unexpected_keys = model.load_state_dict(ckpt['net'], strict=False)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models/mixformer/mixformer_vit_multi_stage_ablation.py
662: missing_keys, unexpected_keys = msvit.load_state_dict(ckpt, strict=False)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models/mixformer_vit/mixformerpp_vit_multi_score.py
324: missing_keys, unexpected_keys = vit.load_state_dict(new_dict, strict=False)
448: # missing_keys, unexpected_keys = model.load_state_dict(ckpt, strict=False)
458: missing_keys, unexpected_keys = model.load_state_dict(ckpt['net'], strict=False)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models/mixformer_vit/mixformerpp_vit_multi_score_seq_cp.py
329: missing_keys, unexpected_keys = vit.load_state_dict(new_dict, strict=False)
465: missing_keys, unexpected_keys = model.load_state_dict(ckpt['net'], strict=False)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models/mixformer_vit/mixformer_deit.py
287: missing_keys, unexpected_keys = model.load_state_dict(new_dict, strict=False)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models/mixformer_vit/mixformer_deit_multi_score.py
338: missing_keys, unexpected_keys = vit.load_state_dict(new_dict, strict=False)
462: # missing_keys, unexpected_keys = model.load_state_dict(ckpt, strict=False)
472: missing_keys, unexpected_keys = model.load_state_dict(ckpt['net'], strict=False)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models/mixformer_vit/mixformer_sparse_vit.py
292: missing_keys, unexpected_keys = vit.load_state_dict(new_dict, strict=False)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models/mixformer_vit/mixformer_vit.py
254: missing_keys, unexpected_keys = vit.load_state_dict(new_dict, strict=False)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models/mixformer_vit/mixformer_vit_add_decoder.py
359: missing_keys, unexpected_keys = vit.load_state_dict(new_dict, strict=False)
460: missing_keys, unexpected_keys = model.load_state_dict(ckpt['net'], strict=False)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models/mixformer_vit/mixformer_vit_decoder.py
280: missing_keys, unexpected_keys = vit.load_state_dict(new_dict, strict=False)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models/mixformer_vit/mixformer_vit_decoder_multi_score.py
359: missing_keys, unexpected_keys = vit.load_state_dict(new_dict, strict=False)
483: # missing_keys, unexpected_keys = model.load_state_dict(ckpt, strict=False)
493: #         missing_keys, unexpected_keys = model.load_state_dict(ckpt['net'], strict=False)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models/mixformer_vit/mixformer_vit_learn_pos.py
246: missing_keys, unexpected_keys = vit.load_state_dict(new_dict, strict=False)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models/mixformer_vit/mixformer_vit_multi.py
220: missing_keys, unexpected_keys = vit.load_state_dict(new_dict, strict=False)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models/mixformer_vit/mixformer_vit_multi_score.py
303: missing_keys, unexpected_keys = vit.load_state_dict(new_dict, strict=False)
407: missing_keys, unexpected_keys = model.load_state_dict(ckpt['net'], strict=False)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models/mixformer_vit/mixformer_vit_window.py
280: missing_keys, unexpected_keys = vit.load_state_dict(new_dict, strict=False)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/test/tracker/mixformer.py
17: network.load_state_dict(torch.load(self.params.checkpoint, map_location='cpu')['net'], strict=True)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/test/tracker/mixformerpp_vit.py
17: network.load_state_dict(torch.load(self.params.checkpoint, map_location='cpu')['net'], strict=True)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/test/tracker/mixformerpp_vit_cp.py
17: network.load_state_dict(torch.load(self.params.checkpoint, map_location='cpu')['net'], strict=True)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/test/tracker/mixformerpp_vit_online.py
17: network.load_state_dict(torch.load(self.params.checkpoint, map_location='cpu')['net'], strict=True)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/test/tracker/mixformer_deit_multi.py
17: network.load_state_dict(torch.load(self.params.checkpoint, map_location='cpu')['net'], strict=True)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/test/tracker/mixformer_online.py
17: network.load_state_dict(torch.load(self.params.checkpoint, map_location='cpu')['net'], strict=True)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/test/tracker/mixformer_vit.py
17: network.load_state_dict(torch.load(self.params.checkpoint, map_location='cpu')['net'], strict=True)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/test/tracker/mixformer_vit_decoder.py
17: network.load_state_dict(torch.load(self.params.checkpoint, map_location='cpu')['net'], strict=True)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/test/tracker/mixformer_vit_learn_pos.py
17: network.load_state_dict(torch.load(self.params.checkpoint, map_location='cpu')['net'], strict=True)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/test/tracker/mixformer_vit_online.py
17: network.load_state_dict(torch.load(self.params.checkpoint, map_location='cpu')['net'], strict=True)

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/train/trainers/base_trainer.py
79: self.load_state_dict(directory)
82: self.load_state_dict(directory_teacher, distill=True)
203: net.load_state_dict(checkpoint_dict[key])
205: self.optimizer.load_state_dict(checkpoint_dict[key])
224: def load_state_dict(self, checkpoint=None, distill=False):
262: missing_k, unexpected_k = net.load_state_dict(checkpoint_dict["net"], strict=False)

In [120]:
ONLINE_MODEL_FILE = (
    MIXSORT_DIR
    / "MixViT"
    / "lib"
    / "models"
    / "mixformer"
    / "mixformer_online.py"
)

text_online = ONLINE_MODEL_FILE.read_text(
    encoding="utf-8",
    errors="ignore"
)

for i, line in enumerate(text_online.splitlines(), start=1):
    if "def build_" in line or "load_state_dict" in line:
        print(f"{i}: {line}")

810:             missing_keys, unexpected_keys = msvit.load_state_dict(ckpt, strict=False)
898: def build_mixformer_online_score(cfg, settings=None, train=True):
913:             missing_keys, unexpected_keys = model.load_state_dict(ckpt['net'], strict=False)

In [121]:
lines = text_online.splitlines()

print("\n".join(
    f"{i+1}: {lines[i]}"
    for i in range(890, 921)
))

891:             outputs_coord = box_xyxy_to_cxcywh(self.box_head(search))
892:             outputs_coord_new = outputs_coord.view(b, 1, 4)
893:             out = {'pred_boxes': outputs_coord_new}
894:             return out, outputs_coord_new
895:         else:
896:             raise KeyError
897:
898: def build_mixformer_online_score(cfg, settings=None, train=True):
899:     backbone = get_mixformer_online_model(cfg)  # backbone without positional encoding and attention mask
900:     box_head = build_box_head(cfg)  # a simple corner head
901:     score_branch = ScoreDecoder(cfg, pool_size=4) # the proposed score prediction module (SPM)
902:     model = MixFormerOnlineScore(
903:         backbone,
904:         box_head,
905:         score_branch,
906:         head_type=cfg.MODEL.HEAD_TYPE
907:     )
908:
909:     if cfg.MODEL.PRETRAINED_STAGE1 and train:
910:         try:
911:             ckpt_path = settings.stage1_model
912:             ckpt = torch.load(ckpt_path, map_location='cpu')
913:             missing_keys, unexpected_keys = model.load_state_dict(ckpt['net'], strict=False)
914:             if is_main_process():
915:                 print("missing keys:", missing_keys)
916:                 print("unexpected keys:", unexpected_keys)
917:                 print("Loading pretrained mixformer weights done.")
918:         except:
919:             print("Warning: Pretrained mixformer weights are not loaded")
920:
921:     return model

In [122]:
# Find the online backbone builder
for i, line in enumerate(text_online.splitlines(), start=1):
    if "def get_mixformer_online_model" in line:
        print(f"Found at line {i}")
        print("\n".join(
            f"{j+1}: {text_online.splitlines()[j]}"
            for j in range(i-1, min(len(text_online.splitlines()), i+45))
        ))

Found at line 796
796: def get_mixformer_online_model(config, **kwargs):
797:     msvit_spec = config.MODEL.BACKBONE
798:     msvit = ConvolutionalVisionTransformer(
799:         in_chans=3,
800:         act_layer=QuickGELU,
801:         norm_layer=partial(LayerNorm, eps=1e-5),
802:         init=getattr(msvit_spec, 'INIT', 'trunc_norm'),
803:         spec=msvit_spec
804:     )
805:
806:     if config.MODEL.BACKBONE.PRETRAINED:
807:         try:
808:             ckpt_path = config.MODEL.BACKBONE.PRETRAINED_PATH
809:             ckpt = torch.load(ckpt_path, map_location='cpu')
810:             missing_keys, unexpected_keys = msvit.load_state_dict(ckpt, strict=False)
811:             if is_main_process():
812:                 print("missing keys:", missing_keys)
813:                 print("unexpected keys:", unexpected_keys)
814:                 print("Loading pretrained CVT done.")
815:         except:
816:             print("Warning: Pretrained CVT weights are not loaded")
817:
818:     return msvit
819:
820: class MixFormerOnlineScore(nn.Module):
821:     """ Mixformer tracking with score prediction module, whcih jointly perform feature extraction and interaction. """
822:     def __init__(self, backbone, box_head, score_branch=None, head_type="CORNER"):
823:         """ Initializes the model.
824:         """
825:         super().__init__()
826:         self.backbone = backbone
827:         self.box_head = box_head
828:         self.score_branch = score_branch
829:         self.head_type = head_type
830:
831:     def forward(self, template, online_template, search, run_score_head=True, gt_bboxes=None):
832:         # search: (b, c, h, w)
833:         if template.dim() == 5:
834:             template = template.squeeze(0)
835:         if online_template.dim() == 5:
836:             template = online_template.squeeze(0)
837:         if search.dim() == 5:
838:             search = search.squeeze(0)
839:         template, search = self.backbone(template, online_template, search)
840:         # search shape: (b, 384, 20, 20)
841:         # Forward the corner head and score head

In [123]:
SEARCH_ROOT = MIXSORT_DIR / "MixViT"

for file in SEARCH_ROOT.rglob("*.py"):
    text_file = file.read_text(encoding="utf-8", errors="ignore")

    if "NLAYER_HEAD" in text_file:
        print(f"\nFILE: {file}")

        for i, line in enumerate(text_file.splitlines(), start=1):
            if "NLAYER_HEAD" in line:
                print(f"{i}: {line.strip()}")

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/config/mixformer_online/config.py
43: cfg.MODEL.NLAYER_HEAD = 3

FILE: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models/mixformer/mixformer_online.py
743: self.score_head = MLP(cfg.MODEL.HIDDEN_DIM, cfg.MODEL.HIDDEN_DIM, 1, cfg.MODEL.NLAYER_HEAD)

In [124]:
cfg.MODEL.NLAYER_HEAD = 3

print("NLAYER_HEAD:", cfg.MODEL.NLAYER_HEAD)
print("HIDDEN_DIM:", cfg.MODEL.HIDDEN_DIM)
print("HEAD_TYPE:", cfg.MODEL.HEAD_TYPE)

NLAYER_HEAD: 3
HIDDEN_DIM: 768
HEAD_TYPE: Heatmap

In [125]:
DEIT_FILES = list((MIXSORT_DIR / "MixViT/lib/models").rglob("*deit*.py"))

for f in DEIT_FILES:
    print(f)

/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models/mixformer_vit/mixformer_deit.py
/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/MixViT/lib/models/mixformer_vit/mixformer_deit_multi_score.py

In [126]:
for file in [
    MIXSORT_DIR / "MixViT/lib/models/mixformer_vit/mixformer_deit.py",
    MIXSORT_DIR / "MixViT/lib/models/mixformer_vit/mixformer_deit_multi_score.py",
]:
    print(f"\n{'='*80}")
    print(file.name)
    print(f"{'='*80}")

    lines = file.read_text(encoding="utf-8", errors="ignore").splitlines()

    for i, line in enumerate(lines, start=1):
        if any(x in line for x in [
            "class MixFormer",
            "def build",
            "def get_mixformer",
            "load_state_dict",
            "VIT_TYPE",
        ]):
            print(f"{i}: {line.strip()}")

================================================================================
mixformer_deit.py
================================================================================
197: def get_mixformer_vit(config):
200: if config.MODEL.VIT_TYPE == 'large_patch16':
205: elif config.MODEL.VIT_TYPE == 'base_patch16':
210: elif config.MODEL.VIT_TYPE == 'deit3_4layers':
216: raise KeyError(f"VIT_TYPE shoule set to 'large_patch16' or 'base_patch16'")
221: class MixFormer(nn.Module):
271: def build_mixformer_deit(cfg):
287: missing_keys, unexpected_keys = model.load_state_dict(new_dict, strict=False)

================================================================================
mixformer_deit_multi_score.py
================================================================================
287: def get_mixformer_vit(config, train):
290: if config.MODEL.VIT_TYPE == 'large_patch16':
295: elif config.MODEL.VIT_TYPE == 'base_patch16':
301: raise KeyError(f"VIT_TYPE shoule set to 'large_patch16' or 'base_patch16'")
338: missing_keys, unexpected_keys = vit.load_state_dict(new_dict, strict=False)
349: class MixFormerOnlineScore(nn.Module):
427: def build_mixformer_deit_multi_score(cfg, settings=None, train=True):
462: # missing_keys, unexpected_keys = model.load_state_dict(ckpt, strict=False)
472: missing_keys, unexpected_keys = model.load_state_dict(ckpt['net'], strict=False)

In [127]:
from pathlib import Path

file = MIXSORT_DIR / "MixViT/lib/models/mixformer_vit/mixformer_deit.py"
lines = file.read_text(encoding="utf-8", errors="ignore").splitlines()

for start, end in [(197, 220), (271, 290)]:
    print(f"\n--- lines {start}-{end} ---")
    for i in range(start, end + 1):
        print(f"{i}: {lines[i-1]}")

--- lines 197-220 ---
197: def get_mixformer_vit(config):
198:     img_size_s = config.DATA.SEARCH.SIZE
199:     img_size_t = config.DATA.TEMPLATE.SIZE
200:     if config.MODEL.VIT_TYPE == 'large_patch16':
201:         vit = VisionTransformer(
202:             img_size_s=img_size_s, img_size_t=img_size_t,
203:             patch_size=16, embed_dim=1024, depth=24, num_heads=16, mlp_ratio=4, qkv_bias=True,
204:             norm_layer=partial(nn.LayerNorm, eps=1e-6), drop_path_rate=0.1)
205:     elif config.MODEL.VIT_TYPE == 'base_patch16':
206:         vit = VisionTransformer(
207:             img_size_s=img_size_s, img_size_t=img_size_t,
208:             patch_size=16, embed_dim=768, depth=12, num_heads=12, mlp_ratio=4, qkv_bias=True,
209:             norm_layer=partial(nn.LayerNorm, eps=1e-6), drop_path_rate=0.1)
210:     elif config.MODEL.VIT_TYPE == 'deit3_4layers':
211:         vit = VisionTransformer(
212:             img_size_s=img_size_s, img_size_t=img_size_t,
213:             patch_size=16, embed_dim=768, depth=4, num_heads=12, mlp_ratio=4, qkv_bias=True,
214:             norm_layer=partial(nn.LayerNorm, eps=1e-6), drop_path_rate=0.1)
215:     else:
216:         raise KeyError(f"VIT_TYPE shoule set to 'large_patch16' or 'base_patch16'")
217:
218:     return vit
219:
220:

--- lines 271-290 ---
271: def build_mixformer_deit(cfg):
272:     backbone = get_mixformer_vit(cfg)  # backbone without positional encoding and attention mask
273:     box_head = build_box_head(cfg)  # a simple corner head
274:     model = MixFormer(
275:         backbone,
276:         box_head,
277:         head_type=cfg.MODEL.HEAD_TYPE
278:     )
279:
280:     if cfg.MODEL.BACKBONE.PRETRAINED:
281:         ckpt_path = cfg.MODEL.BACKBONE.PRETRAINED_PATH
282:         ckpt = torch.load(ckpt_path, map_location='cpu')['net']
283:         new_dict = {}
284:         for k, v in ckpt.items():
285:             if 'pos_embed' not in k and 'mask_token' not in k:
286:                 new_dict[k] = v
287:         missing_keys, unexpected_keys = model.load_state_dict(new_dict, strict=False)
288:         if is_main_process():
289:             print("missing keys:", missing_keys)
290:             print("unexpected keys:", unexpected_keys)

In [128]:
# Use the exact pretrained MixFormer checkpoint
cfg.MODEL.VIT_TYPE = "deit3_4layers"
cfg.MODEL.BACKBONE.PRETRAINED = True
cfg.MODEL.BACKBONE.PRETRAINED_PATH = str(
    MIXSORT_DIR / "pretrained/MixFormerOnlineScore.pth.tar"
)

print("VIT_TYPE:", cfg.MODEL.VIT_TYPE)
print("Checkpoint:", cfg.MODEL.BACKBONE.PRETRAINED_PATH)

VIT_TYPE: deit3_4layers
Checkpoint: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/pretrained/MixFormerOnlineScore.pth.tar

In [129]:
import numpy as np

# Compatibility for old MixSort code with NumPy 2.x
if not hasattr(np, "float"):
    np.float = float

print("np.float compatibility:", np.float)

np.float compatibility: <class 'float'>

In [130]:
import torch

_original_torch_load = torch.load

def torch_load_legacy(*args, **kwargs):
    kwargs.setdefault("weights_only", False)
    return _original_torch_load(*args, **kwargs)

torch.load = torch_load_legacy

print("torch.load patched: weights_only=False")

torch.load patched: weights_only=False

In [137]:
from lib.models.mixformer_vit.mixformer_deit import build_mixformer_deit

print("build_mixformer_deit imported successfully")

build_mixformer_deit imported successfully

In [138]:
model = build_mixformer_deit(cfg)

print("\nModel loaded successfully.")
print("Parameters:", sum(p.numel() for p in model.parameters()))

head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t', 'box_head.conv1.0.weight', 'box_head.conv1.0.bias', 'box_head.conv1.1.weight', 'box_head.conv1.1.bias', 'box_head.conv1.1.running_mean', 'box_head.conv1.1.running_var', 'box_head.conv2.0.weight', 'box_head.conv2.0.bias', 'box_head.conv2.1.weight', 'box_head.conv2.1.bias', 'box_head.conv2.1.running_mean', 'box_head.conv2.1.running_var', 'box_head.conv3.0.weight', 'box_head.conv3.0.bias', 'box_head.conv3.1.weight', 'box_head.conv3.1.bias', 'box_head.conv3.1.running_mean', 'box_head.conv3.1.running_var', 'box_head.conv4.0.weight', 'box_head.conv4.0.bias', 'box_head.conv4.1.weight', 'box_head.conv4.1.bias', 'box_head.conv4.1.running_mean', 'box_head.conv4.1.running_var', 'box_head.conv5.weight', 'box_head.conv5.bias']
unexpected keys: ['score_branch.score_token', 'score_branch.score_head.layers.0.weight', 'score_branch.score_head.layers.0.bias', 'score_branch.score_head.layers.1.weight', 'score_branch.score_head.layers.1.bias', 'score_branch.score_head.layers.2.weight', 'score_branch.score_head.layers.2.bias', 'score_branch.proj_q.0.weight', 'score_branch.proj_q.0.bias', 'score_branch.proj_q.1.weight', 'score_branch.proj_q.1.bias', 'score_branch.proj_k.0.weight', 'score_branch.proj_k.0.bias', 'score_branch.proj_k.1.weight', 'score_branch.proj_k.1.bias', 'score_branch.proj_v.0.weight', 'score_branch.proj_v.0.bias', 'score_branch.proj_v.1.weight', 'score_branch.proj_v.1.bias', 'score_branch.proj.0.weight', 'score_branch.proj.0.bias', 'score_branch.proj.1.weight', 'score_branch.proj.1.bias', 'score_branch.norm1.weight', 'score_branch.norm1.bias', 'score_branch.norm2.0.weight', 'score_branch.norm2.0.bias', 'score_branch.norm2.1.weight', 'score_branch.norm2.1.bias', 'backbone.blocks.0.ls1.gamma', 'backbone.blocks.0.ls2.gamma', 'backbone.blocks.1.ls1.gamma', 'backbone.blocks.1.ls2.gamma', 'backbone.blocks.2.ls1.gamma', 'backbone.blocks.2.ls2.gamma', 'backbone.blocks.3.ls1.gamma', 'backbone.blocks.3.ls2.gamma', 'box_head.conv1_tl.0.weight', 'box_head.conv1_tl.0.bias', 'box_head.conv1_tl.1.weight', 'box_head.conv1_tl.1.bias', 'box_head.conv1_tl.1.running_mean', 'box_head.conv1_tl.1.running_var', 'box_head.conv1_tl.1.num_batches_tracked', 'box_head.conv2_tl.0.weight', 'box_head.conv2_tl.0.bias', 'box_head.conv2_tl.1.weight', 'box_head.conv2_tl.1.bias', 'box_head.conv2_tl.1.running_mean', 'box_head.conv2_tl.1.running_var', 'box_head.conv2_tl.1.num_batches_tracked', 'box_head.conv3_tl.0.weight', 'box_head.conv3_tl.0.bias', 'box_head.conv3_tl.1.weight', 'box_head.conv3_tl.1.bias', 'box_head.conv3_tl.1.running_mean', 'box_head.conv3_tl.1.running_var', 'box_head.conv3_tl.1.num_batches_tracked', 'box_head.conv4_tl.0.weight', 'box_head.conv4_tl.0.bias', 'box_head.conv4_tl.1.weight', 'box_head.conv4_tl.1.bias', 'box_head.conv4_tl.1.running_mean', 'box_head.conv4_tl.1.running_var', 'box_head.conv4_tl.1.num_batches_tracked', 'box_head.conv5_tl.weight', 'box_head.conv5_tl.bias', 'box_head.conv1_br.0.weight', 'box_head.conv1_br.0.bias', 'box_head.conv1_br.1.weight', 'box_head.conv1_br.1.bias', 'box_head.conv1_br.1.running_mean', 'box_head.conv1_br.1.running_var', 'box_head.conv1_br.1.num_batches_tracked', 'box_head.conv2_br.0.weight', 'box_head.conv2_br.0.bias', 'box_head.conv2_br.1.weight', 'box_head.conv2_br.1.bias', 'box_head.conv2_br.1.running_mean', 'box_head.conv2_br.1.running_var', 'box_head.conv2_br.1.num_batches_tracked', 'box_head.conv3_br.0.weight', 'box_head.conv3_br.0.bias', 'box_head.conv3_br.1.weight', 'box_head.conv3_br.1.bias', 'box_head.conv3_br.1.running_mean', 'box_head.conv3_br.1.running_var', 'box_head.conv3_br.1.num_batches_tracked', 'box_head.conv4_br.0.weight', 'box_head.conv4_br.0.bias', 'box_head.conv4_br.1.weight', 'box_head.conv4_br.1.bias', 'box_head.conv4_br.1.running_mean', 'box_head.conv4_br.1.running_var', 'box_head.conv4_br.1.num_batches_tracked', 'box_head.conv5_br.weight', 'box_head.conv5_br.bias']
Loading pretrained ViT done.

Model loaded successfully.
Parameters: 33570185

In [139]:
import inspect

model = model.cuda().eval()

print("Device:", next(model.parameters()).device)
print("\nForward signature:")
print(inspect.signature(model.forward))

Device: cuda:0

Forward signature:
(template, search)

In [140]:
import torch

template = torch.randn(1, 3, cfg.DATA.TEMPLATE.SIZE, cfg.DATA.TEMPLATE.SIZE, device="cuda")
search = torch.randn(1, 3, cfg.DATA.SEARCH.SIZE, cfg.DATA.SEARCH.SIZE, device="cuda")

with torch.no_grad():
    output = model(template, search)

print("Template:", template.shape)
print("Search:", search.shape)
print("Output type:", type(output))

if isinstance(output, dict):
    print("Output keys:", output.keys())
else:
    print("Output shape:", getattr(output, "shape", None))

Template: torch.Size([1, 3, 96, 96])
Search: torch.Size([1, 3, 224, 224])
Output type: <class 'torch.Tensor'>
Output shape: torch.Size([1, 1, 14, 14])

In [134]:
!pip install lmdb

Requirement already satisfied: lmdb in /home/jatin/tf312/lib/python3.12/site-packages (2.3.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [142]:
import sys

# Add MixSort root so Python can find its local yolox package
if str(MIXSORT_DIR) not in sys.path:
    sys.path.insert(0, str(MIXSORT_DIR))

print("MixSort root:", MIXSORT_DIR)
print("In sys.path:", str(MIXSORT_DIR) in sys.path)

from yolox.mixsort_tracker.mixsort_tracker import MIXTracker

print("MIXTracker imported successfully")

MixSort root: /mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort
In sys.path: True
MIXTracker imported successfully

In [143]:
tracker_file = MIXSORT_DIR / "yolox/mixsort_tracker/mixsort_tracker.py"
lines = tracker_file.read_text(encoding="utf-8", errors="ignore").splitlines()

for i, line in enumerate(lines, start=1):
    if "args." in line:
        print(f"{i}: {line.strip()}")

183: # self.det_thresh = args.track_thresh
184: self.det_thresh = args.track_thresh + 0.1
185: self.buffer_size = int(frame_rate / 30.0 * args.track_buffer)
190: self.alpha = args.alpha
191: self.radius = args.radius
192: self.iou_thresh = args.iou_thresh
197: self.settings.script_name = args.script
198: self.settings.config_name = args.config
203: prj_dir, f"experiments/{args.script}/{args.config}.yaml"
214: self.network = network.cuda(torch.device(f"cuda:{args.local_rank}"))
225: # self.det_thresh = args.track_thresh
226: self.det_thresh = args.track_thresh + 0.1
227: self.buffer_size = int(frame_rate / 30.0 * args.track_buffer)
232: self.alpha = args.alpha
233: self.radius = args.radius
234: self.iou_thresh = args.iou_thresh
377: # if iou.min()<self.args.fuse_iou_thresh:
384: #         if iou[i][j]>self.args.fuse_iou_thresh and vit[i][j]<self.args.fuse_vit_thresh:
416: remain_inds = scores > self.args.track_thresh
418: inds_high = scores < self.args.track_thresh
449: # if not self.args.mot20:
452: dists, thresh=self.args.match_thresh
515: # if not self.args.mot20:

In [144]:
from types import SimpleNamespace

args = SimpleNamespace(
    track_thresh=0.6,
    track_buffer=30,
    match_thresh=0.9,
    iou_thresh=0.3,
    alpha=0.6,
    radius=0,
    script="mixformer_deit",
    config="track",
    local_rank=0,
    mot20=False,
)

print(args)

namespace(track_thresh=0.6, track_buffer=30, match_thresh=0.9, iou_thresh=0.3, alpha=0.6, radius=0, script='mixformer_deit', config='track', local_rank=0, mot20=False)

In [145]:
track_cfg = MIXSORT_DIR / "MixViT/experiments/mixformer_deit/track.yaml"

text = track_cfg.read_text(encoding="utf-8")

for i, line in enumerate(text.splitlines(), start=1):
    if "PRETRAINED_PATH" in line:
        print(f"{i}: {line}")

38:     PRETRAINED_PATH: '/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/pretrained/MixFormer_sports_train.pth.tar'

In [146]:
track_cfg = MIXSORT_DIR / "MixViT/experiments/mixformer_deit/track.yaml"

old_path = "pretrained/MixFormer_sports_train.pth.tar"
new_path = str(MIXSORT_DIR / "pretrained/MixFormer_sports_train.pth.tar")

text = track_cfg.read_text(encoding="utf-8")

assert old_path in text, "Expected checkpoint path was not found."

text = text.replace(old_path, new_path)

track_cfg.write_text(text, encoding="utf-8")

print("Updated checkpoint path to:")
print(new_path)

Updated checkpoint path to:
/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/pretrained/MixFormer_sports_train.pth.tar

In [148]:
track_cfg = MIXSORT_DIR / "MixViT/experiments/mixformer_deit/track.yaml"

text = track_cfg.read_text(encoding="utf-8")

for line in text.splitlines():
    if "PRETRAINED_PATH" in line:
        print("Config line:")
        print(line)

        path = line.split(":", 1)[1].strip().strip("'\"")
        checkpoint_path = Path(path)

        print("\nParsed path:")
        print(checkpoint_path)

        print("\nExists exactly as written:", checkpoint_path.exists())

        if not checkpoint_path.is_absolute():
            checkpoint_path = track_cfg.parent / checkpoint_path
            print("Resolved relative to config:", checkpoint_path)
            print("Exists:", checkpoint_path.exists())

Config line:
    PRETRAINED_PATH: '/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort//mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/pretrained/MixFormer_sports_train.pth.tar'

Parsed path:
/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/pretrained/MixFormer_sports_train.pth.tar

Exists exactly as written: False

In [149]:
from pathlib import Path

track_cfg = MIXSORT_DIR / "MixViT/experiments/mixformer_deit/track.yaml"

correct_checkpoint = MIXSORT_DIR / "pretrained/MixFormer_sports_train.pth.tar"

text = track_cfg.read_text(encoding="utf-8")

lines = text.splitlines()

for i, line in enumerate(lines):
    if "PRETRAINED_PATH:" in line:
        lines[i] = f"    PRETRAINED_PATH: '{correct_checkpoint}'"
        break
else:
    raise RuntimeError("PRETRAINED_PATH not found")

track_cfg.write_text("\n".join(lines) + "\n", encoding="utf-8")

print("Fixed path:")
print(correct_checkpoint)
print("Exists:", correct_checkpoint.exists())

Fixed path:
/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/pretrained/MixFormer_sports_train.pth.tar
Exists: True

In [150]:
tracker = MIXTracker(args, frame_rate=25)

print("MIXTracker initialized successfully.")
print("Tracker:", type(tracker).__name__)

head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MIXTracker initialized successfully.
Tracker: MIXTracker

In [152]:
from pathlib import Path

SEQ_DIR = (
    MIXSORT_DIR.parent.parent.parent
    / "datasets/football/benchmarks/sportsmot/extracted/val"
    / "v_2QhNRucNC7E_c017"
)

print("Sequence directory:")
print(SEQ_DIR)

print("\nExists:", SEQ_DIR.exists())

print("\nFirst 30 entries:")
for x in sorted(SEQ_DIR.iterdir())[:30]:
    print(x.name)

Sequence directory:
/mnt/d/My Projects/AthletiQ/AthletiQ/datasets/football/benchmarks/sportsmot/extracted/val/v_2QhNRucNC7E_c017

Exists: True

First 30 entries:
gt
img1
seqinfo.ini

In [154]:
import cv2
import numpy as np
import torch
import inspect
from pathlib import Path

In [155]:

IMG_DIR = SEQ_DIR / "img1"

frames = sorted(IMG_DIR.glob("*.jpg"))

print("Image directory:", IMG_DIR)
print("Frames:", len(frames))
print("First 5:", [f.name for f in frames[:5]])

frame = cv2.imread(str(frames[0]))
print("Frame shape:", frame.shape)

Image directory: /mnt/d/My Projects/AthletiQ/AthletiQ/datasets/football/benchmarks/sportsmot/extracted/val/v_2QhNRucNC7E_c017/img1
Frames: 450
First 5: ['000001.jpg', '000002.jpg', '000003.jpg', '000004.jpg', '000005.jpg']
Frame shape: (720, 1280, 3)

In [156]:
from ultralytics import YOLO
import numpy as np

detector = YOLO(
    str(MIXSORT_DIR.parent.parent / "models/football_player_detector.pt")
)

frame = cv2.imread(str(frames[0]))

result = detector.predict(
    frame,
    conf=0.40,
    iou=0.40,
    device=0,
    verbose=False
)[0]

boxes = result.boxes.xyxy.cpu().numpy()
scores = result.boxes.conf.cpu().numpy()

output_results = np.column_stack([boxes, scores]).astype(np.float32)

print("Detections:", len(output_results))
print("Shape:", output_results.shape)
print("First detection:", output_results[0] if len(output_results) else None)

Detections: 22
Shape: (22, 5)
First detection: [     776.61      385.22      816.67      467.82     0.95881]

In [157]:
if not hasattr(np, "int"):
    np.int = int

print("NumPy compatibility aliases:")
print("np.float →", np.float)
print("np.int   →", np.int)

NumPy compatibility aliases:
np.float → <class 'float'>
np.int   → <class 'int'>

In [158]:
img_info = (frame.shape[0], frame.shape[1])
img_size = (frame.shape[1], frame.shape[0])

online_targets = tracker.update(
    output_results,
    img_info,
    img_size,
    frame
)

print("Active MixSort targets:", len(online_targets))

for t in online_targets[:10]:
    print(
        "track_id:", t.track_id,
        "tlwh:", np.round(t.tlwh, 2),
        "score:", round(float(t.score), 4)
    )

Active MixSort targets: 20
track_id: 1 tlwh: [     1380.6      684.83       71.22      146.85] score: 0.9588
track_id: 2 tlwh: [     1695.3      427.33       69.35      118.76] score: 0.9553
track_id: 3 tlwh: [     1908.5      538.98       48.77      129.48] score: 0.9519
track_id: 4 tlwh: [     905.64      816.65        62.6      161.12] score: 0.9503
track_id: 5 tlwh: [     898.48      673.43       54.77      153.37] score: 0.9436
track_id: 6 tlwh: [     1552.2      708.03       60.64      147.27] score: 0.9405
track_id: 7 tlwh: [     1649.9      369.04       50.48      104.03] score: 0.9369
track_id: 8 tlwh: [     1559.4      370.61       44.36      112.36] score: 0.9345
track_id: 9 tlwh: [      350.5       555.9       90.34      117.27] score: 0.9345
track_id: 10 tlwh: [      13.18      834.85       69.99      186.93] score: 0.9342

In [159]:
print("Detection scores:")
print(np.round(scores, 4))

print("\nScore statistics:")
print("min :", scores.min())
print("max :", scores.max())
print("mean:", scores.mean())
print(">0.7:", np.sum(scores > 0.7))
print(">0.6:", np.sum(scores > 0.6))

Detection scores:
[     0.9588      0.9553      0.9519      0.9503      0.9436      0.9405      0.9369      0.9345      0.9345      0.9342      0.9304      0.9299      0.9269      0.9266      0.9203      0.9081      0.9073       0.785      0.7691      0.7383      0.6311      0.4427]

Score statistics:
min : 0.44268554
max : 0.9588117
mean: 0.8752914
>0.7: 20
>0.6: 21

In [160]:
tracker_file = MIXSORT_DIR / "yolox/mixsort_tracker/mixsort_tracker.py"
lines = tracker_file.read_text(encoding="utf-8", errors="ignore").splitlines()

for i, line in enumerate(lines, start=1):
    if "def activate" in line or "track.activate" in line:
        print(f"{i}: {line.strip()}")

65: def activate(self, kalman_filter, frame_id, template):
540: track.activate(

In [161]:
for i in range(55, 90):
    print(f"{i}: {lines[i-1]}")

55:             for i, st in enumerate(stracks):
56:                 if st.state != TrackState.Tracked:
57:                     multi_mean[i][7] = 0
58:             multi_mean, multi_covariance = STrack.shared_kalman.multi_predict(
59:                 multi_mean, multi_covariance
60:             )
61:             for i, (mean, cov) in enumerate(zip(multi_mean, multi_covariance)):
62:                 stracks[i].mean = mean
63:                 stracks[i].covariance = cov
64:
65:     def activate(self, kalman_filter, frame_id, template):
66:         """Start a new tracklet"""
67:         self.kalman_filter = kalman_filter
68:         self.track_id = self.next_id()
69:         self.mean, self.covariance = self.kalman_filter.initiate(
70:             self.tlwh_to_xyah(self._tlwh)
71:         )
72:         self.template = template
73:
74:         self.tracklet_len = 0
75:         self.state = TrackState.Tracked
76:         if frame_id == 1:
77:             self.is_activated = True
78:         # self.is_activated = True
79:         self.frame_id = frame_id
80:         self.start_frame = frame_id
81:
82:     def re_activate(self, new_track, frame_id, new_id=False, template=None):
83:         self.mean, self.covariance = self.kalman_filter.update(
84:             self.mean, self.covariance, self.tlwh_to_xyah(new_track.tlwh)
85:         )
86:         self.tracklet_len = 0
87:         self.state = TrackState.Tracked
88:         self.is_activated = True
89:         self.frame_id = frame_id

In [162]:
for i in range(520, 570):
    print(f"{i}: {lines[i-1]}")

520:         for itracked, idet in matches:
521:             det = detections[idet]
522:             template = (
523:                 self.crop_and_resize(img, det.tlwh, "template")
524:                 if det._iou < self.iou_thresh
525:                 else None
526:             )
527:             unconfirmed[itracked].update(detections[idet], self.frame_id, template)
528:             activated_starcks.append(unconfirmed[itracked])
529:         for it in u_unconfirmed:
530:             track = unconfirmed[it]
531:             track.mark_removed()
532:             removed_stracks.append(track)
533:
534:         """ Step 4: Init new stracks"""
535:         for inew in u_detection:
536:             track = detections[inew]
537:             if track.score < self.det_thresh:
538:                 continue
539:             # do not consider iou constraint
540:             track.activate(
541:                 self.kalman_filter,
542:                 self.frame_id,
543:                 self.crop_and_resize(img, track._tlwh, "template"),
544:             )
545:             activated_starcks.append(track)
546:         """ Step 5: Update state"""
547:         for track in self.lost_stracks:
548:             if self.frame_id - track.end_frame > self.max_time_lost:
549:                 track.mark_removed()
550:                 removed_stracks.append(track)
551:
552:         # print('Ramained match {} s'.format(t4-t3))
553:
554:         self.tracked_stracks = [
555:             t for t in self.tracked_stracks if t.state == TrackState.Tracked
556:         ]
557:         self.tracked_stracks = joint_stracks(self.tracked_stracks, activated_starcks)
558:         self.tracked_stracks = joint_stracks(self.tracked_stracks, refind_stracks)
559:         self.lost_stracks = sub_stracks(self.lost_stracks, self.tracked_stracks)
560:         self.lost_stracks.extend(lost_stracks)
561:         self.lost_stracks = sub_stracks(self.lost_stracks, self.removed_stracks)
562:         self.removed_stracks.extend(removed_stracks)
563:         self.tracked_stracks, self.lost_stracks = remove_duplicate_stracks(
564:             self.tracked_stracks, self.lost_stracks
565:         )
566:         # get scores of lost tracks
567:         output_stracks = [track for track in self.tracked_stracks if track.is_activated]
568:         self.last_img = img
569:         return output_stracks

In [163]:
print("frame_id:", tracker.frame_id)
print("tracked_stracks:", len(tracker.tracked_stracks))
print("lost_stracks:", len(tracker.lost_stracks))
print("removed_stracks:", len(tracker.removed_stracks))

print("\nTrack states:")
for t in tracker.tracked_stracks[:10]:
    print(
        "ID:", t.track_id,
        "activated:", t.is_activated,
        "state:", t.state,
        "score:", round(float(t.score), 4)
    )

frame_id: 1
tracked_stracks: 20
lost_stracks: 0
removed_stracks: 0

Track states:
ID: 1 activated: True state: 1 score: 0.9588
ID: 2 activated: True state: 1 score: 0.9553
ID: 3 activated: True state: 1 score: 0.9519
ID: 4 activated: True state: 1 score: 0.9503
ID: 5 activated: True state: 1 score: 0.9436
ID: 6 activated: True state: 1 score: 0.9405
ID: 7 activated: True state: 1 score: 0.9369
ID: 8 activated: True state: 1 score: 0.9345
ID: 9 activated: True state: 1 score: 0.9345
ID: 10 activated: True state: 1 score: 0.9342

In [164]:
for i in range(389, 430):
    print(f"{i}: {lines[i-1]}")

389:         self.frame_id += 1
390:         activated_starcks = []
391:         refind_stracks = []
392:         lost_stracks = []
393:         removed_stracks = []
394:
395:         if output_results.shape[1] == 5:
396:             scores = output_results[:, 4]
397:             bboxes = output_results[:, :4]
398:         else:
399:             output_results = output_results.cpu().numpy()
400:             scores = output_results[:, 4] * output_results[:, 5]
401:             bboxes = output_results[:, :4]  # x1y1x2y2
402:         img_h, img_w = img_info[0], img_info[1]
403:         scale = min(img_size[0] / float(img_h), img_size[1] / float(img_w))
404:         bboxes /= scale
405:
406:         # compute all ious
407:         all_dets = [x for x in bboxes]
408:         iou = matching.ious(all_dets, all_dets)
409:         # compute max iou for every det
410:         max_iou = []
411:         for i in range(len(all_dets)):
412:             iou[i][i] = 0
413:             max_iou.append(iou[i].max())
414:         max_iou = np.array(max_iou)
415:
416:         remain_inds = scores > self.args.track_thresh
417:         inds_low = scores > 0.1
418:         inds_high = scores < self.args.track_thresh
419:
420:         inds_second = np.logical_and(inds_low, inds_high)
421:         dets_second = bboxes[inds_second]
422:         dets = bboxes[remain_inds]
423:         max_iou_keep = max_iou[remain_inds]
424:         max_iou_second = max_iou[inds_second]
425:         scores_keep = scores[remain_inds]
426:         scores_second = scores[inds_second]
427:
428:         if len(dets) > 0:
429:             """Detections"""

In [165]:
tracker = MIXTracker(args, frame_rate=25)

print("Fresh tracker frame_id:", tracker.frame_id)

head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
Fresh tracker frame_id: 0

In [166]:
online_targets = tracker.update(
    output_results,
    img_info,
    img_size,
    frame
)

print("frame_id:", tracker.frame_id)
print("Active MixSort targets:", len(online_targets))

for t in online_targets[:10]:
    print(
        "ID:", t.track_id,
        "score:", round(float(t.score), 4),
        "tlwh:", np.round(t.tlwh, 2)
    )

frame_id: 1
Active MixSort targets: 20
ID: 21 score: 0.9588 tlwh: [     2454.5      1217.5      126.61      261.07]
ID: 22 score: 0.9553 tlwh: [     3013.9       759.7      123.29      211.13]
ID: 23 score: 0.9519 tlwh: [     3392.9      958.19       86.71      230.19]
ID: 24 score: 0.9503 tlwh: [       1610      1451.8      111.29      286.44]
ID: 25 score: 0.9436 tlwh: [     1597.3      1197.2       97.37      272.65]
ID: 26 score: 0.9405 tlwh: [     2759.4      1258.7       107.8      261.81]
ID: 27 score: 0.9369 tlwh: [     2933.1      656.07       89.75      184.95]
ID: 28 score: 0.9345 tlwh: [     2772.3      658.86       78.87      199.76]
ID: 29 score: 0.9345 tlwh: [     623.11      988.27      160.61      208.48]
ID: 30 score: 0.9342 tlwh: [      23.43      1484.2      124.43      332.32]

In [167]:
# Correct dimensions: (height, width)
img_info = (frame.shape[0], frame.shape[1])
img_size = (frame.shape[0], frame.shape[1])

tracker = MIXTracker(args, frame_rate=25)

online_targets = tracker.update(
    output_results,
    img_info,
    img_size,
    frame
)

print("Active MixSort targets:", len(online_targets))

for t in online_targets[:10]:
    print(
        "ID:", t.track_id,
        "score:", round(float(t.score), 4),
        "tlwh:", np.round(t.tlwh, 2)
    )

head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
Active MixSort targets: 20
ID: 41 score: 0.9588 tlwh: [     2454.5      1217.5      126.61      261.07]
ID: 42 score: 0.9553 tlwh: [     3013.9       759.7      123.29      211.13]
ID: 43 score: 0.9519 tlwh: [     3392.9      958.19       86.71      230.19]
ID: 44 score: 0.9503 tlwh: [       1610      1451.8      111.29      286.44]
ID: 45 score: 0.9436 tlwh: [     1597.3      1197.2       97.37      272.65]
ID: 46 score: 0.9405 tlwh: [     2759.4      1258.7       107.8      261.81]
ID: 47 score: 0.9369 tlwh: [     2933.1      656.07       89.75      184.95]
ID: 48 score: 0.9345 tlwh: [     2772.3      658.86       78.87      199.76]
ID: 49 score: 0.9345 tlwh: [     623.11      988.27      160.61      208.48]
ID: 50 score: 0.9342 tlwh: [      23.43      1484.2      124.43      332.32]

In [168]:
# Re-run detector so output_results contains the ORIGINAL pixel coordinates
result = detector.predict(
    frame,
    conf=0.40,
    iou=0.40,
    device=0,
    verbose=False
)[0]

boxes = result.boxes.xyxy.cpu().numpy()
scores = result.boxes.conf.cpu().numpy()

output_results = np.column_stack([boxes, scores]).astype(np.float32)

# SportsMOT frame dimensions: H=720, W=1280
img_info = (frame.shape[0], frame.shape[1])
img_size = (frame.shape[0], frame.shape[1])

# Fresh tracker
tracker = MIXTracker(args, frame_rate=25)

online_targets = tracker.update(
    output_results.copy(),
    img_info,
    img_size,
    frame
)

print("Original detection:", output_results[0])
print("Active targets:", len(online_targets))

for t in online_targets[:10]:
    print(
        "ID:", t.track_id,
        "tlwh:", np.round(t.tlwh, 2),
        "score:", round(float(t.score), 4)
    )

head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
Original detection: [     776.61      385.22      816.67      467.82     0.95881]
Active targets: 20
ID: 61 tlwh: [     776.61      385.22       40.06        82.6] score: 0.9588
ID: 62 tlwh: [     953.61      240.38       39.01        66.8] score: 0.9553
ID: 63 tlwh: [     1073.5      303.18       27.43       72.83] score: 0.9519
ID: 64 tlwh: [     509.42      459.37       35.21       90.63] score: 0.9503
ID: 65 tlwh: [     505.39       378.8       30.81       86.27] score: 0.9436
ID: 66 tlwh: [     873.09      398.27       34.11       82.84] score: 0.9405
ID: 67 tlwh: [     928.06      207.58        28.4       58.52] score: 0.9369
ID: 68 tlwh: [     877.17      208.47       24.95        63.2] score: 0.9345
ID: 69 tlwh: [     197.16       312.7       50.82       65.97] score: 0.9345
ID: 70 tlwh: [       7.41       469.6       39.37      105.15] score: 0.9342

In [170]:
# Inspect what MixSort's crop_and_resize actually returns
test_track = tracker.tracked_stracks[0]

template_result = tracker.crop_and_resize(
    frame,
    test_track._tlwh,
    "template"
)

print("Return type:", type(template_result))

if isinstance(template_result, tuple):
    print("Tuple length:", len(template_result))
    for i, item in enumerate(template_result):
        print(
            f"  [{i}] type={type(item)}, "
            f"shape={getattr(item, 'shape', None)}"
        )
else:
    print("Shape:", getattr(template_result, "shape", None))

Return type: <class 'tuple'>
Tuple length: 2
  [0] type=<class 'torch.Tensor'>, shape=torch.Size([3, 96, 96])
  [1] type=<class 'list'>, shape=None

In [171]:
for i in range(290, 350):
    print(f"{i}: {lines[i-1]}")

290:     def compute_mix_dist(
291:         self,
292:         stracks: List[STrack],
293:         dets: List[STrack],
294:         img: torch.Tensor,
295:         fuse: bool = False,
296:     ) -> np.ndarray:
297:         """compute mix distance between stracks and dets.
298:
299:         Args:
300:             stracks (List[STrack]): len = m
301:             dets (List[STrack]): len = n
302:             img (torch.Tensor): current image
303:             fuse (bool, optional): whether to fuse det score into iou. Defaults to False.
304:
305:         Returns:
306:             np.ndarray: m x n
307:         """
308:
309:         # Predict the current location with KF
310:         STrack.multi_predict(stracks)
311:         # compute iou dist
312:         iou = matching.iou_distance(stracks, dets)
313:         if fuse:
314:             iou = matching.fuse_score(iou, dets)
315:
316:         if len(stracks) * len(dets) == 0:
317:             return iou
318:
319:         # for every strack, compute its vit-dist with dets
320:         search_bbox = torch.stack(
321:             [torch.from_numpy(det.tlwh.astype(np.int)) for det in dets]
322:         )
323:         search_imgs = []
324:         search_boxes = []
325:         # vit dist
326:         # self.logger=SummaryWriter('./debug_tensorboard')
327:         # self.visualize(self.logger,template_imgs[0],search_img,search_box.clone())
328:         # self.visualize_box(self.logger,img,stracks,"stracks")
329:         # self.visualize_box(self.logger,img,dets,"dets")
330:         vit = np.zeros((len(stracks), len(dets)), dtype=np.float64)
331:         template_imgs = [s.template for s in stracks]
332:         for strack in stracks:
333:             # centered at predicted position
334:             center = strack.tlwh
335:             # crop search area & transform det coord
336:             s_img, s_box = self.crop_and_resize(img, center, "search", search_bbox)
337:             search_imgs.append(s_img)
338:             search_boxes.append(s_box)
339:
340:         # img transform & compute
341:         template_imgs = normalize(
342:             torch.stack(template_imgs).float().div(255),
343:             self.cfg.DATA.MEAN,
344:             self.cfg.DATA.STD,
345:         )
346:         search_imgs = normalize(
347:             torch.stack(search_imgs).float().div(255),
348:             self.cfg.DATA.MEAN,
349:             self.cfg.DATA.STD,

In [172]:
tracker_file = MIXSORT_DIR / "yolox/mixsort_tracker/mixsort_tracker.py"

text = tracker_file.read_text(encoding="utf-8")

old = "        template_imgs = [s.template for s in stracks]"
new = """        template_imgs = [
            s.template[0] if isinstance(s.template, tuple) else s.template
            for s in stracks
        ]"""

if old not in text:
    print("Original line not found — patch may already be applied.")
else:
    text = text.replace(old, new, 1)
    tracker_file.write_text(text, encoding="utf-8")
    print("Patch applied successfully.")

Patch applied successfully.

In [173]:
import importlib
import yolox.mixsort_tracker.mixsort_tracker as mixsort_module

importlib.reload(mixsort_module)

MIXTracker = mixsort_module.MIXTracker

tracker = MIXTracker(args, frame_rate=25)

print("Tracker reloaded and initialized.")

head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
Tracker reloaded and initialized.

In [174]:
import time
from collections import defaultdict

# Fresh tracker
tracker = MIXTracker(args, frame_rate=25)

track_history = defaultdict(list)

start = time.time()

for frame_idx, frame_path in enumerate(frames[:50], start=1):
    frame = cv2.imread(str(frame_path))

    result = detector.predict(
        frame,
        conf=0.40,
        iou=0.40,
        device=0,
        verbose=False
    )[0]

    boxes = result.boxes.xyxy.cpu().numpy()
    scores = result.boxes.conf.cpu().numpy()

    detections = np.column_stack([boxes, scores]).astype(np.float32)

    img_info = (frame.shape[0], frame.shape[1])
    img_size = (frame.shape[0], frame.shape[1])

    targets = tracker.update(
        detections.copy(),
        img_info,
        img_size,
        frame
    )

    for t in targets:
        track_history[t.track_id].append(frame_idx)

elapsed = time.time() - start

print("Frames processed:", 50)
print("Unique track IDs:", len(track_history))
print("Active IDs at final frame:", len(targets))
print("Total time:", round(elapsed, 2), "sec")
print("FPS:", round(50 / elapsed, 2))

print("\nFirst 15 track histories:")
for track_id, history in list(track_history.items())[:15]:
    print(track_id, "→", len(history), "frames")

head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
Frames processed: 50
Unique track IDs: 21
Active IDs at final frame: 19
Total time: 10.67 sec
FPS: 4.69

First 15 track histories:
101 → 50 frames
102 → 48 frames
103 → 50 frames
104 → 50 frames
105 → 49 frames
106 → 50 frames
107 → 50 frames
108 → 50 frames
109 → 49 frames
110 → 50 frames
111 → 45 frames
112 → 50 frames
113 → 50 frames
114 → 50 frames
115 → 2 frames

In [177]:
# Inspect the exact structure of the 5 evaluation sequences

for seq_name in SEQUENCES:
    seq_dir = VAL_DIR / seq_name

    print("\n" + "=" * 70)
    print(seq_name)
    print("=" * 70)

    if not seq_dir.exists():
        print("SEQUENCE DIRECTORY NOT FOUND")
        continue

    print("Sequence:", seq_dir)

    # Show immediate directories/files
    for p in sorted(seq_dir.iterdir()):
        if p.is_dir():
            print(f"[DIR]  {p.name}")
        else:
            print(f"[FILE] {p.name}")

    # Search for possible GT files
    gt_candidates = list(seq_dir.rglob("gt.txt"))

    print("\nGT candidates:")
    if gt_candidates:
        for p in gt_candidates:
            print(" ", p)
    else:
        print("  NONE")

    # Search for sequence metadata
    seqinfo_candidates = list(seq_dir.rglob("seqinfo.ini"))

    print("\nseqinfo.ini:")
    if seqinfo_candidates:
        for p in seqinfo_candidates:
            print(" ", p)
    else:
        print("  NONE")

======================================================================
v_2QhNRucNC7E_c017
======================================================================
Sequence: /mnt/d/My Projects/AthletiQ/AthletiQ/datasets/football/benchmarks/sportsmot/extracted/val/v_2QhNRucNC7E_c017
[DIR]  gt
[DIR]  img1
[FILE] seqinfo.ini

GT candidates:
  /mnt/d/My Projects/AthletiQ/AthletiQ/datasets/football/benchmarks/sportsmot/extracted/val/v_2QhNRucNC7E_c017/gt/gt.txt

seqinfo.ini:
  /mnt/d/My Projects/AthletiQ/AthletiQ/datasets/football/benchmarks/sportsmot/extracted/val/v_2QhNRucNC7E_c017/seqinfo.ini

======================================================================
v_2QhNRucNC7E_c600
======================================================================
SEQUENCE DIRECTORY NOT FOUND

======================================================================
v_2QhNRucNC7E_c011
======================================================================
SEQUENCE DIRECTORY NOT FOUND

======================================================================
v_2QhNRucNC7E_c067
======================================================================
SEQUENCE DIRECTORY NOT FOUND

======================================================================
v_2QhNRucNC7E_c010
======================================================================
SEQUENCE DIRECTORY NOT FOUND

In [178]:
# Find the actual locations of the 4 missing SportsMOT sequences

SEARCH_ROOT = ROOT / "datasets/football/benchmarks/sportsmot"

missing_sequences = [
    "v_2QhNRucNC7E_c600",
    "v_2QhNRucNC7E_c011",
    "v_2QhNRucNC7E_c067",
    "v_2QhNRucNC7E_c010",
]

print("=" * 70)
print("SEARCHING SPORTS MOT DATASET")
print("=" * 70)

for seq_name in missing_sequences:

    matches = list(SEARCH_ROOT.rglob(seq_name))

    print(f"\n{seq_name}")

    if matches:
        for p in matches:
            print("FOUND:", p)
    else:
        print("NOT FOUND")

======================================================================
SEARCHING SPORTS MOT DATASET
======================================================================

v_2QhNRucNC7E_c600
NOT FOUND

v_2QhNRucNC7E_c011
NOT FOUND

v_2QhNRucNC7E_c067
NOT FOUND

v_2QhNRucNC7E_c010
NOT FOUND

In [179]:
# Correct SportsMOT evaluation sequences

SEQUENCES = [
    "v_2QhNRucNC7E_c017",
    "v_G-vNjfx1GGc_c600",
    "v_ITo3sCnpw_k_c011",
    "v_dw7LOz17Omg_c067",
    "v_i2_I4qquVg0_c010",
]

print("=" * 70)
print("CHECKING MIXSORT EVALUATION SEQUENCES")
print("=" * 70)

for i, seq_name in enumerate(SEQUENCES, 1):

    seq_dir = VAL_DIR / seq_name
    img_dir = seq_dir / "img1"
    gt_path = seq_dir / "gt" / "gt.txt"

    print(f"\n{i}. {seq_name}")
    print("   Directory:", seq_dir.exists())
    print("   Images:   ", img_dir.exists())
    print("   GT:       ", gt_path.exists())

    if img_dir.exists():
        print("   Frames:   ", len(list(img_dir.glob("*.jpg"))))

print("\n" + "=" * 70)
print("READY FOR MIXSORT EVALUATION")
print("=" * 70)

======================================================================
CHECKING MIXSORT EVALUATION SEQUENCES
======================================================================

1. v_2QhNRucNC7E_c017
   Directory: True
   Images:    True
   GT:        True
   Frames:    450

2. v_G-vNjfx1GGc_c600
   Directory: True
   Images:    True
   GT:        True
   Frames:    500

3. v_ITo3sCnpw_k_c011
   Directory: True
   Images:    True
   GT:        True
   Frames:    776

4. v_dw7LOz17Omg_c067
   Directory: True
   Images:    True
   GT:        True
   Frames:    450

5. v_i2_I4qquVg0_c010
   Directory: False
   Images:    False
   GT:        False

======================================================================
READY FOR MIXSORT EVALUATION
======================================================================

In [180]:
# Find the exact location of the SportsMOT c010 sequence

SEARCH_ROOT = ROOT / "datasets/football/benchmarks/sportsmot"

matches = []

for p in SEARCH_ROOT.rglob("*c010"):
    if p.is_dir():
        matches.append(p)

print("=" * 70)
print("SEARCH RESULTS FOR c010")
print("=" * 70)

if matches:
    for p in matches:
        print(p)
else:
    print("No c010 directory found.")

======================================================================
SEARCH RESULTS FOR c010
======================================================================
/mnt/d/My Projects/AthletiQ/AthletiQ/datasets/football/benchmarks/sportsmot/extracted/train/v_HdiyOtliFiw_c010
/mnt/d/My Projects/AthletiQ/AthletiQ/datasets/football/benchmarks/sportsmot/extracted/val/v_i2_L4qquVg0_c010
/mnt/d/My Projects/AthletiQ/AthletiQ/datasets/football/benchmarks/sportsmot/extracted/val/v_ITo3sCnpw_k_c010

In [181]:
# ============================================================
# ATHLETIQ — MixSort 5-Sequence MOT Evaluation
# Same detector + SportsMOT GT + IoU=0.50
# ============================================================

import sys
import time
import cv2
import numpy as np
import pandas as pd
import motmetrics as mm

from pathlib import Path
from collections import defaultdict
from types import SimpleNamespace

from ultralytics import YOLO


# ============================================================
# 1. NUMPY 2.x COMPATIBILITY
# ============================================================

if not hasattr(np, "asfarray"):
    np.asfarray = lambda a, dtype=float: np.asarray(a, dtype=dtype)


# ============================================================
# 2. PROJECT PATHS
# ============================================================

ROOT = Path("/mnt/d/My Projects/AthletiQ/AthletiQ")

MIXSORT_DIR = (
    ROOT
    / "ai-engine/third_party/MixSort"
)

VAL_DIR = (
    ROOT
    / "datasets/football/benchmarks/sportsmot/extracted/val"
)

MODEL_PATH = (
    ROOT
    / "ai-engine/models/football_player_detector.pt"
)


# ============================================================
# 3. EXACT SPORTS MOT VALIDATION SEQUENCES
# ============================================================

SEQUENCES = [
    "v_2QhNRucNC7E_c017",
    "v_G-vNjfx1GGc_c600",
    "v_ITo3sCnpw_k_c011",
    "v_dw7LOz17Omg_c067",
    "v_i2_L4qquVg0_c010",
]


# ============================================================
# 4. CHECK SEQUENCES BEFORE STARTING
# ============================================================

print("=" * 70)
print("MIXSORT 5-SEQUENCE MOT EVALUATION")
print("=" * 70)

for seq_name in SEQUENCES:

    seq_dir = VAL_DIR / seq_name
    img_dir = seq_dir / "img1"
    gt_path = seq_dir / "gt" / "gt.txt"

    print(f"\n{seq_name}")
    print("  Directory:", seq_dir.exists())
    print("  Images:   ", img_dir.exists())
    print("  GT:       ", gt_path.exists())

    if not seq_dir.exists():
        raise FileNotFoundError(
            f"Sequence directory not found:\n{seq_dir}"
        )

    if not img_dir.exists():
        raise FileNotFoundError(
            f"img1 directory not found:\n{img_dir}"
        )

    if not gt_path.exists():
        raise FileNotFoundError(
            f"GT file not found:\n{gt_path}"
        )

print("\nAll 5 sequences verified.")


# ============================================================
# 5. IMPORT MIXSORT
# ============================================================

if str(MIXSORT_DIR) not in sys.path:
    sys.path.insert(0, str(MIXSORT_DIR))

from yolox.mixsort_tracker.mixsort_tracker import MIXTracker


# ============================================================
# 6. MIXSORT CONFIGURATION
# ============================================================

args = SimpleNamespace(
    track_thresh=0.6,
    track_buffer=30,
    match_thresh=0.9,
    iou_thresh=0.3,
    alpha=0.6,
    radius=0,
    script="mixformer_deit",
    config="track",
    local_rank=0,
    mot20=False,
)


# ============================================================
# 7. LOAD FOOTBALL PLAYER DETECTOR
# ============================================================

detector = YOLO(str(MODEL_PATH))

print("\nDetector loaded:")
print(MODEL_PATH)

print("\nEvaluation settings:")
print("  Detection confidence :", 0.40)
print("  Detection IoU        :", 0.40)
print("  MOT matching IoU     :", 0.50)
print("  Tracker              : MixSort")
print("  Tracker threshold    :", args.track_thresh)
print("  Match threshold      :", args.match_thresh)


# ============================================================
# 8. SPORTS MOT GT LOADER
# ============================================================

def load_gt(gt_path):

    gt = defaultdict(list)

    with open(gt_path, "r") as f:

        for line in f:

            parts = line.strip().split(",")

            if len(parts) < 6:
                continue

            frame_id = int(float(parts[0]))
            track_id = int(float(parts[1]))

            x = float(parts[2])
            y = float(parts[3])
            w = float(parts[4])
            h = float(parts[5])

            gt[frame_id].append(
                (track_id, x, y, w, h)
            )

    return gt


# ============================================================
# 9. EVALUATE ALL FIVE SEQUENCES
# ============================================================

all_results = []

total_frames = 0
total_objects = 0
total_predictions = 0
total_matches = 0
total_switches = 0
total_fp = 0
total_fn = 0

for seq_number, seq_name in enumerate(SEQUENCES, start=1):

    print("\n")
    print("=" * 70)
    print(f"SEQUENCE {seq_number}/5: {seq_name}")
    print("=" * 70)

    # --------------------------------------------------------
    # Paths
    # --------------------------------------------------------

    seq_dir = VAL_DIR / seq_name
    img_dir = seq_dir / "img1"
    gt_path = seq_dir / "gt" / "gt.txt"

    frames = sorted(img_dir.glob("*.jpg"))

    gt = load_gt(gt_path)

    gt_count = sum(
        len(v) for v in gt.values()
    )

    print("Frames:", len(frames))
    print("GT rows:", gt_count)

    # --------------------------------------------------------
    # Fresh MixSort tracker
    # --------------------------------------------------------

    tracker = MIXTracker(
        args,
        frame_rate=25
    )

    # MOT accumulator for this sequence only
    acc = mm.MOTAccumulator(
        auto_id=True
    )

    unique_ids = set()

    sequence_predictions = 0

    start_time = time.time()

    # --------------------------------------------------------
    # FRAME LOOP
    # --------------------------------------------------------

    for frame_idx, frame_path in enumerate(
        frames,
        start=1
    ):

        frame = cv2.imread(
            str(frame_path)
        )

        if frame is None:
            raise RuntimeError(
                f"Could not read frame:\n{frame_path}"
            )

        # ----------------------------------------------------
        # PLAYER DETECTION
        # ----------------------------------------------------

        result = detector.predict(
            frame,
            conf=0.40,
            iou=0.40,
            device=0,
            verbose=False
        )[0]

        boxes = (
            result
            .boxes
            .xyxy
            .cpu()
            .numpy()
        )

        scores = (
            result
            .boxes
            .conf
            .cpu()
            .numpy()
        )

        detections = np.column_stack(
            [
                boxes,
                scores
            ]
        ).astype(
            np.float32
        )

        # ----------------------------------------------------
        # MIXSORT INPUT
        # Important: H,W — not W,H
        # ----------------------------------------------------

        img_info = (
            frame.shape[0],
            frame.shape[1]
        )

        img_size = (
            frame.shape[0],
            frame.shape[1]
        )

        # MixSort modifies detection array internally,
        # therefore pass a copy.
        targets = tracker.update(
            detections.copy(),
            img_info,
            img_size,
            frame
        )

        # ----------------------------------------------------
        # MIXSORT PREDICTIONS
        # ----------------------------------------------------

        pred_ids = []
        pred_boxes = []

        for target in targets:

            track_id = int(
                target.track_id
            )

            x, y, w, h = map(
                float,
                target.tlwh
            )

            pred_ids.append(
                track_id
            )

            pred_boxes.append(
                [
                    x,
                    y,
                    w,
                    h
                ]
            )

            unique_ids.add(
                track_id
            )

        sequence_predictions += len(
            pred_ids
        )

        # ----------------------------------------------------
        # GROUND TRUTH
        # ----------------------------------------------------

        gt_entries = gt.get(
            frame_idx,
            []
        )

        gt_ids = []
        gt_boxes = []

        for (
            track_id,
            x,
            y,
            w,
            h
        ) in gt_entries:

            gt_ids.append(
                int(track_id)
            )

            gt_boxes.append(
                [
                    x,
                    y,
                    w,
                    h
                ]
            )

        # ----------------------------------------------------
        # IoU DISTANCE MATRIX
        #
        # max_iou=0.5 means:
        # IoU >= 0.5 -> valid match
        # ----------------------------------------------------

        if (
            len(gt_boxes) == 0
            and len(pred_boxes) == 0
        ):

            distance = np.empty(
                (0, 0)
            )

        elif len(gt_boxes) == 0:

            distance = np.empty(
                (
                    0,
                    len(pred_boxes)
                )
            )

        elif len(pred_boxes) == 0:

            distance = np.empty(
                (
                    len(gt_boxes),
                    0
                )
            )

        else:

            distance = mm.distances.iou_matrix(
                np.asarray(
                    gt_boxes,
                    dtype=float
                ),
                np.asarray(
                    pred_boxes,
                    dtype=float
                ),
                max_iou=0.5
            )

        # ----------------------------------------------------
        # UPDATE MOTMETRICS
        # ----------------------------------------------------

        acc.update(
            gt_ids,
            pred_ids,
            distance
        )

    # ========================================================
    # SEQUENCE TIMING
    # ========================================================

    elapsed = time.time() - start_time

    fps = (
        len(frames) / elapsed
        if elapsed > 0
        else 0
    )

    # ========================================================
    # COMPUTE METRICS
    # ========================================================

    mh = mm.metrics.create()

    summary = mh.compute(
        acc,
        metrics=[
            "num_frames",
            "num_objects",
            "num_predictions",
            "num_matches",
            "num_switches",
            "num_false_positives",
            "num_misses",
            "mota",
            "idf1"
        ],
        name=seq_name
    )

    row = summary.iloc[0]

    mota = float(
        row["mota"]
    )

    idf1 = float(
        row["idf1"]
    )

    switches = int(
        row["num_switches"]
    )

    fp = int(
        row["num_false_positives"]
    )

    fn = int(
        row["num_misses"]
    )

    matches = int(
        row["num_matches"]
    )

    objects = int(
        row["num_objects"]
    )

    predictions = int(
        row["num_predictions"]
    )

    # --------------------------------------------------------
    # Store
    # --------------------------------------------------------

    all_results.append(
        {
            "Sequence": seq_name,
            "Frames": len(frames),
            "GT Objects": objects,
            "Predictions": predictions,
            "Matches": matches,
            "ID Switches": switches,
            "FP": fp,
            "FN": fn,
            "MOTA": mota,
            "IDF1": idf1,
            "Unique IDs": len(unique_ids),
            "FPS": fps
        }
    )

    # --------------------------------------------------------
    # Accumulate totals
    # --------------------------------------------------------

    total_frames += len(frames)
    total_objects += objects
    total_predictions += predictions
    total_matches += matches
    total_switches += switches
    total_fp += fp
    total_fn += fn

    # ========================================================
    # PRINT SEQUENCE RESULT
    # ========================================================

    print("\nRESULTS")

    print(
        f"MOTA:          {mota:.6f}"
    )

    print(
        f"IDF1:          {idf1:.6f}"
    )

    print(
        f"ID Switches:   {switches}"
    )

    print(
        f"FP:            {fp}"
    )

    print(
        f"FN:            {fn}"
    )

    print(
        f"Matches:       {matches}"
    )

    print(
        f"Unique IDs:    {len(unique_ids)}"
    )

    print(
        f"FPS:           {fps:.2f}"
    )


# ============================================================
# 10. FINAL RESULTS TABLE
# ============================================================

results_df = pd.DataFrame(
    all_results
)

print("\n")
print("=" * 100)
print("MIXSORT — FINAL 5-SEQUENCE RESULTS")
print("=" * 100)

display(
    results_df
)


# ============================================================
# 11. ADDITIVE OVERALL MOTA
#
# MOTA = 1 - (FN + FP + IDSW) / GT
#
# This is valid to aggregate across independent sequences.
# ============================================================

overall_mota = (
    1
    - (
        total_fn
        + total_fp
        + total_switches
    )
    / total_objects
)


# ============================================================
# 12. MACRO-AVERAGE IDF1
#
# IDF1 is NOT safely obtained by simply concatenating
# independent sequences with overlapping track IDs.
# Therefore report the mean of the five sequence IDF1 values.
# ============================================================

macro_idf1 = results_df[
    "IDF1"
].mean()

macro_mota = results_df[
    "MOTA"
].mean()

average_fps = results_df[
    "FPS"
].mean()


# ============================================================
# 13. OVERALL SUMMARY
# ============================================================

print("\n")
print("=" * 70)
print("MIXSORT OVERALL SUMMARY")
print("=" * 70)

print(
    f"Total frames:       {total_frames}"
)

print(
    f"Total GT objects:   {total_objects}"
)

print(
    f"Total predictions:  {total_predictions}"
)

print(
    f"Total matches:      {total_matches}"
)

print(
    f"Total ID switches:  {total_switches}"
)

print(
    f"Total FP:            {total_fp}"
)

print(
    f"Total FN:            {total_fn}"
)

print(
    f"Overall MOTA:       {overall_mota:.6f}"
)

print(
    f"Macro MOTA:         {macro_mota:.6f}"
)

print(
    f"Macro IDF1:         {macro_idf1:.6f}"
)

print(
    f"Average FPS:        {average_fps:.2f}"
)

print("\nEvaluation complete.")

======================================================================
MIXSORT 5-SEQUENCE MOT EVALUATION
======================================================================

v_2QhNRucNC7E_c017
  Directory: True
  Images:    True
  GT:        True

v_G-vNjfx1GGc_c600
  Directory: True
  Images:    True
  GT:        True

v_ITo3sCnpw_k_c011
  Directory: True
  Images:    True
  GT:        True

v_dw7LOz17Omg_c067
  Directory: True
  Images:    True
  GT:        True

v_i2_L4qquVg0_c010
  Directory: True
  Images:    True
  GT:        True

All 5 sequences verified.

Detector loaded:
/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/models/football_player_detector.pt

Evaluation settings:
  Detection confidence : 0.4
  Detection IoU        : 0.4
  MOT matching IoU     : 0.5
  Tracker              : MixSort
  Tracker threshold    : 0.6
  Match threshold      : 0.9


======================================================================
SEQUENCE 1/5: v_2QhNRucNC7E_c017
======================================================================
Frames: 450
GT rows: 6622
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.

RESULTS
MOTA:          0.843250
IDF1:          0.759869
ID Switches:   43
FP:            449
FN:            546
Matches:       6033
Unique IDs:    41
FPS:           4.99


======================================================================
SEQUENCE 2/5: v_G-vNjfx1GGc_c600
======================================================================
Frames: 500
GT rows: 5462
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.

RESULTS
MOTA:          0.710546
IDF1:          0.566483
ID Switches:   40
FP:            306
FN:            1235
Matches:       4187
Unique IDs:    59
FPS:           5.52


======================================================================
SEQUENCE 3/5: v_ITo3sCnpw_k_c011
======================================================================
Frames: 776
GT rows: 9736
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.

RESULTS
MOTA:          0.856512
IDF1:          0.596457
ID Switches:   60
FP:            613
FN:            724
Matches:       8952
Unique IDs:    55
FPS:           5.21


======================================================================
SEQUENCE 4/5: v_dw7LOz17Omg_c067
======================================================================
Frames: 450
GT rows: 6959
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.

RESULTS
MOTA:          0.891076
IDF1:          0.792445
ID Switches:   31
FP:            234
FN:            493
Matches:       6435
Unique IDs:    55
FPS:           4.85


======================================================================
SEQUENCE 5/5: v_i2_L4qquVg0_c010
======================================================================
Frames: 758
GT rows: 8262
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.

RESULTS
MOTA:          0.822319
IDF1:          0.480866
ID Switches:   55
FP:            114
FN:            1299
Matches:       6908
Unique IDs:    72
FPS:           5.30


====================================================================================================
MIXSORT — FINAL 5-SEQUENCE RESULTS
====================================================================================================

,Sequence,Frames,GT Objects,Predictions,Matches,ID Switches,FP,FN,MOTA,IDF1,Unique IDs,FPS
0,v_2QhNRucNC7E_c017,450,6622,6525,6033,43,449,546,0.843250,0.759869,41,4.991787
1,v_G-vNjfx1GGc_c600,500,5462,4533,4187,40,306,1235,0.710546,0.566483,59,5.519453
2,v_ITo3sCnpw_k_c011,776,9736,9625,8952,60,613,724,0.856512,0.596457,55,5.214271
3,v_dw7LOz17Omg_c067,450,6959,6700,6435,31,234,493,0.891076,0.792445,55,4.854335
4,v_i2_L4qquVg0_c010,758,8262,7077,6908,55,114,1299,0.822319,0.480866,72,5.297228

======================================================================
MIXSORT OVERALL SUMMARY
======================================================================
Total frames:       2934
Total GT objects:   37041
Total predictions:  34460
Total matches:      32515
Total ID switches:  229
Total FP:            1716
Total FN:            4297
Overall MOTA:       0.831484
Macro MOTA:         0.824741
Macro IDF1:         0.639224
Average FPS:        5.18

Evaluation complete.

In [182]:
# ============================================================
# ATHLETIQ — MixSort Hyperparameter Tuning
# Phase 1: alpha × match_thresh
# Validation sequences: c600 + c010
# ============================================================

import sys
import time
import cv2
import numpy as np
import pandas as pd
import motmetrics as mm

from pathlib import Path
from collections import defaultdict
from types import SimpleNamespace

from ultralytics import YOLO


# ============================================================
# 1. NUMPY COMPATIBILITY
# ============================================================

if not hasattr(np, "asfarray"):
    np.asfarray = lambda a, dtype=float: np.asarray(a, dtype=dtype)


# ============================================================
# 2. PATHS
# ============================================================

ROOT = Path("/mnt/d/My Projects/AthletiQ/AthletiQ")

MIXSORT_DIR = (
    ROOT / "ai-engine/third_party/MixSort"
)

VAL_DIR = (
    ROOT
    / "datasets/football/benchmarks/sportsmot/extracted/val"
)

MODEL_PATH = (
    ROOT
    / "ai-engine/models/football_player_detector.pt"
)


# ============================================================
# 3. ONLY THE TWO DIFFICULT SEQUENCES
# ============================================================

SEQUENCES = {
    "c600": "v_G-vNjfx1GGc_c600",
    "c010": "v_i2_L4qquVg0_c010",
}


# ============================================================
# 4. TUNING GRID
# ============================================================

ALPHAS = [
    0.4,
    0.6,
    0.8
]

MATCH_THRESHES = [
    0.7,
    0.8,
    0.9
]

# Keep this fixed in Phase 1
IOU_THRESH = 0.3

TRACK_THRESH = 0.6
TRACK_BUFFER = 30


# ============================================================
# 5. IMPORT MIXSORT
# ============================================================

if str(MIXSORT_DIR) not in sys.path:
    sys.path.insert(0, str(MIXSORT_DIR))

from yolox.mixsort_tracker.mixsort_tracker import MIXTracker


# ============================================================
# 6. LOAD DETECTOR
# ============================================================

detector = YOLO(
    str(MODEL_PATH)
)


# ============================================================
# 7. GT LOADER
# ============================================================

def load_gt(gt_path):

    gt = defaultdict(list)

    with open(gt_path, "r") as f:

        for line in f:

            parts = line.strip().split(",")

            if len(parts) < 6:
                continue

            frame_id = int(float(parts[0]))
            track_id = int(float(parts[1]))

            x = float(parts[2])
            y = float(parts[3])
            w = float(parts[4])
            h = float(parts[5])

            gt[frame_id].append(
                (track_id, x, y, w, h)
            )

    return gt


# ============================================================
# 8. EVALUATION FUNCTION
# ============================================================

def evaluate_config(
    sequence_name,
    alpha,
    match_thresh
):

    seq_dir = VAL_DIR / sequence_name

    img_dir = seq_dir / "img1"
    gt_path = seq_dir / "gt" / "gt.txt"

    frames = sorted(
        img_dir.glob("*.jpg")
    )

    gt = load_gt(gt_path)

    # --------------------------------------------------------
    # Fresh tracker
    # --------------------------------------------------------

    args = SimpleNamespace(
        track_thresh=TRACK_THRESH,
        track_buffer=TRACK_BUFFER,
        match_thresh=match_thresh,
        iou_thresh=IOU_THRESH,
        alpha=alpha,
        radius=0,
        script="mixformer_deit",
        config="track",
        local_rank=0,
        mot20=False,
    )

    tracker = MIXTracker(
        args,
        frame_rate=25
    )

    acc = mm.MOTAccumulator(
        auto_id=True
    )

    unique_ids = set()

    start_time = time.time()

    # --------------------------------------------------------
    # Frame loop
    # --------------------------------------------------------

    for frame_idx, frame_path in enumerate(
        frames,
        start=1
    ):

        frame = cv2.imread(
            str(frame_path)
        )

        # ----------------------------------------------------
        # Detector
        # ----------------------------------------------------

        result = detector.predict(
            frame,
            conf=0.40,
            iou=0.40,
            device=0,
            verbose=False
        )[0]

        boxes = (
            result.boxes.xyxy
            .cpu()
            .numpy()
        )

        scores = (
            result.boxes.conf
            .cpu()
            .numpy()
        )

        detections = np.column_stack(
            [
                boxes,
                scores
            ]
        ).astype(
            np.float32
        )

        # ----------------------------------------------------
        # MixSort expects H,W
        # ----------------------------------------------------

        img_info = (
            frame.shape[0],
            frame.shape[1]
        )

        img_size = (
            frame.shape[0],
            frame.shape[1]
        )

        targets = tracker.update(
            detections.copy(),
            img_info,
            img_size,
            frame
        )

        # ----------------------------------------------------
        # Predictions
        # ----------------------------------------------------

        pred_ids = []
        pred_boxes = []

        for target in targets:

            track_id = int(
                target.track_id
            )

            x, y, w, h = map(
                float,
                target.tlwh
            )

            pred_ids.append(
                track_id
            )

            pred_boxes.append(
                [x, y, w, h]
            )

            unique_ids.add(
                track_id
            )

        # ----------------------------------------------------
        # GT
        # ----------------------------------------------------

        gt_entries = gt.get(
            frame_idx,
            []
        )

        gt_ids = []
        gt_boxes = []

        for (
            track_id,
            x,
            y,
            w,
            h
        ) in gt_entries:

            gt_ids.append(
                int(track_id)
            )

            gt_boxes.append(
                [x, y, w, h]
            )

        # ----------------------------------------------------
        # IoU distance
        # ----------------------------------------------------

        if (
            len(gt_boxes) == 0
            and len(pred_boxes) == 0
        ):

            distance = np.empty(
                (0, 0)
            )

        elif len(gt_boxes) == 0:

            distance = np.empty(
                (
                    0,
                    len(pred_boxes)
                )
            )

        elif len(pred_boxes) == 0:

            distance = np.empty(
                (
                    len(gt_boxes),
                    0
                )
            )

        else:

            distance = mm.distances.iou_matrix(
                np.asarray(
                    gt_boxes,
                    dtype=float
                ),
                np.asarray(
                    pred_boxes,
                    dtype=float
                ),
                max_iou=0.5
            )

        acc.update(
            gt_ids,
            pred_ids,
            distance
        )

    # ========================================================
    # METRICS
    # ========================================================

    elapsed = time.time() - start_time

    fps = (
        len(frames) / elapsed
        if elapsed > 0
        else 0
    )

    mh = mm.metrics.create()

    summary = mh.compute(
        acc,
        metrics=[
            "num_objects",
            "num_predictions",
            "num_matches",
            "num_switches",
            "num_false_positives",
            "num_misses",
            "mota",
            "idf1"
        ],
        name="result"
    )

    row = summary.iloc[0]

    return {
        "Sequence": sequence_name,
        "alpha": alpha,
        "match_thresh": match_thresh,
        "iou_thresh": IOU_THRESH,
        "MOTA": float(row["mota"]),
        "IDF1": float(row["idf1"]),
        "ID Switches": int(row["num_switches"]),
        "FP": int(row["num_false_positives"]),
        "FN": int(row["num_misses"]),
        "Matches": int(row["num_matches"]),
        "GT": int(row["num_objects"]),
        "Unique IDs": len(unique_ids),
        "FPS": fps,
    }


# ============================================================
# 9. RUN GRID
# ============================================================

results = []

total_runs = (
    len(SEQUENCES)
    * len(ALPHAS)
    * len(MATCH_THRESHES)
)

run_number = 0

print("=" * 80)
print("MIXSORT PHASE 1 HYPERPARAMETER TUNING")
print("=" * 80)

print(
    f"Configurations: {len(ALPHAS) * len(MATCH_THRESHES)}"
)

print(
    f"Sequences: {list(SEQUENCES.keys())}"
)

print(
    f"Total runs: {total_runs}"
)

print()


for seq_label, seq_name in SEQUENCES.items():

    print("\n" + "=" * 80)
    print(
        f"SEQUENCE: {seq_label} → {seq_name}"
    )
    print("=" * 80)

    for alpha in ALPHAS:

        for match_thresh in MATCH_THRESHES:

            run_number += 1

            print(
                f"\n[{run_number}/{total_runs}] "
                f"{seq_label} | "
                f"alpha={alpha} | "
                f"match_thresh={match_thresh}"
            )

            result = evaluate_config(
                seq_name,
                alpha,
                match_thresh
            )

            result["Sequence"] = seq_label

            results.append(
                result
            )

            print(
                f"MOTA={result['MOTA']:.4f} | "
                f"IDF1={result['IDF1']:.4f} | "
                f"IDSW={result['ID Switches']} | "
                f"FP={result['FP']} | "
                f"FN={result['FN']} | "
                f"FPS={result['FPS']:.2f}"
            )


# ============================================================
# 10. RESULTS TABLE
# ============================================================

tuning_df = pd.DataFrame(
    results
)

print("\n")
print("=" * 100)
print("ALL TUNING RESULTS")
print("=" * 100)

display(
    tuning_df.sort_values(
        [
            "Sequence",
            "MOTA"
        ],
        ascending=[
            True,
            False
        ]
    )
)


# ============================================================
# 11. BEST CONFIG PER SEQUENCE
# ============================================================

print("\n")
print("=" * 100)
print("BEST CONFIGURATION BY MOTA")
print("=" * 100)

best_mota = (
    tuning_df
    .sort_values(
        "MOTA",
        ascending=False
    )
    .groupby(
        "Sequence",
        as_index=False
    )
    .first()
)

display(
    best_mota
)


# ============================================================
# 12. BEST CONFIG BY IDF1
# ============================================================

print("\n")
print("=" * 100)
print("BEST CONFIGURATION BY IDF1")
print("=" * 100)

best_idf1 = (
    tuning_df
    .sort_values(
        "IDF1",
        ascending=False
    )
    .groupby(
        "Sequence",
        as_index=False
    )
    .first()
)

display(
    best_idf1
)


# ============================================================
# 13. BEST CONFIG BY LOWEST ID SWITCHES
# ============================================================

print("\n")
print("=" * 100)
print("BEST CONFIGURATION BY ID SWITCHES")
print("=" * 100)

best_ids = (
    tuning_df
    .sort_values(
        [
            "ID Switches",
            "FN"
        ],
        ascending=[
            True,
            True
        ]
    )
    .groupby(
        "Sequence",
        as_index=False
    )
    .first()
)

display(
    best_ids
)


# ============================================================
# 14. COMBINED SCORE
#
# We don't want to optimize only MOTA or only IDF1.
#
# This score is ONLY for selecting candidates for Phase 2.
# It is NOT a standard MOT metric.
# ============================================================

candidate_df = (
    tuning_df
    .groupby(
        [
            "alpha",
            "match_thresh"
        ]
    )
    .agg(
        MOTA=("MOTA", "mean"),
        IDF1=("IDF1", "mean"),
        IDSW=("ID Switches", "sum"),
        FN=("FN", "sum"),
        FP=("FP", "sum"),
        FPS=("FPS", "mean")
    )
    .reset_index()
)

# Normalize MOTA and IDF1 between tested configurations
candidate_df["MOTA_norm"] = (
    (
        candidate_df["MOTA"]
        - candidate_df["MOTA"].min()
    )
    /
    (
        candidate_df["MOTA"].max()
        - candidate_df["MOTA"].min()
        + 1e-9
    )
)

candidate_df["IDF1_norm"] = (
    (
        candidate_df["IDF1"]
        - candidate_df["IDF1"].min()
    )
    /
    (
        candidate_df["IDF1"].max()
        - candidate_df["IDF1"].min()
        + 1e-9
    )
)

candidate_df["Score"] = (
    0.50 * candidate_df["MOTA_norm"]
    +
    0.50 * candidate_df["IDF1_norm"]
)

candidate_df = candidate_df.sort_values(
    "Score",
    ascending=False
)

print("\n")
print("=" * 100)
print("PHASE 2 CANDIDATES")
print("=" * 100)

display(
    candidate_df
)


print("\n")
print("=" * 100)
print("TUNING PHASE 1 COMPLETE")
print("=" * 100)

print(
    "Next: take the strongest configurations "
    "and test iou_thresh."
)

================================================================================
MIXSORT PHASE 1 HYPERPARAMETER TUNING
================================================================================
Configurations: 9
Sequences: ['c600', 'c010']
Total runs: 18


================================================================================
SEQUENCE: c600 → v_G-vNjfx1GGc_c600
================================================================================

[1/18] c600 | alpha=0.4 | match_thresh=0.7
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.2067 | IDF1=0.1201 | IDSW=403 | FP=66 | FN=3864 | FPS=2.90

[2/18] c600 | alpha=0.4 | match_thresh=0.8
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.5254 | IDF1=0.3780 | IDSW=66 | FP=147 | FN=2379 | FPS=5.52

[3/18] c600 | alpha=0.4 | match_thresh=0.9
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.6415 | IDF1=0.5425 | IDSW=30 | FP=191 | FN=1737 | FPS=5.44

[4/18] c600 | alpha=0.6 | match_thresh=0.7
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.6155 | IDF1=0.3510 | IDSW=151 | FP=250 | FN=1699 | FPS=4.81

[5/18] c600 | alpha=0.6 | match_thresh=0.8
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.6792 | IDF1=0.4579 | IDSW=59 | FP=285 | FN=1408 | FPS=5.35

[6/18] c600 | alpha=0.6 | match_thresh=0.9
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.7105 | IDF1=0.5665 | IDSW=40 | FP=306 | FN=1235 | FPS=5.48

[7/18] c600 | alpha=0.8 | match_thresh=0.7
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.7155 | IDF1=0.4122 | IDSW=96 | FP=289 | FN=1169 | FPS=5.26

[8/18] c600 | alpha=0.8 | match_thresh=0.8
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.7437 | IDF1=0.5424 | IDSW=52 | FP=328 | FN=1020 | FPS=5.58

[9/18] c600 | alpha=0.8 | match_thresh=0.9
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.7598 | IDF1=0.5810 | IDSW=42 | FP=347 | FN=923 | FPS=5.64

================================================================================
SEQUENCE: c010 → v_i2_L4qquVg0_c010
================================================================================

[10/18] c010 | alpha=0.4 | match_thresh=0.7
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.

[W1003 10:17:12.472113421 CUDACachingAllocator.cpp:3934] memory allocation failed with OOM on device 0 while trying to allocate 188743680 bytes (free: 0, total: 6441926656).

MOTA=0.2136 | IDF1=0.0860 | IDSW=746 | FP=8 | FN=5743 | FPS=3.03

[11/18] c010 | alpha=0.4 | match_thresh=0.8
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.5748 | IDF1=0.3578 | IDSW=83 | FP=19 | FN=3411 | FPS=5.19

[12/18] c010 | alpha=0.4 | match_thresh=0.9
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.6972 | IDF1=0.5028 | IDSW=37 | FP=43 | FN=2422 | FPS=5.83

[13/18] c010 | alpha=0.6 | match_thresh=0.7
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.7177 | IDF1=0.3472 | IDSW=234 | FP=57 | FN=2041 | FPS=4.95

[14/18] c010 | alpha=0.6 | match_thresh=0.8
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.7806 | IDF1=0.4750 | IDSW=77 | FP=95 | FN=1641 | FPS=5.96

[15/18] c010 | alpha=0.6 | match_thresh=0.9
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.8223 | IDF1=0.4809 | IDSW=55 | FP=114 | FN=1299 | FPS=5.93

[16/18] c010 | alpha=0.8 | match_thresh=0.7
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.8158 | IDF1=0.4562 | IDSW=128 | FP=99 | FN=1295 | FPS=5.49

[17/18] c010 | alpha=0.8 | match_thresh=0.8
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.8427 | IDF1=0.4911 | IDSW=85 | FP=114 | FN=1101 | FPS=5.74

[18/18] c010 | alpha=0.8 | match_thresh=0.9
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.8608 | IDF1=0.5122 | IDSW=67 | FP=137 | FN=946 | FPS=5.41


====================================================================================================
ALL TUNING RESULTS
====================================================================================================

,Sequence,alpha,match_thresh,iou_thresh,MOTA,IDF1,ID Switches,FP,FN,Matches,GT,Unique IDs,FPS
17,c010,0.8,0.9,0.3,0.860809,0.512249,67,137,946,7249,8262,77,5.408747
16,c010,0.8,0.8,0.3,0.842653,0.491086,85,114,1101,7076,8262,103,5.741241
14,c010,0.6,0.9,0.3,0.822319,0.480866,55,114,1299,6908,8262,72,5.933971
15,c010,0.8,0.7,0.3,0.815783,0.456159,128,99,1295,6839,8262,151,5.489752
13,c010,0.6,0.8,0.3,0.780562,0.474963,77,95,1641,6544,8262,101,5.961474
12,c010,0.6,0.7,0.3,0.717744,0.347180,234,57,2041,5987,8262,244,4.954367
11,c010,0.4,0.9,0.3,0.697168,0.502793,37,43,2422,5803,8262,49,5.825693
10,c010,0.4,0.8,0.3,0.574800,0.357752,83,19,3411,4768,8262,100,5.193390
9,c010,0.4,0.7,0.3,0.213629,0.086014,746,8,5743,1773,8262,718,3.029420
8,c600,0.8,0.9,0.3,0.759795,0.580982,42,347,923,4497,5462,59,5.644904
7,c600,0.8,0.8,0.3,0.743684,0.542416,52,328,1020,4390,5462,71,5.583453
6,c600,0.8,0.7,0.3,0.715489,0.412186,96,289,1169,4197,5462,122,5.257689
5,c600,0.6,0.9,0.3,0.710546,0.566483,40,306,1235,4187,5462,59,5.478482
4,c600,0.6,0.8,0.3,0.679238,0.457912,59,285,1408,3995,5462,84,5.351586
2,c600,0.4,0.9,0.3,0.641523,0.542546,30,191,1737,3695,5462,51,5.444371
3,c600,0.6,0.7,0.3,0.615525,0.351029,151,250,1699,3612,5462,174,4.807054
1,c600,0.4,0.8,0.3,0.525449,0.378049,66,147,2379,3017,5462,86,5.519334
0,c600,0.4,0.7,0.3,0.206701,0.120123,403,66,3864,1195,5462,428,2.899272

====================================================================================================
BEST CONFIGURATION BY MOTA
====================================================================================================

,Sequence,alpha,match_thresh,iou_thresh,MOTA,IDF1,ID Switches,FP,FN,Matches,GT,Unique IDs,FPS
0,c010,0.8,0.9,0.3,0.860809,0.512249,67,137,946,7249,8262,77,5.408747
1,c600,0.8,0.9,0.3,0.759795,0.580982,42,347,923,4497,5462,59,5.644904

====================================================================================================
BEST CONFIGURATION BY IDF1
====================================================================================================

,Sequence,alpha,match_thresh,iou_thresh,MOTA,IDF1,ID Switches,FP,FN,Matches,GT,Unique IDs,FPS
0,c010,0.8,0.9,0.3,0.860809,0.512249,67,137,946,7249,8262,77,5.408747
1,c600,0.8,0.9,0.3,0.759795,0.580982,42,347,923,4497,5462,59,5.644904

====================================================================================================
BEST CONFIGURATION BY ID SWITCHES
====================================================================================================

,Sequence,alpha,match_thresh,iou_thresh,MOTA,IDF1,ID Switches,FP,FN,Matches,GT,Unique IDs,FPS
0,c010,0.4,0.9,0.3,0.697168,0.502793,37,43,2422,5803,8262,49,5.825693
1,c600,0.4,0.9,0.3,0.641523,0.542546,30,191,1737,3695,5462,51,5.444371

====================================================================================================
PHASE 2 CANDIDATES
====================================================================================================

,alpha,match_thresh,MOTA,IDF1,IDSW,FN,FP,FPS,MOTA_norm,IDF1_norm,Score
8,0.8,0.9,0.810302,0.546616,109,1869,484,5.526826,1.000000,1.000000,1.000000
7,0.8,0.8,0.793168,0.516751,137,2121,442,5.662347,0.971451,0.932668,0.952060
5,0.6,0.9,0.766432,0.523675,95,2534,420,5.706226,0.926901,0.948278,0.937590
2,0.4,0.9,0.669346,0.522669,67,4159,234,5.635032,0.765127,0.946012,0.855569
4,0.6,0.8,0.729900,0.466438,136,3049,380,5.656530,0.866028,0.819235,0.842631
6,0.8,0.7,0.765636,0.434173,224,2464,388,5.373720,0.925574,0.746491,0.836033
3,0.6,0.7,0.666635,0.349105,385,3740,307,4.880711,0.760610,0.554701,0.657655
1,0.4,0.8,0.550124,0.367900,149,5790,166,5.356362,0.566470,0.597077,0.581774
0,0.4,0.7,0.210165,0.103069,1149,9607,74,2.964346,0.000000,0.000000,0.000000

====================================================================================================
TUNING PHASE 1 COMPLETE
====================================================================================================
Next: take the strongest configurations and test iou_thresh.

In [183]:
# ============================================================
# ATHLETIQ — MixSort Phase 2 Tuning
# Sweep iou_thresh only
#
# Fixed:
#   alpha        = 0.8
#   match_thresh = 0.9
#
# Test:
#   iou_thresh = 0.2, 0.3, 0.4
#
# Sequences:
#   c600, c010
#
# Total runs = 6
# ============================================================

import sys
import gc
import time
import cv2
import numpy as np
import pandas as pd
import motmetrics as mm
import torch

from pathlib import Path
from collections import defaultdict
from types import SimpleNamespace

from ultralytics import YOLO


# ============================================================
# 1. NUMPY 2.x COMPATIBILITY
# ============================================================

if not hasattr(np, "asfarray"):
    np.asfarray = lambda a, dtype=float: np.asarray(a, dtype=dtype)


# ============================================================
# 2. PATHS
# ============================================================

ROOT = Path("/mnt/d/My Projects/AthletiQ/AthletiQ")

MIXSORT_DIR = (
    ROOT / "ai-engine/third_party/MixSort"
)

VAL_DIR = (
    ROOT
    / "datasets/football/benchmarks/sportsmot/extracted/val"
)

MODEL_PATH = (
    ROOT
    / "ai-engine/models/football_player_detector.pt"
)


# ============================================================
# 3. SEQUENCES
# ============================================================

SEQUENCES = {
    "c600": "v_G-vNjfx1GGc_c600",
    "c010": "v_i2_L4qquVg0_c010",
}


# ============================================================
# 4. FIXED PARAMETERS
# ============================================================

ALPHA = 0.8
MATCH_THRESH = 0.9

IOU_THRESHES = [
    0.2,
    0.3,
    0.4
]

TRACK_THRESH = 0.6
TRACK_BUFFER = 30


# ============================================================
# 5. IMPORT MIXSORT
# ============================================================

if str(MIXSORT_DIR) not in sys.path:
    sys.path.insert(0, str(MIXSORT_DIR))

from yolox.mixsort_tracker.mixsort_tracker import MIXTracker


# ============================================================
# 6. LOAD DETECTOR ONCE
# ============================================================

detector = YOLO(
    str(MODEL_PATH)
)

print("=" * 80)
print("MIXSORT PHASE 2 — IOU THRESHOLD TUNING")
print("=" * 80)

print("Fixed alpha:        ", ALPHA)
print("Fixed match_thresh: ", MATCH_THRESH)
print("IoU thresholds:     ", IOU_THRESHES)
print("Sequences:          ", list(SEQUENCES.keys()))
print("Total runs:         ", len(SEQUENCES) * len(IOU_THRESHES))

print()


# ============================================================
# 7. GT LOADER
# ============================================================

def load_gt(gt_path):

    gt = defaultdict(list)

    with open(gt_path, "r") as f:

        for line in f:

            parts = line.strip().split(",")

            if len(parts) < 6:
                continue

            frame_id = int(float(parts[0]))
            track_id = int(float(parts[1]))

            x = float(parts[2])
            y = float(parts[3])
            w = float(parts[4])
            h = float(parts[5])

            gt[frame_id].append(
                (track_id, x, y, w, h)
            )

    return gt


# ============================================================
# 8. SINGLE CONFIG EVALUATION
# ============================================================

def evaluate_config(
    seq_name,
    iou_thresh
):

    seq_dir = VAL_DIR / seq_name

    img_dir = seq_dir / "img1"
    gt_path = seq_dir / "gt" / "gt.txt"

    frames = sorted(
        img_dir.glob("*.jpg")
    )

    gt = load_gt(gt_path)

    # --------------------------------------------------------
    # Create fresh MixSort configuration
    # --------------------------------------------------------

    args = SimpleNamespace(
        track_thresh=TRACK_THRESH,
        track_buffer=TRACK_BUFFER,
        match_thresh=MATCH_THRESH,
        iou_thresh=iou_thresh,
        alpha=ALPHA,
        radius=0,
        script="mixformer_deit",
        config="track",
        local_rank=0,
        mot20=False,
    )

    # --------------------------------------------------------
    # Fresh tracker
    # --------------------------------------------------------

    tracker = MIXTracker(
        args,
        frame_rate=25
    )

    acc = mm.MOTAccumulator(
        auto_id=True
    )

    unique_ids = set()

    start_time = time.time()

    # --------------------------------------------------------
    # Frame loop
    # --------------------------------------------------------

    for frame_idx, frame_path in enumerate(
        frames,
        start=1
    ):

        frame = cv2.imread(
            str(frame_path)
        )

        # ----------------------------------------------------
        # Detection
        # ----------------------------------------------------

        result = detector.predict(
            frame,
            conf=0.40,
            iou=0.40,
            device=0,
            verbose=False
        )[0]

        boxes = (
            result
            .boxes
            .xyxy
            .cpu()
            .numpy()
        )

        scores = (
            result
            .boxes
            .conf
            .cpu()
            .numpy()
        )

        detections = np.column_stack(
            [
                boxes,
                scores
            ]
        ).astype(
            np.float32
        )

        # ----------------------------------------------------
        # MixSort expects H,W
        # ----------------------------------------------------

        img_info = (
            frame.shape[0],
            frame.shape[1]
        )

        img_size = (
            frame.shape[0],
            frame.shape[1]
        )

        # Important: MixSort modifies detections
        targets = tracker.update(
            detections.copy(),
            img_info,
            img_size,
            frame
        )

        # ----------------------------------------------------
        # Predictions
        # ----------------------------------------------------

        pred_ids = []
        pred_boxes = []

        for target in targets:

            track_id = int(
                target.track_id
            )

            x, y, w, h = map(
                float,
                target.tlwh
            )

            pred_ids.append(
                track_id
            )

            pred_boxes.append(
                [x, y, w, h]
            )

            unique_ids.add(
                track_id
            )

        # ----------------------------------------------------
        # Ground truth
        # ----------------------------------------------------

        gt_entries = gt.get(
            frame_idx,
            []
        )

        gt_ids = []
        gt_boxes = []

        for (
            track_id,
            x,
            y,
            w,
            h
        ) in gt_entries:

            gt_ids.append(
                int(track_id)
            )

            gt_boxes.append(
                [x, y, w, h]
            )

        # ----------------------------------------------------
        # IoU distance matrix
        # ----------------------------------------------------

        if (
            len(gt_boxes) == 0
            and len(pred_boxes) == 0
        ):

            distance = np.empty(
                (0, 0)
            )

        elif len(gt_boxes) == 0:

            distance = np.empty(
                (0, len(pred_boxes))
            )

        elif len(pred_boxes) == 0:

            distance = np.empty(
                (len(gt_boxes), 0)
            )

        else:

            distance = mm.distances.iou_matrix(
                np.asarray(
                    gt_boxes,
                    dtype=float
                ),
                np.asarray(
                    pred_boxes,
                    dtype=float
                ),
                max_iou=0.5
            )

        # ----------------------------------------------------
        # Update MOT accumulator
        # ----------------------------------------------------

        acc.update(
            gt_ids,
            pred_ids,
            distance
        )

    # ========================================================
    # METRICS
    # ========================================================

    elapsed = time.time() - start_time

    fps = (
        len(frames) / elapsed
        if elapsed > 0
        else 0
    )

    mh = mm.metrics.create()

    summary = mh.compute(
        acc,
        metrics=[
            "num_objects",
            "num_predictions",
            "num_matches",
            "num_switches",
            "num_false_positives",
            "num_misses",
            "mota",
            "idf1"
        ],
        name="result"
    )

    row = summary.iloc[0]

    result = {
        "Sequence": seq_name,
        "alpha": ALPHA,
        "match_thresh": MATCH_THRESH,
        "iou_thresh": iou_thresh,
        "MOTA": float(row["mota"]),
        "IDF1": float(row["idf1"]),
        "ID Switches": int(row["num_switches"]),
        "FP": int(row["num_false_positives"]),
        "FN": int(row["num_misses"]),
        "Matches": int(row["num_matches"]),
        "GT": int(row["num_objects"]),
        "Predictions": int(row["num_predictions"]),
        "Unique IDs": len(unique_ids),
        "FPS": fps,
    }

    # ========================================================
    # IMPORTANT — FREE GPU MEMORY
    # ========================================================

    del tracker
    del acc
    del gt

    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.ipc_collect()

    return result


# ============================================================
# 9. RUN 6 CONFIGURATIONS
# ============================================================

results = []

run_number = 0
total_runs = (
    len(SEQUENCES)
    * len(IOU_THRESHES)
)

for seq_label, seq_name in SEQUENCES.items():

    print("\n" + "=" * 80)
    print(
        f"SEQUENCE: {seq_label}"
    )
    print("=" * 80)

    for iou_thresh in IOU_THRESHES:

        run_number += 1

        print(
            f"\n[{run_number}/{total_runs}] "
            f"{seq_label} | "
            f"alpha={ALPHA} | "
            f"match_thresh={MATCH_THRESH} | "
            f"iou_thresh={iou_thresh}"
        )

        result = evaluate_config(
            seq_name,
            iou_thresh
        )

        # Replace long sequence name with label
        result["Sequence"] = seq_label

        results.append(
            result
        )

        print(
            f"MOTA={result['MOTA']:.4f} | "
            f"IDF1={result['IDF1']:.4f} | "
            f"IDSW={result['ID Switches']} | "
            f"FP={result['FP']} | "
            f"FN={result['FN']} | "
            f"FPS={result['FPS']:.2f}"
        )

        # ----------------------------------------------------
        # GPU status
        # ----------------------------------------------------

        if torch.cuda.is_available():

            allocated = (
                torch.cuda.memory_allocated()
                / 1024**3
            )

            reserved = (
                torch.cuda.memory_reserved()
                / 1024**3
            )

            print(
                f"GPU memory after cleanup: "
                f"allocated={allocated:.2f} GB, "
                f"reserved={reserved:.2f} GB"
            )


# ============================================================
# 10. RESULTS TABLE
# ============================================================

phase2_df = pd.DataFrame(
    results
)

print("\n")
print("=" * 100)
print("PHASE 2 — ALL RESULTS")
print("=" * 100)

display(
    phase2_df.sort_values(
        [
            "iou_thresh",
            "Sequence"
        ]
    )
)


# ============================================================
# 11. AVERAGE ACROSS c600 + c010
# ============================================================

phase2_summary = (
    phase2_df
    .groupby("iou_thresh")
    .agg(
        MOTA=("MOTA", "mean"),
        IDF1=("IDF1", "mean"),
        IDSW=("ID Switches", "sum"),
        FP=("FP", "sum"),
        FN=("FN", "sum"),
        Matches=("Matches", "sum"),
        GT=("GT", "sum"),
        FPS=("FPS", "mean")
    )
    .reset_index()
)

print("\n")
print("=" * 100)
print("PHASE 2 — CONFIGURATION COMPARISON")
print("=" * 100)

display(
    phase2_summary.sort_values(
        "MOTA",
        ascending=False
    )
)


# ============================================================
# 12. BEST CONFIGURATIONS
# ============================================================

best_mota = phase2_summary.loc[
    phase2_summary["MOTA"].idxmax()
]

best_idf1 = phase2_summary.loc[
    phase2_summary["IDF1"].idxmax()
]

best_ids = phase2_summary.loc[
    phase2_summary["IDSW"].idxmin()
]

print("\n")
print("=" * 100)
print("PHASE 2 WINNERS")
print("=" * 100)

print(
    f"\nBest MOTA:"
    f"  iou_thresh={best_mota['iou_thresh']}"
    f"  → {best_mota['MOTA']:.6f}"
)

print(
    f"Best IDF1:"
    f"  iou_thresh={best_idf1['iou_thresh']}"
    f"  → {best_idf1['IDF1']:.6f}"
)

print(
    f"Fewest ID switches:"
    f"  iou_thresh={best_ids['iou_thresh']}"
    f"  → {int(best_ids['IDSW'])}"
)


# ============================================================
# 13. GPU CLEANUP
# ============================================================

del phase2_df
gc.collect()

if torch.cuda.is_available():
    torch.cuda.empty_cache()
    torch.cuda.ipc_collect()

print("\n")
print("=" * 100)
print("PHASE 2 COMPLETE")
print("=" * 100)

================================================================================
MIXSORT PHASE 2 — IOU THRESHOLD TUNING
================================================================================
Fixed alpha:         0.8
Fixed match_thresh:  0.9
IoU thresholds:      [0.2, 0.3, 0.4]
Sequences:           ['c600', 'c010']
Total runs:          6


================================================================================
SEQUENCE: c600
================================================================================

[1/6] c600 | alpha=0.8 | match_thresh=0.9 | iou_thresh=0.2
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.7598 | IDF1=0.5810 | IDSW=42 | FP=347 | FN=923 | FPS=5.68
GPU memory after cleanup: allocated=0.99 GB, reserved=1.31 GB

[2/6] c600 | alpha=0.8 | match_thresh=0.9 | iou_thresh=0.3
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.7598 | IDF1=0.5810 | IDSW=42 | FP=347 | FN=923 | FPS=5.51
GPU memory after cleanup: allocated=0.99 GB, reserved=1.31 GB

[3/6] c600 | alpha=0.8 | match_thresh=0.9 | iou_thresh=0.4
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.7598 | IDF1=0.5810 | IDSW=42 | FP=347 | FN=923 | FPS=5.84
GPU memory after cleanup: allocated=0.99 GB, reserved=1.31 GB

================================================================================
SEQUENCE: c010
================================================================================

[4/6] c010 | alpha=0.8 | match_thresh=0.9 | iou_thresh=0.2
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.8608 | IDF1=0.5122 | IDSW=67 | FP=137 | FN=946 | FPS=5.78
GPU memory after cleanup: allocated=0.99 GB, reserved=1.31 GB

[5/6] c010 | alpha=0.8 | match_thresh=0.9 | iou_thresh=0.3
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.8608 | IDF1=0.5122 | IDSW=67 | FP=137 | FN=946 | FPS=6.06
GPU memory after cleanup: allocated=0.99 GB, reserved=1.31 GB

[6/6] c010 | alpha=0.8 | match_thresh=0.9 | iou_thresh=0.4
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MOTA=0.8608 | IDF1=0.5122 | IDSW=67 | FP=137 | FN=946 | FPS=6.05
GPU memory after cleanup: allocated=0.99 GB, reserved=1.31 GB


====================================================================================================
PHASE 2 — ALL RESULTS
====================================================================================================

,Sequence,alpha,match_thresh,iou_thresh,MOTA,IDF1,ID Switches,FP,FN,Matches,GT,Predictions,Unique IDs,FPS
3,c010,0.8,0.9,0.2,0.860809,0.512249,67,137,946,7249,8262,7453,77,5.777769
0,c600,0.8,0.9,0.2,0.759795,0.580982,42,347,923,4497,5462,4886,59,5.682720
4,c010,0.8,0.9,0.3,0.860809,0.512249,67,137,946,7249,8262,7453,77,6.056907
1,c600,0.8,0.9,0.3,0.759795,0.580982,42,347,923,4497,5462,4886,59,5.511431
5,c010,0.8,0.9,0.4,0.860809,0.512249,67,137,946,7249,8262,7453,77,6.052204
2,c600,0.8,0.9,0.4,0.759795,0.580982,42,347,923,4497,5462,4886,59,5.837067

====================================================================================================
PHASE 2 — CONFIGURATION COMPARISON
====================================================================================================

   iou_thresh      MOTA      IDF1  IDSW   FP    FN  Matches     GT       FPS
0         0.2  0.810302  0.546616   109  484  1869    11746  13724  5.730244
1         0.3  0.810302  0.546616   109  484  1869    11746  13724  5.784169
2         0.4  0.810302  0.546616   109  484  1869    11746  13724  5.944635

====================================================================================================
PHASE 2 WINNERS
====================================================================================================

Best MOTA:  iou_thresh=0.2  → 0.810302
Best IDF1:  iou_thresh=0.2  → 0.546616
Fewest ID switches:  iou_thresh=0.2  → 109


====================================================================================================
PHASE 2 COMPLETE
====================================================================================================

In [184]:
# ============================================================
# ATHLETIQ — FINAL TUNED MIXSORT EVALUATION
# ============================================================
#
# Tuned configuration:
#   alpha        = 0.8
#   match_thresh = 0.9
#   iou_thresh   = 0.3
#   track_thresh = 0.6
#   track_buffer = 30
#
# Detection:
#   confidence = 0.40
#   NMS IoU    = 0.40
#
# MOT evaluation:
#   matching IoU = 0.50
#
# Sequences:
#   c017, c600, c011, c067, c010
# ============================================================

import sys
import gc
import time
import cv2
import numpy as np
import pandas as pd
import motmetrics as mm
import torch

from pathlib import Path
from collections import defaultdict
from types import SimpleNamespace

from ultralytics import YOLO


# ============================================================
# 1. NUMPY 2.x COMPATIBILITY
# ============================================================

if not hasattr(np, "asfarray"):
    np.asfarray = lambda a, dtype=float: np.asarray(a, dtype=dtype)


# ============================================================
# 2. PATHS
# ============================================================

ROOT = Path("/mnt/d/My Projects/AthletiQ/AthletiQ")

MIXSORT_DIR = (
    ROOT / "ai-engine/third_party/MixSort"
)

VAL_DIR = (
    ROOT
    / "datasets/football/benchmarks/sportsmot/extracted/val"
)

MODEL_PATH = (
    ROOT
    / "ai-engine/models/football_player_detector.pt"
)


# ============================================================
# 3. EXACT VALIDATION SEQUENCES
# ============================================================

SEQUENCES = [
    "v_2QhNRucNC7E_c017",
    "v_G-vNjfx1GGc_c600",
    "v_ITo3sCnpw_k_c011",
    "v_dw7LOz17Omg_c067",
    "v_i2_L4qquVg0_c010",
]


# ============================================================
# 4. FINAL TUNED MIXSORT CONFIG
# ============================================================

args = SimpleNamespace(
    track_thresh=0.6,
    track_buffer=30,
    match_thresh=0.9,
    iou_thresh=0.3,
    alpha=0.8,
    radius=0,
    script="mixformer_deit",
    config="track",
    local_rank=0,
    mot20=False,
)


# ============================================================
# 5. IMPORT MIXSORT
# ============================================================

if str(MIXSORT_DIR) not in sys.path:
    sys.path.insert(0, str(MIXSORT_DIR))

from yolox.mixsort_tracker.mixsort_tracker import MIXTracker


# ============================================================
# 6. LOAD DETECTOR ONCE
# ============================================================

detector = YOLO(
    str(MODEL_PATH)
)


# ============================================================
# 7. GT LOADER
# ============================================================

def load_gt(gt_path):

    gt = defaultdict(list)

    with open(gt_path, "r") as f:

        for line in f:

            parts = line.strip().split(",")

            if len(parts) < 6:
                continue

            frame_id = int(float(parts[0]))
            track_id = int(float(parts[1]))

            x = float(parts[2])
            y = float(parts[3])
            w = float(parts[4])
            h = float(parts[5])

            gt[frame_id].append(
                (track_id, x, y, w, h)
            )

    return gt


# ============================================================
# 8. VERIFY ALL SEQUENCES
# ============================================================

print("=" * 80)
print("FINAL TUNED MIXSORT EVALUATION")
print("=" * 80)

print("\nFinal tracker configuration:")
print("  track_thresh :", args.track_thresh)
print("  track_buffer :", args.track_buffer)
print("  match_thresh :", args.match_thresh)
print("  iou_thresh   :", args.iou_thresh)
print("  alpha        :", args.alpha)

print("\nDetector:")
print("  confidence   : 0.40")
print("  NMS IoU      : 0.40")

print("\nMOT evaluation:")
print("  matching IoU : 0.50")

print("\nSequence verification:")

for seq_name in SEQUENCES:

    seq_dir = VAL_DIR / seq_name
    img_dir = seq_dir / "img1"
    gt_path = seq_dir / "gt" / "gt.txt"

    if not seq_dir.exists():
        raise FileNotFoundError(
            f"Sequence not found:\n{seq_dir}"
        )

    if not img_dir.exists():
        raise FileNotFoundError(
            f"img1 not found:\n{img_dir}"
        )

    if not gt_path.exists():
        raise FileNotFoundError(
            f"GT not found:\n{gt_path}"
        )

    print(
        f"  ✓ {seq_name}"
    )


# ============================================================
# 9. RESULTS STORAGE
# ============================================================

all_results = []

total_frames = 0
total_objects = 0
total_predictions = 0
total_matches = 0
total_switches = 0
total_fp = 0
total_fn = 0

total_elapsed = 0.0


# ============================================================
# 10. EVALUATE EACH SEQUENCE
# ============================================================

for seq_number, seq_name in enumerate(
    SEQUENCES,
    start=1
):

    print("\n")
    print("=" * 80)
    print(
        f"SEQUENCE {seq_number}/5"
    )
    print(seq_name)
    print("=" * 80)

    seq_dir = VAL_DIR / seq_name

    img_dir = seq_dir / "img1"
    gt_path = seq_dir / "gt" / "gt.txt"

    frames = sorted(
        img_dir.glob("*.jpg")
    )

    gt = load_gt(
        gt_path
    )

    print(
        "Frames:",
        len(frames)
    )

    print(
        "GT rows:",
        sum(len(v) for v in gt.values())
    )

    # --------------------------------------------------------
    # Fresh tracker
    # --------------------------------------------------------

    tracker = MIXTracker(
        args,
        frame_rate=25
    )

    acc = mm.MOTAccumulator(
        auto_id=True
    )

    unique_ids = set()

    start_time = time.time()

    # --------------------------------------------------------
    # Frame loop
    # --------------------------------------------------------

    for frame_idx, frame_path in enumerate(
        frames,
        start=1
    ):

        frame = cv2.imread(
            str(frame_path)
        )

        if frame is None:
            raise RuntimeError(
                f"Failed to read:\n{frame_path}"
            )

        # ----------------------------------------------------
        # Player detector
        # ----------------------------------------------------

        result = detector.predict(
            frame,
            conf=0.40,
            iou=0.40,
            device=0,
            verbose=False
        )[0]

        boxes = (
            result
            .boxes
            .xyxy
            .cpu()
            .numpy()
        )

        scores = (
            result
            .boxes
            .conf
            .cpu()
            .numpy()
        )

        detections = np.column_stack(
            [
                boxes,
                scores
            ]
        ).astype(
            np.float32
        )

        # ----------------------------------------------------
        # MixSort expects H,W
        # ----------------------------------------------------

        img_info = (
            frame.shape[0],
            frame.shape[1]
        )

        img_size = (
            frame.shape[0],
            frame.shape[1]
        )

        # MixSort modifies detections in-place
        targets = tracker.update(
            detections.copy(),
            img_info,
            img_size,
            frame
        )

        # ----------------------------------------------------
        # Predictions
        # ----------------------------------------------------

        pred_ids = []
        pred_boxes = []

        for target in targets:

            track_id = int(
                target.track_id
            )

            x, y, w, h = map(
                float,
                target.tlwh
            )

            pred_ids.append(
                track_id
            )

            pred_boxes.append(
                [
                    x,
                    y,
                    w,
                    h
                ]
            )

            unique_ids.add(
                track_id
            )

        # ----------------------------------------------------
        # Ground truth
        # ----------------------------------------------------

        gt_entries = gt.get(
            frame_idx,
            []
        )

        gt_ids = []
        gt_boxes = []

        for (
            track_id,
            x,
            y,
            w,
            h
        ) in gt_entries:

            gt_ids.append(
                int(track_id)
            )

            gt_boxes.append(
                [
                    x,
                    y,
                    w,
                    h
                ]
            )

        # ----------------------------------------------------
        # IoU distance matrix
        # ----------------------------------------------------

        if (
            len(gt_boxes) == 0
            and len(pred_boxes) == 0
        ):

            distance = np.empty(
                (0, 0)
            )

        elif len(gt_boxes) == 0:

            distance = np.empty(
                (
                    0,
                    len(pred_boxes)
                )
            )

        elif len(pred_boxes) == 0:

            distance = np.empty(
                (
                    len(gt_boxes),
                    0
                )
            )

        else:

            distance = mm.distances.iou_matrix(
                np.asarray(
                    gt_boxes,
                    dtype=float
                ),
                np.asarray(
                    pred_boxes,
                    dtype=float
                ),
                max_iou=0.5
            )

        # ----------------------------------------------------
        # MOT accumulator
        # ----------------------------------------------------

        acc.update(
            gt_ids,
            pred_ids,
            distance
        )

    # ========================================================
    # TIMING
    # ========================================================

    elapsed = time.time() - start_time

    fps = (
        len(frames) / elapsed
        if elapsed > 0
        else 0
    )

    total_elapsed += elapsed

    # ========================================================
    # METRICS
    # ========================================================

    summary = mm.metrics.create().compute(
        acc,
        metrics=[
            "num_frames",
            "num_objects",
            "num_predictions",
            "num_matches",
            "num_switches",
            "num_false_positives",
            "num_misses",
            "mota",
            "idf1"
        ],
        name=seq_name
    )

    row = summary.iloc[0]

    num_objects = int(
        row["num_objects"]
    )

    num_predictions = int(
        row["num_predictions"]
    )

    num_matches = int(
        row["num_matches"]
    )

    num_switches = int(
        row["num_switches"]
    )

    fp = int(
        row["num_false_positives"]
    )

    fn = int(
        row["num_misses"]
    )

    mota = float(
        row["mota"]
    )

    idf1 = float(
        row["idf1"]
    )

    # --------------------------------------------------------
    # Store
    # --------------------------------------------------------

    all_results.append(
        {
            "Sequence": seq_name,
            "Frames": len(frames),
            "GT Objects": num_objects,
            "Predictions": num_predictions,
            "Matches": num_matches,
            "ID Switches": num_switches,
            "FP": fp,
            "FN": fn,
            "MOTA": mota,
            "IDF1": idf1,
            "Unique IDs": len(unique_ids),
            "FPS": fps,
        }
    )

    # --------------------------------------------------------
    # Accumulate
    # --------------------------------------------------------

    total_frames += len(frames)
    total_objects += num_objects
    total_predictions += num_predictions
    total_matches += num_matches
    total_switches += num_switches
    total_fp += fp
    total_fn += fn

    # ========================================================
    # PRINT
    # ========================================================

    print("\nRESULTS")

    print(
        f"MOTA:          {mota:.6f}"
    )

    print(
        f"IDF1:          {idf1:.6f}"
    )

    print(
        f"ID Switches:   {num_switches}"
    )

    print(
        f"FP:            {fp}"
    )

    print(
        f"FN:            {fn}"
    )

    print(
        f"Matches:       {num_matches}"
    )

    print(
        f"Unique IDs:    {len(unique_ids)}"
    )

    print(
        f"FPS:           {fps:.2f}"
    )

    # --------------------------------------------------------
    # Free tracker memory before next sequence
    # --------------------------------------------------------

    del tracker
    del acc
    del gt

    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.ipc_collect()

        allocated = (
            torch.cuda.memory_allocated()
            / 1024**3
        )

        reserved = (
            torch.cuda.memory_reserved()
            / 1024**3
        )

        print(
            f"GPU memory after cleanup: "
            f"allocated={allocated:.2f} GB, "
            f"reserved={reserved:.2f} GB"
        )


# ============================================================
# 11. FINAL RESULTS TABLE
# ============================================================

results_df = pd.DataFrame(
    all_results
)

print("\n")
print("=" * 110)
print("FINAL TUNED MIXSORT — 5 SEQUENCE RESULTS")
print("=" * 110)

display(
    results_df
)


# ============================================================
# 12. MACRO METRICS
# ============================================================

macro_mota = results_df[
    "MOTA"
].mean()

macro_idf1 = results_df[
    "IDF1"
].mean()

average_fps = results_df[
    "FPS"
].mean()


# ============================================================
# 13. ADDITIVE OVERALL MOTA
# ============================================================

overall_mota = (
    1
    - (
        total_fn
        + total_fp
        + total_switches
    )
    / total_objects
)


# ============================================================
# 14. FINAL SUMMARY
# ============================================================

print("\n")
print("=" * 80)
print("FINAL TUNED MIXSORT SUMMARY")
print("=" * 80)

print(
    f"Total frames:       {total_frames}"
)

print(
    f"Total GT objects:   {total_objects}"
)

print(
    f"Total predictions:  {total_predictions}"
)

print(
    f"Total matches:      {total_matches}"
)

print(
    f"Total ID switches:  {total_switches}"
)

print(
    f"Total FP:           {total_fp}"
)

print(
    f"Total FN:           {total_fn}"
)

print(
    f"Overall MOTA:       {overall_mota:.6f}"
)

print(
    f"Macro MOTA:         {macro_mota:.6f}"
)

print(
    f"Macro IDF1:         {macro_idf1:.6f}"
)

print(
    f"Average FPS:        {average_fps:.2f}"
)

print("\n")
print("=" * 80)
print("FINAL MIXSORT CONFIG")
print("=" * 80)

print("track_thresh =", args.track_thresh)
print("track_buffer =", args.track_buffer)
print("match_thresh =", args.match_thresh)
print("iou_thresh   =", args.iou_thresh)
print("alpha        =", args.alpha)

print("\nFinal evaluation complete.")

================================================================================
FINAL TUNED MIXSORT EVALUATION
================================================================================

Final tracker configuration:
  track_thresh : 0.6
  track_buffer : 30
  match_thresh : 0.9
  iou_thresh   : 0.3
  alpha        : 0.8

Detector:
  confidence   : 0.40
  NMS IoU      : 0.40

MOT evaluation:
  matching IoU : 0.50

Sequence verification:
  ✓ v_2QhNRucNC7E_c017
  ✓ v_G-vNjfx1GGc_c600
  ✓ v_ITo3sCnpw_k_c011
  ✓ v_dw7LOz17Omg_c067
  ✓ v_i2_L4qquVg0_c010


================================================================================
SEQUENCE 1/5
v_2QhNRucNC7E_c017
================================================================================
Frames: 450
GT rows: 6622
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.

RESULTS
MOTA:          0.854727
IDF1:          0.786027
ID Switches:   42
FP:            465
FN:            455
Matches:       6125
Unique IDs:    42
FPS:           5.27
GPU memory after cleanup: allocated=0.77 GB, reserved=0.95 GB


================================================================================
SEQUENCE 2/5
v_G-vNjfx1GGc_c600
================================================================================
Frames: 500
GT rows: 5462
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.

RESULTS
MOTA:          0.759795
IDF1:          0.580982
ID Switches:   42
FP:            347
FN:            923
Matches:       4497
Unique IDs:    59
FPS:           5.97
GPU memory after cleanup: allocated=0.77 GB, reserved=0.94 GB


================================================================================
SEQUENCE 3/5
v_ITo3sCnpw_k_c011
================================================================================
Frames: 776
GT rows: 9736
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.

RESULTS
MOTA:          0.872227
IDF1:          0.609219
ID Switches:   59
FP:            651
FN:            534
Matches:       9143
Unique IDs:    53
FPS:           5.33
GPU memory after cleanup: allocated=0.77 GB, reserved=0.94 GB


================================================================================
SEQUENCE 4/5
v_dw7LOz17Omg_c067
================================================================================
Frames: 450
GT rows: 6959
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.

RESULTS
MOTA:          0.899698
IDF1:          0.824953
ID Switches:   28
FP:            277
FN:            393
Matches:       6538
Unique IDs:    52
FPS:           4.63
GPU memory after cleanup: allocated=0.77 GB, reserved=0.94 GB


================================================================================
SEQUENCE 5/5
v_i2_L4qquVg0_c010
================================================================================
Frames: 758
GT rows: 8262
head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.

RESULTS
MOTA:          0.860809
IDF1:          0.512249
ID Switches:   67
FP:            137
FN:            946
Matches:       7249
Unique IDs:    77
FPS:           5.49
GPU memory after cleanup: allocated=0.77 GB, reserved=0.95 GB


==============================================================================================================
FINAL TUNED MIXSORT — 5 SEQUENCE RESULTS
==============================================================================================================

,Sequence,Frames,GT Objects,Predictions,Matches,ID Switches,FP,FN,MOTA,IDF1,Unique IDs,FPS
0,v_2QhNRucNC7E_c017,450,6622,6632,6125,42,465,455,0.854727,0.786027,42,5.269293
1,v_G-vNjfx1GGc_c600,500,5462,4886,4497,42,347,923,0.759795,0.580982,59,5.967711
2,v_ITo3sCnpw_k_c011,776,9736,9853,9143,59,651,534,0.872227,0.609219,53,5.327613
3,v_dw7LOz17Omg_c067,450,6959,6843,6538,28,277,393,0.899698,0.824953,52,4.626475
4,v_i2_L4qquVg0_c010,758,8262,7453,7249,67,137,946,0.860809,0.512249,77,5.488540

================================================================================
FINAL TUNED MIXSORT SUMMARY
================================================================================
Total frames:       2934
Total GT objects:   37041
Total predictions:  35667
Total matches:      33552
Total ID switches:  238
Total FP:           1877
Total FN:           3251
Overall MOTA:       0.855134
Macro MOTA:         0.849451
Macro IDF1:         0.662686
Average FPS:        5.34


================================================================================
FINAL MIXSORT CONFIG
================================================================================
track_thresh = 0.6
track_buffer = 30
match_thresh = 0.9
iou_thresh   = 0.3
alpha        = 0.8

Final evaluation complete.

In [185]:
from pathlib import Path
import yaml

ROOT = Path("/mnt/d/My Projects/AthletiQ/AthletiQ")

MODELS_DIR = ROOT / "ai-engine" / "models"
MIXSORT_DIR = ROOT / "ai-engine" / "third_party" / "MixSort"
CHECKPOINT = MIXSORT_DIR / "pretrained" / "MixFormer_sports_train.pth.tar"

CONFIG_PATH = MODELS_DIR / "mixsort_final.yaml"

config = {
    "tracker": {
        "name": "MixSort",
        "track_thresh": 0.6,
        "track_buffer": 30,
        "match_thresh": 0.9,
        "iou_thresh": 0.3,
        "alpha": 0.8,
    },
    "detector": {
        "confidence": 0.40,
        "nms_iou": 0.40,
    },
    "evaluation": {
        "matching_iou": 0.50,
    },
    "model": {
        "architecture": "mixformer_deit",
        "checkpoint": str(CHECKPOINT),
    },
}

MODELS_DIR.mkdir(parents=True, exist_ok=True)

with open(CONFIG_PATH, "w") as f:
    yaml.safe_dump(config, f, sort_keys=False)

print("Config saved:")
print(CONFIG_PATH)

print("\nCheckpoint:")
print(CHECKPOINT)
print("Exists:", CHECKPOINT.exists())

Config saved:
/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/models/mixsort_final.yaml

Checkpoint:
/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/pretrained/MixFormer_sports_train.pth.tar
Exists: True

In [186]:
from pathlib import Path

TRACKING_DIR = ROOT / "ai-engine" / "core" / "tracking"
TRACKING_DIR.mkdir(parents=True, exist_ok=True)

wrapper_path = TRACKING_DIR / "mixsort_tracker.py"

wrapper_code = r'''
from pathlib import Path
from types import SimpleNamespace
import sys
import gc

import numpy as np
import torch
import yaml


class AthletiQMixSort:
    """
    Reusable MixSort tracker for AthletiQ.

    Final configuration:
        track_thresh = 0.6
        track_buffer = 30
        match_thresh = 0.9
        iou_thresh = 0.3
        alpha = 0.8
    """

    def __init__(
        self,
        project_root,
        frame_rate=25,
        config_path=None,
    ):
        self.project_root = Path(project_root)
        self.frame_rate = frame_rate

        self.mixsort_dir = (
            self.project_root
            / "ai-engine"
            / "third_party"
            / "MixSort"
        )

        if config_path is None:
            config_path = (
                self.project_root
                / "ai-engine"
                / "models"
                / "mixsort_final.yaml"
            )

        self.config_path = Path(config_path)

        # ------------------------------------------------------------------
        # NumPy compatibility for older MixSort code
        # ------------------------------------------------------------------
        if not hasattr(np, "float"):
            np.float = float

        if not hasattr(np, "int"):
            np.int = int

        # ------------------------------------------------------------------
        # Add MixSort to Python path
        # ------------------------------------------------------------------
        mixsort_path = str(self.mixsort_dir)

        if mixsort_path not in sys.path:
            sys.path.insert(0, mixsort_path)

        # ------------------------------------------------------------------
        # Load final AthletiQ configuration
        # ------------------------------------------------------------------
        with open(self.config_path, "r") as f:
            cfg = yaml.safe_load(f)

        tracker_cfg = cfg["tracker"]

        self.track_thresh = tracker_cfg["track_thresh"]
        self.track_buffer = tracker_cfg["track_buffer"]
        self.match_thresh = tracker_cfg["match_thresh"]
        self.iou_thresh = tracker_cfg["iou_thresh"]
        self.alpha = tracker_cfg["alpha"]

        # ------------------------------------------------------------------
        # Import MixSort
        # ------------------------------------------------------------------
        from yolox.mixsort_tracker.mixsort_tracker import MIXTracker

        self.MIXTracker = MIXTracker

        # ------------------------------------------------------------------
        # MixSort arguments
        # ------------------------------------------------------------------
        args = SimpleNamespace(
            track_thresh=self.track_thresh,
            track_buffer=self.track_buffer,
            match_thresh=self.match_thresh,
            iou_thresh=self.iou_thresh,
            alpha=self.alpha,
            radius=0,
            script="mixformer_deit",
            config="track",
            local_rank=0,
            mot20=False,
        )

        self.args = args

        # ------------------------------------------------------------------
        # Create tracker
        # ------------------------------------------------------------------
        self.tracker = MIXTracker(
            self.args,
            frame_rate=self.frame_rate
        )

        self.frame_id = 0

    # ----------------------------------------------------------------------
    # Update tracker
    # ----------------------------------------------------------------------
    def update(self, detections, frame):
        """
        Update MixSort with detector outputs.

        Parameters
        ----------
        detections : np.ndarray
            Shape: (N, 5)
            [x1, y1, x2, y2, confidence]

        frame : np.ndarray
            BGR image.

        Returns
        -------
        list of dict
            [
                {
                    "track_id": int,
                    "bbox": [x1, y1, x2, y2],
                    "score": float
                },
                ...
            ]
        """

        if detections is None:
            detections = np.empty((0, 5), dtype=np.float32)

        detections = np.asarray(
            detections,
            dtype=np.float32
        ).copy()

        h, w = frame.shape[:2]

        img_info = (h, w)
        img_size = (h, w)

        online_targets = self.tracker.update(
            detections,
            img_info,
            img_size,
            frame
        )

        results = []

        for target in online_targets:

            tlwh = target.tlwh

            x, y, bw, bh = tlwh

            x1 = float(x)
            y1 = float(y)
            x2 = float(x + bw)
            y2 = float(y + bh)

            results.append({
                "track_id": int(target.track_id),
                "bbox": [x1, y1, x2, y2],
                "score": float(target.score),
            })

        self.frame_id += 1

        return results

    # ----------------------------------------------------------------------
    # Reset tracker
    # ----------------------------------------------------------------------
    def reset(self):
        """
        Create a fresh tracker.
        """

        self.tracker = self.MIXTracker(
            self.args,
            frame_rate=self.frame_rate
        )

        self.frame_id = 0

    # ----------------------------------------------------------------------
    # Cleanup
    # ----------------------------------------------------------------------
    def cleanup(self):
        """
        Release tracker and GPU memory.
        """

        self.tracker = None

        gc.collect()

        if torch.cuda.is_available():
            torch.cuda.empty_cache()
            torch.cuda.ipc_collect()

    # ----------------------------------------------------------------------
    # Configuration
    # ----------------------------------------------------------------------
    def get_config(self):

        return {
            "track_thresh": self.track_thresh,
            "track_buffer": self.track_buffer,
            "match_thresh": self.match_thresh,
            "iou_thresh": self.iou_thresh,
            "alpha": self.alpha,
            "frame_rate": self.frame_rate,
        }
'''

with open(wrapper_path, "w") as f:
    f.write(wrapper_code)

print("Wrapper created:")
print(wrapper_path)

Wrapper created:
/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/core/tracking/mixsort_tracker.py

In [187]:
import sys
import importlib

TRACKING_DIR = ROOT / "ai-engine" / "core" / "tracking"

if str(TRACKING_DIR) not in sys.path:
    sys.path.insert(0, str(TRACKING_DIR))

from mixsort_tracker import AthletiQMixSort

tracker = AthletiQMixSort(
    project_root=ROOT,
    frame_rate=25
)

print("MixSort loaded successfully.")
print()
print("Configuration:")
print(tracker.get_config())

head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.
MixSort loaded successfully.

Configuration:
{'track_thresh': 0.6, 'track_buffer': 30, 'match_thresh': 0.9, 'iou_thresh': 0.3, 'alpha': 0.8, 'frame_rate': 25}

In [188]:
from mixsort_tracker import AthletiQMixSort

tracker = AthletiQMixSort(
    project_root=ROOT,
    frame_rate=25
)

tracks = tracker.update(
    detections,
    frame
)

head channel: 384
missing keys: ['backbone.pos_embed', 'backbone.pos_embed_s', 'backbone.pos_embed_t']
unexpected keys: []
Loading pretrained ViT done.

In [192]:
!grep -n -A5 -B2 "template_imgs =" \
"/mnt/d/My Projects/AthletiQ/AthletiQ/ai-engine/third_party/MixSort/yolox/mixsort_tracker/mixsort_tracker.py"

329-        # self.visualize_box(self.logger,img,dets,"dets")
330-        vit = np.zeros((len(stracks), len(dets)), dtype=np.float64)
331:        template_imgs = [
332-            s.template[0] if isinstance(s.template, tuple) else s.template
333-            for s in stracks
334-        ]
335-        for strack in stracks:
336-            # centered at predicted position
--
342-
343-        # img transform & compute
344:        template_imgs = normalize(
345-            torch.stack(template_imgs).float().div(255),
346-            self.cfg.DATA.MEAN,
347-            self.cfg.DATA.STD,
348-        )
349-        search_imgs = normalize(